### ISSUE TITLE
Group Effects by what they do

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2659] opened 2022-03-10 11:41 UTC
Proposed grouping

# For effects

-   Add Realtime Effect (#2661)
-   Add/Remove Plugins
-   Repeat last effect 
-   ~~Often used effects (#2660)~~
*  -------
-   Volume and compression
    -   Amplify
    -   Compressor
    -   Limiter
    -   Normalize
    -   Loudness Normalization
    -   Auto Duck
-   Fading 
    -   Fade in
    -   Fade out
    -   Studio Fade out
    -   Adjustable fade
    -   Crossfade Clips
    -   Crossfade Tracks
-   Pitch and Tempo
    -   Change Pitch
    -   Change Speed
    -   Change Tempo
    -   Paulstretch
    -   Sliding Stretch
    -   Reverse
-   EQ and Filters
    -   Bass and treble
    -   Graphic EQ
    -   Filter curve EQ
    -   High-pass filter
    -   Low-pass filter
    -   Notch Filter
-   Noise Removal and Repair
    -   Click removal
    -   noise reduction
    -   noise gate
    -   repair
    -   Clip fix
-   Delay and Reverb
    -   Echo
    -   Reverb
    -   Delay
-   Distortion and Modulation
    -   Tremolo
    -   Distortion
    -   Wahwah
    -   Phaser
    -   Vocoder
-   Special 
    -   Repeat
    -   Invert [RENAME effect to INVERT POLARITY]
    -   Truncate Silence 
    -   Vocal reduction and isolation
    -   vocal remover
-   Spectral tools
    -   Spectral Delete
    -   Spectral edit multi tool
    -   Spectral edit parametric EQ
    -   Spectral edit shelves
*   -----
-   [any external plugins, whether it be nyquist, VST or LV2, arranged as thus:]
-   Author/Publisher
    -   Effect, sorted alphabetically by name

(sidenotes: the first 3 items in special and the entirety of "fades" really should be editing tools, not effects. Also, truncate silence is very similar to the "detach at silence" in the edit menu)

# for Generators and Analyzers

* Add/Remove Plugins
* ~~[Often used Generators/Analyzers - only if generate/analyze-type plugins are active]~~
* ----
* Audacity's default generators/analyzers, alphabetically
* ----
* [any external plugins, arranged as thus:
* Author/Publisher
    * Generator/Analyzer, sorted alphabetically

**Comment by petersampsonaudacity** [comment] 2022-04-18 15:57
@vsverchinsky Vitaly  - testing on W10 with your latest branch fix for this:

1. The new "default" grouping for effects looks to do what @LWinterberg proposed in the first post in this thread:
![image](https://user-images.githubusercontent.com/50205984/163835799-8917a1f8-9a6a-49e3-aa25-ba10e7b36c1f.png)


2, **BUT** switching to Sorting by 
a) Publisher and Effect Name
b) Type and Effect name
c) Grouped by Type
all no longer work - they just show the full alphabetical list (same as you get woth Sort by Effect Name i.e. the old default


3. The grouping for Analyze and Generate are also looking odd with this branch build

**Comment by SteveDaulton** [comment] 2022-04-18 18:04
If you wanted to, Nyquist plug-ins could be sorted by what they do.
Some years ago, effects were sorted by what they do, based on http://lv2plug.in/ns/lv2core classes. Nyquist plug-ins had an additional ";categories" header to identify what the plug-in does. An example may be seen here: https://github.com/audacity/audacity/blame/742c91d64d709af2bd0c86c1e6b9676371b6985c/plug-ins/lowpass.ny

I should also add that sorting effects by what they do was unpopular with users, which is why it was later removed.

**Comment by Paul-Licameli** [comment] 2022-04-18 18:38
@SteveDaulton see my review comments at #2831 which I wrote before reading your latest comment about ";categories".

If "user defined grouping" was preferred, I am not aware that it was implemented.  This first implementation from @vsverchinsky may not be modifiable, but we might think about generalizing it later to be customizable, and if a user doesn't like it, still it is only one among many available options for the sorting of effects.

@LWinterberg  are there any ideas about how the preference for the sorting and grouping criteria might be made more discoverable, if un-customizable grouping is really unpopular?

Also, Leo, are you very attached to the specific sorting of effect names within category that you listed here?  I hope that is in fact an inessential over-specification, and we might instead sort each category by its localized name.

**Comment by vsverchinsky** [comment] 2022-04-18 19:15
@petersampsonaudacity 
>BUT switching to Sorting by

Thanks! Found typos and fixed them

**Comment by LWinterberg** [comment] 2022-04-18 19:53
> @LWinterberg are there any ideas about how the preference for the sorting and grouping criteria might be made more discoverable, if un-customizable grouping is really unpopular?

We can put instructions/links to the relevant settings in the What's New (#2718) window if necessary.

**Comment by LWinterberg** [comment] 2022-04-18 19:54
> Also, Leo, are you very attached to the specific sorting of effect names within category that you listed here? I hope that is in fact an inessential over-specification, and we might instead sort each category by its localized name.

Do sort by localized name if possible!

**Comment by Paul-Licameli** [comment] 2022-04-18 19:58
> > Also, Leo, are you very attached to the specific sorting of effect names within category that you listed here? I hope that is in fact an inessential over-specification, and we might instead sort each category by its localized name.
> 
> Do sort by localized name if possible!

The next-level question would be whether the set of categories forming the "major" sort might also somehow be extensible and customizable, and should they sort by localization too?

Or ... would you want either the major or minor sorts, or both, to go by most-recently-used?

**Comment by LWinterberg** [comment] 2022-04-18 20:10
extensibility and customizability is out-of-scope for this release (that said: a "favourite effects" system is something I do want to add sooner rather than later). Sorting the categories alphabetically by localized name would be nice as well.

**Comment by vsverchinsky** [comment] 2022-04-18 20:22
> > Also, Leo, are you very attached to the specific sorting of effect names within category that you listed here? I hope that is in fact an inessential over-specification, and we might instead sort each category by its localized name.
> 
> Do sort by localized name if possible!

@LWinterberg and what about

>sidenotes: the first 3 items in special and the entirety of "fades" really should be editing tools, not effects

?

**Comment by LWinterberg** [comment] 2022-04-18 20:51
>>@LWinterberg and what about  
> sidenotes: the first 3 items in special and the entirety of "fades" really should be editing tools, not effects

This is for another release. Fading controls would probably be Smart Clips 3.0 or something

**Comment by petersampsonaudacity** [comment] 2022-04-19 08:45
> ... a "favourite effects" system is something I do want to add sooner rather than later

Big +1 to that

Many users over the years have requested this.

**Comment by Paul-Licameli** [comment] 2022-04-19 09:42
@LWinterberg an elementary question.  Is your categorization of effects supposed to be exhaustive?  If it is not, then where are all uncategorized effects supposed to be in the menu tree?

Another elementary question.  Are effect categories meant to be mutually exclusive?  If not then one effect might appear in more than one place in the tree.

**Comment by SteveDaulton** [comment] 2022-04-19 12:23
> If "user defined grouping" was preferred, I am not aware that it was implemented.

User feedback was overwhelmingly in support of user defined grouping, but this has never (yet?) been implemented in Audacity.

**Comment by petersampsonaudacity** [comment] 2022-04-19 12:33
@vsverchinsky  Vitaly,

For the sake of clarity of purpose ("does what it says on the tin") and "discoverability" can I suggest that the nomenclature for the "default" setting be changed to one of

1. **Grouped by function (default)**
2. Grouped by functionality (default)
3. Grouped by what they do (default)

I would favor the first option.

And I would strongly suggest putting this new default at the top of the list rather than at the bottom

**Comment by vsverchinsky** [comment] 2022-04-19 12:49
> @vsverchinsky Vitaly,
> 
> For the sake of clarity of purpose ("does what it says on the tin") and "discoverability" can I suggest that the nomenclature for the "default" setting be changed to one of
> 
> 1. **Grouped by function (default)**
> 2. Grouped by functionality (default)
> 3. Grouped by what they do (default)
> 
> I would favor the first option.
> 
> And I would strongly suggest putting this new default at the top of the list rather than at the bottom

@LWinterberg ? There are 3rd party and other prebundled effects that are grouped by publisher

**Comment by LWinterberg** [comment] 2022-04-19 12:57
> @LWinterberg an elementary question. Is your categorization of effects supposed to be exhaustive? If it is not, then where are all uncategorized effects supposed to be in the menu tree?

Effects which aren't shipped with Audacity and enabled by default should be sorted by Author/Publisher. That is to say, the nyquist effects in the Generate/Analyze menus should be sorted alphabetically together with the built-in effects, while Classic Filters and any external plugins would be sorted by author and name. 

> Another elementary question. Are effect categories meant to be mutually exclusive? If not then one effect might appear in more than one place in the tree.

They are right now, however, once favourites or otherwise custom ordering comes in, it is very likely that effects would appear in more than one menu.


----

I support "Grouped by function (default)" as the name of the setting.

**Closed** 2022-06-11 11:55 UTC
Labels: Task, PluginManager

**Comment by SteveDaulton** [comment] 2022-06-11 12:42
Xubuntu 20.04
audacity-linux-3.2.0-alpha-20220611+92d8b2f-x64-20.04 AppImage.
`~/.audacity-data` removed prior to launching.
Is this as intended:

![92d8b2](https://user-images.githubusercontent.com/11681097/173188420-74bba2b4-3602-4d39-910b-0ad17ab5700a.png)

**Comment by Paul-Licameli** [comment] 2022-06-11 15:09
> Xubuntu 20.04 audacity-linux-3.2.0-alpha-20220611+92d8b2f-x64-20.04 AppImage. `~/.audacity-data` removed prior to launching. Is this as intended:
> 
> ![92d8b2](https://user-images.githubusercontent.com/11681097/173188420-74bba2b4-3602-4d39-910b-0ad17ab5700a.png)

Plug-in effects below-the-line are supposed to group by publisher, as they do here, but also all shipped effects are supposed to group above-the-line, and they don't for you on Linux.

Please cd to the folder containing the application and tell me what this reports:

```
find . -name effects_menu_defaults.xml
```

**Comment by SteveDaulton** [comment] 2022-06-11 19:15
> Please cd to the folder containing the application and tell me what this reports:

As I wrote previously, I'm using the AppImage.
The AppImage is mounted at /tmp/.mount_audacinWkVCO/ but there's no sign of an "effects_menu_defaults.xml" file in there.

**Comment by Ryan-Miller-Audacity** [comment] 2022-06-15 19:11
@LWinterberg / @vsverchinsky 

Platform Information: 
* Operating Systems: MacOS Monterey 12.3.1 and Windows 10
* Build Tested: https://github.com/audacity/audacity/actions/runs/2471820247

Main Testing Completed: 
* Default sorting has been updated to match the above sorting of grouping effects by what they do and the sorting of such matches what was provided in the spec. 
*  Sorting is applied and functions appropriate for both native and 3rd party effects
* Updating of preferences to other forms of sorting still works as expected

Bugs: 
* No bugs reported.

Notes/Suggestions:
1. There’s an excessive use of “…” in effect grouping sub-menus even though the text fits perfectly fine and there are no truncated cases of effects with too long names. The menu sizes appear to be dynamic based off the longest title in the dropdown menu, so this seems unnecessary.
    * Even some of the longest names of plugins that I had (‘Amplify left or right channel’, Binural Tones with surf 2') did not need to be shortened and displayed fully. 
    * Below is a screenshot example of this: 
![Image](https://user-images.githubusercontent.com/88568755/173876202-667933d6-17a8-4770-820b-6316f3d560e7.png)
2. If you only have a single effect from a 3rd party/external plugin, it is not displayed as “Publisher -> Effect”; rather, just the effect is displayed alphabetically within the list of 3rd party plugins which is a little confusing, and would be better served to follow the same display of “Publisher -> Effect” even for a single effect instance. 
    * For example, having only the "Vinyl" effect (which is published by Izotope) will just display as "Vinyl" at the bottom of the list of 3rd party plugins, but if you have both "Vinyl" and "Vocal Doubler" (both published by Izotope) it will then display as "Publisher -> Effect". 
3. Nyquist effects, generators etc. that I had installed are currently listed under N/A in the default groupings which seems incorrect. I noted other's screenshots showing these distributed by author names, but this was not the case for me.
4. If I sort by “Publisher and Effect Name” in my preferences I would expect the dividing line (as can currently be seen between Audacity and 3rd party plugins) to be present between each publisher. Not just as a separator between Audacity and 3rd party plugins. 
    * There is no current expectation for this as it is not present in the current public release, so this would be a new addition/enhancement to the display of our EGAT dropdowns.
    * Below is a screenshot example of the divider line I am describing:
![Image](https://user-images.githubusercontent.com/88568755/173885854-0eb4965e-837a-447d-8f81-5f752aac45cc.png)

**Comment by crsib** [comment] 2022-06-15 20:48
> You misunderstand the ellipses.

I would've never guessed that...

**Comment by DavidBailes** [comment] 2022-06-16 07:24
... https://docs.microsoft.com/en-us/windows/win32/uxguide/cmd-menus#using-ellipses.

**Comment by LWinterberg** [comment] 2022-06-16 11:23
Note that Windows has moved away from this standard - their newer stuff no longer uses this pattern, nor is it mentioned in their new documentation https://docs.microsoft.com/en-us/windows/apps/desktop/
![image](https://user-images.githubusercontent.com/87814144/174056640-2436788d-6c54-477e-8cbf-3898a28534d9.png)

Anyway, question for another time. Keep them for now ⋮)

**Comment by Ryan-Miller-Audacity** [comment] 2022-07-05 18:03
Items from above (excluding number 1 which is working as intended as discussed above) are included in #3179.

**Comment by petersampsonaudacity** [comment] 2022-07-06 13:05
@Ryan-Miller-Audacity @LWinterberg 
Now that **Classic Filters** is now auto-enabled by default in the latest 3.2.0 alpha master audacity-win-3.2.0-alpha-20220705+c71177d-x64-msvc2022
surely this should live in the **EQ and Filters** section:
![image](https://user-images.githubusercontent.com/50205984/177556449-cf04eaef-20b3-4835-b30f-ab20b00a1235.png)

Classic Filters is an Audacity supplied effect but one that we kept deliberately hidden _(for reasons I've long forgotten - @SteveDaulton @James maybe one you can recall why we did this )_ by making it disabled by default - and thus it probably should not be in the extras like this but should be within the menu structure.
