### ISSUE TITLE
Redundant blank space around some plugin windows (AU, VST, VST3)

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3233] opened 2022-07-14 14:20 UTC
**Describe the bug**
There's redundant blank space around some VST/VST3/AU plugins which makes the dialog window somewhat larger than it should.

**To Reproduce**
1. Select audio, go to Effect
2. Select a VST/VST3/AU plugin, e.g. Valhalla Room, Kilhearts plugins

**Actual behavior**
There's some excessive space above and under the plugin as well as on the left/ride sides of it:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/70063970/179004436-30263a02-f853-4483-a6d0-f1261ed0a2e1.png">

**Expected behavior**
The plugin window doesn't have any additional blank space around.

**Additional information (please complete the following information):**
 - OS: MacOS 12.2.1, Windows 10
 - latest master build

**Comment by LWinterberg** [comment] 2022-09-22 10:16
This doesn't appear for me with the new design on Windows 11: 
![image](https://user-images.githubusercontent.com/87814144/191721256-9c10e407-4f72-4c4d-914e-fba11e82b791.png)

That said: The grabber that's supposed to resize the plugin window doesn't actually resize the plugin window and just resizes the internal thing. The actual window cannot be resized
![image](https://user-images.githubusercontent.com/87814144/191721425-74fa5e9e-b367-4870-8917-3e2b6a21a945.png)

**Comment by vsverchinsky** [comment] 2022-10-13 13:27
@dozzzzer @Ryan-Miller-Audacity Please note that plugin dialog resize behaviour on Linux and MacOS (for any type of plugin) can't be fixed with reasonable efforts, the problem is that system dialogs have their own resize handle (which sometimes overlap plugins own resize handle), and that can't be changed on these systems. That means that there is no way to completely avoid blank spaces during resize. #3805 removes blank spaces for VST3 when you open the plugin UI and also disables system resize handle on Windows platform.

**Comment by dozzzzer** [comment] 2022-10-17 11:49
Verified. This is now fixed according to @vsverchinsky 's comment. 
No blank space anymore on VST3s on Windows with the ability to properly resize using the plugin's handle:

![image](https://user-images.githubusercontent.com/70063970/196169678-dc71b97c-7536-4763-aa10-c9b24d7dbb13.png)

**Closed** 2022-10-31 13:14 UTC
Labels: bug, P3, UI
