### ISSUE TITLE
Scroll bar does not appear in KDE

### ISSUE THREAD

**Issue by izzylaif** [audacity/audacity#4934] opened 2023-07-19 21:41 UTC
### Bug description

The horizontal scroll does not appear until you resize the window.

### Steps to reproduce

1. Open any .wav file in Audacity. Notice the absence of horizontal scroll above status info in the lower part of the window.
2. Hold CTRL and rotate mouse wheel to zoom in on the timeline. The scroll is still not present.
3. Now use the mouse to hold lower (or any other) border of Audacity window and move mouse to resize it to any shape. Or use the window maximize/minimize buttons.
4.  The scroll appears.

### Expected behavior

The scroll should always be visible.

### Actual behavior

You need to resize the window for scroll to appear.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

**Comment by LWinterberg** [comment] 2023-07-19 22:38
duplicate of #2937

**Closed by LWinterberg** 2023-07-19 22:38 UTC
Labels: bug
