### ISSUE TITLE
Classic Filters does not appear in "EQ and Filters" in the default Effect Menu

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3660] opened 2022-09-21 12:21 UTC
### Bug description
The **Classic Filters** effect does not appear in **"EQ and Filters"** submenu in the default **Effect** menu, rather it appears as its own entry at the bottom of the menu

### Steps to reproduce
1. launch 3.2.0 Beta
2. get some audio
3. Click **Effect** in the menu bar
4. Observe that **Classic Filters** appears at the bottom of the menu and is not in **"EQ and Filters"** submenu

### Expected behavior
**Classic Filters** effect I would expect to find in "EQ and Filters" in the default Effect Menu

### Actual behavior
![image](https://user-images.githubusercontent.com/50205984/191501957-d9174d7b-80bd-4472-a1b0-e451840338b9.png)

### Audacity Version
latest beta - audacity-win-3.2.0-beta-20220921+d3e81cd-x64-msvc2022

### Operating system
Windows - W10

### Additional context
Flagging @Tantacrul and @LWinterberg  as a Design/UX issue

**Comment by dozzzzer** [comment] 2022-12-09 12:50
Closing as a duplicate of #3932

**Closed by dozzzzer** 2022-12-09 12:50 UTC
Labels: bug, P3, Design / UX
