### ISSUE TITLE
Inconsistent AutoDuck behavior

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#4943] opened 2023-07-22 16:45 UTC
### Bug description

A minor bug but discovered incidentally to refactoring and I will include an easy fix

### Steps to reproduce

1. Generate four mono tracks of noise
2. Select the last track only
3. Effect > Auto Duck
4. Observe message "Auto Duck needs a control track which must be placed below the selected track(s)." and the effect fails
5. Select the second and fourth tracks only
6. Effect > Auto Duck

### Expected behavior

According to the error message, this case too should be rejected

### Actual behavior

The effect proceeds, treating the third track, which is between two selected tracks, as the control

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by DavidBailes** [comment] 2023-07-22 17:22
> ### Actual behavior
> The effect proceeds, treating the third track, which is between two selected tracks, as the control

This behaviour is by design, it's the error message which is misleading.
From the manual page: https://manual.audacityteam.org/man/auto_duck.html,

"Place the tracks so that at least one of the selected tracks to be modified is above the unselected control track. Any other tracks below the unselected control track will also be modified if they are selected."

Or to be slightly more precise: The track which is used as the control track is the last unselected track which is immediately below a selected track.

**Comment by Paul-Licameli** [comment] 2023-07-22 19:57
> > ### Actual behavior
> > The effect proceeds, treating the third track, which is between two selected tracks, as the control
> 
> This behaviour is by design, it's the error message which is misleading. From the manual page: https://manual.audacityteam.org/man/auto_duck.html,
> 
> "Place the tracks so that at least one of the selected tracks to be modified is above the unselected control track. Any other tracks below the unselected control track will also be modified if they are selected."
> 
> Or to be slightly more precise: The track which is used as the control track is the last unselected track which is immediately below a selected track.

Which came first, the code or the manual explaining what the program did?

I think the error message does not exactly describe how the program really behaves.  Either the error message should change, or the code and the manual should change.

**Comment by DavidBailes** [comment] 2023-07-24 10:09
> Which came first, the code or the manual explaining what the program did?

I did some digging for the origins of this effect, and found that the original intention was that the control track should be after the last selected track. This quote is from Markus M on the devel mailing list:

    "Hi everyone,
    
    I just committed a new effect called "Auto Duck". This effect can be
    used to automatically "duck" the volume of the selected tracks as soon
    as another track (the "control track") exceeds a configurable volume. It
    can be used to create voice-overs for DJ sets, but also for automatic
    ramping of the talk bed (background music) in radio productions.
    Translators can use it to ramp down the original voice as soon as the
    translation kicks in.
    
    To apply the effect, select the tracks which should be changed
    ("auto-ducked") and place the control track exactly below the last
    selected track. Then choose "Auto Duck" from the effect menu."

However, the original code doesn't match the intention, and has the same behaviour as the current code. Just for reference, here's the original code:
```
bool EffectAutoDuck::Init()
{
   gPrefs->Read(wxT("/Effects/AutoDuck/DuckAmountDb"),
      &mDuckAmountDb, PARAM_DEFAULT_DUCK_AMOUNT_DB);
   gPrefs->Read(wxT("/Effects/AutoDuck/FadeDownLen"),
      &mFadeDownLen, PARAM_DEFAULT_FADE_DOWN_LEN);
   gPrefs->Read(wxT("/Effects/AutoDuck/FadeUpLen"),
      &mFadeUpLen, PARAM_DEFAULT_FADE_UP_LEN);
   gPrefs->Read(wxT("/Effects/AutoDuck/ThresholdDb"),
      &mThresholdDb, PARAM_DEFAULT_THRESHOLD_DB);
   gPrefs->Read(wxT("/Effects/AutoDuck/MaximumPause"),
      &mMaximumPause, PARAM_DEFAULT_MAXIMUM_PAUSE);

   mControlTrack = NULL;
   
   TrackListIterator iter(mTracks);
   Track *t = iter.First();
   
   bool lastWasSelectedWaveTrack = false;
   WaveTrack *controlTrackCandidate = NULL;
   
   while(t)
   {
      if (lastWasSelectedWaveTrack && !t->GetSelected() &&
          t->GetKind() == Track::Wave)
      {
         // This could be the control track, so remember it
         controlTrackCandidate = (WaveTrack*)t;
      }

      lastWasSelectedWaveTrack = false;
      
      if (t->GetSelected())
      {
         if (t->GetKind() == Track::Wave)
         {
            lastWasSelectedWaveTrack = true;
         } else
         {
            wxMessageBox(
               _("You selected a track which does not contain audio. AutoDuck can only process audio tracks."),
               _("AutoDuck"), wxICON_ERROR, mParent);
            return false;
         }
      }

      t = iter.Next();
   }
   
   if (!controlTrackCandidate)
   {
      wxMessageBox(
         _("AutoDuck needs a control track which must be placed below the selected track(s)."),
         _("AutoDuck"), wxICON_ERROR, mParent);
      return false;
   }
```

**Comment by Paul-Licameli** [comment] 2023-07-24 10:29
> > Which came first, the code or the manual explaining what the program did?
> 
> I did some digging for the origins of this effect, and found that the original intention was that the control track should be after the last selected track. This quote is from Markus M on the devel mailing list:
> 
> ```
> "Hi everyone,
> 
> I just committed a new effect called "Auto Duck". This effect can be
> used to automatically "duck" the volume of the selected tracks as soon
> as another track (the "control track") exceeds a configurable volume. It
> can be used to create voice-overs for DJ sets, but also for automatic
> ramping of the talk bed (background music) in radio productions.
> Translators can use it to ramp down the original voice as soon as the
> translation kicks in.
> 
> To apply the effect, select the tracks which should be changed
> ("auto-ducked") and place the control track exactly below the last
> selected track. Then choose "Auto Duck" from the effect menu."
> ```
> 
> However, the original code doesn't match the intention, and has the same behaviour as the current code. Just for reference, here's the original code:
> 
> ```
> bool EffectAutoDuck::Init()
> {
>    gPrefs->Read(wxT("/Effects/AutoDuck/DuckAmountDb"),
>       &mDuckAmountDb, PARAM_DEFAULT_DUCK_AMOUNT_DB);
>    gPrefs->Read(wxT("/Effects/AutoDuck/FadeDownLen"),
>       &mFadeDownLen, PARAM_DEFAULT_FADE_DOWN_LEN);
>    gPrefs->Read(wxT("/Effects/AutoDuck/FadeUpLen"),
>       &mFadeUpLen, PARAM_DEFAULT_FADE_UP_LEN);
>    gPrefs->Read(wxT("/Effects/AutoDuck/ThresholdDb"),
>       &mThresholdDb, PARAM_DEFAULT_THRESHOLD_DB);
>    gPrefs->Read(wxT("/Effects/AutoDuck/MaximumPause"),
>       &mMaximumPause, PARAM_DEFAULT_MAXIMUM_PAUSE);
> 
>    mControlTrack = NULL;
>    
>    TrackListIterator iter(mTracks);
>    Track *t = iter.First();
>    
>    bool lastWasSelectedWaveTrack = false;
>    WaveTrack *controlTrackCandidate = NULL;
>    
>    while(t)
>    {
>       if (lastWasSelectedWaveTrack && !t->GetSelected() &&
>           t->GetKind() == Track::Wave)
>       {
>          // This could be the control track, so remember it
>          controlTrackCandidate = (WaveTrack*)t;
>       }
> 
>       lastWasSelectedWaveTrack = false;
>       
>       if (t->GetSelected())
>       {
>          if (t->GetKind() == Track::Wave)
>          {
>             lastWasSelectedWaveTrack = true;
>          } else
>          {
>             wxMessageBox(
>                _("You selected a track which does not contain audio. AutoDuck can only process audio tracks."),
>                _("AutoDuck"), wxICON_ERROR, mParent);
>             return false;
>          }
>       }
> 
>       t = iter.Next();
>    }
>    
>    if (!controlTrackCandidate)
>    {
>       wxMessageBox(
>          _("AutoDuck needs a control track which must be placed below the selected track(s)."),
>          _("AutoDuck"), wxICON_ERROR, mParent);
>       return false;
>    }
> ```

You exceeded expectations with that code archeology.

So it seems the manual documented real behavior but not original intent, and I'll let this issue stand, and fix it.

**Closed** 2023-08-03 13:54 UTC
Labels: bug, Effects
