### ISSUE TITLE
Splash screen sometimes blank, sometimes doesn't show up at all

### ISSUE THREAD

**Issue by g-easy** [audacity/audacity#4705] opened 2023-05-18 02:23 UTC
### Bug description

When I start Audacity, it sometimes doesn't show the wxSplashScreen at all, and sometimes it opens but is blank (i.e. the Audacity logo is not shown)

If I change the code to run [this YieldFor](https://github.com/audacity/audacity/blob/Audacity-2.4.2/src/AudacityApp.cpp#L1409) a hundred times, the problem goes away.

I don't know if this is due to Audacity or the way it uses wxWidgets but it looks like some kind of concurrency issue because:

1. As above, if I add more calls to YieldFor then the problem reliably goes away.
2. I wrote a basic wx app that just does `new wxSplashScreen` and it doesn't have this problem.
3. I got an `xtrace` of two Audacity runs, one showing and one not showing the logo, and the difference is that in the latter case the X client never sends CreatePixmap or PutImage.

I'm running Audacity in Crostini using the X11 backend, i.e. I'm running `env GDK_BACKEND=x11 audacity`

If I don't force the backend, Audacity uses Wayland and the splash screen never shows up. If I add the YieldFor hack, then it works even in Wayland.

### Steps to reproduce

`env GDK_BACKEND=x11 audacity`

### Expected behavior

The splash screen should display the Audacity logo.

### Actual behavior

The splash screen is missing or blank.

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

![splash](https://github.com/audacity/audacity/assets/29616524/11c1d6a7-e335-434a-ab36-f16a7753135d)

**Comment by petersampsonaudacity** [comment] 2023-05-18 08:36
Testing on W10 and W11 and Mac - I have never seen this occur with any version of Audacity

**Comment by dozzzzer** [comment] 2023-05-18 09:15
I cannot reproduce this on Ubuntu 22.04 / Audacity 3.3.2 Appimage

**Comment by LWinterberg** [comment] 2023-05-19 03:27
If this is exclusive to Linux on ChromeOS, I'd advocate for a wontfix for this one.

**Comment by g-easy** [comment] 2023-05-23 05:40
It also repros on a Debian testing system running Wayland, executing as `env GDK_BACKEND=x11 audacity` (the Debian package sets this env in the `audacity.desktop` file)

I think this is a timing / concurrency bug somewhere in WX and/or how audacity uses WX, and things like Xwayland exacerbate it.

Could this be related to the [EventLoopGuarantor](https://github.com/audacity/audacity/blob/Audacity-2.4.2/src/AudacityApp.cpp#L1064-L1075C35)?

**Comment by LWinterberg** [comment] 2023-06-20 08:55
Given that this is a splash screen and we're migrating away from wx anyway (towards Qt), I don't think this will be fixed

**Closed by LWinterberg** 2023-06-20 08:55 UTC
Labels: Could not reproduce, bug, Linux, Won't fix
