### ISSUE TITLE
Joining multiple clips sometimes causes data loss

### ISSUE THREAD

**Issue by jserquera** [audacity/audacity#2226] opened 2021-12-03 09:55 UTC
When trying to join many audio blocks at once, the result is not well done. I mean, using the Edit menu (I have the Spanish version: Recortar limites-> Unir).

You have to go one by one.

I think it happens in all Windows and Mac versions....

**Comment by LWinterberg** [comment] 2021-12-03 10:45
In the latest 3.1.3 build, having clips like this:
![image](https://user-images.githubusercontent.com/87814144/144589079-7b82e858-6759-4dec-a217-8fa333f03431.png)

causes Select all followed by  Edit > Clip Boundaries > Join to make this
![image](https://user-images.githubusercontent.com/87814144/144589171-f7e0746d-cb05-44bb-be22-9a3a92f32a3a.png)

Which seems correct to me. 

@jserquera can you provide more information? What exactly is the problem? What Audacity version are you using? Can you maybe send a sample of the AUP3 file (you'll need to ZIP it first)?

**Comment by DavidBailes** [comment] 2021-12-03 11:21
Steps to reproduce:
1. Split an audio clip into three clips
2. Move the clips so that there are spaces between the clips.
3. Select all the audio (Ctrl+A)
4. Join the clips (Ctrl+J)
5. Observe that the space between the second and third clips is removed, rather than being replaced with silence.

**Comment by LWinterberg** [comment] 2021-12-03 11:39
following your STR results in the following clip: 
![image](https://user-images.githubusercontent.com/87814144/144596497-ad51abde-7b21-4078-a81f-04efafc54361.png)

I still don't understand what the problem is.

**Comment by jserquera** [comment] 2021-12-03 11:42
Attached is a project that gives me the error
[error.zip](https://github.com/audacity/audacity/files/7649327/error.zip)

**Comment by DavidBailes** [comment] 2021-12-03 12:06
Using commit d2afbf (3.1.3 beta 1):
clips selected:
![image](https://user-images.githubusercontent.com/11887021/144599805-82c2c9f0-9243-408d-be7e-dd2d8bb6f8f8.png)

clips joined:
![image](https://user-images.githubusercontent.com/11887021/144599869-0fa3f782-719d-4cd0-9fb6-b583906df02e.png)

**Comment by LWinterberg** [comment] 2021-12-03 12:44
Ah. I'm on commit 9ca1f56 / [CMake Build #3257](../actions/runs/1530570708) so it might be fixed in the final 3.1.3 after all.

**Comment by jserquera** [comment] 2021-12-03 13:23
Did you try with the project I sent?

**Comment by SteveDaulton** [comment] 2021-12-03 14:38
I can reproduce this bug on Linux with b0dade32d939dbc7a73159e05bc170c30cf0d33c 

1. Generate 10 second Chirp
2. Select from about 3s to about 6s
3. "Ctrl + i" to split
4. Zoom out a bit
5. Drag the third clip so that it ends at about 15 seconds
6. Drag the second clip so that it is roughly mid way between the other two clips
7. "Ctrl + A" to select All

![before](https://user-images.githubusercontent.com/11681097/144620598-3530e0e4-fbd1-4b77-9c1d-464fd73d3b31.png)

8 "Ctrl + J" to join the clips

![after](https://user-images.githubusercontent.com/11681097/144620618-06a00c73-a433-4599-b397-89ba327064b1.png)

**Comment by DavidBailes** [comment] 2021-12-03 14:53
> Ah. I'm on commit [9ca1f56](https://github.com/audacity/audacity/commit/9ca1f56d54261d05435c1b062eb6909f7f8bffdd) / [CMake Build #3257](../actions/runs/1530570708) so it might be fixed in the final 3.1.3 after all.

There aren't any commits in between those commits which should have fixed the problem.
The problem could well be intermittent. If I play around for a while, then sometimes it just starts working properly again.

I've had a quick look at the problem using master, where the problem also occurs.
I'm not that familiar this area of the code, but...
void WaveClip::InsertSilence( ) is called for each of the silences which are inserted using the STR.
The first time it's called, it does not execute ClearSequence(t, GetSequenceEndTime())
But the second time, it does execute that function, which I wasn't expecting.
If I comment out the two lines:
   else if (t == GetPlayEndTime() && t < GetSequenceEndTime())
      ClearSequence(t, GetSequenceEndTime());

Then this fixes the bug for me. I'm not suggesting this as a fix, just an indication of where the problem might be.

**Comment by DavidBailes** [comment] 2021-12-03 14:55
> Did you try with the project I sent?

I did try your project, and couldn't reproduce the problem. However, there is a problem, even if it can't be reproduced all the time.

**Comment by DavidBailes** [comment] 2021-12-03 18:01
> Ah. I'm on commit [9ca1f56](https://github.com/audacity/audacity/commit/9ca1f56d54261d05435c1b062eb6909f7f8bffdd) / [CMake Build #3257](../actions/runs/1530570708) so it might be fixed in the final 3.1.3 after all.

Just for the record, I can reproduce the problem using commit 9ca1f56

**Comment by DavidBailes** [comment] 2021-12-07 12:34
Using the steps to reproduce, if the length of the third clip is greater than the gap between the second and third clips, then data is lost - it's not just a question of incorrect time-shifting.
See, eg, https://github.com/audacity/audacity/issues/2226#issuecomment-985466050

**Comment by SteveDaulton** [comment] 2021-12-07 14:05
I can confirm David's comment about data loss. This bug should be P1 in my opinion - destroying the user's data is arguably the worst possible bug.

**Closed** 2021-12-08 17:12 UTC
Labels: bug, P1
