### ISSUE TITLE
 Envelopes can no longer achieve silence

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2371] opened 2022-01-03 11:59 UTC
**Describe the bug**
Envelopes can no longer achieve silence.

This was fixed apparently at some stage in the 1.3.x Beta series of Audacity - but reverted at some stage apparently.

This was originally logged on Bugzilla by @SteveDaulton  back in November 2018 as Bugzilla 2029:
https://bugzilla.audacityteam.org/show_bug.cgi?id=2029

**To Reproduce**
1. Generate a 30 second tone
2. Use the Envelope tool to create a fade out to "silence" from 5-10 secs and a fade in from "silence" - see Image 1
3. change to the Selection tool
4. Observe: from 10-20 secs looks like silence apart from right hand end - see Image 2
5. Play the audio with volume turned well up
6. Observe the middle section is not silent but plays a faint tone
7. Amplify the track by 50dB three successive times (need to check "Allow clipping" to be on)
8. Observe: the middle section was clearly not made "silent" be the envelope - see Image 3

If instead after step 2 you also select from 10-20 secs and silence it with Ctrl+L then after 3 5odB amplifications it does inded remain silence  - see Image 4
 
**Expected behavior**
Envelopes should be able to fade to genuine zero amplitude silence - not just a close facsimile, an approximation.

An option for envelopes to produce linear fades _(and not just logarithmic fades)_

**Screenshots**
1) Step 2 - envelope tool used to create "silence"
![image](https://user-images.githubusercontent.com/50205984/147927671-f58b2605-5d0c-4317-8e56-50fd66a07a28.png)

2) The sounds of silence ...
![image](https://user-images.githubusercontent.com/50205984/147928237-c43d84c6-853c-420a-9df1-70ee3b72f503.png)

3) After Amplification you can see it wasn't silent at all
![image](https://user-images.githubusercontent.com/50205984/147929024-764e0df8-790e-470f-8586-5366ce3d89e6.png)

4) Proper silence amplified 50dB 3 times
![image](https://user-images.githubusercontent.com/50205984/147930382-659de5eb-08a1-46a0-bdfe-6e60311cfd1b.png)

**Additional information (please complete the following information):**
 - OS: all OS
 - Version 3.1.3 and all earlier at least to 2.0.0

**Additional context**
@SteveDaulton wrote in the Bugzilla thread
>In 'old' versions of Audacity, Envelopes could fade down by about -140 dB, and then step down to absolute silence.
>
>In 2.3.1 alpha, envelopes can fade down by about -140 dB, but no lower.
>
>In practice this is rarely of any consequence as the minimum level is below dither level, even at 24-bit integer, but **it is still enough to prevent "Detach at Silences" from working.**

**Comment by petersampsonaudacity** [comment] 2022-01-03 12:21
@SteveDaulton wrote to me offline when we discussed this

>This was a long time ago, but if I recall correctly the issue was fixed in some version of 1.3.x, but was then broken again.
In many cases it may not matter very much, but it does matter if you want to "Detach at Silences".
>
>Again if I recall correctly, the fixed version worked by using a short linear fade when the control point was below -140 dB. For example, a fade from 0 dB to silence would be a logarithmic curve from 0 dB to -140 dB, followed by a linear fade from -140 dB to absolute silence.
>
>It's  so darned fiddly to make fades that go close to zero. In my opinion, envelopes should be linear by default (much easier to make precise fades), with an option for logarithmic fades (for backward compatibility).

**Comment by Penikov** [comment] 2022-01-10 10:28
I think this is not a bug, but specifics of signal processing.

If we change a default waveform scale in preferences to Logarithmic, we'll see a true amplification scale from -60 dB to 0 dB:

![изображение](https://user-images.githubusercontent.com/25851359/148749988-31c73387-ab87-4972-843e-fb2a49d1081f.png)

It means we haven't ever gotten true silence.  Because the Envelope tool does not erase the signal but reduces the waveform up to -60 dB. 

That's why the signal stays still after 3x 50dB amplification. Because there is no absolute zero. The signal is still there. It is just reduced.

And this behaviour is a cause why Datach at Silences doesn't work with envelope silence. Because there is no silence.

So, in my opinion there is not a bug on the calculation side, but a UX-specific issue.

**Comment by werame** [comment] 2022-01-26 18:27
Bottom line is that one needs more than exp envelopes for professional audio, despite what the "theory" of hearing might say. Most DAWs will give that kind of choice:

![image](https://user-images.githubusercontent.com/97036286/151217526-b580137e-e913-4faf-9a16-5151b4ffb1a2.png)

![image](https://user-images.githubusercontent.com/97036286/151224142-0d2891c8-75f4-4425-ab86-946a499da1db.png)


By the way, SuperCollider has the same annoying issue that a "pure" \exp envelope cannot reach zero. But most stuff people use in SC including the default (co)sine envelope used by Ndef [for audio] don't have that problem... because it's not an exp envelope (but equal power cross-fade).

**Comment by ShoneBrooks** [comment] 2022-05-12 20:19
I upgraded from v3.0.3 to v3.1.3 today and suddenly found that the Fade In and Fade Out (linear) also no longer fade from/to silence. Looks like the issue has been noted here, but hope the fix gets applied to that linear Fade tool as well as the Envelope tool.

**Comment by SteveDaulton** [comment] 2022-05-12 20:39
> Fade In and Fade Out (linear) also no longer fade from/to silence.

They do for me.

**Comment by ShoneBrooks** [comment] 2022-05-12 20:51
Screenshot showing tail end of Fade Out (in the darker segment to the left) and generated silence (in the lighter highlighted segment to the right):
![Fade Out](https://user-images.githubusercontent.com/105459525/168165916-a2397a1e-6a51-4aa1-8f0b-53819c8f7de5.png)
.

**Comment by petersampsonaudacity** [comment] 2022-05-13 08:26
Works for me on W10 with 3.1.3

1) genearate a 10 second chirp
2) Fade Out
3) move cursor to end of ttack
4) zoom in a lot
5) Observe: the audio fades to zero/silence

![image](https://user-images.githubusercontent.com/50205984/168242910-9dc5c3d3-693d-4d15-b84d-fea8b66446b8.png)

**Comment by SteveDaulton** [comment] 2022-05-13 12:11
> Screenshot showing tail end of Fade Out (in the darker segment to the left) and generated silence (in the lighter highlighted segment to the right):

I suspect you are seeing this issue: #2929

**Comment by ShoneBrooks** [comment] 2022-05-13 12:20
@SteveDaulton I believe you are correct. Thank you.

**Comment by LWinterberg** [comment] 2022-06-08 19:34
We need to properly introduce automation down the line anyway, at which point this will get addressed. Closing for now.

**Closed by LWinterberg** 2022-06-08 19:34 UTC
Labels: bug, P4, regression, Known Issue
