### ISSUE TITLE
In 3.2.2 Mixer/Meter Controls Toolbars do not retain their sizing. Regression on 3.2.1

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#4057] opened 2022-12-12 14:17 UTC
### Bug description

3.2.2. Meter Toolbars do not seem to remember their positioning across Audacity sessions.  This is a regression on 3.2.1.

### Steps to reproduce

1) Open Audacity 3.2.2
2) Tools > Reset Configuration
3) Drag left-edge of Speaker Meter/Mixer down to create new Toolbar row
4) Drag right-edge of Speaker Meter/Mixer over to the right so that meter extends the full width of the screen.
5) Exit Audacity
6) Open Audacity 3.2.2

### Expected behavior

Speaker Meter/Mixer should remain stretched as it was set before restarting Audacity

### Actual behavior

Speaker Meter/Mixer reverts to default size

If instead I replace step 6, above with "Open Audacity 3.2.1" if appears to work properly.  So Audacity 3.2.2 seems to be saving the information correctly.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Toolbars as saved:
![Toolbars003](https://user-images.githubusercontent.com/76828213/207068049-f6b2074a-973d-43e6-abd0-79e93c589234.png)

Audacity 3.2.2 when restarted:
![Toolbars004](https://user-images.githubusercontent.com/76828213/207068161-6331cb58-e756-4164-a64b-81e240ecfbc3.png)

**Comment by JohnColket** [comment] 2022-12-12 14:19
This issue was reported by forum user Pnokio: https://forum.audacityteam.org/viewtopic.php?p=460486#p460486

**Comment by petersampsonaudacity** [comment] 2022-12-12 14:25
Looks like a duplicate of:

 3.2.2 prohibits re-docked double-height meter toolbars - and reverts extended meter toolbar to default length on re-launch #4049

**Comment by Ryan-Miller-Audacity** [comment] 2022-12-14 12:56
Reopening this issue to declutter and separate out #4049

**Comment by Ryan-Miller-Audacity** [comment] 2022-12-14 13:01
Utilizing this issue going forward over #4049 to reduce clutter and assigning this a P3 priority as it is an inconvenience to users, but is easily workable as well.

**Comment by petersampsonaudacity** [comment] 2022-12-14 13:03
Another user report/complaint re this on the Forum:
https://forum.audacityteam.org/viewtopic.php?f=46&t=128251&p=460815

**Comment by petersampsonaudacity** [comment] 2022-12-14 13:05
This also impacts my personal workflow - as I always work with an extended length recording meter.

**Comment by petersampsonaudacity** [comment] 2022-12-15 09:52
@Ryan-Miller-Audacity wrote in issue #4049 about this issue _(it was originally reported in 4049 before being split off here)_

>... this should definitely be fixed. Changes to the interface should be retained when closing the program or saving a project and closing the program which is currently not the case.

**Comment by SteveDaulton** [comment] 2023-01-15 17:25
Is there a workaround for this? It's really annoying to have to manually resize the meters on every launch, and they are virtually useless at the default size.

**Closed** 2023-01-20 12:37 UTC
Labels: bug, P3, regression, duplicate

**Comment by petersampsonaudacity** [comment] 2023-01-20 13:46
@LWinterberg  this bug duplicates part of:

 **3.2.2 prohibits re-docked double-height meter toolbars #4049**

**Comment by Ryan-Miller-Audacity** [comment] 2023-01-23 20:26
Verified this fix on MacOS as well as Windows. Mixer/Meter toolbars properly retain their sizing. This includes between opening and closing the same Audacity version as well as (mocking) an update from a previous version to a newer version.
