### ISSUE TITLE
Bug in Audacity 2.4.1

### ISSUE THREAD

**Issue by Marco-Lugo** [audacity/audacity#541] opened 2020-05-27 16:14 UTC
**Describe the bug**
A crash.

**To Reproduce**
1. Go to 'Tracks'.
2. Click on 'Add New'.
3. Click on 'Mono Track'.
4. Double click the Gain slider on the left of the new audio track.
5. In the open request named "Gain" cancel the zero value.
6. Boom! A crash occurs.

**Expected behavior**
Not a crash! :D

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version Audacity 2.4.1

In the zip file you can find an MP4 video that show the reproduction of the bug:
[Audacity bug.zip](https://github.com/audacity/audacity/files/4689972/Audacity.bug.zip)

**Comment by JamesCrook** [comment] 2020-05-28 13:25
Works for me (no crash)
Please check your steps to see if you missed out some crucial step.

**Comment by Marco-Lugo** [comment] 2020-05-28 14:25
Re: [audacity/audacity] Bug in Audacity 2.4.1 (#541)



Ciao James,

in data giovedì 28 maggio 2020, alle ore 15:26, hai scritto:





Works for me (no crash)
Please check your steps to see if you missed out some crucial step.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.



Hi James,
For me is perfectly replicable.
In the zip file you can found the dump generated by audacity after the crash.

Kind Regards.

Marco Lugo


--
I migliori saluti,                        Scrivi a:
 Marco                                luponero2k@tin.it

**Comment by petersampsonaudacity** [comment] 2020-05-28 14:31
Works for me on W10 - no crash

**Comment by JamesCrook** [comment] 2020-05-28 15:19
I see some extra steps in the video.  I'm guessing:

1. Go to 'Tracks'.
2. Click on 'Add New'.
3. Click on 'Mono Track'.
4. Double click the Gain slider on the left of the new audio track.
5. Press right arrow key
6. Press delete key
7. Press Enter
8. Boom! A crash occurs.

However that works for me too.  Also works with Italian language selected.
Was that the sequence of keys you pressed?

**Comment by Marco-Lugo** [comment] 2020-05-28 15:22
When the requester named "Gain" come up don't click in the edit gadget but leave the "0" high lighted and press the backspace key.

**Comment by JamesCrook** [comment] 2020-05-28 15:35
I've just tried that:
a) With the delete left key, followed by the enter key
b) With the left arrow key, followed by the enter key

In both cases works fine for me.

**Comment by Marco-Lugo** [comment] 2020-05-28 17:24
James at this point, if you can, try it on a PC different from that you use.
There is a video of the crash, there is a report with a dump, there is a complete description of how to reproduce it.
I think that an user can't make more. :)

**Comment by JamesCrook** [comment] 2020-05-28 17:50
Marco - Thanks you for the report and the details.
My/Audacity's problem is that we can't progress it until/unless we can reproduce it on our machines.  We DO believe you.  We can see it crashing in the video!

We have tried it on two machines, with no crash.  It looks like we will have trouble tracking it down.  If we make progress we'll report it here.

**Comment by lllucius** [comment] 2020-05-28 18:02
I've tried it here as well (and I'll give it a try again in a bit).  And like James, I can't reproduce it either.

**Comment by lllucius** [comment] 2020-05-28 18:04
I take that back!  I CAN reproduce it here.  Let me dig a bit and I'll comment more.

**Comment by lllucius** [comment] 2020-05-28 19:35
James, try it with a release build.

**Comment by JamesCrook** [comment] 2020-05-28 21:24
I am trying with 2.4.1 actual release (which is a release build :-) ).  What am I missing?

**Comment by lllucius** [comment] 2020-05-28 21:58
Great...no I can't get it to happen again.  :-(  Grrr.  Let me see if I can pin it down.

**Comment by lllucius** [comment] 2020-05-29 00:33
James, we may not be able to recreate the issue, but we do have a visual clue something isn't right.  Try the steps in a Debug build.  You'll see the slider in the dialog go all the way to the left.  In a Release build it doesn't move at all.

**Comment by lllucius** [comment] 2020-05-29 00:56
Good news Marco.  I'm pretty sure I've found the cause.  While I can't reproduce the crash directly, I am able to simulate it.  Your comment about the "-nan" above clued was the key to finding it.

But #2458 created to resolve it:

https://bugzilla.audacityteam.org/show_bug.cgi?id=2458

**Comment by lllucius** [comment] 2020-05-29 01:10
Fix committed here:

https://github.com/audacity/audacity/commit/8ae8e0f

Closing this bug. Thanks Marco for reporting it (and being patient with us :-)).

**Closed by lllucius** 2020-05-29 01:10 UTC

**Comment by Marco-Lugo** [comment] 2020-05-29 10:42
Thanks Lucius and James. :)
If you want a quick test I'm disponible.

**Comment by JamesCrook** [comment] 2020-05-29 12:07
@Marco-Lugo  please try windows 'artifact' from here; (top right corner where it says 'Artifacts 4'
https://github.com/audacity/audacity/runs/718875503

**Comment by Marco-Lugo** [comment] 2020-05-29 13:44
I tested it and the bug is fixed!
When there will be an official installer with this fix?
Thanks again :)

**Comment by JamesCrook** [comment] 2020-05-29 14:02
Great!

We plan to release 2.4.2 22nd June https://wiki.audacityteam.org/wiki/Next_Release
However, our experience is that we usually find new bugs close to release and have to delay to fix them.  We will update that page with progress.

Feel free to contact me or Leland (lllucius) directly about anything Audacity related, and thanks for your bug report and details, and testing confirmed fixed.
