### ISSUE TITLE
Audacity Freezes Upon Adjusting Real Time Effects with Live Monitoring

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#6311] opened 2024-04-19 10:48 UTC
### Bug description

If the User chooses to add and adjust a real-time effect on a track in Audacity, while the Live Monitoring featuer is turned on, Audacity will freeze. 

### Steps to reproduce

1. Launch Audacity
2. Enable 'Audible Input Monitoring' in Preferences
3. Start recording into a new track
4. While recording, add a new real time effect
5. Adjust any of the parameters of the real time effect while recording
6. Observe result

### Expected behavior

Audacity shouldn't freeze when the User adjusts a real time effect during live input monitoring. 

### Actual behavior

Audacity freezes when the User adjusts a real time effect during live input monitoring. 

### Audacity Version

latest beta

### Operating system

Windows, Linux

### Additional context

This is reproducible on 3.3.3, 3.4.0, 3.4.1 and release-3.5.0 latest build.

**Comment by dozzzzer** [comment] 2024-04-19 11:34
Duplicate of https://github.com/audacity/audacity/issues/5218

**Closed by dozzzzer** 2024-04-19 11:34 UTC
Labels: bug, P3, crash / freeze
