### ISSUE TITLE
Data folder placement: use XDG dirs on Linux

### ISSUE THREAD

**Issue by es20490446e** [audacity/audacity#453] opened 2020-03-10 12:18 UTC
On Linux the Audacity data folder is on:
~/.audacity-data

Most likely it should be:
~/.config/audacity

**Comment by SteveDaulton** [comment] 2020-03-10 13:16
Thanks for your feedback Alberto. We  are aware of this issue and it is
logged on our issue tracker.

Resolving the issue is a bit more complex than may first appear as we would
want to develop an upgrade path for existing users that avoids losing their
Preference and plug-in settings, and avoids leaving debris in their home
folder. Currently our (very small) team of volunteers have their hands full
with higher priority issues.

Steve

**Comment by JamesCrook** [comment] 2021-05-14 16:14
This is tracked in our bugzilla database at:
https://bugzilla.audacityteam.org/show_bug.cgi?id=2201

Closing in favour of the bugzilla bug (which is more extensive)
Cross referenced to here, for completeness.

**Comment by DC7IA** [comment] 2021-10-29 21:24
> Most likely it should be:
> ~/.config/audacity

Actually it should be taken from the appropriate variable.

Specification: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by es20490446e** [comment] 2021-10-29 23:07
On a rolling release distro, Manjaro, If I do:
echo $XDG_CONFIG_HOME

The output is empty.

So we should use the variable only if not empty. Otherwise:
$HOME/.config/audacity

**Comment by imciner2** [comment] 2021-10-30 01:51
If there is an option to use GLib directly, then just calling `g_get_user_config_dir()` will give you the user config dir respecting the variable if it exists and providing the default of `$HOME/.config` if it doesn't - removing the need to perform that logic directly in the code.

**Comment by es20490446e** [comment] 2021-10-30 10:43
I wonder if there's even a single user in the world which config folder isn't under ".config"... but anyway.

**Comment by DC7IA** [comment] 2021-10-30 12:46
> On a rolling release distro, Manjaro, If I do: echo $XDG_CONFIG_HOME
> 
> The output is empty.
> 
> So we should use the variable only if not empty. Otherwise: $HOME/.config/audacity

Exactly. If not set, just use $HOME/.config/audacity

But please do not put cache or other data in there, that is **only** for configs. The idea is that you can simply copy or sync that folder to a new Linux machine and all your settings are the same, but cache and data aren't copy. As well as state/lock files.

For everything **not** config, the appropriate folder has to be used.

Otherwise things break when people start to sync their folders.

**Comment by es20490446e** [comment] 2021-10-30 13:10
Cache is ".cache".

**Comment by DC7IA** [comment] 2021-10-30 13:22
> Cache is ".cache".

Again, only if the variable isn't set. It could be elsewhere.

**Comment by es20490446e** [comment] 2021-10-30 16:08
I'm just messing with you.

**Comment by ryliejamesthomas** [comment] 2021-11-01 19:55
See also: https://github.com/audacity/audacity/issues/412

**Comment by Jorengarenar** [comment] 2021-11-05 17:50
> I wonder if there's even a single user in the world which config folder isn't under ".config"... but anyway.

Yes, me. `XDG_CONFIG_HOME` is `~/.local/config`

**Comment by itaranto** [comment] 2022-03-24 21:35
Please fix this, users are tired to deal with "junk" under their home directories.

**Closed** 2022-06-24 14:21 UTC
Labels: Request, Linux

**Comment by shmerl** [comment] 2022-07-08 02:44
So this will be included in the next release of audacity?

**Comment by LWinterberg** [comment] 2022-07-08 08:53
It already is included in the next release of Audacity, you can test the alpha on https://audacityteam.org/nightly. 

There is no release date yet, but you can follow the progress on https://github.com/audacity/audacity/milestone/8

**Comment by FranzXaver** [comment] 2022-07-08 12:42
> It already is included in the next release of Audacity, you can test the alpha on https://audacityteam.org/nightly.
> 
> There is no release date yet, but you can follow the progress on https://github.com/audacity/audacity/milestone/8

I just tested the latest alpha (audacity-linux-3.2.0-alpha-20220708+aca9aaf-x64.AppImage) and it still creates a folder .audacity directly in my home? 

`echo $XDG_CONFIG_HOME

/home/XXX/.config`

**Comment by LWinterberg** [comment] 2022-07-08 13:32
Seems like that particular instance was overlooked! Thanks for finding it @FranzXaver, I made #3201 for it.
