### ISSUE TITLE
Filter curve tool help link is broken

### ISSUE THREAD

**Issue by jpear1** [audacity/audacity#633] opened 2020-07-27 20:18 UTC
**Describe the bug**
The link to the online manual for filter curve eq tool is broken.

**To Reproduce**
1. Record some short audio clip
2. Select it
3. Open Effect -> Filter Curve...
4. Click on the question mark on the bottom of the new window
5. Click on the link with the text "view the Manual online"
6. The link leads to a 404 page

**Expected behavior**

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version Audacity 2.4.2

**Comment by SteveDaulton** [comment] 2020-07-28 09:19
Thanks for the report. I can confirm that this also happens on Linux, so I assume it is the same on all platforms.
I'll log it on our bug tracker.
I think I know what the problem is, so hopefully it will be fixed in the next Audacity release.

**Comment by SteveDaulton** [comment] 2020-07-28 11:34
This has been fixed for  the next release.

**Closed by SteveDaulton** 2020-07-28 11:34 UTC
