### ISSUE TITLE
Interface goes blank when opening a project.

### ISSUE THREAD

**Issue by Antony-Edward-Stark** [audacity/audacity#7227] opened 2024-09-02 11:27 UTC
### Bug description

The whole working area of audacity goes blank when opening ausacity project file.

### Steps to reproduce

1. Open audacity
2.  Open any project 

### Expected behavior

The work should be seen.

### Actual behavior

The working interface goes blank on startup
[Screencast from 2024-09-02 16-50-07.webm](https://github.com/user-attachments/assets/69cd4a58-ac96-4feb-9180-0b278662436c)

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

**Comment by Antony-Edward-Stark** [comment] 2024-09-02 11:36
But I was able to copy some, not all, clips to a new project.

**Comment by petersampsonaudacity** [comment] 2024-09-03 09:59
I cannot reproduce this on W10 with current release 3.6.1 or the latest Beta test build I have for the upcoming 3.6.2

**Comment by LWinterberg** [comment] 2024-09-03 10:42
This is fixed in 3.6.2

**Closed by LWinterberg** 2024-09-03 10:42 UTC
Labels: bug, Linux
