### ISSUE TITLE
Macro creation says nope

### ISSUE THREAD

**Issue by Milkanoobie** [audacity/audacity#3952] opened 2022-11-17 02:56 UTC
### Bug description

I'm running Audacity as Admin and I go to make a macro using Filter Curve EQ and edit the parameters of Filter Curve EQ, and it crashes Audacity.  
(I'm on Windows 10 so unclear as to why it says NT)

Operating system: Windows NT
                  10.0.19044 
CPU: amd64
     family 25 model 80 stepping 0
     12 CPUs

GPU: UNKNOWN

Crash reason:  EXCEPTION_ACCESS_VIOLATION_READ
Crash address: 0x80
Process uptime: 102 seconds

Thread 0 (crashed)
 <no frames>

Thread 1
 <no frames>

Thread 2
 <no frames>

Thread 3
 <no frames>

Thread 4
 <no frames>

Thread 5
 <no frames>

Thread 6
 <no frames>

Thread 7
 <no frames>

Thread 8
 <no frames>

Thread 9
 <no frames>

Thread 10
 <no frames>

Thread 11
 <no frames>

Thread 12
 <no frames>

Thread 13
 <no frames>

Thread 14
 <no frames>

Thread 15
 <no frames>

Thread 16
 <no frames>

Thread 17
 <no frames>

Thread 18
 <no frames>

Thread 19
 <no frames>

Thread 20
 <no frames>

Thread 21
 <no frames>

Thread 22
 <no frames>

Loaded modules:
0x7ff686e10000 - 0x7ff68803afff  Audacity.exe  3.2.1.0  (main)
0x7ffa63110000 - 0x7ffa63c48fff  wxmsw313u_core_vc_x64_custom.dll  3.1.3.0
0x7ffa67180000 - 0x7ffa6751ffff  wxbase313u_vc_x64_custom.dll  3.1.3.0
0x7ffa68ce0000 - 0x7ffa68f0afff  lib-theme-resources.dll  ???
0x7ffa78bd0000 - 0x7ffa78bedfff  msacm32.dll  6.2.19041.1
0x7ffa8b100000 - 0x7ffa8b13dfff  dataexchange.dll  6.2.19041.1387
0x7ffa8c2e0000 - 0x7ffa8c378fff  libcurl.dll  7.75.0.0
0x7ffa8c620000 - 0x7ffa8c6aafff  opus.dll  ???
0x7ffa90080000 - 0x7ffa9010dfff  msvcp140.dll  14.32.31332.0
0x7ffa910b0000 - 0x7ffa9115efff  vorbisenc.dll  ???
0x7ffa91ca0000 - 0x7ffa91cbefff  wxbase313u_xml_vc_x64_custom.dll  3.1.3.0
0x7ffa91cc0000 - 0x7ffa91da9fff  vorbis.dll  ???
0x7ffa91fb0000 - 0x7ffa91fe2fff  libexpat.dll  ???
0x7ffa91ff0000 - 0x7ffa9209dfff  sndfile.dll  1.0.31.0
0x7ffa92180000 - 0x7ffa92195fff  lib-ipc.dll  ???
0x7ffa921a0000 - 0x7ffa921dafff  portaudio_x64.dll  ???
0x7ffa921e0000 - 0x7ffa92299fff  wxmsw313u_html_vc_x64_custom.dll  3.1.3.0
0x7ffa922a0000 - 0x7ffa92384fff  wxmsw313u_aui_vc_x64_custom.dll  3.1.3.0
0x7ffa926d0000 - 0x7ffa92716fff  FLAC.dll  ???
0x7ffa92720000 - 0x7ffa9275cfff  wavpackdll.dll  5.4.0.0
0x7ffa93210000 - 0x7ffa93220fff  lib-uuid.dll  ???
0x7ffa93230000 - 0x7ffa93299fff  mpg123.dll  ???
0x7ffa932f0000 - 0x7ffa9330afff  VCRUNTIME140.dll  14.32.31332.0
0x7ffa95810000 - 0x7ffa95839fff  FLAC++.dll  ???
0x7ffa958a0000 - 0x7ffa958b3fff  ogg.dll  ???
0x7ffa95af0000 - 0x7ffa95b05fff  vorbisfile.dll  ???
0x7ffa95b10000 - 0x7ffa95baafff  lib-math.dll  ???
0x7ffa95f60000 - 0x7ffa95f83fff  zlib1.dll  1.2.11.0
0x7ffa95f90000 - 0x7ffa95ffefff  lib-theme.dll  ???
0x7ffa96090000 - 0x7ffa9612bfff  dsound.dll  6.2.19041.1
0x7ffa96160000 - 0x7ffa96173fff  portmidi.dll  ???
0x7ffa96180000 - 0x7ffa961bffff  wxmsw313u_qa_vc_x64_custom.dll  3.1.3.0
0x7ffa96550000 - 0x7ffa96556fff  msimg32.dll  6.2.19041.1466
0x7ffa9aeb0000 - 0x7ffa9aee9fff  lib-network-manager.dll  ???
0x7ffa9aef0000 - 0x7ffa9af43fff  lib-track.dll  ???
0x7ffa9afe0000 - 0x7ffa9b005fff  lib-strings.dll  ???
0x7ffa9b0b0000 - 0x7ffa9b0d1fff  lib-string-utils.dll  ???
0x7ffa9b0e0000 - 0x7ffa9b130fff  lib-ffmpeg-support.dll  ???
0x7ffa9b320000 - 0x7ffa9b336fff  lib-utility.dll  ???
0x7ffa9b450000 - 0x7ffa9b481fff  lib-preferences.dll  ???
0x7ffa9b610000 - 0x7ffa9b63bfff  lib-files.dll  ???
0x7ffa9bbb0000 - 0x7ffa9bbc5fff  lib-exceptions.dll  ???
0x7ffa9bef0000 - 0x7ffa9bf1dfff  lib-xml.dll  ???
0x7ffa9c190000 - 0x7ffa9c1f5fff  oleacc.dll  7.2.19041.746
0x7ffa9c4e0000 - 0x7ffa9c4f3fff  lib-basic-ui.dll  ???
0x7ffa9c500000 - 0x7ffa9c522fff  lib-registries.dll  ???
0x7ffa9d3d0000 - 0x7ffa9d40ffff  lib-cloud-audiocom.dll  ???
0x7ffa9d7f0000 - 0x7ffa9d89bfff  TextShaping.dll  ???
0x7ffaa0340000 - 0x7ffaa0373fff  lib-audio-devices.dll  ???
0x7ffaa2120000 - 0x7ffaa213ffff  lib-components.dll  ???
0x7ffaa2330000 - 0x7ffaa2428fff  textinputframework.dll  6.2.19041.2075
0x7ffaa2600000 - 0x7ffaa2620fff  lib-project.dll  ???
0x7ffaa2b80000 - 0x7ffaa2bb8fff  lib-sentry-reporting.dll  ???
0x7ffaa2d80000 - 0x7ffaa2d92fff  lib-cloud-upload.dll  ???
0x7ffaa4440000 - 0x7ffaa4468fff  lib-screen-geometry.dll  ???
0x7ffaa5d80000 - 0x7ffaa5da5fff  ncryptsslp.dll  6.2.19041.546
0x7ffaa6540000 - 0x7ffaa6562fff  lib-project-history.dll  ???
0x7ffaa65d0000 - 0x7ffaa65e4fff  lib-transactions.dll  ???
0x7ffaa6800000 - 0x7ffaa6819fff  lib-url-schemes.dll  ???
0x7ffaa8590000 - 0x7ffaa8598fff  wsock32.dll  6.2.19041.1
0x7ffaa85a0000 - 0x7ffaa85b4fff  mskeyprotect.dll  6.2.19041.1202
0x7ffaa8960000 - 0x7ffaa896bfff  secur32.dll  6.2.19041.546
0x7ffaa9660000 - 0x7ffaa9676fff  lib-graphics.dll  ???
0x7ffaa9680000 - 0x7ffaa969bfff  lib-audio-graph.dll  ???
0x7ffaa96a0000 - 0x7ffaa96f0fff  lib-module-manager.dll  ???
0x7ffaa9700000 - 0x7ffaa9729fff  lib-sample-track.dll  ???
0x7ffaaac60000 - 0x7ffaaacf7fff  winspool.drv  6.2.19041.2251
0x7ffaac280000 - 0x7ffaac2a5fff  winmmbase.dll  6.2.19041.1
0x7ffaacce0000 - 0x7ffaacd06fff  winmm.dll  6.2.19041.546
0x7ffaad940000 - 0x7ffaad95cfff  lib-project-rate.dll  ???
0x7ffab0ca0000 - 0x7ffab0cabfff  VCRUNTIME140_1.dll  14.32.31332.0
0x7ffab1670000 - 0x7ffab169bfff  dbgcore.dll  6.2.19041.789
0x7ffab3900000 - 0x7ffab3b99fff  comctl32.dll  6.10.19041.1110
0x7ffab3cc0000 - 0x7ffab3d44fff  MMDevAPI.dll  6.2.19041.1503
0x7ffab3d50000 - 0x7ffab3ed1fff  AudioSes.dll  6.2.19041.1865
0x7ffab4b10000 - 0x7ffab4cf3fff  dbghelp.dll  6.2.19041.867
0x7ffab5e20000 - 0x7ffab6082fff  d3d11.dll  6.2.19041.2075
0x7ffab64f0000 - 0x7ffab66d2fff  dcomp.dll  6.2.19041.2075
0x7ffab6a60000 - 0x7ffab6dbdfff  CoreUIComponents.dll  6.2.19041.546
0x7ffab6dc0000 - 0x7ffab6eb1fff  CoreMessaging.dll  6.2.19041.2193
0x7ffab72d0000 - 0x7ffab74cffff  twinapi.appcore.dll  6.2.19041.1865
0x7ffab7e70000 - 0x7ffab7e79fff  version.dll  6.2.19041.546
0x7ffab7e80000 - 0x7ffab7f10fff  apphelp.dll  6.2.19041.2075
0x7ffab7f90000 - 0x7ffab7fd5fff  wdmaud.drv  6.2.19041.1
0x7ffab8380000 - 0x7ffab83fffff  FWPUCLNT.DLL  6.2.19041.2006
0x7ffab8480000 - 0x7ffab8489fff  avrt.dll  6.2.19041.546
0x7ffab8740000 - 0x7ffab8749fff  rasadhlp.dll  6.2.19041.546
0x7ffab8a10000 - 0x7ffab8a1afff  midimap.dll  6.2.19041.488
0x7ffab8c10000 - 0x7ffab8c1cfff  msacm32.drv  6.2.19041.488
0x7ffab9340000 - 0x7ffab9346fff  MSVCP140_CODECVT_IDS.dll  14.32.31332.0
0x7ffab93e0000 - 0x7ffab93e8fff  ksuser.dll  6.2.19041.1
0x7ffaba020000 - 0x7ffaba173fff  WinTypes.dll  6.2.19041.2130
0x7ffabaab0000 - 0x7ffabac63fff  WindowsCodecs.dll  6.2.19041.1706
0x7ffabad40000 - 0x7ffabadddfff  uxtheme.dll  6.2.19041.2193
0x7ffabaeb0000 - 0x7ffabaec3fff  resourcepolicyclient.dll  6.2.19041.546
0x7ffabb270000 - 0x7ffabb281fff  kernel.appcore.dll  6.2.19041.546
0x7ffabb490000 - 0x7ffabbc21fff  windows.storage.dll  6.2.19041.2251
0x7ffabbc90000 - 0x7ffabbd82fff  dxgi.dll  6.2.19041.2075
0x7ffabc2f0000 - 0x7ffabc386fff  schannel.dll  6.2.19041.2194
0x7ffabc4f0000 - 0x7ffabc522fff  ntmarta.dll  6.2.19041.546
0x7ffabc810000 - 0x7ffabc84afff  IPHLPAPI.DLL  6.2.19041.1865
0x7ffabc8a0000 - 0x7ffabc969fff  dnsapi.dll  6.2.19041.1865
0x7ffabcb20000 - 0x7ffabcb89fff  mswsock.dll  6.2.19041.546
0x7ffabcd30000 - 0x7ffabcd3bfff  CRYPTBASE.DLL  6.2.19041.546
0x7ffabcdc0000 - 0x7ffabcdeffff  wldp.dll  6.2.19041.2075
0x7ffabcdf0000 - 0x7ffabce2afff  ntasn1.dll  6.2.19041.546
0x7ffabce30000 - 0x7ffabce56fff  ncrypt.dll  6.2.19041.662
0x7ffabd110000 - 0x7ffabd13bfff  devobj.dll  6.2.19041.1620
0x7ffabd220000 - 0x7ffabd231fff  umpdc.dll  ???
0x7ffabd240000 - 0x7ffabd28afff  powrprof.dll  6.2.19041.546
0x7ffabd290000 - 0x7ffabd2c1fff  sspicli.dll  6.2.19041.2130
0x7ffabd310000 - 0x7ffabd32efff  profapi.dll  6.2.19041.844
0x7ffabd440000 - 0x7ffabd595fff  crypt32.dll  6.2.19041.1889
0x7ffabd5a0000 - 0x7ffabd69ffff  ucrtbase.dll  6.2.19041.789
0x7ffabd6a0000 - 0x7ffabd73cfff  msvcp_win.dll  6.2.19041.789
0x7ffabd740000 - 0x7ffabd84efff  gdi32full.dll  6.2.19041.2130
0x7ffabd850000 - 0x7ffabd89dfff  cfgmgr32.dll  6.2.19041.1620
0x7ffabd8a0000 - 0x7ffabdb71fff  KERNELBASE.dll  6.2.19041.2193
0x7ffabdb80000 - 0x7ffabdc01fff  bcryptPrimitives.dll  6.2.19041.1415
0x7ffabdcc0000 - 0x7ffabdce1fff  win32u.dll  6.2.19041.2251
0x7ffabdcf0000 - 0x7ffabdd16fff  bcrypt.dll  6.2.19041.1023
0x7ffabdda0000 - 0x7ffabe0f3fff  combase.dll  6.2.19041.2130
0x7ffabe100000 - 0x7ffabe1aefff  clbcatq.dll  2001.12.10941.16384
0x7ffabe230000 - 0x7ffabe25afff  gdi32.dll  6.2.19041.2130
0x7ffabe6d0000 - 0x7ffabe7f4fff  rpcrt4.dll  6.2.19041.1806
0x7ffabe800000 - 0x7ffabe8acfff  SHCore.dll  6.2.19041.1865
0x7ffabe8b0000 - 0x7ffabe9d9fff  ole32.dll  6.2.19041.1202
0x7ffabe9e0000 - 0x7ffabea11fff  imm32.dll  6.2.19041.2193
0x7ffabea20000 - 0x7ffabeaf9fff  comdlg32.dll  6.2.19041.1806
0x7ffabeb00000 - 0x7ffabf242fff  shell32.dll  6.2.19041.2075
0x7ffabf250000 - 0x7ffabf2fdfff  advapi32.dll  6.2.19041.2130
0x7ffabf310000 - 0x7ffabf3abfff  sechost.dll  6.2.19041.1865
0x7ffabf3b0000 - 0x7ffabf46efff  kernel32.dll  6.2.19041.2251
0x7ffabf470000 - 0x7ffabf584fff  msctf.dll  6.2.19041.2193
0x7ffabf590000 - 0x7ffabf62dfff  msvcrt.dll  7.0.19041.546
0x7ffabf6c0000 - 0x7ffabf78cfff  oleaut32.dll  6.2.19041.985
0x7ffabf7f0000 - 0x7ffabf844fff  shlwapi.dll  6.2.19041.2075
0x7ffabfa60000 - 0x7ffabfa67fff  nsi.dll  6.2.19041.610
0x7ffabfa70000 - 0x7ffabfadafff  ws2_32.dll  6.2.19041.546
0x7ffabfae0000 - 0x7ffabfc7cfff  user32.dll  6.2.19041.2130
0x7ffabfc80000 - 0x7ffabfc87fff  psapi.dll  6.2.19041.546
0x7ffabfcd0000 - 0x7ffabfec7fff  ntdll.dll  6.2.19041.2130

### Steps to reproduce

go to tools/macro manager/new/insert Filter Curve EQ/ Edit parameters

### Expected behavior

it should allow me to create a macro 

### Actual behavior

it crashes Audacity

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by petersampsonaudacity** [comment] 2022-11-17 09:13
This was reported earlier as:
 Crash editing Amplify (and some other effects) macro parameters #3769 

And this has been fixed for the upcoming 3..2.2

**Comment by LWinterberg** [comment] 2022-11-17 09:27
duplicate of https://github.com/audacity/audacity/issues/3769

**Closed by LWinterberg** 2022-11-17 09:27 UTC
Labels: bug
