### ISSUE TITLE
Faults when adding realtime effects to audio that is already playing

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4865] opened 2023-06-29 12:22 UTC
### Bug description
There are a couple of faults when adding realtime effects to audio that is already playing.

1) adding a fresh RT effect to audio that is playing with existing realtime effects
2) adding a first RT effect to audio that that is playing

Audio stops playing, cursor moves rapidly to the end, audio is moved leftwards, cursor again moves rapidly to the end and then cursor returns to T=0

This is a regression on 3.3.3 

I tested this on @saintmatthieu 's hotfix branch build for #4859 as this is likely to replace the latest alpha and the results from this build are listed here.

Testing with the latest 3.4.0 alpha I also get errors, I can add the extra RT effect, but
a) the effect is not applied 
b) trying to adjust RT effect parametrs causes Audacity to hang and then a short time later crash.

### Steps to reproduce
1. get some audio
2. add a couple of realtime effects (_or just skip this step)_
3. Press play
4. Observe: Audio plays with RF effect applied _(if present)_
5. Press: Add effect in the RT effects panel
6. Add another RT effect
7. Observe: Audio stops playing, cursor moves rapidly to the end, audio is moved leftwards, cursor again moves rapidly to the end and then cursor returns to T=0

### Expected behavior
RT effects should be added and implemented by Audacity while Audacity is playing

### Actual behavior
Adding an RT effect while audio is playing causes Audacity to stop the playback and then exhibit erratic cursor behaviors

### Audacity Version
@saintmatthieu 's hotfix branch build for #4859:   audacity-win-3.4.0-alpha-20230629+0feda0a-x64

### Operating system
Windows 10 

### Additional context
See also:   Non-op realtime effects (incl. the built-ins) #4859

**Comment by dozzzzer** [comment] 2023-06-29 12:26
Duplicate of #4864

**Closed by dozzzzer** 2023-06-29 12:26 UTC
Labels: bug, regression, Effects

**Comment by petersampsonaudacity** [comment] 2023-06-29 15:39
Testing on W10 with @saintmatthieu 's latest branch build for this:  audacity-win-3.4.0-alpha-20230629+9e1333a-x64

All seems to be well now with regards to #4859 and #486r / #4865 in this branch build.

a) RT effects work properly from the effects stack
b) an initial  RT effect can be successfully added to audio that is already playing
c) an additional  RT effect can be successfully added to audio that is already playing with other RT effects applied
