### ISSUE TITLE
Dark Mode is a travesty.

### ISSUE THREAD

**Issue by iriscal** [audacity/audacity#4910] opened 2023-07-14 01:55 UTC
### Your idea

Dark Mode needs to be made complete.

### Problem to be solved

The title bar is white.
The menu bar and all its menus are white.
The preferences window is white.
The scroll bars are white.
The status bar is white.
The "snap" drop-down is white.
The time format selection context menu is white.
None of these things should be white, in a true dark mode.
![image](https://github.com/audacity/audacity/assets/11424910/09ac30e0-8546-4cd8-bf5f-056f6dc24baf)

**Comment by petersampsonaudacity** [comment] 2023-07-14 07:26
This is a known issue, logged a long time ago.

It is unlikely to be fixed while Audacity continues to use WXwidgets - in later versions of Audacity a plane exists to move to Qt - this is when dark mode may be addressed properly.

**Comment by LWinterberg** [comment] 2023-07-14 08:15
Duplicate of https://github.com/audacity/audacity/issues/1296

**Closed by LWinterberg** 2023-07-14 08:15 UTC
Labels: Enhancement Request
