### ISSUE TITLE
Plot Spectrum misbehaves for square wave

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2384] opened 2022-01-05 13:09 UTC
**Describe the bug**
Plot Spectrum misbehaves for square wave.

Originally logged on Bugzilla by @Paul-Licameli in May2015 as 971
https://bugzilla.audacityteam.org/show_bug.cgi?id=971

**To Reproduce**
1. Generate  Tone -  Square, no alias of exactly 430.664062 Hz.
2. View with Analyze, Spectrum, and a Rectangular window and window size 2048.
3. Resize the window horizontally
4. Observe: the heights of the lines indicating the overtones varies.  As the window narrows, the lines tend to become shorter though varying up and down, and they may disappear completely when the window narrows enough.

Similar problems can be seen with the other algorithms.

**Expected behavior**
Overtone lines not to vary as window size changes

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: all
 - Version: all - but recently re-tested on 3.1.3

**Additional context**
Steve wrote recently in the Bugzilla thread
>I think this is an example of: https://github.com/audacity/audacity/issues/2238

**Comment by LWinterberg** [comment] 2024-11-26 09:04
Duplicate of https://github.com/audacity/audacity/issues/2238

**Closed by LWinterberg** 2024-11-26 09:04 UTC
Labels: AU3-bug, P4
