### ISSUE TITLE
Wrong switching of user presets in DTMF generator and Echo effect

### ISSUE THREAD

**Issue by pietro68** [audacity/audacity#2822] opened 2022-04-14 10:08 UTC
**Describe the bug**
So far this happens in the DTMF generator, most likely because it is the only effect which was transitioned to be stateless - another effect (Echo) showed this behavior while worked on to be made stateless.

**To Reproduce**
1. start Audacity
2. Generate | DTMF Tones...
3. click Manage button, Save Preset... call it presetA
4. change the settings to something else
5. click Manage button, Save Preset... call it presetB
6. select presetA
7. select presetB

Update (PRL): also try Import (which requires you first so save some settings using Export), and Factory Presets > Defaults.  Similar misbahevior.

**Actual behavior**
the current values are the values for presetA.

**Expected behavior**
the current values should be the values for presetB.

**Additional information (please complete the following information):**
 - OS: Win10
 - Version commit on master: 2a04bce

**Additional context**
Not 100% sure but I guess this is due to the usage of class EffectWithSettings<>

**Comment by DavidBailes** [comment] 2022-04-14 10:57
Steps 1-5, as above, then:
6. select presetA
7. select presetB

Actual behaviour: the current values are the values for presetA.

**Comment by DavidBailes** [comment] 2022-04-14 11:08
This is a regression wrt Audacity 3.1.3

**Comment by petersampsonaudacity** [comment] 2022-04-15 11:43
Testing on W10 with latest alpha master audacity-win-3.2.0-alpha-20220414+e78705b-x64-msvc2022
which incorporates the Pull Request:
Make echo stateless 2 #2801 

The same now happens with the **Echo** effect

**Comment by petersampsonaudacity** [comment] 2022-04-15 16:50
@Paul-Licameli  - I tested your latest branch build for this on W10  audacity-win-3.2.0-alpha-20220415+339512b-x64-msvc2022 

1) it works fine for Echo

2) but for DTMF 

a) at Step 5 the DTMF sequence and the Ampitude of setting A are restored  - but _**NOT**_ so the Duration

b) at Step 6 it looks as though B is restored properly - but that's presumably as the duration remains fro,m the setting at step 4

**Comment by petersampsonaudacity** [comment] 2022-04-16 15:46
@Paul-Licameli @LWinterberg @dozzzzer 
Further testing on 3.1.3 shows that for all the other generators (Chirp,Noise, Silence, Tone, Pluck and Rhythm Track) the Duration **_is_** stored as part of a user preset and is properly restored when that preset is invoked.

Thus it is **_only_** DTMF that fails to store the duration - and thus this inconsistency really should be fixed.  Do we need a new separate issue logged for this.

**Comment by Paul-Licameli** [comment] 2022-04-16 19:39
> @Paul-Licameli @LWinterberg @dozzzzer Further testing on 3.1.3 shows that for all the other generators (Chirp,Noise, Silence, Tone, Pluck and Rhythm Track) the Duration **_is_** stored as part of a user preset and is properly restored when that preset is invoked.
> 
> Thus it is **_only_** DTMF that fails to store the duration - and thus this inconsistency really should be fixed. Do we need a new separate issue logged for this.

Thanks.  Do not make another issue.

I knew that the treatment of duration in generators is odd and needs other work to complete my proposed fix.

DTMF was the first of the generators I rewrote.  All effects need some restructuring for “statelessness” to fix an old defect in the design of the effect system. They can and will be done individually.  Not all must be done for the next release — effects that are real-time capable, or could be made so, are the most important to do.  Pietro and I will be dividing that work.  Echo is so far the only proper effect (not a generator) to be rewritten.  As others are rewritten, they will need some attention for testing.  You will know which they are if you watch the commit logs.

All this applies to the third party effect families too.  I expect Ladspa to be done first, followed by Audio Units.  VST 2 and 3 and lv2 must also be done this release.  Vamp (analyzers only) and Nyquist (not real-time capable) can be left to a later release.

**Comment by Paul-Licameli** [comment] 2022-04-20 22:58
> @Paul-Licameli @LWinterberg @dozzzzer Further testing on 3.1.3 shows that for all the other generators (Chirp,Noise, Silence, Tone, Pluck and Rhythm Track) the Duration **_is_** stored as part of a user preset and is properly restored when that preset is invoked.
> 
> Thus it is **_only_** DTMF that fails to store the duration - and thus this inconsistency really should be fixed. Do we need a new separate issue logged for this.

You left out Risset Drum

**Comment by Paul-Licameli** [comment] 2022-04-20 23:32
> @Paul-Licameli @LWinterberg @dozzzzer Further testing on 3.1.3 shows that for all the other generators (Chirp,Noise, Silence, Tone, Pluck and Rhythm Track) the Duration **_is_** stored as part of a user preset and is properly restored when that preset is invoked.
> 
> Thus it is **_only_** DTMF that fails to store the duration - and thus this inconsistency really should be fixed. Do we need a new separate issue logged for this.

I find you are incorrect about the behavior of 3.1.3.  Exactly what I did with that version (which is following Pietro's steps):

- delete pluginsettings.cfg
- start Audacity
- open the Silence dialog (duration is its only control)
- Enter 10 in the control, Manage > Save Preset... , enter "ten", OK
- Enter 20 in the control, Manage > Save Preset... , enter "twenty", OK
- Manage > UserPresets > ten

Expected: control changes its value to 10
Observed: no change

So this problem with durations not saved in presets is a real problem, but not a regression in this development cycle.  I think it is an old problem never noticed before.

**Comment by Paul-Licameli** [comment] 2022-04-20 23:36
I made a new issue out of my last comment about the problem with duration.  My pull request restores behavior of user presets for Echo and DTMF as they were in 3.1.3, still with the incompleteness for DTMF duration but that is not a regression.  Vitaly has reviewed and approved it.  I will merge it and close this issue.

**Closed** 2022-04-20 23:37 UTC
Labels: bug, regression

**Comment by petersampsonaudacity** [comment] 2022-04-21 08:22
> You left out Risset Drum

And that's because Risset Drum doesn't have a duration field like the other generators.

**Comment by petersampsonaudacity** [comment] 2022-04-21 09:56
Testing on W10 with latest alpha master audacity-win-3.2.0-alpha-20220420+5b46f42-x64-msvc2022

I confirm that the user presets work properly for DTMF and echo

**Comment by Paul-Licameli** [comment] 2022-04-21 11:48
> > You left out Risset Drum
> 
> And that's because Risset Drum doesn't have a duration field like the other generators.

Hm, why not then?

**Comment by petersampsonaudacity** [comment] 2022-04-21 12:02
> > > You left out Risset Drum
> > 
> > 
> > And that's because Risset Drum doesn't have a duration field like the other generators.
> 
> Hm, why not then?

I'm no expert - but I'm guessing that it's because it's a short percussive drum beat - it doesn't seem to make sense to make a 30 second clip of something like that.

**Comment by dozzzzer** [comment] 2022-04-22 14:26
Verified both on MacOS Monterey and Win10 x64
