### ISSUE TITLE
Program crashes when checking for updates in macOS Sonoma 14.0

### ISSUE THREAD

**Issue by jwaldrip16** [audacity/audacity#5259] opened 2023-09-26 23:18 UTC
### Bug description

The program crashes when checking for update and shows an error called bad handling and bad address.updates

### Steps to reproduce

Updated to Mac Os Sonoma 14.0

### Expected behavior

It should say no updates are available

### Actual behavior

The program crashes when checking for update and shows an error called bad handling and bad address.

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by jwaldrip16** [comment] 2023-09-27 03:11
See previous issue # 4836

**Comment by dozzzzer** [comment] 2023-09-27 07:49
I cannot reproduce this with [the latest master](https://github.com/audacity/audacity/actions/runs/6317682945) on macOS 14.0

**Comment by crsib** [comment] 2023-09-27 10:47
This issue will be fixed in 3.4

**Closed by crsib** 2023-09-27 10:47 UTC
Labels: Could not reproduce, bug
