### ISSUE TITLE
Icons missing from dialog windows

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2279] opened 2021-12-13 13:28 UTC
**Describe the bug**
Icons (such as "Alert", "Error",...) are missing from pop-up message dialog screens

**To Reproduce**
1. Select a mono track
2. "Effect menu > Auto Duck"
3. Observe the generic icon placeholder  in the pop-up error message.

**Expected behavior**
The correct icon to be displayed

**Screenshots**

![error-message](https://user-images.githubusercontent.com/11681097/145820962-2b857b56-3b6f-41dd-b972-e35d96a79a31.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: 3.2.0-alpha-20211210

**Additional context**
Regression.

**Comment by SteveDaulton** [comment] 2021-12-13 13:29
May be related to https://github.com/audacity/audacity/issues/2270

**Comment by LWinterberg** [comment] 2021-12-23 18:59
I can reproduce this with 3.1.3 on Ubuntu 21.10

**Comment by nadrolinux** [comment] 2021-12-23 21:58
For me both icons and widgets like a check boxes, radio buttons, sliders, standard buttons etc. are missing. As you can see at attached screenshot I can't even see which options are enabled. I tried different Ubuntu and Audacity themes, but nothing helped. My platform: Audacity 3.1.3 (AppImage) + Ubuntu 21.10. I had the same problem with Audacity 3.1.2 (AppImage). Flatpak version looks good, however Flatpak version has problem with Pipewire, so at now all versions are broken for me.

![audacity_broken_widgets](https://user-images.githubusercontent.com/11942352/147294619-793c5736-6a4a-494c-b718-ef369d703aa8.png)

**Comment by LunaGNUisance** [comment] 2022-01-06 04:30
I've tried the Audacity 3.1.3 Appimage on Arch Linux/GNOME 41.2/X11 with the same results as @nadrolinux . The lack of a visible scrollbar makes it very hard to use. 
![appimage-widgets-missing-1](https://user-images.githubusercontent.com/78894455/148326787-c41f6fbc-bf51-4a77-ad7d-d7606db1700d.png)

I tried a few AppImages and the issue was present across all of them. I didn't bother with the Flatpak version.

I then tried to build it using [this AUR package,](https://aur.archlinux.org/packages/audacity-gtk4/) which failed early due to a conan issue.

I then tried to build it using [this AUR package](https://aur.archlinux.org/packages/audacity-wxgtk2/), which did work. It doesn't suffer from the same issue as the AppImage, and doesn't suffer from the same slowness as 2.4.1-4 with the same project file—the reason I tried an updated version of Audacity in the first place.

![audacity-wx-working-2](https://user-images.githubusercontent.com/78894455/148328232-be155d9b-7ad4-43b5-acbf-d1f2eb5829b5.png)

So, all in all, it works. Compiling it seems to be the best option.

**Comment by nadrolinux** [comment] 2022-01-09 21:04
I can confirm that manually compiled version works fine. I used simple settings from BUILDING.md:
`cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -Daudacity_use_ffmpeg=loaded ../audacity`

**Comment by Penikov** [comment] 2022-01-21 10:22
The issue is specific to Ubuntu 21.10 distro. 
I've checked recently 3.1.3 on MX Linux with Fluxbox DM and icons for errors and alerts (in particular, Auto Duck) are there.  
Also checked Debian 11xfce. Icons are available:
Audacity 3.1.3 Appimage:
![image](https://user-images.githubusercontent.com/25851359/150510400-c54e9bff-793f-4632-826e-758bfb33eeb0.png)
![image](https://user-images.githubusercontent.com/25851359/150510440-b23c7dbe-a0f5-4114-8c4d-8ea7fb60f316.png)

**Comment by SteveDaulton** [comment] 2022-01-21 10:35
> The issue is specific to Ubuntu 21.10 distro.



> **Additional information (please complete the following information):**
> 
>     * OS: Xubuntu 20.04
> 
>     * Version: 3.2.0-alpha-20211210

**Comment by LunaGNUisance** [comment] 2022-01-21 11:15
@Penikov Hello, I'm using Arch Linux and all of the AppImages (tested on two of my Arch machines) feature broken icons, missing scrollbars, among other missing or distorted graphical elements. Here's an example of the [3.1.3 AppImage I just downloaded from the Releases section in Github.](https://github.com/audacity/audacity/releases/download/Audacity-3.1.3/audacity-linux-3.1.3-x86_64.AppImage)
![audacity-images-broken](https://user-images.githubusercontent.com/78894455/150516884-43b5b0f1-272f-4f74-a755-f8962583ae51.png)

For example, it is impossible to tell whether an option (e.g. Check For Updates) is checked or not because the radio button is completely gone.
![audacity-check-for-updates-broken](https://user-images.githubusercontent.com/78894455/150517340-fa9ec6d9-0a48-4763-a11b-da5c1d29af5d.png)

@nadrolinux experiences exactly the same issues with the AppImages on Ubuntu 21.10.

**Comment by Penikov** [comment] 2022-01-21 11:17
> > The issue is specific to Ubuntu 21.10 distro.
> 
> > **Additional information (please complete the following information):**
> > ```
> > * OS: Xubuntu 20.04
> > 
> > * Version: 3.2.0-alpha-20211210
> > ```

I see. But I have checked with XFCE on Debian, Ubuntu 21.04, Ubuntu 21.10 (with recent updates). Broken icons have been revealed only on Ubuntu 21.10.

**Comment by Penikov** [comment] 2022-01-21 11:19
> @Penikov Hello, I'm using Arch Linux and all of the AppImages

Hello. What DE or DM are you using?

**Comment by LunaGNUisance** [comment] 2022-01-21 11:21
> > @Penikov Hello, I'm using Arch Linux and all of the AppImages
> 
> Hello. What DE or DM are you using?

GNOME 41.3. @nadrolinux suspects this to be a GTK4 issue.

**Comment by SteveDaulton** [comment] 2022-01-21 11:34
> @nadrolinux suspects this to be a GTK4 issue.

Xubuntu 20.04 does not have GTK4, but does show this bug.

**Comment by Penikov** [comment] 2022-01-21 11:55
> > > @Penikov Hello, I'm using Arch Linux and all of the AppImages
> > 
> > 
> > Hello. What DE or DM are you using?
> 
> GNOME 41.3. @nadrolinux suspects this to be a GTK4 issue.

This is 3.1.3 Appimage on manjaro. KDE

![image](https://user-images.githubusercontent.com/25851359/150522925-537f05a8-6c75-4dc1-b29a-cf8b7eb61588.png)


Hmm... Interesting...

**Comment by LunaGNUisance** [comment] 2022-01-21 12:21
> > > > @Penikov Hello, I'm using Arch Linux and all of the AppImages
> > > 
> > > 
> > > Hello. What DE or DM are you using?
> > 
> > 
> > GNOME 41.3. @nadrolinux suspects this to be a GTK4 issue.
> 
> This is 3.1.3 Appimage on manjaro. KDE
> 
> ![image](https://user-images.githubusercontent.com/25851359/150522925-537f05a8-6c75-4dc1-b29a-cf8b7eb61588.png)
> 
> Hmm... Interesting...

Here's OpenSUSE Tumbleweed KDE 5.23.5 on X11, which doesn't suffer from these UI issues:
![opensuse-kde-audacity-1](https://user-images.githubusercontent.com/78894455/150525561-6e0ac7b6-e87f-43f1-9476-a12633d91ac7.png)
![opensuse-kde-audacity-2](https://user-images.githubusercontent.com/78894455/150525592-923ea664-cb1f-49f5-a6dc-767e8ffeec7e.png)

It's most likely something to do with GTK, then. @SteveDaulton , do you have the exact same issues as I do with XFCE Xubuntu? Do you lack visible scrollbars and checkboxes, etc. or are just lacking icons?

**Comment by Penikov** [comment] 2022-01-21 13:20
I have updated my Manjaro instance recently and now Audacity shows me this at startup:

![image](https://user-images.githubusercontent.com/25851359/150533436-0185400e-57af-4558-97c9-aeb8fc242aaa.png)
![image](https://user-images.githubusercontent.com/25851359/150533445-67c611dc-5701-4560-9395-192046296f96.png)


What is also interesting is the console output when Audacity was launched from CLI: 
![image](https://user-images.githubusercontent.com/25851359/150533631-8496cae4-f248-4b83-b24f-63a14378fdf6.png)

I think there could be a clue to a root cause of broken images.

**Comment by SteveDaulton** [comment] 2022-01-21 13:21
> @SteveDaulton , do you have the exact same issues as I do with XFCE Xubuntu? Do you lack visible scrollbars and checkboxes, etc. or are just lacking icons?

Scroll bars are present. It's just the icons that are missing.

Note that the problem occurs when Audacity is built on Xubuntu 20.04. It does not occur with the AppImages built on Ubuntu 18.04 when run on Xubuntu 20.04.

**Comment by LWinterberg** [comment] 2022-09-09 11:09
Fixed by #3571

**Closed by LWinterberg** 2022-09-09 11:09 UTC
Labels: bug, regression, Linux

**Comment by ville-v** [comment] 2023-02-10 15:30
> Fixed by #3571

I just compiled version 3.2.4 on Xubuntu 20.04.5, and I am facing the same issue. Are there some steps I should follow to fix this?

![missing icons](https://user-images.githubusercontent.com/22340294/218130141-26b75d85-ce8c-46b7-8779-6a2b5fc663ab.png)

**Comment by sirius-c** [comment] 2023-02-21 20:51
Same issue as previous post with Audacity 3.2.4 on Xubuntu 22.04.1 LTS.
