### ISSUE TITLE
"Eating" a clip by un-trimming another clip misbehaves

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7757] opened 2024-11-20 11:30 UTC
### Steps to reproduce

1. Put two clips next to each other
2. Select the entire left-hand clip
3. Trim the right-hand one and move it closer 
4. Start un-trimming the right-hand clip so that it starts overlapping the left one

### Expected behavior

No flickering and the right-hand clip goes on top of the left-hand one

### Actual behavior

The clip flickers and the right-hand clip sometimes goes underneath, sometimes on top of the left-hand clip.

https://github.com/user-attachments/assets/a88fddaf-8c1b-40da-b25a-446740107283

### Audacity Version

Audacity 4 alpha

### Operating system

Windows, macOS, Linux

**Comment by grliszas14** [comment] 2024-11-20 11:34
It may be a duplicate of: https://github.com/audacity/audacity/issues/7657

**Comment by grliszas14** [comment] 2024-11-28 14:31
QA bulletpoints:
Both issues mentioned in the description should be fixed:
* no flickering when using hover trim handles
* currently edited clip should be on top

* additionally improved trim mouse cursor - it should stay being trim cursor no matter where you point your mouse at as long as you keep your mouse btn pressed
* fixed crash on deleting single selected clip (it was re-introduced somewhere along working with BPM changes)

**Comment by chinakov** [comment] 2024-12-02 14:25
Thanks, this is fixed.

**Closed** 2024-12-02 14:48 UTC
Labels: P1, bug
