### ISSUE TITLE
Crash editing Amplify (and some other effects) macro parameters

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3769] opened 2022-10-06 06:36 UTC
### Bug description

Reported to me by Larry Hudson who has for years taught classes in the use of Audacity for voiceover.

### Steps to reproduce

1. Tools > Macro Manager
2. Now in left pane, enter "My macro", or select existing macro name
3. Insert in right pane
4. Click Amplify in command list
5. Click "Edit Parameters" near the top
Crash!

But a known workaround:

0.  Select some sound, open Amplify once from the Effect menu, Esc key

Thereafter, editing the macro parameter is possible, so long as you do not close the Audacity project window in which you opened Amplify

### Expected behavior

No crash

### Actual behavior

a) _No response_  in some cases

b) in other cases one gets the ET-phone-home dialog

### Audacity Version

current master / alpha / nightly build

3.2.1

### Operating system

Windows, macOS, Linux

### Additional context

This bisects to 35581fa4b81753303a45b9229d89d8f2138c76e8 and does not affect all effects.

I don't know yet the complete list of effects that suffer.  Specific Amplify code wasn't changed.  It was instead things in the framework.  But Nyquist effects (example, Low-pass filter) do not have the problem.

Another rescue for this user could be to write a simple Nyquist effect to substitute for amplify and share it.

**Comment by petersampsonaudacity** [comment] 2022-10-06 15:09
Testing on W10 with 3.2.1   both **Graphic EQ** and **Filter Curve EQ** cause a crash too  -   I got the ET-phone-home-message and pressed the OK to send it on

**Comment by petersampsonaudacity** [comment] 2022-10-06 15:16
And **Autoduck** does the same

And two of the Vamp plugins:  **Bar and Beat Tracker: Bars**  and  **Bar and Beat Tracker: Beats**

**Comment by Paul-Licameli** [comment] 2022-10-06 16:44
Suspect effects include those that override the `Init` function

So these should be checked:
Nyquist (but negative, I checked)
Vamp
Amplify
AutoDuck
ChangeSpeed
ChangeTempo
Equalization
Classic Filters

**Comment by petersampsonaudacity** [comment] 2022-10-10 16:07
@Paul-Licameli @crsib @LWinterberg 

Testing with Paul's Branch build:  audacity-win-3.2.2-alpha-20221006+73eb7de-x64
**Fix crash when editing macro parameters of Amplify and others... Build Audacity #2740**

The following now do _**NOT**_ crash Audacity at Step of of the STR:
1. Amplify
2. Auto Duck
3. Classic Filters
4. Spectral Edit Shelves
5. Change Speed
6. Change Tempo

BUT the following still cause a crash as step 5
7. **Graphic EQ**
8. **Filter Curve EQ**
9. **Spectral Edit Parametric EQ**

**Comment by petersampsonaudacity** [comment] 2022-10-10 16:34
> Nor do they show up in the Analyze menu with the latest 3,3,0 alpha either - I will log this as a separate issue

Logged as:   3.3 alpha fails to load Vamp plugins #3795

**Comment by dozzzzer** [comment] 2022-10-11 10:35
I confirm the crashes in the three EQ effects from @petersampsonaudacity 's comment. The rest seem to not cause the crash.

**Comment by petersampsonaudacity** [comment] 2022-10-12 08:33
@Paul-Licameli @crsib @LWinterberg 

Testing with Paul's Branch build:  Fix crash when editing macro parameters of Amplify and others... Build Audacity #2750

I confirm that the three effects that still previously crashed Audacity when trying to set parameters in a Macro di _**NOT**_ do so now
7. **Graphic EQ**
8. **Filter Curve EQ**
9. **Spectral Edit Parametric EQ**

I also retested to confirm that the following still do _**NOT**_ crash Audacity at Step of of the STR:
1. Amplify
2. Auto Duck
3. Classic Filters
4. Spectral Edit Shelves
5. Change Speed
6. Change Tempo

So all looks OK with this bug now in Paul's branch build.

### Vamp
I still cannot test the Vamp plugins as these do not show up in the Analyze menu with  Paul's branch build

**Comment by petersampsonaudacity** [comment] 2022-10-12 10:29
BTW testing shows that this is a regression on 3.1.3 (introduced in 3.2.0)

**Comment by dozzzzer** [comment] 2022-10-17 15:43
Verified.

**Comment by petersampsonaudacity** [comment] 2022-10-17 16:31
I confirm this remains un-fixed in latest 3.2.2 Beta:  audacity-win-3.2.2-beta-20221017+31f4fee-x64-msvc2022

and in 3.3 alpha:  audacity-win-3.3.0-alpha-20221011+69764a4-x64-msvc2022

**Comment by dozzzzer** [comment] 2022-10-18 11:49
@petersampsonaudacity it's not yet merged into the release branch

**Comment by petersampsonaudacity** [comment] 2022-10-18 16:14
@dozzzzer I figured that...

so this was really a "nudge" to see if this could get merged, particularly since it's a P1 regression bug - and one that real-life users are falling foul of (as reported on the Forum)

**Comment by petersampsonaudacity** [comment] 2022-10-18 17:08
Testing on W10 with latest 3.2.2 Beta:  audacity-win-3.2.2-beta-20221018+1196ca9-x64-msvc2022

I confirm that the three effects that still previously crashed Audacity when trying to set parameters in a Macro do _**NOT**_ do so now in this Beta
7. **Graphic EQ**
8. **Filter Curve EQ**
9. **Spectral Edit Parametric EQ**

I also retested to confirm that the following still do _**NOT**_ crash Audacity at Step of of the STR:
1. Amplify
2. Auto Duck
3. Classic Filters
4. Spectral Edit Shelves
5. Change Speed
6. Change Tempo

So all looks OK with this bug now in the latest 3.2.2 Beta

**Closed** 2022-11-07 15:28 UTC
Labels: bug, P1, crash / freeze, regression, macros / scripting, Effects
