### ISSUE TITLE
Indication of hidden audio in clip

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2271] opened 2021-12-12 15:33 UTC
**Is your feature request related to a problem? Please describe.**
When a clip is edited or trimmed, it will initially have hidden audio (the "deleted" audio has not really been deleted, just hidden).
There is no indication of whether an audio clip has hidden audio or not.

**Describe the solution you'd like**
An indication of whether a clip is "what you see" or if there is also hidden audio

**Describe alternatives you've considered**

An indication in the clip graphic, such as:

![hidden](https://user-images.githubusercontent.com/11681097/145718506-2d7762d7-a56a-4e9a-ad38-2fbe31c961dd.png)

**Additional context**
It is possible (default behaviour) for projects to contain hidden audio that is no longer required by the user. In some cases this can bloat a project with GB of unwanted data, which will slow down the work process and may unnecessarily use excessive amounts of disk space.
As a first step, users should be aware of where and when the project contains hidden data.
There should also be an obvious way for users to remove hidden data, but that goes beyond this simple feature request.

**Comment by petersampsonaudacity** [comment] 2021-12-13 11:01
Maybe the hidden audio could be shown but be grayed-out (like muted audio is grayed-out)

**Comment by petersampsonaudacity** [comment] 2021-12-13 11:03
An additional right-click context menu for clips to "Show "Hidden Audio" could be useful too.

Debatable as to whether that should "unhide" the audio - or keep it hidden, but show it grayed-out.

**Comment by SteveDaulton** [comment] 2021-12-13 11:15
> An additional right-click context menu for clips to "Show "Hidden Audio" could be useful too.

If you mean *expand* the clip to reveal the hidden audio, there may not be sufficient room to do that if the clips have been moved after hiding the ends.

**Comment by petersampsonaudacity** [comment] 2021-12-13 12:02
> > An additional right-click context menu for clips to "Show "Hidden Audio" could be useful too.
> 
> If you mean _expand_ the clip to reveal the hidden audio, there may not be sufficient room to do that if the clips have been moved after hiding the ends.

Yes indeed - but you can show that which would be within the current zoom-level window.

**Comment by werame** [comment] 2022-01-25 11:37
It might be helpful if there were a similar indicator at the beginning of the clip, depending on whether anything has been "smart-trimmed" there.

**Comment by LWinterberg** [comment] 2022-03-03 20:56
duplicate of #1912

**Closed by LWinterberg** 2022-03-03 20:56 UTC
Labels: Enhancement Request, Design / UX, minor feature
