### ISSUE TITLE
AppImage doesn't start 

### ISSUE THREAD

**Issue by dev-nicolaos** [audacity/audacity#7585] opened 2024-10-20 06:46 UTC
### Steps to reproduce

Follow the instructions for [installing Audacity on Linux](https://support.audacityteam.org/basics/downloading-and-installing-audacity)

- Download the AppImage from the Audacity Home Page
- Mark the AppImage as executable
- Run the AppImage

### Expected behavior

Audacity launches

### Actual behavior

Nothing happens.

### Audacity Version

Other

### Operating system

Linux

### Additional context

Audacity Version: 3.6.4 (latest available at time of report)
OS: Fedora 40

I have verified that fuse is installed by running  `dnf fuse fuse-libs` per the link provided by the note on the instructions page.

Repeating the steps after restarting my computer yielded the same results. 

Attempting to run the AppImage from the terminal produces this output:

```
~/Downloads >  ./audacity-linux-3.6.4-x64.AppImage
/lib64/libatk-1.0.so.0
/lib64/libatk-bridge-2.0.so.0
/lib64/libcairo-gobject.so.2
/lib64/libcairo.so.2
/lib64/libgio-2.0.so.0
/lib64/libglib-2.0.so.0
/lib64/libgmodule-2.0.so.0
/lib64/libgobject-2.0.so.0
/lib64/libgthread-2.0.so.0
/usr/lib64/pipewire-0.3/jack/libjack.so.0
/lib64/libpixman-1.so.0
findlib: libportaudio.so: cannot open shared object file: No such file or directory
/home/nicolaos/Downloads/audacity-linux-3.6.4-x64.AppImage: Using fallback for library 'libportaudio.so'
/tmp/.mount_audaci02Fk1Q/bin/audacity: /tmp/.mount_audaci02Fk1Q/lib/libselinux.so.1: no version information available (required by /lib64/libgio-2.0.so.0)
/tmp/.mount_audaci02Fk1Q/bin/audacity: /tmp/.mount_audaci02Fk1Q/lib/libmount.so.1: version `MOUNT_2_40' not found (required by /lib64/libgio-2.0.so.0)
```

**Comment by kryksyh** [comment] 2024-10-20 07:13
@dev-nicolaos thank you for this report, the issue will be fixed in 3.7

Duplicate of #6233

**Closed by kryksyh** 2024-10-20 07:13 UTC
Labels: bug
