### ISSUE TITLE
Deselecting audio should clear the selection in the timeline

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2322] opened 2021-12-21 09:52 UTC
**Describe the bug**
The recent fix of  #2067 may introduce the behaviour when the selected region still stay even when the selection has been changed or cancelled.

That brings inconsistency to the playback looping flow.

**To Reproduce**
Steps to reproduce the behaviour:
1. Generate a chirp
2. Select a new looping region, then select a region on the waveform as shown on the picture below
![изображение](https://user-images.githubusercontent.com/25851359/146905263-90bd6e80-10e3-4e43-9c88-93b755525aa9.png)

3. Click at empty space below the track
Observe: the selection of the waveform is cancelled at the track, but it still stays at the timeline
![изображение](https://user-images.githubusercontent.com/25851359/146906041-1795f709-2121-47fb-a09f-77573d176b24.png)

4. Click the Play button
5. See the playback has been running from the beginning of the phantom waveform selection at the timeline

**Expected behaviour**
When the waveform selection is cancelled, there is no phantom region at the timeline. Playback starts from the beginning of the playback looping region, or from the audio cursor that should be placed before the end of the looping region.

For example:
In this case, playback should start from the cursor's point and when it will reach the end of the looping region, playback should be continued from the start of the looping.

But if the cursor stays behind the end of the looping region, the cursor should be ignored and playback should start from the beginning of the looping region:

![изображение](https://user-images.githubusercontent.com/25851359/146907090-8f467c4c-c898-49da-bd56-0945bcc3a122.png)

**Additional information (please complete the following information):**
 - Version: 3.1.3

**Comment by LWinterberg** [comment] 2021-12-21 10:15
You can use the arrow keys and enter to select/deselect audio from this "phantom" selection on different tracks, also in previous versions (even in the 3.1 versions in which the selection isn't visible). I'd say this is more of an accessibility thing and not-a-bug (cc @DavidBailes ? ), and in each case it's not introduced with that fix.

**Comment by petersampsonaudacity** [comment] 2021-12-21 10:22
Surely at Step 3 one would reasonably expect that with the disappearance of the selection then the gray play-region in the Timeline should also just disappear.

**Comment by LWinterberg** [comment] 2021-12-21 10:29
![image](https://user-images.githubusercontent.com/87814144/146914894-46df3526-8ed5-4f61-89df-494a8624c4d7.png)

3.0.3 has the same thing going on

**Comment by petersampsonaudacity** [comment] 2021-12-21 10:46
> 3.0.3 has the same thing going on

But that's because in 3.0.3 and earlier we had the concept of a "Play-Region" - that's what the double-headed arrow is.

We even had a command in the Transport sub- menus to lock the play region - using that would make the double-headed arrow turn red - and Audacity would then honor that locked-play region for playback rather than using any subsequent selection or cursor position.

But in 3.1 the "Play-Region" has been removed and so has its command and sub-commands in the Transport menu.

![image](https://user-images.githubusercontent.com/50205984/146917297-ca934a91-8f70-4a1e-bf84-2a060f62c77c.png)

**Comment by LWinterberg** [comment] 2021-12-21 10:52
![image](https://user-images.githubusercontent.com/87814144/146917642-3cd64024-0520-4de1-bd8e-3120931148ec.png)

The behavior of a "phantom" selection remains the same - the blue color is there in the previous screenshot, but if you use a locked play region it becomes more apparent.

**Comment by Paul-Licameli** [comment] 2021-12-21 11:55
Not a bug.  I will not fix it as requested.  Close this issue.

Selection of a time interval is meant to be an independent dimension of selection from the toggling of each track’s selected state.

One reason @SteveDaulton wanted this fixed is the case where there is no track.  But the selection affects generators or making a label with ctrl+b.  You need to see it.

**Comment by DavidBailes** [comment] 2021-12-21 13:24
> I'd say this is more of an accessibility thing and not-a-bug (cc @DavidBailes ? )

Not a bug, and not an accessibility problem either.

**Comment by Penikov** [comment] 2021-12-22 09:05
I think we need to reconsider this behaviour later.

**Comment by sahilsekr42** [comment] 2022-04-03 10:41
I've reproduced this error on my linux mint system and would like to work on this.Can anyone please assign this to me along with some suggestions like what might be causing this error as @Penikov mentioned it might be caused by fix of #2067 which was done in #2280 probably. I am new to this community so a little guidance will help a lot.

**Comment by SteveDaulton** [comment] 2022-04-03 12:36
"Selections" have two _dimensions_. There's the temporal selection, and the track(s) selection. The time selection _should_ be independent of the track(s) selection. This is an important feature (not a bug). For example, you should be able to select a time region (temporal selection) using the Selection Toolbar, irrespective of the number of tracks selected. The temporal selection should be visible in the Timeline regardless of how many (if any) tracks are selected.

This may change when multiple simultaneous temporal selections are supported, but until then, please don't break the way that it has successfully worked for 20 years.

As described, I completely agree with Paul and David that this is not a bug and should therefore be closed.

**Closed** 2022-04-03 19:08 UTC
Labels: Enhancement Request, P5, minor feature
