### ISSUE TITLE
Making a stereo track from tracks with different effects stacks - results in the bottom track's stack to be lost/discarded

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5166] opened 2023-09-07 16:31 UTC
### Bug description
When you make a stereo track from tracks with different effects stacks, this results in the bottom track's stack to be lost/discarded

### Steps to reproduce
1. generate a 30 second chirp
2. put Wahwah in its effects stack
3. new mono track
4. generate a 30 second DTMF
5. put Reverb in its effects stack
6. make a stereo track from the two mono tracks
7. Observe: the effects stack has only Wahwah
8. Split the stereo track
9. Observe: both tracks Have only Wahwah in their effects stack

### Expected behavior
This may be desired/design behavior, but at the very least the user should be warned that they will lose the lower track's effects stack and asked if they want to proceed.

Maybe there could be a "Don't show this again" checkbox
Maybe there should be a preference to control this behavior

If this is desired behavior it should be documented in the Manual.

### Actual behavior
The lower track loses forever its effects stack, discarded in favor of the upper tracks effects stack.

### Audacity Version
3.4.0 alpha and 3.3.3

### Operating system
Windows 10 but assume all OS

### Additional context
None

**Comment by Paul-Licameli** [comment] 2023-09-07 18:35
Thanks, Peter.

As I also lately wrote elsewhere, the feature that joins mono tracks into stereo is in an unstable state right now in alpha.  But in the release, if we still allow such merging, something must be done about this and other attributes of tracks.

The exhaustive list of other things I know of:

Name, selected state, gain, pan, muteness, solo-ness, spectrogram settings, waveform vertical scale type and range, view type(wave vs spectrum vs split) and split order and height proportions, color to be assigned to new clips — for these the left channel’s setting prevail and right channel’s are just discarded.

Sample rates and formats — disallow the merge if there is any difference.

**Comment by Paul-Licameli** [comment] 2023-09-07 18:43
“Split Order” means, which one is above, spectrum or waveform

**Comment by Paul-Licameli** [comment] 2023-09-07 18:44
Also the last known project tempo— and internal thing I must not forget, I think it could differ when there is cross project copy and paste

**Comment by dozzzzer** [comment] 2023-09-22 14:36
Not actual anymore since it was decided that the expected behavior in this case would be the effect stack of both mono tracks to be cleared while the effects from both stacks should be applied to the resulting stereo track.

See https://github.com/audacity/audacity/issues/5200

**Closed by dozzzzer** 2023-09-22 14:36 UTC
Labels: bug, P3, Tracks
