### ISSUE TITLE
Play-at-speed sometimes does not "finish" the playback

### ISSUE THREAD

**Issue by TheRealAyCe** [audacity/audacity#3888] opened 2022-11-02 15:22 UTC
### Bug description

After playback completes using play-at-speed, you must *sometimes* press Stop once the cursor has reached the end.

### Steps to reproduce

1. Drag in an audio file.
2. Use play-at-speed with a custom speed.
3. Wait for it to finish playing.
4. The playback must be explicitly stopped if you want to remove the track for example.

Try it with different lengths and speed settings.

### Expected behavior

It used to be the case that once play-at-speed finished, the playback would always be stopped automatically.

### Actual behavior

The cursor would sometimes stick to the end and the playback would technically still be running, as the Stop button must be pressed before editing can be done.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by Paul-Licameli** [comment] 2022-11-02 15:29
I think commit 7a2df4fe9ad26bf02162f89ecdb4a7317c854ff8 in the release-3.2.2 branch fixes this already

**Comment by samanth-jain** [comment] 2022-11-02 16:47
I am not able to reproduce this issue. It seems to be working fine. The playback stopped automatically.

**Comment by Ryan-Miller-Audacity** [comment] 2022-11-03 12:40
Yes @Paul-Licameli, I confirmed that this is fixed by David's work in #3792 and tested it within the most recent Release 3.2.2 build (https://github.com/audacity/audacity/actions/runs/3361522918) and verified that play mode is properly exited after using play-at-speed function.

**Closed by Ryan-Miller-Audacity** 2022-11-03 12:40 UTC
Labels: bug
