### ISSUE TITLE
Audacity Reverb GUI too small in realtime on Linux

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#4210] opened 2023-01-19 15:31 UTC
### Bug description

The GUI for  Audacity's Reverb effect (now  a "real-time" effect) is  too small so the sliders are unusable.

### Steps to reproduce

1. Add Audacity's Reverb effect to a track as a real-time effect
2. Open Reverb's interface

### Expected behavior

![expected](https://user-images.githubusercontent.com/11681097/213483675-a49b0851-62a6-4b44-bda0-1a10c5d332e2.png)

### Actual behavior

![reverb](https://user-images.githubusercontent.com/11681097/213483732-af28d3ed-4cac-49d7-93b4-829223098fae.png)

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by LWinterberg** [comment] 2023-01-19 15:45
![image](https://user-images.githubusercontent.com/87814144/213487445-5cbc56e9-46ee-403c-b925-f838c33fead3.png)
lgtm on windows

**Comment by petersampsonaudacity** [comment] 2023-01-19 17:38
OK on W10 - but it could benefit perhaps from a little more width:
![image](https://user-images.githubusercontent.com/50205984/213519310-301f9a72-36f9-452b-9d39-d3111cdd3d5d.png)

**Comment by Ryan-Miller-Audacity** [comment] 2023-02-03 13:29
Obviously the default Reverb GUI that Steve is seeing in Linux is not functionable; however, I do agree I think we could stand to widen the natural width of the popup for easier/more accurate scrubbing of the parameters.

**Comment by LWinterberg** [comment] 2023-02-03 14:06
![image](https://user-images.githubusercontent.com/87814144/216623066-50bcbddc-7eca-407a-9172-682881211490.png)

cannot reproduce on Linux either, even in HiDPI it's functional.

**Comment by SteveDaulton** [comment] 2023-02-03 14:47
Are you testing the Reverb effect as a "real-time" effect?

When I posted this bug report, Reverb was only available as a real-time effect.
In my  latest build, Reverb is available as either real-time or destructive. I don't see the issue when opening Reverb as a destructive effect. I do still see the problem when Reverb is used as a real-time effect in a track.

**Comment by LWinterberg** [comment] 2023-02-03 22:42
ah, yeah. I observe the same as you then; it indeed is too small in realtime view

**Comment by LWinterberg** [comment] 2024-10-15 10:31
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.

**Closed by LWinterberg** 2024-10-15 10:31 UTC
Labels: AU3-bug, P4, Linux
