### ISSUE TITLE
v3.1.3 - crash on Windows IME switch

### ISSUE THREAD

**Issue by nr1995** [audacity/audacity#2419] opened 2022-01-12 21:27 UTC
Hi, noob here.
Audacity freezes when switching language input via the in-built Windows 10 IME.
It may just be Chinese input.  Or it may be the act of switching itself.

The whole program becomes unresponsive,
and switching back to English input doesn't fix it.
Terminating the program and opening it up again in English input does the trick.

**Comment by Piglet1994** [comment] 2022-01-13 02:24
Yes,  I meet this problem from version 3.0.0, also use Chinese input, waiting to be fixed.

**Comment by LWinterberg** [comment] 2022-01-13 10:46
Duplicate of #805 - the workaround is to either use "Use dialog for the name of a new label" from the Track Preferences, or to use IME in compatibility mode.

**Closed by LWinterberg** 2022-01-13 10:46 UTC

**Comment by SteveDaulton** [comment] 2022-02-16 10:02
In notice that both this bug, and https://github.com/audacity/audacity/issues/805 have been closed, but no mention of a fix. Is that intentional?

**Comment by 0142929** [comment] 2023-10-27 09:54
The problem still exists, when I try to save an audio file, it crashes even in japanese ime A mode, I lost all my work in half an hour...
