### ISSUE TITLE
Audacity hangs when changing realtime effect parameters while recording

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3151] opened 2022-06-27 16:59 UTC
**Describe the bug**
In testing of https://github.com/audacity/audacity/issues/3073, it was discovered that attempting to edit sliders within the plugin interface while recording is active will cause Audacity to deadlock and become unresponsive.

**To Reproduce**
1. Start recording
2. Open realtime effects side panel
3. Select 'Audacity > Reverb'
4. Click gear icon of Reverb
5. Change any slider's position

**Actual behavior**
Audacity freezes/becomes unresponsive

**Expected behavior**
Audacity does not become unresponsive

**Additional information (please complete the following information):**
 - OS:  Windows 10
 - Version: latest master

**Comment by crsib** [comment] 2022-06-28 08:13
I'm not sure I agree with the exoected behavior. @Tantacrul what are your thoughts?

**Comment by Tantacrul** [comment] 2022-06-28 09:15
I think it makes sense that the user can tweak effects in the chain, even as they are recording. The only reason we'd prevent it would be as a temporary measure to avoid really bad stuttering or similar problems resulting from too much strain on the CPU. I would not call it desired behaviour.

Perhaps it does make sense to prevent the user from **adding** new realtime effects during recording because they can require a reasonable amount of CPU to initialise. But, again, I'd probably wait to see if it is a problem first. I'm going to close this as a 'wont fix' for now. If we find issues when RT effects are properly functioning, we'll solve them at that point.

Thanks!

**Comment by Paul-Licameli** [comment] 2022-06-28 12:10
Agree not to close this as a won't-fix.

There should not be a trap waiting for the user like that.

**Comment by pietro68** [comment] 2022-06-30 08:36
While trying to reproduce the problem, on commit `e1cb8f4` (start of the branch), I get a problem of a different sort which stops me at step 3; it persists also on `db4add8` (head of the branch). What I get is a failed assert, because an optional (mpTransportState) is found empty:

![image](https://user-images.githubusercontent.com/16491307/176631880-9354ca3f-edb9-4e65-b2e5-de55aff10ec1.png)


This on a Debug Windows build. This is  what I do to get there:

1) Tracks | Add New | Mono Track
2) make sure that the recording device is set to mono
3) press record
4) try instantiating a reverb in the sidebar

**Closed** 2022-07-08 10:49 UTC
Labels: bug, P1, crash / freeze
