### ISSUE TITLE
Effect plugin window beautifications

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#3090] opened 2022-06-16 19:50 UTC
Dev checklist:

* If `!mwState.expired()`: Power button is visible, no buttons on the right
* Otherwise: No power button:
  * **Apply** is always shown
  * **Preview** is shown if `mSupportsRealtime == true`  
* **Presets & Settings** is always shown

---------------------  

essentially a redesign of the existing play controls on plugins. 
<details><summary>see design files</summary>

![9 0](https://user-images.githubusercontent.com/87814144/174152014-4e24668e-eaf0-4e07-965c-b212a58ebac0.png)
![10 0](https://user-images.githubusercontent.com/87814144/174152035-d851dd76-cc06-48c0-b53c-639571bb49ce.png)
![11 0](https://user-images.githubusercontent.com/87814144/174152042-41c8bce8-7c92-4060-8611-d1041966aeb4.png)

</details>

Note: In addition to what's shown in the images, there needs to be a play/stop button

**Comment by LWinterberg** [comment] 2022-06-16 21:31
Why are they modal? They weren't modal in 3.1.3. And the designs show the user doing stuff with the UI while the effect settings are open.

**Comment by Paul-Licameli** [comment] 2022-06-16 21:44
> Why are they modal? They weren't modal in 3.1.3. And the designs show the user doing stuff with the UI while the effect settings are open.

Non-modal dialogs are inherently harder to do right.

Addressing this issue, putting the decorations in place on the dialog, may acutally be the easier way.

**Comment by LWinterberg** [comment] 2022-06-17 13:12
Okay. Spun off #3102 for later, and added this to the kanban board.

**Comment by DavidBailes** [comment] 2022-07-05 08:10
@LWinterberg 
1. Which types of plugins are going to be affected by these changes? Does this include Audacity's built-in plugins?
2. For VST, LV2 etc which don't have their graphical user interface enabled, are there going to be any changes? For example:
![image](https://user-images.githubusercontent.com/11887021/177281312-9d76d040-fec5-4442-8808-618149a3cd6a.png)

**Comment by Paul-Licameli** [comment] 2022-07-26 10:42
I observe that when opening the dialog from the sidebar, there is no button to close it other than the top bar decorations added by the operating system, shown here as macOS style.

Assuming the dialog can be so closed -- or also with the ESC key -- then there is no way to distinguish between keeping the changes you have tried, and cancelling them so the settings revert as they were before you opened it.

I think that's a design omission.  Do you?  @jessjwilliamson @LWinterberg @Tantacrul

**Comment by crsib** [comment] 2022-07-26 10:47
https://github.com/audacity/audacity/pull/3176#discussion_r929812957

**Comment by Tantacrul** [comment] 2022-07-26 11:07
For real time effects plug-ins, There is no need to cancel or confirm changes. For example, pressing escape would not undo or reset any changes you make.

**Comment by Paul-Licameli** [comment] 2022-07-26 11:27
So if I try settings changes, listen, don't like them, and just want to revert them all as they were -- then there is no way but to reset all all again exactly.

**Comment by jessjwilliamson** [comment] 2022-07-26 11:29
In this case you can either (if option is available in plugin or VST) to go back and reset to default plugin settings, or delete the plugin slot from the panel and apply it again, then start again

**Comment by crsib** [comment] 2022-07-26 11:30
>So if I try settings changes, listen, don't like them, and just want to revert them all as they were

The optimal way is obviously what Ableton does, but I say that is out of scope for 3.2.

**Comment by Paul-Licameli** [comment] 2022-07-26 11:32
In my opinion the extra effort to implement the Esc key would be worth the effort as a later enhancement, if not a necessity for the release.

I say this as the one who in the past carefully rewrote all click-drag-release mouse actions to respond to the Esc key and restore all state as it was at the start of the drag.

**Comment by crsib** [comment] 2022-07-26 11:59
The use case is quite different. It is normal to have multiple settings windows open so you can tweak several effect at once. It is expected behavior that settings are applied immediately. Reverting settings, and specifically reverting them using Esc may and will cause confusion when the dialog is closed unexpectedly. 

Stacked effects are really different from what happens during the usual, one-by-one processing.

![image](https://user-images.githubusercontent.com/2660628/181000505-f157db78-4612-479e-950e-f58ab2646285.png)

**Comment by Paul-Licameli** [comment] 2022-07-26 12:34
"When the dialog is closed unexpectedly"

So we could revert only in response to an explicit user action 🤷

**Comment by Tantacrul** [comment] 2022-07-26 12:40
I would definitely avoid using the escape key as a way of reverting settings. As someone who relies on RT effects, I’d find this unusual and I suspect it would be hard to learn. 

Generally, there is a dedicated 'reset' option in any given VST.

**Comment by jessjwilliamson** [comment] 2022-07-26 12:44
Yes, a lot of VST plugins will have an 'Init preset' (init short for initialized) which means resetting plugin back to default.

**Comment by Paul-Licameli** [comment] 2022-07-26 14:55
> Yes, a lot of VST plugins will have an 'Init preset' (init short for initialized) which means resetting plugin back to default.

"Back to default" is not the same as "back to the last state when I opened the dialog" which is what I suggest.

**Comment by Paul-Licameli** [comment] 2022-07-26 14:58
I found unintended mouse drags of all kinds to be bothersome and make Esc cancel them all, because there are often many things you can click and drag and you may miss the target you intended.  Maybe that's a sound design rule that doesn't apply here.

**Comment by Tantacrul** [comment] 2022-07-26 15:11
> "Back to default" is not the same as "back to the last state when I opened the dialog" which is what I suggest.
> 
> 

Yes, I understand that but I'm pretty sure it is over-design. It's not something you generally need with RT effects. On balance, it's better not to have something that could potentially undo a change you intended to leave there. Better to only build that type of functionality later if there's a call for it.

**Comment by Tantacrul** [comment] 2022-07-26 15:13
@jessjwilliamson - can you check a few other apps and report back in what the 'esc' shortcut does? That should really determine what we do too. My guess is it either closes the RealTime FX pop up or does nothing.

**Comment by crsib** [comment] 2022-07-26 15:14
>I found unintended mouse drags of all kinds to be bothersome and make Esc cancel them all

How is this the same? Reverting all the changes to Esc would be more similar to the case when you drag a bunch of bars in the way you like and everything is reverted back

**Comment by Tantacrul** [comment] 2022-07-26 15:17
Yeah, I think esc. being used to cancel changes is more useful / predictable when there is also a 'cancel' and 'apply' option.

**Comment by crsib** [comment] 2022-07-26 15:18
Ableton, Performer and Ardour do nothing, Reaper save setting and closes the window.

**Comment by jessjwilliamson** [comment] 2022-07-26 15:18
I 100% assume Esc does nothing in other apps (Logic I checked anyway). I don't think I've even myself ever used esc key in DAW/mixing situation.

**Comment by Paul-Licameli** [comment] 2022-07-26 20:03
Okay, forget about Esc.

But a different question is whether to "ModifyState

**Comment by crsib** [comment] 2022-07-26 20:27
The last time I discussed this @Tantacrul we agreed that undo support is out of scope for Audacity 3.2. This is what number of DAWs do anyway. For consistency sake we probably should share RealtimeEffectState so it is fully immune to the undo, but I say let's see if it causes much confusion first. I do not expect that this change will take any significant amount of time and I am open to implement it now.

**Closed** 2022-08-25 21:18 UTC
Labels: Task, plugins, UI

**Comment by dozzzzer** [comment] 2022-08-29 10:32
Some cosmetic findings. Will be moved to a separate ticket due its minor severity.

When switching off the power button, it slightly shifts to the left:

<img width="326" alt="image" src="https://user-images.githubusercontent.com/70063970/187181418-460c7ce4-aa19-4e44-814f-c402b8e7f3c5.png">

**Stop Preview** label doesn't fit the button:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/70063970/187181754-52b62808-1778-41fb-ac02-3419b2dd3084.png">

**Comment by crsib** [comment] 2022-08-29 10:33
Looks like the off power button icon has a wrong size
