### ISSUE TITLE
"Fit to height" does not fit

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1422] opened 2021-08-04 10:33 UTC
**Describe the bug**
"Fit to height" should fit tracks within the visible track area (when possible), leaving a small amount of empty space below the bottom track. In the latest AppImage version, it resizes tracks too big (looks like the new drag bar may have been forgotten),

**To Reproduce**
1. Launch Audacity
2. Add two audio tracks
3. "View menu > Track Size > Fit vertically"
4. Observe that the tracks have been resized too tall to fit in the viewable track space.

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version audacity-linux-3.0.4-alpha-20210803+f90698c-x86_64.AppImage

**Additional context**
https://manual.audacityteam.org/man/view_menu_track_size.html#fit_to_height

**Comment by petersampsonaudacity** [comment] 2021-08-04 11:28
Same is true on W10 with audacity-win-3.0.4-alpha-20210803+f90698c-64bit

This is a regression on 3.0.3

**Comment by petersampsonaudacity** [comment] 2021-08-12 15:52
Isn't this a duplicate of Issue #1339
 Affordances: Verify that "Fit to Height" acts as in version 3.0.3. #1339

**Comment by petersampsonaudacity** [comment] 2021-08-12 16:03
Now that 1442 has been pulled into master

Testing on W10 with latest alpha master build for 3.1.0/3.0.4 

This now woks fine

![image](https://user-images.githubusercontent.com/50205984/129229530-d8f64012-206e-4b70-9f2d-a7004cba0625.png)

**Closed by petersampsonaudacity** 2021-08-12 16:03 UTC
Labels: bug, release 3.1, regression
