### ISSUE TITLE
AppImage fails to load FFmpeg

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1201] opened 2021-06-30 15:59 UTC
**Describe the bug**
Self built Audacity 3.0.2 loads FFmpeg correctly.
audacity-linux-3.0.3-RC2-x86_64.AppImage fails to load FFmpeg (regression against 3.0.2)

**To Reproduce**
1. Launch audacity-linux-3.0.3-RC2-x86_64.AppImage
2. Observe error message:
`FFmpeg was configured in Preferences and successfully loaded before, 
but this time Audacity failed to load it at startup. 
You may want to go back to Preferences > Libraries and re-configure it.`

**Expected behavior**
FFmpeg will be loaded.

**Comment by petersampsonaudacity** [comment] 2021-06-30 17:17
That is almost certainly because you have 32-bit FFmpeg installed and you are running 64-bit Audacity.

I had similar on Windows until I installed  64-bit FFmpeg from Buanzo's new page on his site.
https://lame.buanzo.org/ffmpeg64audacity.php

Does the Linux FFmpeg page need updating?
https://alphamanual.audacityteam.org/man/Installing_and_updating_Audacity_on_Linux#linff

**Comment by SteveDaulton** [comment] 2021-06-30 22:50
I'm on 64-bit Linux, so I've been using 64-bit builds of Audacity and FFmpeg for years.

**Comment by crsib** [comment] 2021-07-01 14:10
@SteveDaulton can you please provide some insight on your setup?

I've managed to compile FFMPEG using a modified script from Leland and after setting up `DT_RUNPATH` everything works like a charm for me. I will share the script after a bit of polishing.

The question is, what we do for this release anyway. 

For the next release I plan:

* Upgrade the FFMPEG (once again, yes), so system FFMPEG can be used on Linux
* Provide a set of scripts on how to build the "correct" version, so it can be easily buildable by users.

@AnitaBats @Tantacrul FYI

**Comment by SteveDaulton** [comment] 2021-07-01 15:09
My system is pretty standard Xubuntu 20.04 LTS.
FFmpeg library installed from official Ubuntu repository.

I prefer to use the system FFmpeg library as it is a dependency for many other audio apps.
The usual  way to build Audacity 2.x with FFmpeg support was to disable dynamic loading during 'configure' - this has worked without any problems for years.

Self built 3.0.4-alpha-20210628 also loads FFmpeg without any problems.

FFmpeg version: F(58.29.100),C(58.54.100),U(56.31.100)

**Comment by crsib** [comment] 2021-07-01 15:18
Lemme have a quick look into the loader code

**Comment by crsib** [comment] 2021-07-01 17:35
Seems like at least avcodec 58 has an incompatible interface with what Audacity expects for dynamic loading. While functions are similar, structures, used as contexts, have nothing in common. For example, `AVCodecContext` has changed around its 5th member and has changed significantly. 

When you build against the system headers, this is not a problem. By default, however, Audacity is built against FFMPEG 2.2 (avformat 55). What is even more problematic - we build AppImage on 18.04, so avcodec 58 is not available as a system library for us as well (at least without PPA).

@shoogle any thoughts?

**Comment by SpencerWF** [comment] 2021-09-03 11:58
Hello @crsib and @AnitaBats, is there a temporary workaround for this release?

**Comment by SpencerWF** [comment] 2021-09-03 12:05
> Hello @crsib and @AnitaBats, is there a temporary workaround for this release?

Solution linked to in documentation for 3.0.3
https://gist.github.com/crsib/d985afddf739f91edb15c1abbaec21e7

**Comment by Penikov** [comment] 2021-09-23 11:39
Still remains in Audacity 3.1.0-alpha-20210921
![изображение](https://user-images.githubusercontent.com/25851359/134499914-aa09b429-5e82-4d98-82db-840b5a5fe2de.png)

**Comment by crsib** [comment] 2021-09-23 11:42
You have used a build from FFmpeg branch?

**Comment by Penikov** [comment] 2021-09-23 11:50
> 
> 
> You have used a build from FFmpeg branch?

Not yet. I've tried to reproduce the bug before the fix will be merged.

**Closed** 2021-09-24 18:03 UTC
Labels: bug, P2, release 3.1
