### ISSUE TITLE
"Get Info: Preferences" macro command crashes Audacity

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4798] opened 2023-06-16 12:47 UTC
### Bug description

When running Preferences command from the Get Info menu, Audacity crashes.

Sentry link: https://sentry.audacityteam.org/share/issue/9e646086c7d04ba09c12c6d8b3e97111/

### Steps to reproduce

1. Enable Extra menu in View > Extra Menu
2. Extra > Scriptables II > Get Info
3. select Type: Preferences and click **OK**
4. Observe

### Expected behavior

Corresponding info collected and presented in JSON format

### Actual behavior

A crash

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

### Additional context

Was first introduced in 3.3.0

**Comment by Paul-Licameli** [comment] 2023-06-16 14:33
For Commands, I don't observe the crash.  I do observe a very long delay before it completes.  Commands is loading every installed effect plug-in into memory.  That might crash in buggy third-party code, depending on what you have installed.

For Preferences, the bug is reproducible and the fix involves just a few null checks, and I wrote a PR to fix it.

Maybe you should separate two issues.

**Comment by crsib** [comment] 2023-06-16 14:39
I get a crash with a VST plugin, which works otherwise. So I doubt that the issue is related to the 3d party code.

**Comment by dozzzzer** [comment] 2023-06-16 18:57
> Maybe you should separate two issues.
OK, so here's the issue about Type=Commands crash: #4804

As for the Preferences, testing PR #4799 I see no crash anymore, however, after JSON formatted text is printed out, at the left upper corner of the screen there appears Privacy Policy link, which can be removed by config reset:

<img width="780" alt="Screenshot 2023-06-16 at 18 53 49" src="https://github.com/audacity/audacity/assets/70063970/27e6f119-b949-469b-882c-7c5817eb8653">

Anyways, this is a pretty minor issue and is logged as #4803 
@Paul-Licameli

**Comment by Paul-Licameli** [comment] 2023-06-16 19:55
Don’t close this issue until the PR is merged!

**Closed** 2023-06-21 13:07 UTC
Labels: bug, P3, crash / freeze, regression, macros / scripting

**Comment by chinakov** [comment] 2024-06-27 13:01
This issue is present once again on 3.5.1, and the latest master.

**Comment by petersampsonaudacity** [comment] 2025-01-28 11:25
Still present in 3.7.1 - and on latest 3.7.2 Beta
