### ISSUE TITLE
Audacity alters WAV file

### ISSUE THREAD

**Issue by jbaker6953** [audacity/audacity#2497] opened 2022-01-30 18:09 UTC
**Describe the bug**
Audacity alters audio data despite no user changes.

**To Reproduce**
1. Open a WAV file.
2. Export to WAV (same format, e.g., 16-bit 44.1kHz).
3. Compare audio.
4. WAV exported by Audacity has different sample values.

**Expected behavior**
Absent any changes made by the user, Audacity should not be changing audio data.

**Additional information (please complete the following information):**
 - Windows 10
 - Audacity 3.1.3 64-bit

**Comment by Pokechu22** [comment] 2022-01-30 18:10
Does #2387 describe your issue?

**Comment by jbaker6953** [comment] 2022-01-30 18:29
That seems a lot more convoluted, but perhaps. In my case literally nothing is being done to manipulate the waveform. Not even opening a tool. All that's required is to open the WAV with Audacity and export it without doing anything else. The WAV data is radically different afterwards.

For example, here's the original WAV:
![2022-01-30 10_26_21-HxD -  E__Music_12  If You Intend wav](https://user-images.githubusercontent.com/8323559/151712410-df9914b3-7893-4947-923f-e2635a47bbf6.png)

And here's the WAV exported by Audacity:
![2022-01-30 10_26_52-HxD -  E__Music_12  If You Intend2 wav](https://user-images.githubusercontent.com/8323559/151712462-67bc3d65-4981-4e96-8925-f118bce538b7.png)

**Comment by Pokechu22** [comment] 2022-01-30 18:42
Yeah, I'm pretty sure that's the same issue: you're seeing [dithering](https://en.wikipedia.org/wiki/Dither).  FFFF is -1, which is 1 away from 0 (just like 01 00 is).  Looks like #698 is supposed to fix that; if you have the ability to build Audacity for yourself you might want to test that PR and see if it solves the issue.

**Comment by jbaker6953** [comment] 2022-01-30 18:55
I used to be able to, but ever since they changed the build system a year or two back I haven't been successful in building for myself.

**Comment by LWinterberg** [comment] 2022-01-30 21:26
https://github.com/audacity/audacity/actions/runs/1734265332 has builds which fell out of CI

**Comment by LWinterberg** [comment] 2022-02-07 10:10
duplicate of https://github.com/audacity/audacity/issues/2387

**Closed by LWinterberg** 2022-02-07 10:10 UTC
