### ISSUE TITLE
Multiband Compressor crashes Audacity on MacOS Sonoma 14.3 Macbook Air M1

### ISSUE THREAD

**Issue by climbingOB** [audacity/audacity#5907] opened 2024-02-01 18:47 UTC
### Bug description

When I try to use the multiband compressor on Audacity on my mackbook air M1 running Sonoma 14.3, it gives me the following error: 
Crash reason:  EXC_BAD_ACCESS / KERN_PROTECTION_FAILURE
Crash address: 0x158ff6910
Process uptime: 87 seconds

### Steps to reproduce

1. Select audo track; 2. Under "Effect" toolbar, select AUMultibandCompressor

### Expected behavior

The compressor should open normally 

### Actual behavior

Crashing 

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by LWinterberg** [comment] 2024-02-02 08:26
Duplicate of https://github.com/audacity/audacity/issues/5799

**Closed by LWinterberg** 2024-02-02 08:26 UTC
Labels: bug
