### ISSUE TITLE
Another "smart" clip bug

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#2917] opened 2022-05-12 10:46 UTC
**Describe the bug**

**To Reproduce**
1. Generate a 30s chirp
2. Select a short section of audio in the chirp
3. Split delete (ctrl+alt+k).
4. Generate a tone using the default duration.

**Actual behavior**
All the clips have the wrong length and overlap:
![image](https://user-images.githubusercontent.com/11887021/168053488-d91e443e-a038-48ae-b988-5898f699267b.png)

**Expected behavior**
Behaviour in 3.1.3
![image](https://user-images.githubusercontent.com/11887021/168052653-1f76d255-b930-45ec-818c-73c7cc1ce77c.png)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version Audacity 3.2.0 alpha

**Additional context**
Regression wrt Audacity 3.1.3
Discovered when fixing: https://github.com/audacity/audacity/issues/2911

**Comment by petersampsonaudacity** [comment] 2022-05-12 11:13
Tested in W10 with latest alpha master audacity-win-3.2.0-alpha-20220511+aa0019f-x64-msvc2022

I confirm that this is a regression on 3.1.3

**Comment by dozzzzer** [comment] 2022-05-12 12:49
Working fine on MacOS Monterey.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/70063970/168078446-248e3ffd-fe86-4ee1-8cad-a8d5df95fbfc.png">

**Comment by DavidBailes** [comment] 2022-05-12 13:13
@dozzzzer , if between steps 3 and 4 you adjust the start of the selection so that it's slightly before the end of the first clip, does it still produce the expected results on MacOS?

**Comment by SteveDaulton** [comment] 2022-05-12 14:29
Confirmed on Linux with recent 3.2.0 alpha.
Does not occur with deaa3f

**Comment by petersampsonaudacity** [comment] 2022-05-12 15:11
Testing on my Macbook Pro macOS Monterey 12.3.1

I confirm I see the same errant bug behavior on Mac

**Comment by dozzzzer** [comment] 2022-05-12 15:18
Confirmed on macOS Monterey

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/70063970/168109809-c89c8001-03a8-460f-b7ec-9b1e92ed62fc.png">

**Comment by vsverchinsky** [comment] 2022-08-30 18:51
@dozzzzer this bug might be fixed with #3364 as well, I tried and cannot reproduce it any more, could you please confirm that later?

**Comment by petersampsonaudacity** [comment] 2022-08-31 09:38
@vsverchinsky @dozzzzer 

Testing on W10 with latest 3.2.0 alpha  

I can no longer replicate this on Windows

**Comment by vsverchinsky** [comment] 2022-08-31 11:45
> @vsverchinsky @dozzzzer
> 
> Testing on W10 with latest 3.2.0 alpha
> 
> I can no longer replicate this on Windows

Thanks!

**Comment by dozzzzer** [comment] 2022-08-31 11:56
Confirm this is no longer an issue on macOS either.

**Closed by dozzzzer** 2022-08-31 11:56 UTC
Labels: bug, P2, regression, Clips
