### ISSUE TITLE
The Incredible Shrinking Toolbar

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2865] opened 2022-04-27 20:30 UTC
**Describe the bug**
On Windows 10, if the time toolbar is undocked, then after opening preferences and pressing OK, the time control shrinks slightly.

**To Reproduce**
1. Undock the time toolbar and resize it larger
2. Open Preferences
3. Click "OK"

**Actual behavior**
The time toolbar shrinks a bit.

**Expected behavior**
The time toolbar to remain the size set in step 1.

**Screenshots**
![Audacity_01](https://user-images.githubusercontent.com/11681097/165625549-5c2319b1-3e97-4528-a509-84129c64fe32.png)

![Audacity_02](https://user-images.githubusercontent.com/11681097/165625590-bef49e4b-4664-4ada-81d9-d16d2eb5f60c.png)

**Additional information (please complete the following information):**
 - OS:  Windows 10
 - Version Audacity 3.1.3
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
Bug reported here: https://forum.audacityteam.org/viewtopic.php?f=70&t=124802

**Comment by petersampsonaudacity** [comment] 2022-04-28 08:23
Testing on W10 with latest alpha master

Not only does it shrink the first time you OK the prefs dialog - every subsequent use of prefs causes it to shrink even more each time.

**Comment by petersampsonaudacity** [comment] 2022-04-28 08:33
This is nit a regression - this bug has been in place ever since @JamesCrook first introduced the Time toolbar in 2.4.0 _(splitting it off from the old form Selection toolbar)_.

**Comment by LWinterberg** [comment] 2022-05-02 18:31
In that case I don't see us fixing this. It might incidentally get fixed with the replatform though.

**Closed by LWinterberg** 2022-05-02 18:31 UTC
Labels: bug, P3, Known Issue

**Comment by petersampsonaudacity** [comment] 2022-05-02 21:56
So now bugs are just being closed because they're not liked or no-one can be bothered to fix them !

This is clearly a bug and at the very least should remain open even if it's not gonna get fixed.
