### ISSUE TITLE
Frequently hangs when IME is "微軟倉頡, 中文 - 繁體, 香港特別行政區" and when press Ctrl-A or started typing.

### ISSUE THREAD

**Issue by johnnytemp** [audacity/audacity#3004] opened 2022-05-29 14:58 UTC
**Describe the bug**
Audacity always hangs when I press any keyboard shortcut (like Ctrl-A or Ctrl-V) or typing if my IME is Microsoft ChangJie for Traiditional Chinese, Hong Kong SAR.

**To Reproduce**
1. Set default IME to "Microsoft ChangJie (Traiditional Chinese, Hong Kong SAR)" (微軟倉頡, 中文 - 繁體, 香港特別行政區)
2. Open Audacity.
3. Open some audio file.
4. Just press Ctrl-A to select whole track, OR "Save project as" and type letters "ABC" in the filename.
5. Hangs forever.

**Actual behavior**
The program hangs forever. Need force quit.

**Expected behavior**
Not hang.

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: Audacity 3.1.3

**Comment by johnnytemp** [comment] 2022-05-29 15:00
Or even changing step 3 to "Type letter A (English input mode of ChangJie (倉頡) input method)" will hang immediately.

**Comment by LWinterberg** [comment] 2022-05-30 08:57
Duplicate of #805 - unfortunately, this is a bug with wxWidgets, and there's nothing we can do about it except not use wxWidgets. A switch to Qt is planned (see the [roadmap](https://github.com/audacity/audacity/wiki/Roadmap) but will take some time. We won't fix this bug in the meantime.

**Closed by LWinterberg** 2022-05-30 08:57 UTC
