### ISSUE TITLE
Missing text in Time Signature and Snapping toolbars (Linux)

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4735] opened 2023-05-26 15:08 UTC
### Bug description

When starting fresh, Tempo, LTS and Snapping interval values are missing. What's even worse, when clicking into the text boxes and entering the values by either typing or by clicking +/- buttons, the values will only be visible until clicking anywhere outside within the project. 

### Steps to reproduce

1. Build from [sources](https://github.com/audacity/audacity/suites/13130193429/artifacts/713513873)
2. Launch Audacity
3. Check the Snapping and Time Signature toolbars

### Expected behavior

Both have text visible in the text boxes

### Actual behavior

- Time Signature toolbar is missing text in the Tempo and LTS text boxes
- Sanpping toolbar is missing text in the text box too:

![image](https://github.com/audacity/audacity/assets/70063970/1e71a38a-5d73-4091-b1c9-bdc81b69736b)

### Audacity Version

current master / alpha / nightly build

### Operating system

Ubuntu 22.04

### Additional context

Compiled from source

**Comment by petersampsonaudacity** [comment] 2023-05-27 11:42
Testing on W10 with 3.3.2 and latest 3.4.0 alpha

This works fine on Windows:
![image](https://github.com/audacity/audacity/assets/50205984/5913a771-1307-4269-ac60-dd03f70dd60a)

**Comment by luzpaz** [comment] 2023-12-01 13:52
Can't reproduce on 3.4.2 Appimage
![Screenshot_20231201_085226](https://github.com/audacity/audacity/assets/4140247/bc38237e-04b6-4e17-8ed4-02b2e3c34ade)

**Comment by LWinterberg** [comment] 2024-10-15 11:29
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.

**Closed by LWinterberg** 2024-10-15 11:29 UTC
Labels: AU3-bug, P3, Linux
