### ISSUE TITLE
Imported Opus files skip first 882 samples and append garbage

### ISSUE THREAD

**Issue by Cygon** [audacity/audacity#7385] opened 2024-09-21 22:21 UTC
### Bug description

When I import `.opus` audio files into Audacity 3.6.4 (by drag and drop), it appears that the first 882 samples are skipped (the audio data is shifted left on the time axis compared to the same audio data loaded from a `.wav` file that has been produced by decoding the `.opus` file via `opusdec`):

![opus-decode-whole](https://github.com/user-attachments/assets/4e421954-f85f-4237-8e2a-425c3345b8ef)

I hand-aligned the imported Opus track to line up again and better reveal the missing samples. Here's a zoom-in to the beginning of the audio file.

![opus-decode-skips-882-samples](https://github.com/user-attachments/assets/17072c8b-7327-451f-9531-87958e58231b)

In exchange for skipping the beginning, Audacity appends semi-garbage at the end:

![opus-decode-garbage-appended-to-end](https://github.com/user-attachments/assets/db29d673-cf54-48ce-a47a-30bed6e8daff)

- - -

I have taken a look at Audacity's Opus importer code, and I have a hunch what might be going wrong. In `ImportOpus.cpp`, there is this loop:

https://github.com/audacity/audacity/blob/36918d5655ac2a87a94e0645889313835a632e2a/modules/import-export/mod-opus/ImportOpus.cpp#L219-L226

The variable `samplesRead` is used as the `size_t len` parameter to `WaveChannel::AppendBuffer()`.

**Here's the bug** (look in `ImportOpus.cpp`): `samplesRead` is only assigned *after* the `AppendBuffer()` call, so for the first audio packet, `samplesRead` will still be 0 and zero samples will be added to the wave track.

It also explains why there is garbage at the end -- upon reaching the last packet (and `op_decode_float()` returns 0 samples decoded), `samplesRead` still holds the amount of samples read in the previous call and will append whatever happens to be lingering in the `floatBuffer`, producing the garbage data seen in the screenshot above.

**Possible solution:** Move the assignment (`samplesRead = samplesPerChannelRead;`) above the block with the `AppendBuffer()` call.

### Steps to reproduce

1. Generate audio data where you can notice small amounts of samples being truncated. I used a 50 Hz sinus wave.
2. Export the audio data to Opus
3. Import the Opus file next to the just-exported audio data
4. Notice how the audio data imported from the Opus file is now shifted and contains garbage at the end.

### Expected behavior

For the audio data imported from Opus to line up with the original audio data and/or the decoded audio data as it is when using `opusdec` from the command line and importing the resulting `.wav` file.

### Actual behavior

Audacity skips the first 882 audio samples, shifting the audio data so it plays a little early, as well as appending garbage samples at the end of the track.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Additional context

Gentoo Linux withkernel 6.6.30, Audacity running on KDE Plasma 5, with PipeWire on amd64.

**Comment by petersampsonaudacity** [comment] 2024-09-22 10:15
Testing on W10 with 3.6.4 

I cannot reproduce this

1. Set selection toolbar to be start/length and Samples
2. Import an audio file (MP4 I used)
3. Export it as .opus file
4. Import the ,opus file
5. Select original track
6. the select imported track
7. Observe: both tracks have exactly the same number of samples

Also zooming in at beginning and end shows that both tracks appear to be identical.

**Comment by Cygon** [comment] 2024-09-22 20:29
I tried it on a Windows 10 VM with the current Audacity 3.6.4 amd64 download w/installer linked from the official website (plus the ffmpeg library linked in the wiki).

I can **not** reproduce it with the Windows version, either.

--

I recompiled Audacity 3.6.4 on my Linux system from the GitHub source release .tar.gz once more and tried an `.mp4` file.

The error is readily reproducible on my Linux system and shows up every time:

![audacity-mp4-to-opus-export-import](https://github.com/user-attachments/assets/03dd7b94-8b0d-44bb-862b-f0b4542bd252)

This is the version output right now:

![audacity-version](https://github.com/user-attachments/assets/bb2c5b52-d846-43cf-b98d-29275fb11de2)

--

I'm not sure what's going on with the Windows side. Does Audacity maybe import `.opus` through ffmpeg rather than use its own `mod-opus`?

The bug I believe to have found in `ImportOpus.cpp` would (and does, on my Linux build) trigger 100% of the time.

**Comment by kryksyh** [comment] 2024-10-22 16:57
@Cygon thank you for this report
You correctly spotted the bug in the code, it will be fixed in the next release (PR: #7602)

**Comment by kryksyh** [comment] 2024-10-22 16:58
@Cygon 
> I'm not sure what's going on with the Windows side. Does Audacity maybe import .opus through ffmpeg rather than use its own mod-opus?

That's correct.

**Comment by dozzzzer** [comment] 2024-10-25 16:31
Tested. The "Garbage" part at the end is inherent to the exporter and is caused by the compression algorithm. 
<img width="600" alt="image" src="https://github.com/user-attachments/assets/0fd90275-0e44-48dc-b7ba-f26d066a5a51">

**Closed** 2024-10-25 16:39 UTC
Labels: AU3-bug, Linux
