### ISSUE TITLE
[AU4] Effect preview function

### ISSUE THREAD

**Issue by ianalarina** [audacity/audacity#7527] opened 2024-10-14 12:06 UTC
### Description

Add Effect preview feature in AU4

**Comment by dozzzzer** [comment] 2024-11-20 13:58
@igorkorsukov 

- After preview progress reaches 100%, the progress dialog remains:
<img width="500" alt="image" src="https://github.com/user-attachments/assets/45298ebd-b1bc-403e-be11-bcab647a0f2e">

- If the selection is short (less than 1s) and the preview is run, the progress dialog remains at 0%:
<img width="500" alt="image" src="https://github.com/user-attachments/assets/92b81d3a-08f2-43a6-959b-d2c6cdac5e4d">

- After the preview is run, the effect dialog cannot be closed by either Esc or by clicking the cross icon:
![2024-11-20_14-57-16 (1)](https://github.com/user-attachments/assets/a00875f0-05e8-46bf-b3c2-8db69e89359c)

**Comment by igorkorsukov** [comment] 2024-11-21 11:37
@dozzzzer 
* After preview progress reaches 100%, the progress dialog remains - fixed 
* If the selection is short (less than 1s) and the preview is run, the progress dialog remains at 0% - fixed 
* After the preview is run, the effect dialog cannot be closed by either Esc or by clicking the cross icon - should be closed by a button, but Escape does not work in this case. This is not related this PR, the problem is in the system of working with dialogs, in the Muse framework. It is better to create a new separate bug report and it is better to add a tag "MF" (Muse framework)

**Comment by igorkorsukov** [comment] 2024-11-25 09:46
@dozzzzer 

* When the entire clip is selected, the preview cannot be run: - error in other functionality, when selecting the entire clip, its data is not selected

**Comment by igorkorsukov** [comment] 2024-11-26 12:46
@dozzzzer added applying effect to selected clip

**Comment by chinakov** [comment] 2024-11-26 13:48
The preview can now be played when clips are chosen as the seleciton. 

The only thing that remains is to find out what to do regarding:

>When playing the preview for the generated tone, you can see that it plays what's in the project (which I assume it shouldn't) and runs the playback for as long as the duration is entered into the generator dialog, which is also reflected in the progress dialog. @DilsonsPickles @Tantacrul @LWinterberg please suggest what the correct behavior here should be.

**Closed** 2024-11-27 08:25 UTC
Labels: Task
