### ISSUE TITLE
Playback looping. The waveform selection affects the start point of looping playback

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2321] opened 2021-12-21 09:23 UTC
**Describe the bug**
When the playback looping is on and none of the points of the waveform selection corresponds to the playback region, the looping region has been ignored/ Playback starts from the beginning of the waveform selection. 

**For example:**
1. Generate a chirp
2. Select a new looping region
3. Select a region on the waveform as shown in the picture below:
Please note the looping mode is on. 
![изображение](https://user-images.githubusercontent.com/25851359/146901437-1504bb72-c450-485a-bb26-2ff95f9d20f7.png)

4. Click the Play button 
5. Observe: the playback starts from the beginning of the waveform selection and the looping selection has been ignored.

That makes no sense if the looping mode is on. 

**Expected behavior**
If the looping mode is on, a looping region has a higher priority than a waveform selection if the starting point of the waveform selection does not correspond to a playback looping region.

**Comment by LWinterberg** [comment] 2021-12-21 09:39
similar to #2112, this is intended. Playback starts from the selection until it reaches the looping region, at which point it gets trapped inside the looping region. If it never reaches a looping region, it also doesn't loop. There is a task in #2101 to make a looping mode though where only the looping region plays, and always loops.

**Comment by LWinterberg** [comment] 2021-12-21 09:45
(what probably isn't intended though is that playback continues to the end of the track instead of stopping at the end of selection)

**Comment by Penikov** [comment] 2021-12-21 09:53
I think so because a user should have an opportunity to change the positioning of the starting point of the looping. But if the looping mode has a higher priority, there is no sense to ignore the looping region if the cursor position or a waveform selection have not corresponded to the looping region at all.

**Comment by petersampsonaudacity** [comment] 2021-12-21 09:54
A side effect of this is that it also affects the use cases where you change the loop region entirely while loop playing is active.

### Use Case 1
1. Generate 30 second chirp
2. create a loop region 10-15 secs
3. Press Play
4. Observe looping occurs 10-15secs
5. change loop region to 20-25 secs
6. Observe: play continues with the 10-15 seconds (original loop region)
7. Observe: play continues on from 25-25seconds
8. Observe: play loops from 20-25 seconds

### Use Case 2
1. Generate 30 second chirp
2. create a loop region 10-15 secs
3. Press Play
4. Observe looping occurs 10-15secs
5. change loop region to 0-5 secs
6. Observe: play continues with the 10-15 seconds (original loop region)
7. Observe: play continues from 15-20 seconds and then stops
8. Observe: the 0-5 second region is **_not_** loop-played

**Comment by Penikov** [comment] 2021-12-21 10:03
> A side effect of this is that it also affects the use cases where you change the loop region entirely while loop playing is active.
> ### Use Case 1
> 
>     1. Generate 30 second chirp
> 
>     2. create a loop region 10-15 secs
> 
>     3. Press Play
> 
>     4. Observe looping occurs 10-15secs
> 
>     5. change loop region to 20-25 secs
> 
>     6. Observe: play continues with the 10-15 seconds (original loop region)
> 
>     7. Observe: play continues on from 25-25seconds
> 
>     8. Observe: play loops from 20-25 seconds
> 
> 
> ### Use Case 2
> 
>     1. Generate 30 second chirp
> 
>     2. create a loop region 10-15 secs
> 
>     3. Press Play
> 
>     4. Observe looping occurs 10-15secs
> 
>     5. change loop region to 0-5 secs
> 
>     6. Observe: play continues with the 10-15 seconds (original loop region)
> 
>     7. Observe: play continues from 15-20 seconds and then stops
> 
>     8. Observe: the 0-5 second region is **_not_** loop-played

In the second use case, it works that way because the looping is designed as a trap for a playhead. 
So if the end of this 'trap' changes its position before the playhead reaches it - the playhead will escape the trap and playback will be not looped.

**Comment by Paul-Licameli** [comment] 2021-12-21 12:09
I agree with @LWinterberg that this behaves as last specified.  There is not a bug for 3.1.3 here.  There might be enhancement that designers must agree to.

if you have a looping region, it is useful to begin play in it, not at its left edge, by selecting in it.  If it is long and you want to know that it will not click at the end, it is useful to start play near the end.

**Comment by petersampsonaudacity** [comment] 2021-12-21 12:14
> I agree with @LWinterberg that this behaves as last specified. There is not a bug for 3.1.3 here. There might be enhancement that designers must agree to.

In which case flagging this for @Tantacrul as a UX/design issue

**Comment by LWinterberg** [comment] 2021-12-21 12:49
Closing in favor of #2325

**Closed by LWinterberg** 2021-12-21 12:49 UTC
Labels: bug, P2, Looping
