### ISSUE TITLE
Malformed meters when orientated vertically

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3510] opened 2022-09-01 17:17 UTC
### Bug description

![Screenshot_2022-09-01_18-13-31](https://user-images.githubusercontent.com/11681097/187973639-066dfb67-740a-4fcd-bfc8-107aad4d461f.png)

### Steps to reproduce

1. Change the orientation of the recording and / or playback meters to vertical, and resize to a reasonable size.

### Expected behavior

The dB settings to be correctly rendered, and a slider that looks less strange.

### Actual behavior

See screenshot.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by LWinterberg** [comment] 2022-09-01 18:19
duplicate of #3242

**Comment by SteveDaulton** [comment] 2022-09-01 19:45
> duplicate of #3242

But there's no mention of the dB numbers in #3242, which is the main point of #3510.
> **Expected behavior**
> The dB settings to be correctly rendered, ...

**Comment by LWinterberg** [comment] 2024-10-15 11:10
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.

**Closed by LWinterberg** 2024-10-15 11:10 UTC
Labels: AU3-bug, P4, UI
