### ISSUE TITLE
Sudden program crashes during a recording

### ISSUE THREAD

**Issue by mapan001** [audacity/audacity#7030] opened 2024-08-04 15:50 UTC
### Bug description

Sudden program crashes occur during a live service recording. The program crashes several times during a session. 
Sometimes after a few minutes, the next time after a longer recording time.
In previous software versions, recordings were interrupted, since 3.6.1 the software crashes completely. 
The sound card used is a Steinberg UR22C via USB 3.0.
After restarting the software, the tracks are restored, but part of the recording is always missing because the event is not waiting.

The crash report is very long with many entries:

![Error](https://github.com/user-attachments/assets/4076701a-4d51-481a-933a-c925b2158838)

### Steps to reproduce

1. Start recording
2. simply wait until the crash

### Expected behavior

Stable workflow without crashes.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Sound card: Steinberg UR22C

**Comment by garlic-os** [comment] 2024-08-04 22:25
Just happened to me. Was recording through a 3.5mm. The problem report failed to send, but I have the text if a developer wants me to DM it to them.

**Comment by petersampsonaudacity** [comment] 2024-08-05 11:16
@mapan001 

See:   Crashes when recording using temporary files, automatic submit fails #7018

**Comment by dozzzzer** [comment] 2024-08-13 07:46
Duplicate of https://github.com/audacity/audacity/issues/7018; The fix will be released in 3.6.2.

**Closed by dozzzzer** 2024-08-13 07:46 UTC
Labels: bug, crash / freeze
