### ISSUE TITLE
Cancel/Export button order on Export Audio is reversed 

### ISSUE THREAD

**Issue by Stevoisiak** [audacity/audacity#6118] opened 2024-03-10 01:16 UTC
### Bug description

When using the Export Audio function in Audacity, the order of buttons puts "Cancel" to the left of "Export".  This is inconsistent with button positioning throughout the rest of Audacity, which typically puts "Accept" actions before "Cancel".

### Steps to reproduce

1. Open an Audacity project
2. Select 'File > Export Audio'

### Expected behavior

The 'Export' button should appear on the left of the 'Cancel' button for consistency with the rest of Audacity's UI. 

### Actual behavior

The 'Cancel' button is to the left of the 'Export' button.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

The "Export Audio" menu with "Cancel" to the left of "Export".

![image](https://github.com/audacity/audacity/assets/1330770/b5d50b54-336c-450b-94e7-ac6374d3c1bc)

UI examples that put the "Accept" option first include:

The "save before closing" popup

![image](https://github.com/audacity/audacity/assets/1330770/8cc0618e-5f55-47cd-bf8d-288f63e57d35)

The Save Project warning

![image](https://github.com/audacity/audacity/assets/1330770/b2fc0158-3ad9-4ac9-8c1d-db4056a110c1)

The label editor

![image](https://github.com/audacity/audacity/assets/1330770/503649fa-961b-416a-be1e-4526ced60b4f)

The metadata editor

![image](https://github.com/audacity/audacity/assets/1330770/2f839a70-1f54-4a0e-97d0-377575157c8a)

The preferences menu

![image](https://github.com/audacity/audacity/assets/1330770/2a0f8ad6-920b-4738-b236-5e701fc6c99f)

The plugin manager

![image](https://github.com/audacity/audacity/assets/1330770/6146bc88-3ce7-4de5-ae36-519973db4582)

The Save Project menu

![image](https://github.com/audacity/audacity/assets/1330770/9121e16f-534e-4761-8d8e-382552218a5c)

And several more menus not listed here.

**Comment by LWinterberg** [comment] 2024-03-10 10:51
Duplicate of https://github.com/audacity/audacity/issues/5963

**Closed by LWinterberg** 2024-03-10 10:51 UTC
Labels: bug
