### ISSUE TITLE
Timeline time tracker not updating with playback [GNOME Wayland]

### ISSUE THREAD

**Issue by docquantum** [audacity/audacity#459] opened 2020-03-18 20:08 UTC
**Describe the bug**
Timeline vertical bar tracker does not update position automatically and requires me to click the waveform to update it's visual location. The audio still plays as expected.

**To Reproduce**
1. Open a audio file or record one.
2. Play the file and watch the vertical line that follows the playback position.
3. It will not update, clicking anywhere on the waveform as it plays back will update the tracker position.

**Expected behavior**
The playback tracker will update automatically as the audio is played back.

**Screenshots**
![animation](https://user-images.githubusercontent.com/3020563/77002306-4aef6500-6929-11ea-9618-015e99b2b015.gif)

**Additional information (please complete the following information):**
 - Arch Linux 5.5.9-1-clear using GNOME Shell 3.36.0 in Wayland (Also existed in older version of GNOME 3 going back to 3.32 at least [in Wayland].)
 - Audacity 2.3.3
 - ALSA

**Additional context**
This does not occur when running GNOME on Xorg.

**Comment by imsedgar** [comment] 2020-04-19 18:10
It also occurs in Fedora 31 with Gnome on Wayland with the following packages installed:

audacity-freeworld-2.3.3-1.fc31.x86_64
gnome-shell-3.34.5-1.fc31.x86_64
gnome-session-wayland-session-3.34.2-2.fc31.x86_64
libwayland-client-1.17.0-2.fc31.x86_64

There is a downstream bug report on RPMFusion: https://bugzilla.rpmfusion.org/show_bug.cgi?id=5551

**Comment by lysiasthefox** [comment] 2020-06-25 01:27
I can confirm the missing playback cursor under Wayland (GNOME Shell 3.34.5 - Fedora 31), using Xorg/X11 mitigates the issue.

Audacity 2.3.3
Linux XXXXX 5.6.16-200.fc31.x86_64

**Comment by SteveDaulton** [comment] 2020-06-25 09:44
Audacity currently requires GTK2 and Wayland is not yet supported.
Building with GTK3  or running on Wayland are both likely to cause problems.

**Comment by lllucius** [comment] 2020-06-26 20:59
What Steve says is still true...GTK2 is still preferred for now.  But, you might want to try the recently released 2.4.2.  You might find it works a tad bit better with GTK3 and Wayland.  Let us know how it goes if you try it.

**Comment by aaronjohnsabu1999** [comment] 2020-08-07 06:38
This happened to me using GNOME on Ubuntu 20.04.1 LTS

In `/usr/share/applications/audacity.desktop`, replace `Exec=audacity %F` by `Exec=env GDK_BACKEND=x11 audacity %F`

**Comment by ettavolt** [comment] 2021-01-14 09:50
Root cause is probably in wxWidgets: 17820 in their Trak raises a problem with some 'caret sample'.

**Comment by MrBeBo999** [comment] 2021-03-11 14:12
Still no moving timeline tracker. Tracker appears on the right place on pause or stop.

Audacity 2.4.2
wxWidgets 3.0.5
Fedora 33
Gnome 3.38.4
Wayland

**Comment by SteveDaulton** [comment] 2021-03-11 14:20
> Still no moving timeline tracker. Tracker appears on the right place on pause or stop.
> 
> Audacity 2.4.2
> wxWidgets 3.0.5
> Fedora 33
> Gnome 3.38.4
> Wayland

Your version of wxWidgets is too old, and Audacity does not yet fully support Wayland.

As stated in the build instructions (https://github.com/audacity/audacity/blob/master/linux/build.txt) Audacity should be built with wxWidgets 3.1.3 (preferably the Audacity version which includes some bug fixes).

Even with your current version of Audacity, you will probably get better, more reliable performance if you log into an xorg session before using Audacity.

**Comment by MrBeBo999** [comment] 2021-03-11 19:43
Your version of wxWidgets is too old, and Audacity does not yet fully support Wayland.

As stated in the build instructions (https://github.com/audacity/audacity/blob/master/linux/build.txt) Audacity should be built with wxWidgets 3.1.3 (preferably the Audacity version which includes some bug fixes) built with gtk2.

Even with your current version of Audacity, you will probably get better, more reliable performance if you log into an xorg session before using Audacity.

> > Still no moving timeline tracker. Tracker appears on the right place on pause or stop.
> > Audacity 2.4.2
> > wxWidgets 3.0.5
> > Fedora 33
> > Gnome 3.38.4
> > Wayland
> 
> Your version of wxWidgets is too old, and Audacity does not yet fully support Wayland.
> 
> As stated in the build instructions (https://github.com/audacity/audacity/blob/master/linux/build.txt) Audacity should be built with wxWidgets 3.1.3 (preferably the Audacity version which includes some bug fixes) built with gtk2.
> 
> Even with your current version of Audacity, you will probably get better, more reliable performance if you log into an xorg session before using Audacity.

Okay.
I installed it with
dnf install audacity
assuming this would built audacity with the right dependencies. Well, no so.
I assume the only way to fix this is making my own build?
Thanks in advance!

**Comment by imsedgar** [comment] 2021-03-11 19:50
wxWidgets 3.0.5 is the current stable version. In Fedora 33 you get it with package wxGTK3 (and wxGTK3-devel).
wxWidgets 3.1.4 is the current development version. In Fedora 33 you get it with package wxGTK (and wxGTK-devel).

Packages audacity and audacity-freeworld (from repo rpmfusion-free) both use the stable version of wxWidgets to build the packages. You can see it in the source rpm packages (which contains the spec file).

You can try modifying the source rpm and build a new package with a modified spec file.

I will try it myself, but I cannot say when I will have time for it.

**Comment by ettavolt** [comment] 2021-03-11 20:53
[Like stated in the wxWidgets bugtracker](http://trac.wxwidgets.org/ticket/17820) the used component doesn't support sending updates when run under Wayland.

**Comment by imsedgar** [comment] 2021-03-11 21:34
> [Like stated in the wxWidgets bugtracker](http://trac.wxwidgets.org/ticket/17820) the used component doesn't support sending updates when run under Wayland.
Thanks for the note. This bug report is four years old...
So it seams that using the current wxWidgets development version will not solve the problem with wayland yet.

**Comment by MrBeBo999** [comment] 2021-03-12 11:11
For all of you who are curious: I installed the Audacity snap on the same system (Fedora 33, Gnome 3.38.4, Wayland) and the moving cursor works. This snap has wxWidgets 3.1.3 running. So seems like with the wxWidgets updated to a newer version the moving cursor works. However this is in a snap, not native on the system,  so a lot of other things are not the same either. 
This snap image scales not with my hi-dpi laptop display, so the user interface of Audacity is unworkable small, but the moving cursor works ;)
As soon as I have the time, I will follow the build instructions link above and builds a native Audacity on my system with the latest wxWidgets. I'll post the results here.

**Comment by iMonZ** [comment] 2021-03-20 14:34
Is there a full Wayland support planed?

**Comment by clort81** [comment] 2021-04-01 01:46
I get working playback cursor when setting environment variable GDK_BACKEND=x11 before launching audacity.  THANKS 

> This happened to me using GNOME on Ubuntu 20.04.1 LTS
> 
> In `/usr/share/applications/audacity.desktop`, replace `Exec=audacity %F` by `Exec=env GDK_BACKEND=x11 audacity %F`

This fixes playback cursor under wayfire (wayland) for me. Many thanks.
audacity 2.4.2~dfsg0-3
libwxbase3.0-0v5: 3.0.5.1+dfsg-2

**Comment by JamesCrook** [comment] 2021-05-13 21:21
Closing:
>Setting environment variable GDK_BACKEND=x11 fixes playback cursor under wayfire (wayland) for me. 
>Many thanks.

**Comment by iMonZ** [comment] 2021-05-14 17:17
> Closing:
> 
> > Setting environment variable GDK_BACKEND=x11 fixes playback cursor under wayfire (wayland) for me.
> > Many thanks.

This is just a dirty workaround and not a fix. 
Could you please reopen the issue?

**Comment by tesfabpel** [comment] 2021-05-14 17:54
As a note, all major linux distributions are moving or moved to Wayland as **default** (the latest Ubuntu 21.04 is already using it as default as well as the latest Fedora)

**Comment by JamesCrook** [comment] 2021-05-14 18:03
> This is just a dirty workaround and not a fix.
> Could you please reopen the issue?
Reopening.

**Comment by imsedgar** [comment] 2021-05-14 18:04
It may be better to open an new issue that audacity should support Wayland,
because the specific problem of this issue is solved with the workaround.
So it will be clear what the task is.

**Comment by mortie** [comment] 2021-07-12 16:43
I'm sorry, but this issue isn't solved. The issue is still specifically that the timeline tracker is not updating with playback in Wayland. The "workaround" is to spin up an X server and run Audacity as an X11 client in that X server. It doesn't solve anything about the timeline not working under Wayland.

This issue should absolutely be un-closed.

**Comment by iMonZ** [comment] 2021-07-12 17:07
> I'm sorry, but this issue isn't solved. The issue is still specifically that the timeline tracker is not updating with playback in Wayland. The "workaround" is to spin up an X server and run Audacity as an X11 client in that X server. It doesn't solve anything about the timeline tracker not working under Wayland.

This is not an solution.
There must be an other way

**Comment by SteveDaulton** [comment] 2021-09-23 16:23
See also: https://bugzilla.audacityteam.org/show_bug.cgi?id=2810

**Comment by sjfricke** [comment] 2022-03-02 02:37
I tried running Audacity on Weston (version 10.0.90, which uses Wayland 1.20+) in a separate tty to remove GNOME from the equation and see the same behavior which leads me to believe this is correctly a client-side bug of Audacity not properly update the timeline tracker when using Wayland

**Comment by LWinterberg** [comment] 2022-03-02 08:00
@crsib is this something your work is likely to address?

**Closed** 2022-05-02 12:31 UTC
Labels: bug-distros, Linux, Known Issue

**Comment by HubKing** [comment] 2023-01-12 20:26
Damn, it looks like a joke that they closed this because forcing the app to use X11 on Wayland "solved" the problem, instead of updating the GUI framework to a modern one.

**Comment by LWinterberg** [comment] 2023-01-12 20:32
We *are* updating the GUI framework to a modern one (QML specifically), hence why this is closed. There is no action to be taken on this specific issue which isn't just part of the Qt migration.
