### ISSUE TITLE
Ubuntu 22.04 Appimage: menu color doesn't change

### ISSUE THREAD

**Issue by Tibsun75** [audacity/audacity#4449] opened 2023-03-26 12:03 UTC
### Bug description

The Menu Color doesn't change. Therefore audacity looks like an app from 90ths.
In Appimage version 3.1.3 it worked fine

### Steps to reproduce

1. Download audacity-linux-3.2.5-x64.AppImage
2. Start Audacity
3. Change the theme to dark

### Expected behavior

After changing the Theme to black, the menu should change to black

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Ubuntu 22.04

**Comment by LWinterberg** [comment] 2023-03-27 13:13
Duplicate of https://github.com/audacity/audacity/issues/3734 - This is necessary to keep Audacity working on a range of other distributions.

**Closed by LWinterberg** 2023-03-27 13:13 UTC
Labels: bug, Linux
