### ISSUE TITLE
[Plugin issue] Unable to type in plugin window, Audacity interprets them as commands.

### ISSUE THREAD

**Issue by theAwesomeFufuman** [audacity/audacity#4227] opened 2023-01-24 11:47 UTC
### Plugin

Sonible Balancer

### Plugin Format

VST3

### Plugin source

https://www.sonible.com/balancer/

### Bug description

Hi!
I am unable to paste or write all of the characters needed for the license key for the Sonible Balancer plugin since Audacity interprets them as commands. While having a plugin window in the foreground, it should be possible to type A-Z characters, or at least to paste in a text string.

### Steps to reproduce

1. Download and install the Sonible Balancer plugin from https://www.sonible.com/balancer/
2. Try to add the Balancer real-time effect
3. Try typing the character 'Z' in the license text box

### Expected behavior

The key binding for **Select Menu** -> **At Zero Crossings** gets executed instead.

### Actual behavior

The character 'Z' gets typed

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Architecture

64 bit Intel/AMD processors

### Additional context

https://user-images.githubusercontent.com/57533864/214282719-de235892-a5bf-4140-a51e-b3b7b15650da.mp4

**Comment by Ryan-Miller-Audacity** [comment] 2023-02-02 19:20
This appears to be  duplicate of #3808. Closing in Favor of that ticket.

**Closed by Ryan-Miller-Audacity** 2023-02-02 19:21 UTC
Labels: bug, plugins

**Comment by theAwesomeFufuman** [comment] 2023-02-03 12:35
I didn't find the other ticket when I looked, thanks a lot!
