### ISSUE TITLE
unable to close "update audacity window" on Mac OSX on laptop

### ISSUE THREAD

**Issue by sleslie** [audacity/audacity#5809] opened 2023-12-20 19:46 UTC
### Bug description

when I open audacity on my laptop it comes up with a nag screen to update audacity. However, the "ok"or "dismiss" buttons are below the level of the bottom of the screen. there is no way to resize the window and no way to close the window without using those buttons, which surely violates Mac's design guidelines. Renders the program functionally inoperable until I attach an external monitor. 
<img width="1024" alt="Screenshot 2023-12-20 at 11 43 27 AM" src="https://github.com/audacity/audacity/assets/1186782/52bfcc15-9c5e-4545-b537-721746cebaad">

### Steps to reproduce

open audacity

### Expected behavior

should be able to close upgrade window if I don't want to upgrade

### Actual behavior

can't close update window

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

**Comment by petersampsonaudacity** [comment] 2023-12-21 11:23
I have a recollection that Muse may already have fixed this for the next release 3.5.5

@LWinterberg @crsib can either of you confirm (or deny) this please.

**Comment by crsib** [comment] 2023-12-21 12:06
This is a duplicate of #5637 indeed, but that issue is not fixed yet

**Closed by crsib** 2023-12-21 12:06 UTC
Labels: bug, macOS

**Comment by petersampsonaudacity** [comment] 2023-12-21 12:28
Thanks Dmitry

**Comment by sleslie** [comment] 2023-12-21 16:55
Who is Dmitry?

Scott Leslie
Systems Manager, BC Libraries Cooperative
***@***.***
250-415-3490
________________________________

**Comment by petersampsonaudacity** [comment] 2023-12-21 17:23
> Who is Dmitry?

Iff you go to Help > About Audacity you will see that Dmitry is one of the Muse developers working on Audacity - he often works as the Release Manager:
![image](https://github.com/audacity/audacity/assets/50205984/5c35f7f5-d7c4-4291-9707-ab6af8523b69)
