### ISSUE TITLE
Windows: Audacity crashes, when making a stereo track using keyboard

### ISSUE THREAD

**Issue by Giovani93** [audacity/audacity#5858] opened 2024-01-11 08:26 UTC
### Bug description

<details>
Hello.
I have a problem with Audacity. When I make stereo tracks using make stereo track in track menu, Audacity crashes.
Also, there are some mistakes in this report. I use really Windows 10 (64 bit), not Windows NT.
Please, could You look on this report, if It is possible? Or what can It be? Something with My notebook?
Thank You.
Marco Oros
</details>

### Steps to reproduce

1. create two mono tracks
2. Open the first track's menu by pressing the Application key or Shift + M
3. Choose Make stereo track, using either the mouse or the keyboard. 

### Expected behavior

A stereo track is made

### Actual behavior

A crash

[Audacity crash report.txt](https://github.com/audacity/audacity/files/13899552/Audacity.crash.report.txt)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Not reproducible on macOS and Linux

**Comment by Giovani93** [comment] 2024-01-11 09:43
I've tried to reinstall Audacity, but with same result.
So, what should I do? I don't want to change My computer due to one software.

**Comment by DavidBailes** [comment] 2024-01-11 09:54
> I cannot reproduce this on W10 with 3.4.2 - works fine for me.

@petersampsonaudacity . Whether or not there is a crash seems to depend on whether the first track's menu was opened using   the keyboard or the mouse:
1. Open the first track's menu by pressing the Application key or Shift + M.
2. Choose Make stereo track, using either the mouse or the keyboard. The combine mono to stereo message box opens.
3. Press the Yes button, using either the mouse or the keyboard.
Audacity crashes.

If step 1 is replaced by Open the track's menu using the mouse, then Audacity does not crash.

**Comment by dozzzzer** [comment] 2024-01-11 09:56
Thanks, @DavidBailes ! Great observation

**Comment by dozzzzer** [comment] 2024-01-11 10:07
@Giovani93 FYI as for the crash reports failing to send, there's an issue logged https://github.com/audacity/audacity/issues/4154

**Comment by petersampsonaudacity** [comment] 2024-01-11 10:12
@DavidBailes 

 good catch (I always use the mouse, so I overlooked the Shift+M to get the menu of the focused track)

The additional fascinating thing is that if you accept the offered recovery on relaunch then the project is restored with the track as stereo.

1. Import a stereo track
2. Split the stereo track
3. Observe: two single channel tracks
4. Ensure focus is on top track
5. Shift+M to get the TCP menu
6. choose Make Stereo Track
7. Observe: Crash
8. Relaunch Audacity
9. Observe: Project is restored as a stereo track

**Comment by petersampsonaudacity** [comment] 2024-01-11 10:18
Further testing shows this this a regression on 3.3.3, introduced in 3.4.0

**Comment by Giovani93** [comment] 2024-01-11 10:59
Thank You for Your help. So problem can be with using keyboard. So, I am blind and ofcourse, I forgot to mention, that stereo track is created instead.
Sorry to write about It manytimes, but if is problem, must be solved. It is My point about issue.

**Comment by petersampsonaudacity** [comment] 2024-01-11 12:38
> So problem can be with using keyboard.

NO - the problem only occurs when you use the keyboard for this.  It works if you use the cursor to get the Track Control Panel menu - which is a problem for users who are blind like you.

**Comment by DavidBailes** [comment] 2024-01-12 10:44
Bisects to: 410a0515c

**Comment by SteveDaulton** [comment] 2024-01-12 14:21
I can't reproduce this on Linux with Audacity  3.5.0 commit id: 9817f6
Looks like a Windows only bug.

**Comment by JoeS209** [comment] 2024-01-22 05:16
In CellularPanel::DoContextMenu (CellularPanel.cpp, line 967), pCell pointer is non-NULL but points to garbage.  I don't know yet if that value was passed to the function or if it was obtained by the code in the block at the start of the function.

**Comment by JoeS209** [comment] 2024-01-22 05:41
I'm going to take a wild guess here; guessing that CellularPanel::OnSetFocus is not called when the keyboard shortcut, thus leaving a stale pointer for the focused cell.

**Comment by JoeS209** [comment] 2024-01-25 23:06
From poking around at this over the last couple of days, I've been able to make some progress here.  If I change CellularPanel::DoContextMenu to use the pointer returned from the call to GetFocusedCell() only for the delegate stuff, and instead pass the original pCell pointer to ProcessUIHandleResult, then this bug does not occur.  If I pass the focused cell pointer to ProcessUIHandleResult as the original code does, then somehow inside that call stack, the data that pCell points to becomes invalid.  If I instead pass the original pCell value to ProcessUIHandleResult, which in this case is null, then the problem does not occur.

Here is the function as I have changed it.  Bug does not occur, but is this the right fix?  Maybe this is just masking the problem and perhaps there is a better fix inside ProcessUIHandleResult or some call downstream from there?  Looking for suggestions/comments.  Thanks.

```
void CellularPanel::DoContextMenu( TrackPanelCell *pCell )
{
   TrackPanelCell *pCellFocused = pCell;
   if( !pCellFocused ) {
      pCellFocused = GetFocusedCell();
      if( !pCellFocused )
         return;
   }

   const auto delegate = pCellFocused->ContextMenuDelegate();
   if (!delegate)
      return;

   auto rect = FindRect( *delegate );
   const UIHandle::Result refreshResult =
      delegate->DoContextMenu(rect, this, nullptr, GetProject());

   // To do: use safer shared_ptr to pCell
   ProcessUIHandleResult(pCell, pCell, refreshResult);
//   ProcessUIHandleResult(pCellFocused, pCellFocused, refreshResult);
}
```

**Comment by JoeS209** [comment] 2024-01-27 21:01
OK, I think my prior findings are a red herring.  On the latest code today, unchanged, the crash no longer repros for me.  With the 3.4.2 released code, the crash does occur, but if I make the change above in my last comment, it does not repro.  I think this is really a timing/lifetime issue, and I think the correct fix for this would be to use a shared_ptr for pCell as the comment in the code suggests.  This also tells me that whoever wrote that comment knew that there was a problem here or at least a potential for one.

**Comment by petersampsonaudacity** [comment] 2024-02-05 11:43
@dozzzzer @DavidBailes 

Testing on W10 with @JoeS209 's latest branch build:  audacity-win-3.5.0-alpha-20240204+b11feb8-x64

This now seems to work properly in Joe's branch with no crash and the stereo track is properly created.

I tested entirely using the keyboard with no mouse
1. Shift+M in the top track to get the menu
2. scroll down in menu with down arrow to get the "Make Stereo Track" command
3. Press enter
4. Observe: stereo track is made (and no crash occurs)

**Comment by chinakov** [comment] 2024-02-06 15:24
Tested, thanks!

**Closed** 2024-02-06 16:10 UTC
Labels: bug, P1, crash / freeze, regression, Windows, Tracks
