### ISSUE TITLE
Waveform not updated correctly on pasting into a clip.

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#6422] opened 2024-05-11 17:49 UTC
### Bug description

When pasting audio inside an audio clip, the waveform is not updated correctly.

### Steps to reproduce

1. Generate a 1 second "Pluck" sound.
2. "Ctrl + C" to copy the clip.
3. Click about halfway along the clip to set the insert position.
4. "Ctrl + V" to paste.

### Expected behavior

The copied audio to appear at the cursor position.

### Actual behavior

https://youtu.be/h1zuzzs3xBM

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by petersampsonaudacity** [comment] 2024-05-12 13:50
@SteveDaulton 

This is showing similar behavior to:
 **"Silence Audio" command silently fails #6421** 

Whereby if after the paste you 
1. select a portion beyond or begore the pasted section
2. Trim the audio
3. Undo to undo the trim
4. Observe : the paste did actually take place and now shows
![image](https://github.com/audacity/audacity/assets/50205984/c09f9ccf-6c76-4681-8613-ada3a8c177cc)

And similar to #6421 playing the audio after the paste then you will here two Plucks - indicating again taht this is actually a waveform display issue.

**Comment by petersampsonaudacity** [comment] 2024-05-12 13:51
This is a regression on 3.5.1

**Comment by LWinterberg** [comment] 2024-05-13 08:13
Are these fixed by https://github.com/audacity/audacity/pull/6400 ?

**Comment by dozzzzer** [comment] 2024-05-13 08:18
Duplicate of https://github.com/audacity/audacity/issues/6373

**Closed** 2024-05-13 08:19 UTC
Labels: bug, P1, regression, Tracks
