### ISSUE TITLE
UX improvement - "smart" clips

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#1178] opened 2021-06-28 14:39 UTC

**Comment by jounih** [comment] 2021-07-01 11:36
Smart clips are a way to adjust the length of a clip _non-destructively_. When hovering on the edge of a clip, the cursor changes to a trim cursor, and by clicking and dragging the user will be able to shorten the clip (or lengthen later on, if the current shown length of the clip is shorter than the actual length). The idea is that the complete clip data will be retained, so that users can split and trim clips without worrying about losing the original audio data. 

![smart clip 1@2x](https://user-images.githubusercontent.com/10109867/124116626-12fd2a00-da67-11eb-8610-67a854ba771a.jpg)
![smart clip 2@2x](https://user-images.githubusercontent.com/10109867/124116621-12649380-da67-11eb-9acf-3379a9fb0688.jpg)
![smart clip 3@2x](https://user-images.githubusercontent.com/10109867/124116619-109ad000-da67-11eb-8903-626073ab4925.jpg)
![smart clip 4@2x](https://user-images.githubusercontent.com/10109867/124116620-11cbfd00-da67-11eb-8b4a-8695f93c4f6f.jpg)

UX video of the behaviour (doesn't show the cursor change due to limitations in the prototype) - https://vimeo.com/562162689#t=14m1s

**Comment by jounih** [comment] 2021-07-01 11:42
There is an edge case which will require resolving - when a part of an audio has been selected all the way to the edge of a clip, the hit area between the selection edge, and the clip edge may overlap. There have been a couple of suggestions to resolve this:

1. Using the current behaviour of "Esc" key in Audacity to switch between conflicting contexts/hit areas (not very discoverable), also "Esc" often is used as a shortcut for de-selection
2. A selection mode tool (like today) - a special tool mode could be used when selecting audio, and a more generic pointer tool for anything else (moving, trimming etc)
3. The clip selection hit area could be just outside the clip edges, rather than inside. This could be problematic with two clips right next to each other

Regardless of the solution for this hit area conflict edge case, the main work on the Smart Clips can commence, and this edge case can be resolved separately.

**Comment by DavidBailes** [comment] 2021-07-02 12:34
> so that users can split and trim clips without worrying about losing the original audio data

You may well have thought through this, but...
In an editor which has only non-destructive editing, when you split a clip, both clips can be a "view" of the same data.
But in Audacity, this can't be the case, since either clip could be destructively edited, and this shouldn't affect the other clip.

**Comment by Paul-Licameli** [comment] 2021-07-12 08:04
@AnitaBats this design is surely not "Done" yet.

@DavidBailes points out an unspecified case.  @jounih may have an incorrect mental model of how Audacity works.  Clips in Audacity are not and cannot simply be "views" into the same data, as David says they are in purely non-destructive editors.

So design might specify:  When a clip is split, each clip gets a complete copy of the wave data, including any hidden wave data that the original clip had.  (The implementation can do this easy with real sharing, not duplication.)  But thereafter, clip contents are independently modifiable.

The design should also specify: dragging of clip edges shall not result in overlapping clips within one channel.  Audacity doesn't support overlapping clips (yet).

But then: if two clips touch, and you drag the boundary between them -- should that adjust both clips at once (shortening one, lengthening the other)?  I would think that is useful, and should be specified.

BUT then: you might really want to drag one edge and not the other.  So how do you specify what you really want?

Which suggests:  MORE hit-test target candidates perhaps.  Esc key might cycle between adjusting this clip, OR that clip, OR both clips, OR change the selection.

And then:  How will the user know what the hit-test target is?  Are there enough cursor changes possible?  Or do we do something like drawing the boundary of a clip in a changed color?

**Comment by jounih** [comment] 2021-07-12 09:03
@Paul-Licameli 

I like your first idea - The suggestion of including potentially hidden wave data in split clips, and turning them into independent clips after the split sounds good to me - I'll add this to the description/spec. I'm aware there is no "instancing" of clips in Audacity yet, could be desirable in the future but let's not tackle that now.

The second issue you mention - Hit area conflicts for smart clip length trimming - is a tricky one, still something I'm thinking about, I outlined some thoughts on 3 potential options [above](https://github.com/audacity/audacity/issues/1178#issuecomment-872173922) with pros/cons. I have a feeling this will take a bit of time and discussions to resolve, but the internal/non-UI dev work on smart clips should be able to commence.

My thoughts - I don't think cycling selection with "Esc" is very discoverable, and the common pattern from other apps is for "Esc" to deselect.

I don't think the hit area can be outside/on the edge for the reasons you mention due to conflict with other adjacent clips, it should be slightly inside of the edge of the clip. If there are two clips next to each other, being able to lengthen one and shorten the other would be useful, will add this to the final spec. The only hit area conflict with inside the edge is that in Audacity you can also select a part of the waveform, the waveform selection may extend to the end of the clip. In this instance there would be a hit area conflict between the edge of the waveform selection, and the edge of the clip for trimming the clip. A separate selection tool mode (like today) would resolve the conflict, I think. I have a feeling that in the future we will need some new tool modes anyway, for instance for spectral selection. So I'm not sure we can get rid of tool modes completely, as we previously hoped. Let's brainstorm this one this week.

**Comment by Paul-Licameli** [comment] 2021-07-12 09:26
Describe "instancing."

I think modes are an idea we want to move away from.  That was generally agreed in the old team.  Advanced spectral selection, such as Edward is working on, is a very special case that would justify a mode.  But otherwise, I think anything you can point at should have its own affordance in a single mode for changing anything.  (That would include the selection box for the old, simple spectral selections.)

I prefer the Esc key (or some other key).  The system we have for adding click-drag-release actions implements Esc key generally and for free in cases of hit area conflicts.  Or maybe, you can research what 3d modelling programs do. The problem of multiple hit-test candidates, having a z-order, must arise often.  Are there conventional solutions here?  (I remember how Pro/ENGINEER did it with three-button mice... but we won't assume the users have those.)

You are wrong that selection is the only possible hit area conflict.  Other conflicts might happen such as with envelope points or dragging samples at a high level of zoom.  With more ingenuity, we might invent yet more click-drag-release actions and have more possibilities of conflict.

You must also remember that clicking on a split between clips causes them to merge.  There is one more conflicting action at a mouse point.

I don't think unnatural changes in the hit test areas should be done just to avoid every possible conflict.  Have the general means and make it better known.

Still, you might also consider this possibility.  Partition the range of y coordinates along the edge into different zones.  Clicking to merge clips, and clicking to drag the edge, could be disjoint areas.  That resolves some but not all possible conflicts.

You are right that the other necessary internals work is in no way blocked by design issues.  We devs just haven't reached it yet.

**Comment by SteveDaulton** [comment] 2021-07-12 09:32
> I think modes are an idea we want to move away from. That was generally agreed in the old team.

I'm not sure that it  is correct to say that the old team  was generally against modes. I recall that you were quite strongly against modes, but I don't recall a strong  consensus about that. My personal view is that modes can be very useful when used appropriately and implemented well.

**Comment by Paul-Licameli** [comment] 2021-07-12 09:55
> > I think modes are an idea we want to move away from. That was generally agreed in the old team.
> 
> I'm not sure that it is correct to say that the old team was generally against modes. I recall that you were quite strongly against modes, but I don't recall a strong consensus about that. My personal view is that modes can be very useful when used appropriately and implemented well.

Well fair enough, but @JamesCrook and I seemed to agree for long that the Tools toolbar ought to be reduced.  I think the "multi" tool behavior should be the behavior of select tool, the Envelope should be a toggle for visibility of it and not a mode, and the Zoom tool is really a mode, but I for one never use it and wonder who does.  So just two or three buttons,  but Edward's project might justify another new button.

**Comment by jounih** [comment] 2021-07-12 10:04
> > I think modes are an idea we want to move away from. That was generally agreed in the old team.
> 
> I'm not sure that it is correct to say that the old team was generally against modes. I recall that you were quite strongly against modes, but I don't recall a strong consensus about that. My personal view is that modes can be very useful when used appropriately and implemented well.

Yeah.. Tool modes are not my first choice because they can also hide functionality and constantly switching between them is annoying, but sometimes they are useful, when operating on distinct tasks on what would otherwise use the same/overlapping targets.

I am also thinking about the potential future of Audacity on tablets/touch interfaces, how do patterns we establish now work with touch in the future, and "Esc" doesn't feel like a right solution there.

Let's keep thinking and discussing!

**Comment by DavidBailes** [comment] 2021-07-13 10:27
@Paul-Licameli
> So design might specify: When a clip is split, each clip gets a complete copy of the wave data, including any hidden wave data that the original clip had. (The implementation can do this easy with real sharing, not duplication.) But thereafter, clip contents are independently modifiable.

Maybe I'm misunderstanding what you're saying here, but isn't there a problem with real sharing. If the clip contents are independently modifiable, then they can be adjusted so that a section of the original data occurs in both clips. If that data is destructively edited in one clip, then the other clip will be affected - surely not what a user would expect?

**Comment by Paul-Licameli** [comment] 2021-07-13 12:59
@DavidBailes are you familiar with the details inside classes WaveClip and Sequence?

When we make a new row id for a block of samples, the data associated with the id are immutable thereafter.  If you edit a clip, by cutting and pasting or doing an effect or what have you, then new sample blocks are made to hold modified data.

In this case, the two clips would no longer share data.  The modified clip will point to new data.  No problem.

It's a bit like Git commits, though the ids here are not a function of contents.

**Comment by DavidBailes** [comment] 2021-07-13 14:53
@Paul-Licameli

thanks for the explanation.

**Closed** 2021-07-20 12:07 UTC
Labels: Design
