### ISSUE TITLE
No progress line when using Wayland

### ISSUE THREAD

**Issue by Devorlon** [audacity/audacity#2248] opened 2021-12-07 23:57 UTC
**Describe the bug**
When using Wayland the progress bar does not move while playing audio.

**To Reproduce**
Steps to reproduce the behaviour:
1. Play audio

**Expected behaviour**
A green progress bar / line moves across the screen

**Screenshots**
Soon™

**Additional information (please complete the following information):**
 - OS: Arch Linux
 - Version Git 

**Additional context**
This doesn't happen under X11

This happens when using:

Archs system package,
Building from the source,
Building from source with audacity_use_wxwidgets=system (wxWidgets (wxgtk3) v3.1.5)

**Comment by LWinterberg** [comment] 2021-12-08 09:11
![image](https://user-images.githubusercontent.com/87814144/145181005-723a5cbe-f850-43e5-8297-acf382f5e103.png)
You mean this thing?

**Comment by Devorlon** [comment] 2021-12-08 17:31
> 

Yes.

**Comment by j-james** [comment] 2022-03-15 02:18
Ooh, I can confirm this. I've been wondering why the play bar wasn't appearing for a while.

Is there a way to force Audacity to run under XWayland as a workaround?

**Comment by Devorlon** [comment] 2022-03-15 02:21
IIRC Audacity uses GTK, so `GDK_BACKEND=x11` should work.

**Comment by j-james** [comment] 2022-03-15 02:26
Thanks, that works. Looks like it's definitely a Wayland issue.

**Comment by j-james** [comment] 2022-03-26 08:25
Seems like the green triangle doesn't move when playing either.

**Comment by ericschdt** [comment] 2022-04-16 12:52
Looks like a duplicate of https://github.com/audacity/audacity/issues/459

**Closed** 2022-04-17 09:03 UTC
Labels: bug-distros, Linux
