### ISSUE TITLE
Conan 2.0.1 build issue

### ISSUE THREAD

**Issue by j-jorge** [audacity/audacity#4405] opened 2023-03-12 07:43 UTC
### Bug description

A fresh clone of tag Audacity-3.2.5 does not build with Conan 2.0.1.

### Steps to reproduce

mkdir build
cd build
cmake ..

### Expected behavior

Configure step complete without errors.

### Actual behavior

Configure step fails with the following message:

```
-- Conan: checking conan executable
-- Conan: Found program /usr/bin/conan
-- Conan: Version found Conan version 2.0.1
usage: conan profile [-h] [-v [V]] [--logger] {detect,list,path,show} ...
conan profile: error: argument subcommand: invalid choice: 'new' (choose from 'detect', 'list', 'path', 'show')
ERROR: Exiting with code: 2
-- Conan: Adding audacity remote repository (https://artifactory.audacityteam.org/artifactory/api/conan/audacity-binaries) verify ssl (True)
usage: conan remote [-h] [-v [V]] [--logger]
                    {add,auth,disable,enable,list,list-users,login,logout,remove,rename,set-user,update}
                    ...
conan remote: error: unrecognized arguments: https://artifactory.audacityteam.org/artifactory/api/conan/audacity-binaries True
ERROR: Exiting with code: 2
CMake Error at cmake-proxies/cmake-modules/conan.cmake:858 (message):
  Conan remote failed='2'
Call Stack (most recent call first):
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:57 (conan_add_remote)
  CMakeLists.txt:237 (include)
```

### Audacity Version

other

### Operating system

Linux

### Additional context

```console
$ conan --version
Conan version 2.0.1
$ cmake --version
cmake version 3.24.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.10
DISTRIB_CODENAME=kinetic
DISTRIB_DESCRIPTION="Ubuntu 22.10"
```

**Comment by LWinterberg** [comment] 2023-03-12 12:23
Duplicate of #4360

**Closed by LWinterberg** 2023-03-12 12:23 UTC
Labels: bug
