### ISSUE TITLE
Pasting a clip resets its name

### ISSUE THREAD

**Issue by luca-trifan** [audacity/audacity#6926] opened 2024-07-19 18:26 UTC
### Bug description

When pasting a clip either from another file or even from the same track, the original name of the clip resets to an auto-generated one.

### Steps to reproduce

1. Copy any clip in its entirety
2. Paste it either in the same file or another file

### Expected behavior

The name of the clip is preserved.

### Actual behavior

The clip is renamed with an auto-generated title

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, Linux

**Comment by petersampsonaudacity** [comment] 2024-07-20 10:58
This is a duplicate of #6928

**Comment by luca-trifan** [comment] 2024-07-20 11:05
So it's a duplicate of an issue reported after I did?

**Comment by petersampsonaudacity** [comment] 2024-07-20 11:28
> So it's a duplicate of an issue reported after I did?

Yes, sorry,  🥇 

I was working my way down from the top of the issues log and thus encountered #6928 first   ...

**Comment by dozzzzer** [comment] 2024-07-22 13:29
Bisects to https://github.com/audacity/audacity/commit/983dc1b7c7fd5008fd40420fefe6b63d68cd6a77

**Comment by kryksyh** [comment] 2024-07-25 10:50
_CC from PR_

While discussing this issue, @LWinterberg @dozzzzer @kryksyh came up with these changes to new clip naming:

Previous behavior:

- Recordings are named as TrackName `#TakeNo`
- Generated clips are named as `TrackName ClipNo`
- Clip copies are named as `OriginalName.CopyNo`, which was broken since 3.5.0
- The numbering of recordings and generated clips was parallel, meaning there could be a recording named `TrackName #1` and a generated clip named `TrackName 1`

To unify and simplify naming, the behavior will be changed as follows:

- Recordings are named as `TrackName.ClipNo`
- Generated clips are named the same as recordings `TrackName.ClipNo`
- Clip copies keep the original name without additional numbering

@petersampsonaudacity I would appreciate your feedback on these changes.

**Comment by SteveDaulton** [comment] 2024-07-25 11:21
I'm not a big user of clip names, but the proposed, simplified scheme, sounds reasonable to me.

**Comment by petersampsonaudacity** [comment] 2024-07-25 12:00
@kryksyh 

Dmitry, l agree with Steve that this simplified approach sounds very sensible.  I'm pretty sure most end-users would agree too.

**Comment by dozzzzer** [comment] 2024-07-25 14:35
Tested

**Comment by petersampsonaudacity** [comment] 2024-07-30 14:56
@kryksyh @dozzzzer @LWinterberg 

Testing on W11 with latest 3.6.2 Beta

As far as I can tell this now looks to be fixed for 3.6.2

**Comment by SteveDaulton** [comment] 2024-08-06 11:34
> To unify and simplify naming, the behavior will be changed as follows:
> 
> *  ...
> * Clip copies keep the original name without additional numbering


This is not working for me with Audacity 3.7.0 alpha id: 132049 

**Steps to reproduce:**

1. Launch Audacity
2. Generate a 30 second Chirp
3. Rename the clip "chirp"
4. Generate a 30 second tone into a new track
5. Select the "chirp" clip and "Ctrl + C" to  copy.
6. Click on the second track after the first clip
7. "Ctrl + V" to paste.

**Expected behaviour:**

"Clip copies keep the original name without additional numbering", so the pasted clip will be called "chirp".

**Actual behaviour**

The pasted clip is named "Audio 2 1"

**Comment by LWinterberg** [comment] 2024-08-06 11:40
3.6.2 will get merged back into master after that's released.

**Closed by LWinterberg** 2024-08-06 11:40 UTC
Labels: bug, regression, Clips

**Comment by SteveDaulton** [comment] 2024-08-06 12:20
It might be a good idea to leave issues open until they are actually fixed. Not only would this save time and confusion for community contributors, but would provide an opportunity for testing fixes prior to release.
