### ISSUE TITLE
Space added when pasting a clip selection at T=0

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#7816] opened 2024-11-29 09:45 UTC
### Bug description

A space is added at the beginning of a track when pasting a selection at T=0
i.e the track is shifted rightwards - see images below

The length of the shift varies with the length of the selection but I can determine no mathematical relationship between the length of the selection and the size of the shift.

Testing shows that this is a regression on 3.4.1

### Steps to reproduce
1. generate a 30 second chirp
2. select from 10-15 second
3. Ctrl+C to add this to the clipboard
4. move cursor to T=0
5. Ctrl+V to paste
6. Observe: the 5 second clip is pasted at the beginning in the chirp but the whole track is shifted rightwards

_Oddly, if you select the whole 30 second chirp at step 2 then no shift of the track occurs_

### Expected behavior
![image](https://github.com/user-attachments/assets/18faa2bd-be86-424a-a411-cade73805955)

### Actual behavior
![image](https://github.com/user-attachments/assets/ccf2fa9e-b995-4077-a4ba-ad0edd318ac8)

### Audacity Version
Audacity 3.7.x - all 3.x Audacity from 3.4.2 onwards

### Operating system
Windows 10

### Additional context
None

**Comment by DavidBailes** [comment] 2024-11-29 09:50
Duplicate of https://github.com/audacity/audacity/issues/7410

**Closed** 2024-11-29 09:56 UTC
Labels: AU3-bug, regression
