### ISSUE TITLE
Stereo tracks splitting for no apparent reason when moving audio clips around

### ISSUE THREAD

**Issue by pokepress** [audacity/audacity#5491] opened 2023-11-04 03:15 UTC
### Bug description

While adding segments to a podcast episode today, I noticed that several of my stereo tracks were turning into a pair of mono tracks for no apparent reason. This occurred when dragging clips between tracks. Rejoining the tracks was technically an option, however that would remove any clip boundaries on the clip that got split, so it usually made more sense to undo a few times and try the move again. The track that got split isn't necessarily one that the clip was being moved to or from-sometimes it was in between, so maybe there's an issue if a track is dragged across multiple stereo tracks. I think I also had this happen during a cut/paste operation, but I'm not sure.

### Steps to reproduce

1. Move a clip from one stereo track to another stereo track in the same project.
2. One or more of the stereo tracks in the project may split into two mono tracks, despite the user not requesting that action.

### Expected behavior

No tracks should be split in this workflow.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

My best workaround this seemed to be to move tracks up so they were adjacent before performing the drag operation. I'm not sure if it really made a difference, though.

**Comment by RadioSoundWave** [comment] 2023-11-04 03:56
Facing the same problem with Mono tracks splitting when copy pasting within the same track. Each time I paste, a new clip is created in the place. Finding it very difficult to precisely edit audio due to this issue! I just updated to the new version! Old one was fine.

**Comment by petersampsonaudacity** [comment] 2023-11-04 09:29
I managed to make this happen once testing on W10 with 3.4.0 - anf not only did the track I moved the clip to get split to mono, so did the track I moved the clip from.

But is is **_FAR_** from repeatable - even trying hard for many many time I can't get it to happen again

_@Paul-Licameli I know you did some work on stereo tracks for 3.4.0, can you cast any insight onto what might be happening?_

**Comment by petersampsonaudacity** [comment] 2023-11-04 09:39
Here seem to be some repeatable steps

1. launch 3.4.0
2. get some stereo audio
3. select a section and split the clip
4. add two stereo tracks
5. drag the middle clip down to the lower stereo track
6. Observe: the originating track and the middle stereo track (empty one) get split to mono
 
![image](https://github.com/audacity/audacity/assets/50205984/3ce19692-46d7-44cb-980e-52874e4db409)

**Comment by crsib** [comment] 2023-11-04 09:41
@chinakov fyi

**Comment by dozzzzer** [comment] 2023-11-04 09:56
Duplicate of https://github.com/audacity/audacity/issues/5389

**Closed by dozzzzer** 2023-11-04 09:56 UTC
Labels: bug
