### ISSUE TITLE
MacOS: Copy/Paste in "Save As..." dialog window is broken

### ISSUE THREAD

**Issue by dreikelvin** [audacity/audacity#5582] opened 2023-11-11 12:10 UTC
### Bug description

Somehow I seem to be unable to paste a string of text into the textbox of the "Save As..." dialog on MacOS. 

### Steps to reproduce

1. create an audio project
2.  click on file->export audio
3.  in the save dialog, open the file browser by clicking on “browse…”
4. now try to copy and paste a piece of text in the file name field

### Expected behavior

Cmd+V just pastes your text into the field

### Actual behavior

“standard error” sound meaning something seems to be blocked/disabled

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

### Additional context

A workaround is to use right-click and then “paste” - but that can’t be a standard solution as it circumvents the “regular” user pattern.

**Comment by LWinterberg** [comment] 2023-11-13 09:49
Cannot reproduce on Windows

Fwiw, the file browser is just the system file browser now. It should behave the same as the cmd+s dialog in other programs

**Comment by dreikelvin** [comment] 2023-11-13 09:52
Correct, this is a MacOS only issue. Reason why I put this in the title 👍Am 13-11-2023 um 10:49 schrieb LWinterberg ***@***.***>:﻿
Cannot reproduce on Windows
Fwiw, the file browser is just the system file browser now. It should behave the same as the cmd+s dialog in other programs

**Comment by chinakov** [comment] 2023-11-17 14:42
Reproduced on macOS Sonoma.

**Comment by LWinterberg** [comment] 2024-10-15 13:55
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.

**Closed by LWinterberg** 2024-10-15 13:55 UTC
Labels: AU3-bug, P3, macOS
