### ISSUE TITLE
"Failed To Send Crash Report" - Crash Reports Do Not Send Successfully.

### ISSUE THREAD

**Issue by scramblr** [audacity/audacity#7084] opened 2024-08-12 23:03 UTC
### Bug description

Whenever a crash happens, the button labelled "Send" in the Crash Report window fails to actually send the crash report. This is regardless of the internet connection being used, or the crash type involved as I have attempted to submit crash reports under quite a few different scenarios at this point. Attached is a screenshot of the latest crash and submission failure. 

![Screenshot 2024-08-12 155405](https://github.com/user-attachments/assets/309d7325-f0bb-4e8e-b21d-3f237735869c)

### Steps to reproduce

Steps to reproduce:
1.) Experience crash in Audacity - Usually during recording.
2.) Review Crash details in Crashpad window
3.) Attempt to send details to team for debugging by clicking "Send"
4.) Experience failure "Failed To Send Crash Report"

### Expected behavior

The crash reports should send. 

### Actual behavior

The crash reports do not send. 

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

This appears to be a mostly agnostic issue.

**Comment by dozzzzer** [comment] 2024-08-13 07:45
Duplicate of https://github.com/audacity/audacity/issues/4154

**Closed by dozzzzer** 2024-08-13 07:45 UTC
Labels: bug

**Comment by petersampsonaudacity** [comment] 2024-08-13 07:46
This is a known and already logged _(over a year and a half ago)_ issue that thus far Muse have been unable to solve:

see:  Crash report fails to send #4154
