### ISSUE TITLE
Project bloat when resampling

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3951] opened 2022-11-17 00:55 UTC
### Bug description

Resampling large projects in Audacity 3.2.1 is about 40% slower than in Audacity 2.4.2, and the resulting project size is more than 300% bigger. 

### Steps to reproduce

1. Generate a 2 hour, stereo tone, 440 Hz, 0.8 amplitude, 44100 Hz sample rate.
2. Resample the track to 96000
3. Repeat steps with Audacity 2.4.2 and Audacity 3.2.1 (AppImage)

Testing with a budget i7 laptop + SSD, Xubuntu 22.04:

Audacity 2.4.2:
Time: 100 seconds (total)
Project size: 7.6 GiB

Audacity 3.2.1:
Time: 142 seconds (total)
Project size: 24.5 GiB

### Expected behavior

The project size is expected to be around 7.6 GiB

### Actual behavior

The project size in Audacity 3.2.1 (and 3.2.2 alpha) is 24.5 GiB, and (not surprisingly) resampling is very noticeably slower.

While the AUP3 file in 3.2.1 / 3.2.2 is only slightly larger than 2.4.2's AUP + _data folder, Audacity 3.2.1's WAL file has grown to a massive 16.9 GiB (18,135,403,912 bytes).

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

**Comment by LWinterberg** [comment] 2022-11-17 09:57
Can't quite reproduce this. After resampling, the project file is 8.2GB (same as your 7.6GiB), with the WAL being 8.9GB. After saving and closing, the project file (resp. _data folder) is 5.6GB for both versions.

**Comment by crsib** [comment] 2022-11-17 10:00
The way Audacity checkpoints the journal is quite complex and confusing. However I expect the very similar peak size for Audacity 2 project as well.

**Comment by SteveDaulton** [comment] 2022-11-17 12:44
> However I expect the very similar peak size for Audacity 2 project as well.

I've just tested in a VM that had 4.7G free disk space and performed the test but  with just 1 hour stereo. The test completed successfully using Audacity 2.

Using `watch -n 1 df -h /dev/sda1` indicated progressively decreasing free disk space with 903M free at the end.

**Comment by crsib** [comment] 2022-11-17 13:00
I'm not sure what exactly I should understand from this message.

Audacity has to keep all the previous samples before it is closed in order to allow you to undo resampling. Any *destructive* action increases the total disk space consumption proportionally to the processed samples count. The space is reclaimed when Audacity is closed. I am pretty sure that this is the way Audacity always worked.

SQLite-based project format used by Audacity 3 stores all the new data in the WAL file initially, which is "checkpointed" at some point into the AUP3. Probably the most serious drawback is that reclaiming disk space requires potentially a large amount of the free disk space to complete. However, I don't think that this is the case you described. I cannot reproduce the issue either, similar to @LWinterberg.

In any case we are unable to change the file format significantly in Audacity 3.

**Comment by SteveDaulton** [comment] 2022-11-17 13:09
> I'm not sure what exactly I should understand from this message.

2 hours, 2 channels, 4 bytes per sample at 44100 Hz = 2.54 GB
2 hours, 2 channels, 4 bytes per sample at 96000 Hz = 5.53 GB
Expected project size (including undo data) around 8 GB total.

For 1 hour, the expected size is around 4GB.

In Audacity 2, the actual disk usage matches the expected size.
In Audacity 3.2.1 the actual disk usage is more than three times the expected size.

**Comment by crsib** [comment] 2022-11-17 13:55
2 hours chirp at 44100

```
dvedenko@crsib-desktop:/mnt/d/Audacity$ ls -l
total 2512256
-rwxrwxrwx 1 dvedenko dvedenko 2572550144 Nov 17 16:13 resampling.aup3
```

After resampling (58 secs on SATA3 SSD)
```
dvedenko@crsib-desktop:/mnt/d/Audacity$ ls -l
total 15500192
-rwxrwxrwx 1 dvedenko dvedenko 8217690112 Nov 17 16:17 resampling.aup3
-rwxrwxrwx 1 dvedenko dvedenko     950272 Nov 17 16:17 resampling.aup3-shm
-rwxrwxrwx 1 dvedenko dvedenko 7653212192 Nov 17 16:17 resampling.aup3-wal
```
After closing
```
dvedenko@crsib-desktop:/mnt/d/Audacity$ ls -l
total 5484772
-rwxrwxrwx 1 dvedenko dvedenko 5616406528 Nov 17 16:18 resampling.aup3
```

Audacity 2.4
Chirp:
```
du -h resampling-2_data/
....
2.5G    resampling-2_data/
```
Resamling (>90 secs on SATA3 SSD)
```
dvedenko@crsib-desktop:/mnt/d/Audacity$ du -h resampling-2_data/
...
7.7G    resampling-2_data/
```
After closing
```
dvedenko@crsib-desktop:/mnt/d/Audacity$ du -h resampling-2_data/
...
5.3G    resampling-2_data/
```

So there is no size difference after the project is closed and there no  "more than three times" difference when the project is open. It appears that SQLite does not truncates the WAL file, so yes, there is an additional overhead, roughly similar to the size required for the longest operation. Two times in this specific case. However, as I said in my previous comment - **we are not able to change the file format significantly in Audacity 3**. This issue is not a bug and it won't be addressed in Audacity 3.

FWIW it took Audacity 2 several seconds to open the project, while it was instantaneous with Audacity 3.

**Closed by crsib** 2022-11-17 13:55 UTC
Labels: bug
