### ISSUE TITLE
Internal error at[...] waveclip.cpp line xxx

### ISSUE THREAD

**Issue by rhea-kinn** [audacity/audacity#4830] opened 2023-06-23 07:41 UTC
### Bug description

Pop up error/bug when adding effects (might happen to other audio related edits) to tracks/audio clip(s) in Audacity. 

### Steps to reproduce

1. Add an audioclip(s)/tracks
2. Select the audioclip(s)/tracks
3. Add an effect (might work with other audio related edits) e.g. EQ, limiter, etc.
![image](https://github.com/audacity/audacity/assets/137411450/a69a1079-3ba7-4297-a025-a667bd06e368)
N.B. the error/bug might be variable e.g. line 161, 174, 176, etc. with different steps/actions

### Expected behavior

The effects should've been added without errors

### Actual behavior

![image](https://github.com/audacity/audacity/assets/137411450/a69a1079-3ba7-4297-a025-a667bd06e368)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

-----

**Comment by LWinterberg** [comment] 2023-06-23 10:25
Duplicate of #4653

**Closed by LWinterberg** 2023-06-23 10:25 UTC
Labels: bug
