### ISSUE TITLE
Labeled audio operations no longer work on selected audio tracks in 3.x

### ISSUE THREAD

**Issue by JC3** [audacity/audacity#3679] opened 2022-09-23 17:10 UTC
### Bug description

When any audio tracks are selected, all labeled audio operations (e.g. delete, split cut, etc.) become a no-op (although they're still added to the undo stack, oddly). Additionally, even when *all* audio tracks are selected, the operations do not work.

The only way to perform any labeled audio operations is to select the label track, ensure no audio tracks are selected, and then apply the operation. The action will be performed on *every* audio track.

This is new behavior present in at least 3.1.3 and 3.2.0 (did not test earlier 3.x), but not in 2.4.2 or prior. 

In 2.4.2 and prior, if specific audio tracks were selected, labeled audio operations were applied only to the selected audio tracks.

As a consequence, it is no longer possible to perform labeled audio operations on specific individual audio tracks. It's either all or none.

Also, possibly related, sometimes the labeled audio menu items are disabled even when a label track is selected, although I'm unable to reproduce that consistently.

### Steps to reproduce

1. In a project with multiple audio tracks and a label track, select the label track and any (or all) audio tracks.
2. Edit -> Labeled Audio -> Pick anything.

### Expected behavior

Operation is applied on the selected audio tracks, using the selected label track.

From 2.4.2:

![242opt](https://user-images.githubusercontent.com/5651184/192015532-30d6010a-fce4-4041-8a2d-2cc04ca4f50a.gif)

### Actual behavior

Nothing happens unless no audio tracks are selected.

From 3.2.0:

https://user-images.githubusercontent.com/5651184/192015616-7afce3fe-da5a-46d4-8eec-948111e11349.gif

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS

**Comment by JC3** [comment] 2022-09-23 17:17
Note: In my opinion this one is a slightly higher than medium priority; since this is an operation I perform a lot, I'm actually just using 2.4.2 when I need to do a lot of label operations on projects with many tracks for now.

**Comment by petersampsonaudacity** [comment] 2022-09-24 17:00
Testing on W10 shows that this is a regression on 2.4.2, introduced in 3.0.0

_Given that 3.0.0 was released 18 months ago and this is the first report of this I suspect that not many folk use this._

**Comment by JC3** [comment] 2022-09-24 19:33
> Testing on W10 shows that this is a regression on 2.4.2, introduced in 3.0.0
> 
> _Given that 3.0.0 was released 18 months ago and this is the first report of this I suspect that not many folk use this._

Possibly; or it's unreported; or it's unused because it doesn't work; or a lot of label-related functionality is unused because 2.x left a semi-permanent bad taste with things like time shifting a selection not working on labels (really killed their usefulness in editing; works great now though). You'd have to add appropriate usage analytics to Audacity.

Still: If an audio editor lets you label areas and lets you select tracks, then doing things with those areas on those selected tracks seems like a basic feature for that editor; so it should probably work. :)

**Comment by petersampsonaudacity** [comment] 2022-10-01 11:19
@LWinterberg @dozzzzer @Tantacrul 

Surely this should get a fairly high P-rating as it is functionality that no longer works in Audacity and hasn't done since 2.4.0

**Comment by JC3** [comment] 2023-02-03 17:20
I want to mess around trying to add some new label operations, but I can't because the labels don't really work in 3.x.

Can somebody take a look at this? I'm not familiar enough with the source to diagnose the problem.

**Comment by SteveDaulton** [comment] 2023-05-09 13:31
Labelled audio commands are still non-functional in Audacity 3.3. (Tested with AppImage on Ubuntu 22.04)

**Comment by SteveDaulton** [comment] 2023-07-21 10:39
Labelled audio commands are still non-functional in Audacity 3.4.0 (Tested with Commit Id: ab110a on ubuntu 22.04)

**Comment by Paul-Licameli** [comment] 2023-07-21 14:46
May have been broken by commits 235cc242e4678c7b65428156056afe652447c07a and e8b2602473374468df28d490c62beafe75b0992b

**Comment by Paul-Licameli** [comment] 2023-07-21 14:49
> May have been broken by commits [235cc24](https://github.com/audacity/audacity/commit/235cc242e4678c7b65428156056afe652447c07a) and [e8b2602](https://github.com/audacity/audacity/commit/e8b2602473374468df28d490c62beafe75b0992b)
> 
> Which was addressing: https://bugzilla.audacityteam.org/show_bug.cgi?id=2616

Which had these steps to reproduce (it was only about the menu item statuses):

1) Get some audio
2) range label some sections
3) Edit>Labeled Audio
4) make a selection in the label track that covers all or some of step 2's labels
5) Observe Cut and Delete are black and usable
6) Turn on Sync-Lock
7) Observe: Cut and Delete are grayed-out and un-usable

**Comment by Paul-Licameli** [comment] 2023-07-21 14:51
Other parts of that fix are at commits 086cacad76210ad74ec2bd782b0f5c99b8fe2229 and 26d8fcad66479754b1481b4136022379d2240030

**Comment by Paul-Licameli** [comment] 2023-07-21 15:18
I have reviewed the source code history.

Until 2.4.2, all of these commands affected wave tracks only.  When no wave tracks were selected, they applied to all wave tracks.  When any wave tracks were selected, they would be applied to all selected wave tracks and all other wave tracks sync-locked to them.  But the Bugzilla issue was that the menu items were disabled with sync lock on.

The commits mentioned made many changes, including, to apply the commands to tracks of other types, but I think all the combinations were not tested well.

So in Audacity 3, if you select only the label track, or if you sync lock, you can in fact see changes in other wave tracks.

There is a difference with sync lock:  the cutting and deleting commands do also delete the labels in that case, but not when there is no sync lock.

Other weird behavior:  it is not necessary to copy from non-selected tracks in sync lock groups to keep synchronization, but that is done, as you can see if you paste after the copy.

Likewise Silence, Split, Join, Detach At Silences should not affect non-selected tracks.

**Comment by ianalarina** [comment] 2023-11-09 19:09
@dozzzzer this was supposed to be addressed within refactoring that is already merged. double-check pls whether this is fixed

**Comment by dozzzzer** [comment] 2023-11-10 11:26
As of 3.4.1, this is still relevant: current behavior is exactly the same as described in the Actual Behavior above. @ianalarina

**Comment by dozzzzer** [comment] 2024-07-19 08:49
Testing this shows that **Labeled Audio** operations now work as they should, with the only exception of **Split Cut** still failing to work properly, namely when it's applied and the option in Preferences _"Track Behaviors > Editing a clip can move other clips"_ is set to OFF, the user sees
<img width="368" alt="image" src="https://github.com/user-attachments/assets/58f4c44e-7188-4d25-90f8-9fd509277995">

Since this a "cut" type operation, rather than "paste", it's never supposed to return such an error.

https://github.com/user-attachments/assets/8f570bfd-23dd-49f7-8c8e-d7478d52d8ec

With that being said, moving it back to In Progress and aiming for 3.6.2. @kryksyh

**Comment by dozzzzer** [comment] 2024-07-23 12:29
@kryksyh 

Previously reported issues are fixed now. However, there's another problem: Join command doesn't work as intended.

See the screenshot below. This is the result of the Split command after selecting both the stereo and label tracks.

<img width="900" alt="image" src="https://github.com/user-attachments/assets/ddd16c72-9809-46f0-bca3-ae2ad81c3bfb">

If you now apply the Join command while leaving the selection untouched, the result will look like this:

<img width="900" alt="image" src="https://github.com/user-attachments/assets/4bb3d441-562a-4863-9033-289fb8b34112">

...which is incorrect. The expected behaviour, in this case, would be one solid clip without the vertical split lines in place.

**Comment by dozzzzer** [comment] 2024-07-24 10:39
Tested

**Closed** 2024-07-29 07:27 UTC
Labels: bug, P3, regression, Labels
