### ISSUE TITLE
Can't rename clips

### ISSUE THREAD

**Issue by robindouglasjohnson** [audacity/audacity#3704] opened 2022-09-27 15:33 UTC
### Bug description

Seems to be intermittent, but I'm unable to rename audio clips. Double-clicking the title of the click in the track just selects the clip. Right-clicking and selecting "Rename clip", or pressing ctrl+F2, both do nothing.

### Steps to reproduce

1. Get some audio
2.  split it into two clips
3. Separate the clips such that only the first clip is on screen
4. Try to rename the clip, either by double-clicking its title, or selecting it then either right-clicking and choosing "Rename clip" or pressing Ctrl+F2
5. Observe:  Nothing happens

 _@vsverchinsky Vitaly  I, Peter Sampson, edited the STRs following a reliable simple reproducible set pointed out later in this bug-thread by @DavidBailes_

### Expected behavior

You should be able to rename clips

### Actual behavior

I cannot rename clips

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Windows 11. Behaviour is intermittent but I can't see a pattern. Possibly once a project gets into this state (or beyond a certain size/number of clips?) it becomes permanently impossible to rename clips. I'm actually able to rename the clips in a new project I just created, but not in my existing one, both open at the same time.

**Workaround**
@DavidBailes points out in a comment below in this bug-thread - there is a workaround to be had by setting the **Tracks Behaviors** pref for  "**Use dialog for the name of a new label**" to be **on**.

Somewhat surprisingly this totally undocumented Easter-Egg trick works as for some unknown reason this setting also affects the behaviour of clip renaming forcing that to be done by dialog rather than in the clip-handle drag-bar:
a) this is undocumented in the Manual
b) it is totally unexpected behavior from the labeling of the preference, with no indication that it also acts on clips
c) maybe there should be separate new **Tracks Behaviors** pref for  "**Use dialog for editing clip names**" - for greater clarity of purpose,

**Comment by LWinterberg** [comment] 2022-09-27 16:07
I could reproduce something similar once - I was able to rename the clip but no change showed until I pressed Enter. Same thing for resizing clips, they resized just fine but their visuals didn't update until I let go

**Comment by petersampsonaudacity** [comment] 2022-09-28 08:16
Testing on W10 with 3.2.0 I cannot reproduce this

**Comment by Ryan-Miller-Audacity** [comment] 2022-09-28 10:44
Taking a look at this I cannot reproduce this either. A couple of things I noted when testing: Be sure you have the track/clip selected other "rename clip" will disabled in the context menu, Ctrl+F2 shortcut also only works when the track/clip is selected, if you have multiple clips within the same track you have to select a specific clip to utilize the rename clip option in the context menu. I did not notice any abnormalities with double-clicking the clip name (which selects the clip and then enters the editing of the clip name). 

I did not notice any abnormalities with changes/editing field not showing either. When conditions were met the field was editable and changes were seen instantly for me.

**Comment by Korsani** [comment] 2022-10-03 21:57
Same here : Ctrl+F2 does nothing, and the mentionned conditions are met.
I reverted to 3.1.3 on which Ctrl+F2 is ok. Double clicking is also ok in 3.1.3, but fails in 3.2.0

> Taking a look at this I cannot reproduce this either. A couple of things I noted when testing: Be sure you have the track/clip selected other "rename clip" will disabled in the context menu, Ctrl+F2 shortcut also only works when the track/clip is selected, if you have multiple clips within the same track you have to select a specific clip to utilize the rename clip option in the context menu. I did not notice any abnormalities with double-clicking the clip name (which selects the clip and then enters the editing of the clip name).
> 
> I did not notice any abnormalities with changes/editing field not showing either. When conditions were met the field was editable and changes were seen instantly for me.

**Comment by petersampsonaudacity** [comment] 2022-10-12 09:51
See also:   A clip needs to be selected for the context menu to enable "Rename Clip" #3101

**Comment by petersampsonaudacity** [comment] 2022-10-12 10:05
Another user on the Forum's Russian section, Ruslan, has reported the same issue:
https://forum.audacityteam.org/viewtopic.php?f=10&t=127231

He sent me an AUP3 project that fails for him - at first I could not reproduce this but now although I can rename clips in the first half of his project I now find the renaming clips when I scroll to the second half.

I can probably supply a copy of the project or a link to it if the devs want to take a look at this one, just let me know.

**Comment by petersampsonaudacity** [comment] 2022-10-13 17:09
@LWinterberg  - does anybody at Muse want a copy of Ruslan's project that exhibits this bug

**Comment by crsib** [comment] 2022-10-13 19:21
@petersampsonaudacity I do

**Comment by petersampsonaudacity** [comment] 2022-10-14 08:43
> @petersampsonaudacity I do

@crsib Hi Dmitry, I sent you an email with a link to the project in my Dropbox.

**Comment by petersampsonaudacity** [comment] 2022-11-09 12:37
Testing on W10 with latest 3.2.2 beta:  audacity-win-3.2.2-beta-20221109+f0bb347-x64-msvc2022

I still cannot reproduce this.

@Dmitry  _did you get anywhere with that project that failed that a Forum user sent me and I forwarded to you?_

**Comment by Goldmaster** [comment] 2022-11-13 18:26
Im having this issue. if i right click and rename, nothing happens. tried ctrl f2 and nothing. im using audacity protable on windows

**Comment by dozzzzer** [comment] 2022-11-23 16:26
>  im using audacity protable on windows

which version?

**Comment by robolton** [comment] 2022-11-24 00:53
I too am having this problem in Audacity 3.2.1 with Windows 11. Double clicking the bar at the top of the clip and right clicking in the clip won't let me rename. This is in a project with a number of clips. I tried renaming in a project with just one clip and it works. But the project with multiple clips is where renaming is most useful!

**Comment by theAwesomeFufuman** [comment] 2022-12-03 10:04
I am experiencing the same issue, but I can always rename the clip after I move them to another track and then back again, or if I cut(Ctrl + X) and paste(Ctrl + V) them back again, see attached video:
https://user-images.githubusercontent.com/57533864/205434793-5660a3a8-012c-4a2b-b595-f6ae49e26793.mp4

OS: Windows 11 Pro x86_64

**The Build**
- Program build date: Oct 5 2022
- Commit Id: 969e36 of Wed Oct 5 13:43:02 2022 +0300
- Build type: CMake Release build (debug level 1), 64 bits
- Compiler: MSVC 19.33.31630.00

**Core Libraries**
- wxWidgets    (Cross-platform GUI library)    3.1.3 (Audacity)
- PortAudio    (Audio playback and recording)    v19
- libsoxr    (Sample rate conversion)    Enabled

**File Format Support**
- libmpg123    (MP3 Importing)    Enabled
- libvorbis    (Ogg Vorbis Import and Export)    Enabled
- libid3tag    (ID3 tag support)    Enabled
- libflac    (FLAC import and export)    Enabled
- libtwolame    (MP2 export)    Enabled
- QuickTime    (Import via QuickTime)    Disabled
- ffmpeg    (FFmpeg Import/Export)    Enabled
- gstreamer    (Import via GStreamer)    Disabled

**Features**
- Nyquist    (Plug-in support)    Enabled
- LADSPA    (Plug-in support)    Enabled
- Vamp    (Plug-in support)    Enabled
- Audio Units    (Plug-in support)    Disabled
- VST    (Plug-in support)    Enabled
- LV2    (Plug-in support)    Enabled
- PortMixer    (Sound card mixer support)    Enabled
- SoundTouch    (Pitch and Tempo Change support)    Enabled
- SBSMS    (Extreme Pitch and Tempo Change support)    Enabled

**Comment by DeeFeeCee** [comment] 2022-12-11 20:32
Can reproduce. Moving clips from & back to track seems to work. Bug tends to happen with particularly long tracks/clips.

Before fixing, the clip cannot be renamed with ctrl+F2, right click dialogue, or Edit > Rename Clip. Things that seemed to fix the bug include moving the clip, moving adjacent clips, Edit > Audio Clips > Join (despite the result being identical to the original), & applying an effect that alters the duration of the clip (although you have to deselect & reselect). None of the workarounds work after undoing the fix (ctrl+Z).

Audacity 3.2.2, all Features enabled except Audio Units, Preferences: Tracks Behaviors all disabled except "dragging selection edges". Windows 10.

**Comment by DavidBailes** [comment] 2022-12-12 09:58
> Can reproduce.

I think that there is a workaround for this. In the Track behaviors section of preferences, set "use dialog for the name of a new label".

**Comment by petersampsonaudacity** [comment] 2022-12-12 10:00
> I think that there is a workaround for this. In the Track behaviors section of preferences, set "use dialog for the name of a new label".

@DavidBailes  - surely this workaround affects only labels - not the clip-names that this bug thread is about ??

**Comment by DavidBailes** [comment] 2022-12-12 10:02
> @DavidBailes - surely this workaround affects only labels - not the clip-names that this bug thread is about ??

@petersampsonaudacity . Try it!

**Comment by petersampsonaudacity** [comment] 2022-12-12 10:05
> Try it!

I would, but I can never get clip renaming to fail no matter how hard I try  ;-)

**Comment by DavidBailes** [comment] 2022-12-12 10:27
Create two audio clips, with a gap between them. Arrange for only the first clip to be visible. Try changing its name. (Its possible that there's more than one bug preventing renaming.)

**Comment by petersampsonaudacity** [comment] 2022-12-12 10:46
@DavidBailes  - yes, thanks, nice simple steps to get an un-renamable clip

And yes, indeed the workaround works  - but that's because the Tracks Behaviors pref for  "**Use dialog for the name of a new label**"  also acts on the renaming of clips:
 "use dialog for the name of a new label"

And
a) that is an undocumented "Eater-egg"
b) it means that the pref should probably be recast as  "**Use dialog for the name of a new label and for editing clip names**"

**Comment by petersampsonaudacity** [comment] 2022-12-12 11:05
Following @DavidBailes simple and reproducible STRs I updated the original post in this bug-thread with the updated STRs and additional comments.

**Comment by DavidBailes** [comment] 2022-12-12 11:09
> Create two audio clips on one track, with a gap between them. Arrange for only the first clip to be visible. Try changing its name. (It's possible that there's more than one bug preventing renaming.)

For this example, in bool WaveTrackAffordanceControls::StartEditClipName(), mClipNameVisible is incorrectly false. But if the use of a dialog is enabled, it's in not affected by this.

**Comment by petersampsonaudacity** [comment] 2022-12-12 14:34
Testing on W10 with @vsverchinsky 's latest branch build:  audacity-win-3.2.2-alpha-20221212+b998bb3-x64

Using the Steps To Reproduce this now appears to be fixed in Vitaly's branch build

_I cannot vouch for any other possible causes listed in this bug-thread as @DavidBailes 's STRs are the _**only**_ way I've ever gotten to see this bug,_

**Comment by konradphoto** [comment] 2022-12-22 10:12
I have the same issue with Audacity 3.2.2 on MacOS Monterej 12.6

**Comment by petersampsonaudacity** [comment] 2023-01-07 14:55
Another Forum user report of this:

https://forum.audacityteam.org/viewtopic.php?f=48&t=128636&p=462086

**Comment by Ryan-Miller-Audacity** [comment] 2023-01-18 12:44
I've tested and verified this fix on MacOS and Windows. 

These changes do appear to have introduced a change in behavior/bug though: 

Now when you are editing a clip name and you delete the last letter of text, it will remove focus from the editing field, reset the clip name and make the entire (split) clip the focus. TLDR; You can no longer fully remove the name of a clip. Previously (before this fix - verified in 3.2.3) you could backspace the text in the clip name all the to nothing left and continue editing the clip name just fine.

This effects both split clips and non split clips.

STR:

1. Open Audacity and generate some audio
2. Double click a clip name or right click and select Rename clip
3. Select the end of the text line (to remove the highlight that is on the text) 
4. Backspace through the text until you get to the last character
5. Note that upon deletion of the last character the clip name is reset and your focus is removed from clip name editing field.

You can see the different behaviors in the following videos: 

Before the fix: 

https://user-images.githubusercontent.com/88568755/213174615-3f8ac155-0528-415a-b304-8bd7756e4f7e.mp4


After the fix: 

https://user-images.githubusercontent.com/88568755/213174646-a51b897d-8058-4de5-bddc-377285b4b680.mp4

**Comment by Ryan-Miller-Audacity** [comment] 2023-01-23 20:30
Confirmed that the bug I mentioned above has been fixed in the most recent build from PR #4056 . Sanity checked original bug as well and confirmed good there too. After review this is good for merge.

**Closed** 2023-01-26 09:06 UTC
Labels: bug, Clips
