### ISSUE TITLE
v3.4.0 default file extension not working

### ISSUE THREAD

**Issue by aschiefe** [audacity/audacity#5495] opened 2023-11-04 19:13 UTC
### Bug description

When I export an .mp3 file the .mp3 file extension is not added as a courtesy to the file if not fully qualifed on the input.

### Steps to reproduce

1. Open an audio project
2. Export a .mp3 file but do not add .mp3 as a suffix

### Expected behavior

it should add the appropriate file extension as a courtesy as it had in the previous versions 

### Actual behavior

The file extension will be blank and it should be appropriate for the type

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

I installed v3.4.0 as an upgrade from the previous version.  Do I need a full reinstall instead?

**Comment by LWinterberg** [comment] 2023-11-06 10:17
Duplicate of https://github.com/audacity/audacity/issues/5007

**Closed by LWinterberg** 2023-11-06 10:17 UTC
Labels: bug
