### ISSUE TITLE
Audacity does not respond to changes in USB configurations

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#2570] opened 2022-02-18 14:15 UTC
related: #2409

We seem to be having more and more reports on the forum of problems due to intermittent connections to recording and playback devices.  @SteveDaulton replied recently to one user here: https://forum.audacityteam.org/viewtopic.php?f=46&t=123833&start=20#p446407

"For an intermittent fault as you describe, the problem is very likely to be due to a lost USB connection.

Note that the connection only needs to be down for a fraction of a second to cause Audacity to loose the device. The computer will try to reconnect the device if the USB connection becomes available again, but even if successfully reconnected, the device will be allocated a different id by Windows, so Audacity will not be able to recognize it as the same device.

Common causes for lost USB connections:
1. Faulty USB cable (common)
2. Faulty USB connector (either end - fairly common)
3. USB hubs (don't use them for real time audio or video - usually OK for printers, keyboards, mice, other hardware that is not time critical)
4. High CPU usage causing USB to be temporarily suspended (unlikely unless other apps are putting high demand on the CPU)

To avoid having to restart the computer, check the USB lead and connectors, then "Transport menu > Rescan Audio Devices". This allows Audacity to look again for connected (and re-connected) audio devices."

Other programs can dynamically detect and adjust for a change in USB configuration.  Audacity should be doing this as well.

**Comment by petersampsonaudacity** [comment] 2022-02-18 17:50
See:  Proposal Auto Detect Audio Device Changes #2409 #2517

**Comment by Paul-Licameli** [comment] 2022-02-24 14:22
https://github.com/audacity/audacity/pull/2457

**Comment by LWinterberg** [comment] 2022-11-28 13:32
duplicate of #2409

**Closed by LWinterberg** 2022-11-28 13:32 UTC
Labels: Enhancement Request, medium feature
