### ISSUE TITLE
[3.3.3/ARM Mac on 14.0 preview] Audacity crashes upon startup, 0x1

### ISSUE THREAD

**Issue by jadenquinn** [audacity/audacity#4977] opened 2023-07-31 19:58 UTC
### Bug description

This started happening when I updated to one of the MacOS Sonoma 14.0 preview builds, I knew stuff like this would happen, and I'm doing my part to make sure it gets a jump on.
What happens is that I try to start Audacity up, but it crashes when it gets to the main window.
Reinstalling/redownloading Audacity does not fix this issue.

### Steps to reproduce

1. Get ARM Mac
2. Sign up for dev preview of MacOS 14.0
3. Get Audacity
4. Get mad and submit this bug report XD

### Expected behavior

When I download Audacity, I expect the application to work as expected.

### Actual behavior

Audacity crashes when it gets to the main window. The "boot" or "splash" sequence goes by as expected, but when the main window pops up, it almost instantly goes away, and a crash report of sorts is left in its place.
Crash report: 

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

### Additional context

This is a Mac mini (M2 Pro, 2023) on MacOS Sonoma 14.0, which.. is "Version 14.0 Beta (23A5301g)", according to About This Sackintosh.

Ok so this is kinda awkward, I literally just tested if it still crashes when I reinstall/redownload it right before I started submitting this bug report, but upon trying to start it up one more time (because I forgot the actual crash report text and had by then copied something else to my clipboard so I had to make it crash again so I could get the bug report text and copy it once more) it somehow works now??! This doesn't make any sense. If the crash happens again at some point, I will put said report here, but for now... it looks like it works now for some reason.

**Comment by LWinterberg** [comment] 2023-08-01 07:00
Duplicate of #4836

**Closed by LWinterberg** 2023-08-01 07:00 UTC
Labels: bug
