### ISSUE TITLE
Export menu enhancement idea

### ISSUE THREAD

**Issue by SpeedyCharly** [audacity/audacity#5672] opened 2023-11-24 09:08 UTC
### Your idea

Currently the export widget reverts to last folder used as default which is fine for some users, but it would be nice to have the option to set default output to ‘Original folder’ with option to either overwrite original or rename the exported file (by adding incremental #, for example). The current system seems overly cumbersome to me… Such a change would also be a time saving godsend when doing large batch jobs!

### Problem to be solved

Inadvertent saving to 'last folder' and avoiding having to copy/paste to proper folder afterwards while files may be intermixed with others and hard to identify quickly

[This to be done in step with other proposed changes to batch job Export widget in Macro Manager]

**Comment by LWinterberg** [comment] 2023-12-01 08:59
Duplicate of #762

**Closed by LWinterberg** 2023-12-01 08:59 UTC
Labels: Enhancement Request, import-export

**Comment by SpeedyCharly** [comment] 2023-12-01 12:57
@LWinterberg 
Out of scope!  How so?  'Tis a feature available in most competing apps which eases the pain, especially on large batch jobs...
