### ISSUE TITLE
Audacity randomly speeding up tracks after update

### ISSUE THREAD

**Issue by AnikiTakaZ** [audacity/audacity#6849] opened 2024-07-10 17:04 UTC
### Bug description

Since an update few months ago, Audacity when opening some AUP3 projects increases the speed of certain tracks, thus creating a sort of pitch

### Steps to reproduce

1. Creating a project
2. Recording my tracks
3. Saving my project
4. Closing it
5. Opening my project weeks after
6. Recording new tracks and listening previous ones

### Expected behavior

Not getting fucked up tracks that are speeded up for no reason

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by Glevion** [comment] 2024-07-13 15:10
It has happened to me two times already and screwed up two projects. Absolutely annoying.

**Comment by AnikiTakaZ** [comment] 2024-07-14 22:23
Do you found any fix ?

**Comment by dozzzzer** [comment] 2024-07-16 13:30
The issue is supposed to be fixed by https://github.com/audacity/audacity/pull/6880; the fix will be released in 3.6.0.

**Closed** 2024-07-16 15:33 UTC
Labels: bug

**Comment by AnikiTakaZ** [comment] 2024-07-19 13:32
Thank you guys !
