### ISSUE TITLE
Clip Renaming

### ISSUE THREAD

**Issue by kibbenkat** [audacity/audacity#4308] opened 2023-02-13 18:44 UTC
### Bug description

You cannot rename clips because the methods to do it do not work and nothing happens.

### Steps to reproduce

1. Generate audio

2. Double-click the clip name
Alt 2. Select track and press Ctrl+F2
Alt 2. Right click track and select “Rename clip...” 

### Expected behavior

Name of clip is selected and can be edited and changed.

### Actual behavior

Nothing happens.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Backspace deletes the clip as if you never selected Rename clip.

**Comment by LWinterberg** [comment] 2023-02-13 19:08
This should be fixed in the current master - https://audacityteam.org/nightly

Closing as Duplicate of #3704

**Closed by LWinterberg** 2023-02-13 19:08 UTC
Labels: bug

**Comment by kibbenkat** [comment] 2023-02-23 05:35
> This should be fixed in the current master - https://audacityteam.org/nightly
> 
> Closing as Duplicate of #3704

Tthat's a lot of artifacts. How do I know which one is the current master and correct operating system?

**Comment by kibbenkat** [comment] 2023-02-23 05:37
> This should be fixed in the current master - https://audacityteam.org/nightly
> 
> Closing as Duplicate of #3704

Is there an installer for this?
