### ISSUE TITLE
Mix and Render handles Track Gain / Pan incorrectly

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3508] opened 2022-09-01 16:33 UTC
### Bug description

A rendered track should sound the same as the track before rendering (it doesn't).

### Steps to reproduce

1. Generate a tone, amplitude 1.0 (0 dB)
2. Adjust the Track Gain to -6 dB
3. Play, and observe that the peak playback level is -6  dB.
4. Mix and Render
5. Play

### Expected behavior

The peak playback level to be -6 dB.

### Actual behavior

The peak playback level is -12 dB.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

The Track Pan / Gain settings are copied to the new track, even though they have already been applied.

**Comment by LWinterberg** [comment] 2022-09-01 18:27
duplicate of #2386

**Comment by SteveDaulton** [comment] 2022-09-01 19:30
> duplicate of #2386

Looks like a different issue to me.

**Comment by Paul-Licameli** [comment] 2022-09-02 00:02
Regression since 3.1.3

**Comment by Paul-Licameli** [comment] 2022-09-02 00:16
> > duplicate of #2386
> 
> Looks like a different issue to me.

Agree with @SteveDaulton , not the same buig

**Comment by Paul-Licameli** [comment] 2022-09-02 00:18
Observe the wavefor is right, the slider is wrong, but 3.1.3 makes the slider right

**Comment by Paul-Licameli** [comment] 2022-09-05 23:20
Didn't #3515 fix this?

**Comment by LWinterberg** [comment] 2022-09-06 08:14
looks fixed to me

**Closed by LWinterberg** 2022-09-06 08:14 UTC
Labels: bug, regression
