### ISSUE TITLE
Ability for Audacity to import and show video to facilitate dubbing the audio track

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2167] opened 2021-11-19 14:09 UTC
**Is your feature request related to a problem? Please describe.**
There is no ability with Audacity to import and show videos, this would be useful to be able to dub them. 

**Describe the solution you'd like**
Functionality in Audacity to import and show videos to facilitate dubbing the audio track

**Describe alternatives you've considered**
None

**Additional context**
This post is "nudged" by this recent post on the Forum:
https://forum.audacityteam.org/viewtopic.php?f=20&t=121667&p=439781

But I note that it is a long-standing Feature Request in the Audacity Wiki (one of the most popular with 47 votes).
_**Update:** now 49 votes - added a Forum user's plus mine_
https://wiki.audacityteam.org/wiki/Feature_Requests#newformats
Where it states:
>**Import/play video for synchronized soundtrack editing** (47 votes 09Dec18) 
>No need for Audacity to edit the video. Alternatively, Audacity could send/receive 
>SMPTE or MTC timecode data e.g. to VLC or mplayer.

**Comment by SteveDaulton** [comment] 2021-11-19 14:24
**Describe alternatives you've considered**

For Linux users, "Jack Transport" support would allow the use of XJadeo (http://xjadeo.sourceforge.net/main.html)
Jack Transport would also allow many other benefits for synchronizing with other apps.

**Comment by Penikov** [comment] 2021-11-22 10:28
@petersampsonaudacity Hmm! Nice Idea! I think we can ask @Tantacrul for that feature in future releases.

**Comment by Tantacrul** [comment] 2021-11-22 13:21
I definitely think this is a BIG win for Audacity. We've already done some preliminary design work on it. I don't quite know where it will fit in our backlog though. But certainly on our radar, for sure.

**Comment by petersampsonaudacity** [comment] 2021-11-22 13:30
> I definitely think this is a BIG win for Audacity. We've already done some preliminary design work on it.

Excellent  👍

**Comment by LWinterberg** [comment] 2022-09-30 11:04
duplicate of https://github.com/audacity/audacity/issues/1023

**Closed by LWinterberg** 2022-09-30 11:04 UTC
Labels: Enhancement Request, major feature
