### ISSUE TITLE
Timeline Quick-Play stops at end of selection

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2181] opened 2021-11-23 20:09 UTC
**Describe the bug**
Clicking on the Timeline should start playback at the clicked time position and continue to the end of the project unless interrupted by the user. This does not happen when there is a selection - playback stops at the end of the selection.
However, if the cursor position is after the clicked position but without a selected region, then playback continues past the cursor position.

**To Reproduce**
1. Open a project with some audio
2. Make a short audio selection somewhere near the middle
3. Click on the Timeline a short distance before the start of the selection
4. Observe that playback stops unexpectedly at the end of the audio selection.

**Expected behavior**
Clicking on the Timeline should start playback at the clicked time position and continue to the end of the project unless interrupted by the user. 

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version Audacity 3.1.3 alpha AppImage

**Additional context**
This is something like the 20th bug created while "improving" Timeline Quick Play. I find it quite disheartening to see my work repeatedly butchered.

**Comment by petersampsonaudacity** [comment] 2021-11-25 13:22
This is a regression on 3.0.5 and earlier Audacity versions

Confirmed on W10 with 3.1.2 and 3.1.3 Beta-1

**Comment by petersampsonaudacity** [comment] 2022-03-24 14:24
Testing on W10 with latest 3.2.0 alpha master audacity-win-3.2.0-alpha-20220323+6c64dc4-x64-msvc2022

This no longer appears to be  the case.

@LWinterberg @Penikov  - I suspect this can be closed

**Comment by LWinterberg** [comment] 2022-04-06 10:36
I can still reproduce it in both 3.1.3 and the latest master on windows 11

**Comment by petersampsonaudacity** [comment] 2022-04-06 13:20
> I can still reproduce it in both 3.1.3 and the latest master on windows 11

@LWinterberg  Leo, oddly I now cannot repeat what I found earlier (two weeks ago) and this now fails for me with 3.1.3 and the latest 3.2.0 alpha master  audacity-win-3.2.0-alpha-20220405+793cd28-x64-msvc2022

**Comment by SteveDaulton** [comment] 2022-04-06 13:34
> I can still reproduce it in both 3.1.3 and the latest master on windows 11
Same here on Linux.

**Comment by tboat** [comment] 2024-01-13 03:13
Hi team, does anyone have an idea when this is scheduled to be fixed? Still experiencing it on 3.4.2 and Windows 11. 

The ability to be able to rapidly compare/listen to the audio of the selection I'm editing with the audio around it is so useful. Personally haven't been able to upgrade for sometime now because of this bug. 

Thanks

**Comment by petersampsonaudacity** [comment] 2024-01-14 12:01
@lw

Like @tboat I got caught out by this on Friday when I was using 3.4.2 for production use.

Testing on W10 shows that this regression issue reamains present in the latest 3.0.5 alpha test build.

**Comment by kryksyh** [comment] 2024-09-22 13:54
@SteveDaulton @petersampsonaudacity I'm looking into this issue and got slightly confused what the correct behavior should be. 

- If there is nothing selected then
  - Clicking on the Timeline starts the playback from the click position till the end
  - Pressing Play button starts the playback from the playback cursor till the end
- If there is a portion of the track selected then
  - Clicking on the Timeline starts the playback from the click position till the end of the selection
  - Pressing Play button starts the playback from the beginning of the selection till the end of the selection

Is my understanding of this issue correct that we should distinguish playback started with the Play button (or hotkey/menu) from the playback started with a click on the Timeline?

**Comment by kryksyh** [comment] 2024-09-22 14:00
@dozzzzer I have another related issue with looping, not sure if there is an issue for it already created.

If you have looping brackets visible, then you can drag one onto the other and they become invisible, but still present. Now instead of looping inside the selected area, the playback loops from the beginning till the location of the invisible looping brackets.

**Comment by petersampsonaudacity** [comment] 2024-09-22 15:25
@kryksyh 

For Audacity 3.0.5 and earlier:  Clicking on the Timeline starts the playback from the click position till the end of the project, regardless of whether or not there is a portion of the track selected.

This is precisely the regression that is logged as this bug.

What happens now if you have a portion of the track selected varies:
1. if the click position in the Timeline is before the selection then Audacity plays up to the selection and to the end of the selection
2. If the click position is within the rage of the selection, then Audacity plays from that position to the end of the selection
3. If the click position in the Timeline is after the selection, then Audacity plays from that position to the end of the project.

**Comment by Kurtsley** [comment] 2024-09-22 15:50
I will add that the quickplay works as expected if a loop exists at an earlier point on the timeline. Audacity will play past the end of the selection to the end of the project.

**Comment by LWinterberg** [comment] 2024-10-15 10:57
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.

**Closed by LWinterberg** 2024-10-15 10:57 UTC
Labels: AU3-bug, P3, Design / UX, regression
