### ISSUE TITLE
Macro operation crashes 

### ISSUE THREAD

**Issue by antonzuykov** [audacity/audacity#5189] opened 2023-09-12 06:37 UTC
### Bug description

I have a bunch of 500-700MB m4a files that need some recompressing, so I created a macro to normalize an audio file, and export it to an mp3 file (joined stereo, 48kbps constant).

When using that script on files, it seem to process just one file, saving it before crashing Audacity.
I tried it on smaller files of the same format and the result was the same.
So, it does work when processing it one by one, but I wondering why was it crashing for a set of files.

### Steps to reproduce

1. Create a macro
2. get several m4a files
3. attempt to apply the script to m4a files.
4. Observe the app crashing after the first converted file is saved.

### Expected behavior

Process a bunch of files in a batch fashion, and do it successfully without crashing after each file is saved. 

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by dozzzzer** [comment] 2023-09-12 09:05
Duplicate of #4444

**Closed** 2023-09-12 09:05 UTC
Labels: bug
