### ISSUE TITLE
Most (nearly all) effects overwrite right channel data with left channel data

### ISSUE THREAD

**Issue by deus-e-x** [audacity/audacity#5055] opened 2023-08-18 17:30 UTC
### Bug description

Applying most (nearly all) effects to a stereo track copies the normalized left track data to the right channel, overwriting the entire original right channel data.

Repeat appears to be the sole exception.

Oddly this does **_NOT_** seem to affect **_some_** external plug-in effects - see further on in this thread ...

### Steps to reproduce

1. Import any stereo audio track
2. Navigate to the Effect menu and access the entry Normalize...
3. The entire stereo audio data gets autoselected
3. Apply an effect on the selected stereo audio data

### Expected behavior
The left and right channel audio data should be acted according to the selected parameters of the effect dialog.

### Actual behavior

Upon executing the effect, the left channel data is copied to the right channel, overwriting the entire original right channel data.

_**Audacity-win-3.3.3-x64, correct normalize-effect behavior:**_

![1](https://github.com/audacity/audacity/assets/45689656/053cdbc2-579c-42de-bbdf-f90826abedf0)

_**Audacity v3.4.0 alpha 20230817+b2626a1-x64, incorrect normalize-effect behavior:**_

![2](https://github.com/audacity/audacity/assets/45689656/e9ac3878-fc54-4a49-8405-d22045c3d428)

**_Normalize effect dialog settings, used for both versions above:_**

![3](https://github.com/audacity/audacity/assets/45689656/3cd361fa-169a-412f-9a90-e9cd0e5b1799)

### Audacity Version
3.4.0 alpha test build

### Operating system
Windows - but assume all OS

### Additional context
The **Tracks > Mix**   commands do **_NOT_** seem to be similarly affected, they work OK

**Comment by petersampsonaudacity** [comment] 2023-08-19 09:35
Testing on W10 with 3.3.3 I cannot reproduce this,

But with latest 3.4.0 alpha test build:  audacity-win-3.4.0-alpha-20230817+b2626a1-x64-msvc2022
This is readily reproducible.

I suspect that this may have something to do with the re-working of stereo tracks that @Paul-Licameli  is currently undertaking.

For my test track I created a track with a 30 second chirp in the left channel and a 30m second DTMF in the right channel so the results can be clearly see.  I tested with:
a) the setting for **Normalize stereo channels independently** set to **off** _(default setting)_
a) the setting for **Normalize stereo channels independently** set to **on**
Both worked correctly and 3.3.3 and failed with 3.4.0 alpha

The Amplify effect also suffers from the same affliction with 3.4.0 alpha

**Comment by petersampsonaudacity** [comment] 2023-08-19 09:45
Further testing shows that this afflicts most (nearly all) effects - the only exception appears to be **Repeat**

Reverse gives an interesting result where the left chanel has the chirp reversed and the right channel has its DTMF overwritten with an un-reversed chirp:
![image](https://github.com/audacity/audacity/assets/50205984/ed36f7d2-84de-4f9f-9b80-bff73d1cd632)

This has to be a M**UST-FIX** for 3.4.0 so I shall assign it a **P1** priority rating

**Comment by petersampsonaudacity** [comment] 2023-08-19 09:52
Excellent catch @deus-e-x  - many thanks for the report   :-)

**Comment by petersampsonaudacity** [comment] 2023-08-19 09:59
Further testing shows that applying Vocal Reduction and Isolation to my test project causes Audacity to crash.

I will log this as a separate issue.

**Comment by petersampsonaudacity** [comment] 2023-08-19 10:27
Oddly this does **_NOT_** seem to affect external plug-in effects

I tested with
1. iZotope Vinyl
2. the rea effect set

**Comment by deus-e-x** [comment] 2023-08-19 12:26
> Testing on W10 with 3.3.3 I cannot reproduce this,

Just for clarification, in my bug report above, I wanted to express that the master from 2023-08-17 is affected by the bug, while the latest stable release v3.3.3 and earlier not.

The issue must have crept in after the nightly release from 08. August 2023, which isn't affected by this bug, the next nightly I tried was released on August 17th 2023 which has the reported bug.  :)

**Comment by deus-e-x** [comment] 2023-08-19 12:29
@petersampsonaudacity

Thank you for your continuous support and for digging deeper into this issue. Great job!

**Comment by petersampsonaudacity** [comment] 2023-08-19 15:40
Looking at my earlier test above I noted the the errant right channel appeared to be Normalized Amplified more than the left channel so I tried again with Amplify  (default setting) and with show clipping turned on:

### Before Amplify
![Spectral test project](https://github.com/audacity/audacity/assets/50205984/e45d2484-f861-4e22-ad85-136d24a28a3b)

### After Amplify
![image](https://github.com/audacity/audacity/assets/50205984/afd25503-7306-4b10-a492-10cdfc6a91a4)

**Comment by Paul-Licameli** [comment] 2023-08-20 13:34
Bisected to 1698b5010e24f673eaa4bf1319e4f9f3c6b3cc01

**Comment by petersampsonaudacity** [comment] 2023-08-21 10:31
Testing on W10 with @Paul-Licameli 's latest branch build:  audacity-win-3.4.0-alpha-20230820+9d21d5c-x64

This does  appears to fix this issue  - in Paul's branch build

I have only tested with a small handful of effects

**Comment by petersampsonaudacity** [comment] 2023-08-21 10:44
I also tested the unequal amplification of the right channel and this also now appears to be fixed.

Tested with Amplify and Normalize - with Normalize tested on independent and non-independent channels - using a 30-second generated tone.

**Comment by deus-e-x** [comment] 2023-08-21 14:23
@Paul-Licameli 
@petersampsonaudacity 

Thank you for fixing the issues. Great job everybody!! 👍

**Comment by dozzzzer** [comment] 2023-08-22 10:21
Tested

**Closed** 2023-08-22 10:31 UTC
Labels: bug, P1, regression, Effects
