### ISSUE TITLE
build: RPATH is still incorrect

### ISSUE THREAD

**Issue by mikhailnov** [audacity/audacity#2165] opened 2021-11-19 10:52 UTC
[00:01:22] Verifying ELF objects in /usr/src/tmp/audacity-buildroot (arch=normal,fhs=normal,lfs=relaxed,lint=relaxed,rpath=normal,stack=normal,textrel=normal,unresolved=normal)
[00:01:22] verify-elf: WARNING: ./usr/lib64/audacity/modules/mod-script-pipe.so: RPATH contains several entries: /usr/src/RPM/BUILD/audacity-src-3.1.2/x86_64-alt-linux/bin/Debug/lib64/audacity:/usr/src/RPM/BUILD/audacity-src-3.1.2/x86_64-alt-linux/shared/Debug
[00:01:22] verify-elf: ERROR: ./usr/lib64/audacity/modules/mod-script-pipe.so: RPATH contains illegal absolute entry "/usr/src/RPM/BUILD/audacity-src-3.1.2/x86_64-alt-linux/bin/Debug/lib64/audacity": /usr/src/RPM/BUILD/audacity-src-3.1.2/x86_64-alt-linux/bin/Debug/lib64/audacity:/usr/src/RPM/BUILD/audacity-src-3.1.2/x86_64-alt-linux/shared/Debug
<...>
3.1.2/x86_64-alt-linux/shared/Debug
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: not found: lib-screen-geometry.so
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: not found: lib-project-rate.so
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: not found: lib-ffmpeg-support.so
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: not found: lib-theme.so
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: not found: lib-audio-devices.so
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: not found: lib-project.so
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: not found: lib-registries.so
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: not found: lib-xml.so
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: not found: lib-string-utils.so
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: not found: lib-math.so
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: not found: lib-files.so
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: not found: lib-exceptions.so
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: not found: lib-preferences.so
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: not found: lib-utility.so
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: not found: lib-components.so
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: not found: lib-basic-ui.so
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: not found: lib-strings.so
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: undefined symbol: _ZTIN8Registry8BaseItemE
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: undefined symbol: _ZTI15ModuleInterface
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: undefined symbol: _ZTIN10ClientData4BaseE
[00:01:23] verify-elf: ERROR: ./usr/bin/audacity: undefined symbol: _ZTI13PrefsListener
<...>

https://github.com/audacity/audacity/pull/1030#issuecomment-873630620
Still an issue in v3.1.2

I have to do in %install section of the spec:
```bash
patchelf --set-rpath '$ORIGIN/../%_lib/audacity' %buildroot%_bindir/audacity
find %buildroot%_libdir/audacity -name '*.so' -print | while read -r line
do
	patchelf --set-rpath '$ORIGIN' "$line"
done
```

May be Audacity built from Fedora 34 spec also has an incorrect RPATH and does not work at all??

**Comment by crsib** [comment] 2021-11-19 11:02
This is probably a regression, I will check. It surely worked from https://github.com/audacity/audacity/blob/master/linux/packages/fedora34/audacity.spec

**Comment by mikhailnov** [comment] 2021-11-19 11:17
It should not be a problem to make some basic tests, I have a project https://github.com/mikhailnov/bbb-load-tester where bbb-load-tester.sh runs a headless X server (Xfvb), a window manager inside it, makes required actions using xdotool, takes screenshots, finds places where to click using opencv (find-center.py). A similar approach can be used in Audacity. I can try to implement it.

**Comment by crsib** [comment] 2021-11-19 12:27
Reran the build for `release-3.1.2` branch - generated RPM works just fine

```
dd: ./audacity: No such file or directory
[dvedenko@fedora ~]$ ldd /usr/bin/au
audacity     audit2why    aulastlog    authselect   
audit2allow  aulast       ausyscall    auvirt       
[dvedenko@fedora ~]$ ldd /usr/bin/audacity 
	linux-vdso.so.1 (0x00007ffef8758000)
	lib-screen-geometry.so => /usr/bin/../lib64/audacity/lib-screen-geometry.so (0x00007f75901f9000)
	lib-project-rate.so => /usr/bin/../lib64/audacity/lib-project-rate.so (0x00007f75901ec000)
	lib-ffmpeg-support.so => /usr/bin/../lib64/audacity/lib-ffmpeg-support.so (0x00007f75901b1000)
	lib-theme.so => /usr/bin/../lib64/audacity/lib-theme.so (0x00007f759012e000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f7590116000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f75900f5000)
	lib-audio-devices.so => /usr/bin/../lib64/audacity/lib-audio-devices.so (0x00007f75900ce000)
	libasound.so.2 => /lib64/libasound.so.2 (0x00007f758ffc1000)
	lib-project.so => /usr/bin/../lib64/audacity/lib-project.so (0x00007f758ffb2000)
	lib-registries.so => /usr/bin/../lib64/audacity/lib-registries.so (0x00007f758ff9a000)
	lib-xml.so => /usr/bin/../lib64/audacity/lib-xml.so (0x00007f758ff7a000)
	lib-string-utils.so => /usr/bin/../lib64/audacity/lib-string-utils.so (0x00007f758ff6f000)
	lib-math.so => /usr/bin/../lib64/audacity/lib-math.so (0x00007f758ff56000)
	lib-files.so => /usr/bin/../lib64/audacity/lib-files.so (0x00007f758ff32000)
	lib-exceptions.so => /usr/bin/../lib64/audacity/lib-exceptions.so (0x00007f758ff27000)
	lib-preferences.so => /usr/bin/../lib64/audacity/lib-preferences.so (0x00007f758ff13000)
	lib-utility.so => /usr/bin/../lib64/audacity/lib-utility.so (0x00007f758ff0d000)
	lib-components.so => /usr/bin/../lib64/audacity/lib-components.so (0x00007f758ff01000)
	lib-basic-ui.so => /usr/bin/../lib64/audacity/lib-basic-ui.so (0x00007f758fef9000)
	lib-strings.so => /usr/bin/../lib64/audacity/lib-strings.so (0x00007f758fee0000)
	libwx_baseu-3.1.so.4 => /lib64/libwx_baseu-3.1.so.4 (0x00007f758fc9f000)
	libwx_gtk3u_core-3.1.so.4 => /lib64/libwx_gtk3u_core-3.1.so.4 (0x00007f758f494000)
	libwx_gtk3u_html-3.1.so.4 => /lib64/libwx_gtk3u_html-3.1.so.4 (0x00007f758f3b9000)
	libwx_gtk3u_qa-3.1.so.4 => /lib64/libwx_gtk3u_qa-3.1.so.4 (0x00007f758f38d000)
	libwx_baseu_net-3.1.so.4 => /lib64/libwx_baseu_net-3.1.so.4 (0x00007f758f347000)
	libsqlite3.so.0 => /lib64/libsqlite3.so.0 (0x00007f758f20f000)
	libid3tag.so.0 => /lib64/libid3tag.so.0 (0x00007f758f1f1000)
	libFLAC.so.8 => /lib64/libFLAC.so.8 (0x00007f758f196000)
	libFLAC++.so.6 => /lib64/libFLAC++.so.6 (0x00007f758f179000)
	libmad.so.0 => /lib64/libmad.so.0 (0x00007f758f156000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f758f010000)
	libvorbisfile.so.3 => /lib64/libvorbisfile.so.3 (0x00007f758f005000)
	libvorbis.so.0 => /lib64/libvorbis.so.0 (0x00007f758efd6000)
	libvorbisenc.so.2 => /lib64/libvorbisenc.so.2 (0x00007f758ef2b000)
	libogg.so.0 => /lib64/libogg.so.0 (0x00007f758ef20000)
	libtwolame.so.0 => /lib64/libtwolame.so.0 (0x00007f758eef9000)
	liblilv-0.so.0 => /lib64/liblilv-0.so.0 (0x00007f758eed9000)
	libsuil-0.so.0 => /lib64/libsuil-0.so.0 (0x00007f758eed3000)
	libportmidi.so.0 => /lib64/libportmidi.so.0 (0x00007f758eec7000)
	libsndfile.so.1 => /lib64/libsndfile.so.1 (0x00007f758ee50000)
	libportaudio.so.2 => /lib64/libportaudio.so.2 (0x00007f758ee1f000)
	libSoundTouch.so.2 => /lib64/libSoundTouch.so.2 (0x00007f758ee08000)
	libvamp-hostsdk.so.3 => /lib64/libvamp-hostsdk.so.3 (0x00007f758edca000)
	libgtk-3.so.0 => /lib64/libgtk-3.so.0 (0x00007f758e61a000)
	libgdk-3.so.0 => /lib64/libgdk-3.so.0 (0x00007f758e515000)
	libgdk_pixbuf-2.0.so.0 => /lib64/libgdk_pixbuf-2.0.so.0 (0x00007f758e4e5000)
	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007f758e48a000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f758e350000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f758e12f000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f758e114000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f758df45000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7591263000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f758df3a000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f758df07000)
	libsoxr.so.0 => /lib64/libsoxr.so.0 (0x00007f758dea8000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f758de8e000)
	libsecret-1.so.0 => /lib64/libsecret-1.so.0 (0x00007f758de41000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f758de15000)
	libpangocairo-1.0.so.0 => /lib64/libpangocairo-1.0.so.0 (0x00007f758de01000)
	libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00007f758ddad000)
	libcairo.so.2 => /lib64/libcairo.so.2 (0x00007f758dc91000)
	libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x00007f758dabd000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f758d976000)
	libSM.so.6 => /lib64/libSM.so.6 (0x00007f758d96b000)
	libXtst.so.6 => /lib64/libXtst.so.6 (0x00007f758d960000)
	libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00007f758d946000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f758d8f8000)
	libSDL2-2.0.so.0 => /lib64/libSDL2-2.0.so.0 (0x00007f758d776000)
	libpng16.so.16 => /lib64/libpng16.so.16 (0x00007f758d73d000)
	libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00007f758d6c4000)
	libtiff.so.5 => /lib64/libtiff.so.5 (0x00007f758d63c000)
	libmspack.so.0 => /lib64/libmspack.so.0 (0x00007f758d627000)
	libwx_baseu_xml-3.1.so.4 => /lib64/libwx_baseu_xml-3.1.so.4 (0x00007f758d611000)
	libserd-0.so.0 => /lib64/libserd-0.so.0 (0x00007f758d5f8000)
	libsord-0.so.0 => /lib64/libsord-0.so.0 (0x00007f758d5ec000)
	libsratom-0.so.0 => /lib64/libsratom-0.so.0 (0x00007f758d5de000)
	libgsm.so.1 => /lib64/libgsm.so.1 (0x00007f758d5cf000)
	libopus.so.0 => /lib64/libopus.so.0 (0x00007f758d575000)
	libjack.so.0 => /lib64/libjack.so.0 (0x00007f758d520000)
	libcloudproviders.so.0 => /lib64/libcloudproviders.so.0 (0x00007f758d506000)
	libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007f758d4fe000)
	libXi.so.6 => /lib64/libXi.so.6 (0x00007f758d4ec000)
	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007f758d4e3000)
	libcairo-gobject.so.2 => /lib64/libcairo-gobject.so.2 (0x00007f758d4d7000)
	libatk-1.0.so.0 => /lib64/libatk-1.0.so.0 (0x00007f758d4ae000)
	libatk-bridge-2.0.so.0 => /lib64/libatk-bridge-2.0.so.0 (0x00007f758d475000)
	libwayland-client.so.0 => /lib64/libwayland-client.so.0 (0x00007f758d462000)
	libepoxy.so.0 => /lib64/libepoxy.so.0 (0x00007f758d32d000)
	libfribidi.so.0 => /lib64/libfribidi.so.0 (0x00007f758d30f000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007f758d23f000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f758d17b000)
	libXinerama.so.1 => /lib64/libXinerama.so.1 (0x00007f758d176000)
	libXrandr.so.2 => /lib64/libXrandr.so.2 (0x00007f758d167000)
	libXcursor.so.1 => /lib64/libXcursor.so.1 (0x00007f758d15a000)
	libXcomposite.so.1 => /lib64/libXcomposite.so.1 (0x00007f758d155000)
	libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00007f758d150000)
	libxkbcommon.so.0 => /lib64/libxkbcommon.so.0 (0x00007f758d107000)
	libwayland-cursor.so.0 => /lib64/libwayland-cursor.so.0 (0x00007f758d0fd000)
	libwayland-egl.so.1 => /lib64/libwayland-egl.so.1 (0x00007f758d0f6000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f758d0e1000)
	libffi.so.6 => /lib64/libffi.so.6 (0x00007f758d0d6000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f758d05e000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f758d018000)
	libgcrypt.so.20 => /lib64/libgcrypt.so.20 (0x00007f758cedb000)
	libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f758ceb5000)
	libthai.so.0 => /lib64/libthai.so.0 (0x00007f758ceaa000)
	libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00007f758cdfe000)
	libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00007f758cdf9000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f758cdce000)
	libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007f758cdbc000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f758cdaf000)
	libmount.so.1 => /lib64/libmount.so.1 (0x00007f758cd6c000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f758cd40000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f758cd26000)
	libICE.so.6 => /lib64/libICE.so.6 (0x00007f758cd08000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f758ccfd000)
	libxml2.so.2 => /lib64/libxml2.so.2 (0x00007f758cb74000)
	libwebp.so.7 => /lib64/libwebp.so.7 (0x00007f758cb06000)
	libzstd.so.1 => /lib64/libzstd.so.1 (0x00007f758ca10000)
	libjbig.so.2.1 => /lib64/libjbig.so.2.1 (0x00007f758ca02000)
	libdb-5.3.so => /lib64/libdb-5.3.so (0x00007f758c836000)
	libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007f758c7e4000)
	libatspi.so.0 => /lib64/libatspi.so.0 (0x00007f758c7a7000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007f758c786000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f758c773000)
	libbrotlidec.so.1 => /lib64/libbrotlidec.so.1 (0x00007f758c763000)
	libdatrie.so.1 => /lib64/libdatrie.so.1 (0x00007f758c75a000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f758c754000)
	libblkid.so.1 => /lib64/libblkid.so.1 (0x00007f758c71f000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007f758c688000)
	libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007f758c5c2000)
	libbrotlicommon.so.1 => /lib64/libbrotlicommon.so.1 (0x00007f758c59f000)
	liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f758c57b000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007f758c571000)
```

https://crsib-screenshots.s3.amazonaws.com/audacity-3.0~test-0.fc34.x86_64.rpm (please, ignore the versions...)

**Comment by LWinterberg** [comment] 2021-12-23 18:50
closing as this has been on could not reproduce for a while. Feel free to reopen if you have additional information regarding reproducability.

**Closed by LWinterberg** 2021-12-23 18:50 UTC
Labels: Could not reproduce, Build / CI
