### ISSUE TITLE
Plugin Manager: Unable to toggle state of multiple selected plug-ins

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#6419] opened 2024-05-11 15:02 UTC
### Bug description

When a user has a lot of plug-ins installed, it is very useful to be able to enable / disable multiple plug-ins at the same time. For example, the Guitarix package contains around 70 separate effects which are primarily designed for real-time "stomp box" emulation, and are not really useful for audiobook production. Having hundreds of unused effects in Audacity is an inconvenience, so it is very useful to be able to select all of the Guitarix plug-ins and disable them.

The newly implemented Pulgin Manager only allows one plug-in at a time to be enabled or disabled. This makes the task of managing a large number of plug-ins extremely tedious compared with the previous version.

### Steps to reproduce

1. Open the Plugin Manager
2. Select multiple plug-ins
3. Try to enable or disable them with one click

### Expected behavior

I would expect an "Enable" and a "Disable" option that can be applied to the selected plug-ins

### Actual behavior

There appears to be no way to enable / disable more than one plug-in at a time.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

A "regression" in the  sense that something that was previously easy and convenient is now extremely tedious and inconvenient,

**Comment by petersampsonaudacity** [comment] 2024-05-12 09:14
THere is an "Easter egg" involved here ...

1. Make your multple selection og EGATs (use shift and or ctrl modified select)
2. Do **_NOT_** click in any of the selected checkboxes
3. **INSTEAD:**  use the **space-bar** to toggle the selectedness

Note this appears to toggle based on the state of the last selected item (as you may have selection with mixed states, some on and some off).

The use of the space-bar is documented in the 3.5 manual:
https://manual.audacityteam.org/man/manage_effects_generators_and_analyzers.html

![image](https://github.com/audacity/audacity/assets/50205984/7d43aac8-60d5-41e4-9c50-8fcf0e4d354d)

_Note that I did not document the tricksy behavior of selecting EGATs in diffent states and the toggle based on last-selected._

**Comment by petersampsonaudacity** [comment] 2024-05-12 09:22
>Note that I did not document the tricksy behavior of selecting EGATs in diffent states and the toggle based on last-selected.

I just fixed this (and a typo) for the 3.6 alpha manual.

![image](https://github.com/audacity/audacity/assets/50205984/6192876e-d1d5-4d67-b5f1-2ecf83be6655)

**Comment by SteveDaulton** [comment] 2024-05-12 09:51
Functionality should not be hidden in Easter Eggs, so I don't think this is a "Could not reproduce" issue.

**Comment by petersampsonaudacity** [comment] 2024-05-12 13:08
> Functionality should not be hidden in Easter Eggs,

@LWinterberg @Tantacrul @dozzzzer 

I'm **_strongly_** minded to agree with @SteveDaulton 

1. given that changing the status of any individual EGAT is achieved by clicking in its checkbox it would be far better, more "_discoverable_" if in the case where multiple EGATs are selected then a click on the checkbox of any of them toggles the selected set of EGATs.
  
2. Furthermore rather than a toggle based on the "last selected" in the set it would surely be better to toggle each EGAT in the selected set based on its own current status.

_The fact that Steve (who is a very experienced Audacity user) did not "discover" the use of the spave bar indicates that many other users are likely to be similarly fooled._

**Comment by Tantacrul** [comment] 2024-05-12 13:20
Def agree we should allow for multi-selection for this purpose.

**Comment by dozzzzer** [comment] 2024-05-13 08:32
Duplicate of https://github.com/audacity/audacity/issues/6133

**Closed by dozzzzer** 2024-05-13 08:32 UTC
Labels: Enhancement Request, Design / UX, regression, PluginManager, feature tweak
