### ISSUE TITLE
Audacity 3.3.1 Appimage: findlib: libportaudio.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Moltkex** [audacity/audacity#4630] opened 2023-04-28 16:58 UTC
### Bug description

I downloaded audacity-linux-3.3.1-x64.Appimage, launched it from terminal, but didn't start and got this error:
```
./audacity-linux-3.3.1-x64
/lib/x86_64-linux-gnu/libatk-1.0.so.0
/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0
/lib/x86_64-linux-gnu/libcairo-gobject.so.2
/lib/x86_64-linux-gnu/libcairo.so.2
/lib/x86_64-linux-gnu/libgio-2.0.so.0
/lib/x86_64-linux-gnu/libglib-2.0.so.0
/lib/x86_64-linux-gnu/libgmodule-2.0.so.0
/lib/x86_64-linux-gnu/libgobject-2.0.so.0
/lib/x86_64-linux-gnu/libgthread-2.0.so.0
/lib/x86_64-linux-gnu/libjack.so.0
findlib: libportaudio.so: cannot open shared object file: No such file or directory
/home/moltke/Appimages/audacity-linux-3.3.1-x64: Using fallback for library 'libportaudio.so'
/tmp/.mount_audaciVTI2fx/bin/audacity: /tmp/.mount_audaciVTI2fx/lib/libselinux.so.1: no version information available (required by /lib/x86_64-linux-gnu/libgio-2.0.so.0)

(process:147738): Gdk-CRITICAL **: 11:39:02.186: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(process:147738): Gdk-CRITICAL **: 11:39:02.186: _gdk_pixmap_new: assertion '(drawable != NULL) || (depth != -1)' failed
../source_subfolder/src/gtk/bitmap.cpp(827): assert ""IsOk()"" failed in ConvertToImage(): invalid bitmap
../source_subfolder/src/common/image.cpp(2172): assert ""IsOk()"" failed in SetMaskColour(): invalid image
../source_subfolder/src/common/image.cpp(2223): assert ""IsOk()"" failed in SetMask(): invalid image
../source_subfolder/src/common/image.cpp(1853): assert ""IsOk()"" failed in GetWidth(): invalid image
../source_subfolder/src/common/image.cpp(1860): assert ""IsOk()"" failed in GetHeight(): invalid image
../source_subfolder/src/common/image.cpp(2112): assert ""IsOk()"" failed in GetAlpha(): invalid image
../source_subfolder/src/common/image.cpp(2232): assert ""IsOk()"" failed in HasMask(): invalid image
../source_subfolder/src/common/image.cpp(1986): assert ""IsOk()"" failed in GetData(): invalid image

(process:147738): GdkPixbuf-CRITICAL **: 11:39:02.190: gdk_pixbuf_new_from_data: assertion 'data != NULL' failed

(process:147738): Gdk-CRITICAL **: 11:39:02.190: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(process:147738): Gdk-CRITICAL **: 11:39:02.190: IA__gdk_drawable_get_display: assertion 'GDK_IS_DRAWABLE (drawable)' failed

(process:147738): Gdk-CRITICAL **: 11:39:02.190: IA__gdk_cursor_new_from_pixbuf: assertion 'GDK_IS_DISPLAY (display)' failed

(process:147738): GLib-GObject-CRITICAL **: 11:39:02.190: g_object_unref: assertion 'G_IS_OBJECT (object)' failed



```
I installed **libportaudio2** hoping it helped, but it didn't; audacity-linux-3.3.1-x64.Appimage doesn't start and keeps throwing the same error. 

### Steps to reproduce

1. Download audacity-linux-3.3.1-x64.Appimage.
2. Launch a terminal, type ./audacity-linux-3.3.1-x64.Appimage, hit **Enter** to try and start the app.
3. Check for error messages.

### Expected behavior

audacity-linux-3.3.1-x64.Appimage should start without issues.

### Actual behavior

audacity-linux-3.3.1-x64.Appimage doesn't start and throws an error. 

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Additional context

Operating System: KDE neon Testing Edition
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.9
Kernel Version: 5.19.0-41-generic (64-bit)
Graphics Platform: X11

**Comment by mrbumpy409** [comment] 2023-04-28 17:55
Those same errors are thrown by the 3.3.0 AppImage, except that version actually starts. So, I don't think the issue is related to the error messages. Looks like you and I posted our bug reports around the same time: https://github.com/audacity/audacity/issues/4629

**Comment by Moltkex** [comment] 2023-04-28 18:03
> Those same errors are thrown by the 3.3.0 AppImage, except that version actually starts. So, I don't think the issue is related to the error messages. Besides, the next line says that it will use a fallback for 'libportaudio.so' (I'm guessing a version internal to the AppImage). Looks like you and I posted our bug reports around the same time, heehee: #4629

Yes, 3.3.0 does starts, I didn't try that one from CLI tho, so I wasn't aware it throws the same errors, but just checked and indeed it does.

**Comment by glennpc** [comment] 2023-04-28 20:40
Still getting these errors with latest Windows 64-bit version:

13:37:47: Audacity 3.3.1
13:37:47: sqlite3 message: (1) no such table: project in "SELECT 1 FROM project LIMIT 1;"
13:37:47: Error: Failed to load shared library 'avformat-60.dll' (error 126: The specified module could not be found.)
13:37:47: Error: Failed to load shared library 'avformat-59.dll' (error 126: The specified module could not be found.)
13:37:47: Error: Failed to load shared library 'avformat-58.dll' (error 126: The specified module could not be found.)
13:37:47: Error: Failed to load shared library 'avformat-57.dll' (error 126: The specified module could not be found.)
13:37:47: FFmpeg libraries loaded successfully from: C:\Program Files\Audacity\FFmpeg\avformat-55.dll

**Comment by LWinterberg** [comment] 2023-04-29 10:28
Duplicate of #4629

**Closed by LWinterberg** 2023-04-29 10:28 UTC
Labels: bug, Linux
