### ISSUE TITLE
Not Responding after copy/paste to new Window

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#3790] opened 2022-10-08 22:31 UTC
Windows 10.  Regression from 3.1.3.

In Audacity 3.2.1:

1) File Open > Junk1.WAV 2-hour MONO WAV file.
2) Select 10-60 seconds of audio beginning around 20 minute mark then Edit > Copy
3) File > New
4) Edit > Paste
5) Click Audacity Title Bar
6) Observe Audacity Title Bar (eventually) changes to Not Responding for several minutes before Paste is complete.

The same actions in 3.1.3 result in an immediate paste at step 4.

This difficulty was initially reported by forum user Kisai here: https://forum.audacityteam.org/viewtopic.php?p=456933#p456933

**Comment by petersampsonaudacity** [comment] 2022-10-09 09:11
Testing on W10 I confirm this regression
a) fails on 3.2.1
b) fails on latest 3.2 alpha - audacity-win-3.2.2-beta-20221006+df0ffd2-x64-msvc2022

**Comment by Ryan-Miller-Audacity** [comment] 2022-10-13 12:55
I have been unable to reproduce this on my machine at all using Audacity 3.2.1. I've followed the steps both from above and directly from the video attached to the forum post and each time my paste goes through as expected and I am able to continue working in that new window without any issue. 

I'm not sure if I'm missing something, but from my machine at least I cannot reproduce this. Perhaps @dozzzzer or @LWinterberg can take a look and see if they can. I will go ahead and assign this further labels and such, but I personally have not been able to reproduce at all.

**Comment by petersampsonaudacity** [comment] 2022-10-13 13:55
I can replicate this on 3.1.2 if I

1. Generate a 2 hour mono chirp
2. select 60 seconds from 20-21 mins
3. Ctrl+C to copy
4. Ctrl+N for new project
5. Crl+V to paste in new project
6. Observe: long period with Audacity reporting "not responding" - eventually the paste is made

If I uses a short 30 second chirp and cut 210 seconds to paste in the new project, then the paste takes place immediately.

**Comment by Ryan-Miller-Audacity** [comment] 2022-10-14 13:28
@dozzzzer Can you take a look at this and see if you can reproduce?

**Comment by DeeFeeCee** [comment] 2022-12-11 20:41
Reproduced by copying/cutting clips from a ~25 minute track. Audacity 3.2.2

**Comment by LWinterberg** [comment] 2022-12-30 15:50
closing in favor of #3820 which has a PR already

**Closed by LWinterberg** 2022-12-30 15:50 UTC
Labels: bug, P2, crash / freeze, regression
