### ISSUE TITLE
3.1.3 Windows, locale number format not respected in UI

### ISSUE THREAD

**Issue by Liggliluff** [audacity/audacity#2518] opened 2022-02-06 18:06 UTC
**Describe the bug**
The number format in Audacity is based on the translation, and not the system settings. By default, number formats should be based on the system. I use English (Sweden) for proper ISO 80000-1 support, but setting Audacity to English gives me an improper number format, since it's based on British/American usage.

**To Reproduce**
1. Set Windows number format to a language such as German, Swedish, or English (Sweden)
2. Start up Audacity and set the display language to English
3. The number formats at the bottom of the screen (by default) shows up as "000,000,000 samples" and "00h00m00.000s" (hh:mm:ss+milliseconds)

**Expected behavior**
Software in Windows should be using the number format of Windows unless there's a good reason not to. Audacity currently bases the symbols on the translation, which is not a valid reason. For consistency, accessibility reason and more, all number formats in Audacity should show based on what the Windows number format is set to.

**Screenshots**
Audacity number formats:
![image](https://user-images.githubusercontent.com/822352/152694549-45e7b96d-815b-4597-9b85-79b2142955cd.png)
Windows number format settings:
![image](https://user-images.githubusercontent.com/822352/152694551-19a5ba5c-37b5-41fd-b310-86a26975edd9.png)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: Audacity 3.1.3

**Additional context**
Good software design should take different locales into account. For example, English (Sweden) has the number format 000 000 000,000 and this format is as of now not supported by Audacity. By following Windows number format setting, a user can choose what they want as their symbols in any software that has proper locale support.

You can't make this based on translations, because you currently don't support English (Sweden) as an option, and users might have a valid reason to change how the symbols appear. For example, a user should have the option to change the decimal mark to • if they so choose to have a more visible symbol. In my case, I want to use a space as thousand separator since using comma or period is confusing, and I want comma as a decimal mark since it's a more visible mark than a period.

The Swedish translation is also incorrectly using format 000,000,000.000 when it should be 000 000 000,000 regardless, so I can't even get the ISO 80000-1 format by selecting Swedish as the language.

**Comment by petersampsonaudacity** [comment] 2022-02-07 11:07
Given that Audacity has been the way it is since 1.2.6 at least right up to the present day 3.1.3 (and 3.2.0 alpha) using the setting that the user makes in Interface Preferences for Audacity's language setting to determine what format to to display numbers in with their separators - if this change were made to instead rely on the computer's locale then this could introduce an unsettling regression for many users.

So if Audacity were to have the ability to base its number format based on locale, then this should probably be controlled by a new preference in Interface Preferences, say for example "Use locale not language setting for numerical separators".
And this setting should be "off" by default, so the the current and well-established behavior remains as the default for users.

**Comment by Liggliluff** [comment] 2022-02-07 11:14
@petersampsonaudacity 
> Given that Audacity has been the way it is since 1.2.6 at least right up to the present day 3.1.3 (and 3.2.0 alpha)

Irrelevant. Doesn't matter how long it has been wrong, it should preferably be corrected early on.

> if this change were made to instead rely on the computer's locale then this could introduce an unsettling regression for many users.

Could you explain how? If a user prefers their numbers to be 1,000.000 they can set that in their system settings. It should be up to the user to choose their format. Audacity does not let the user choose.

> So if Audacity were to have the ability to implement its number format based on locale, then this should probably be controlled by a new preference in Interface Preferences

Sure, fine. As long as it can display numbers like most other software, it would be great. Forcing the wrong format on the user is not that great of a user experience.

> And this setting should definitely be "off" by default, so the the current and well-established behavior remains as the default for users.

I strongly disagree on having the default be a well-established error. Users should have the option to opt-out of the bug fix. Not opt-in of the bug fix.

**Comment by LWinterberg** [comment] 2022-02-07 12:15
> Irrelevant. Doesn't matter how long it has been wrong, it should preferably be corrected early on.

Oh, it is relevant. If a behavior has existed for decades and you're the first person who reports it, it probably isn't a super high priority thing to change.

**Comment by Liggliluff** [comment] 2022-02-07 12:16
I'd also like to add the point that most users are probably running Windows in English (United States), English (United Kingdom) or any other major English locale, and therefore uses the format 1,000.000 in Windows, and Audacity is using the format 1,000.000 so for all these users, if the setting is on or off doesn't change anything.

Then you might have a lot of German users, Russian users and more, who has both Windows and Audacity set to German, Russian, and so on. These users would also have the same format in Windows and in Audacity, so for all these users, it also doesn't change whether the setting is on or off.

It does matter for the users who use English (Sweden), German (Switzerland), or any other locale that doesn't follow the "default" language's format. These users therefore don't get their format in Audacity, and this setting would be beneficial for these users. I can't speak for these users and therefore have no idea if they prefer Audacity, unlike all other software, to use the wrong format. Having a setting is beneficial still, but most software don't, and just use the locale from the system.

**Comment by Liggliluff** [comment] 2022-02-07 12:18
@LWinterberg 
> Oh, it is relevant. If a behavior has existed for decades and you're the first person who reports it, it probably isn't a super high priority thing to change.

The vast majority don't report bugs. The vast majority probably don't even have a mismatch in format between Windows and Audacity and therefore have no reason to report anything. I just happen to be the first.

**Comment by petersampsonaudacity** [comment] 2022-02-07 12:42
> > And this setting should definitely be "off" by default, so the the current and well-established behavior remains as the default for users.
> 
> I strongly disagree on having the default be a well-established error. Users should have the option to opt-out of the bug fix. Not opt-in to the bug fix.

This is not a well-established error, it is a design decision made by the originator of this application, Dominic Mazzoni, 20+ years ago when he first wrote it.

Note that I did not say that this should not or could not be done, rather I offered a solution which maintained current behaviors while offering an alternative prefs setting.

One important use case for using the Interface Prefs language setting has been QA testing of things like number format display in various languages.  I did much of the QA testing of that for many years (semi-retired now) and whilst I was happy enough to test Audacity in a foreign language by resetting the language in Interface prefs, the was NO way that I would consider that by changing the locale on my PC and Mac.  _Resetting Audacity to English was (and remains) a simple purge of the Audacity settings folder._

**Comment by Liggliluff** [comment] 2022-02-07 12:58
@petersampsonaudacity 
> I did much of the QA testing of that for many years (semi-retired now) and whilst I was happy enough to test Audacity in a foreign language by resetting the language in Interface prefs, the was NO way that I would consider that by changing the locale on my PC and Mac.

You are confusing language and format. You don't change language by changing the system formats. I also feel like your quality testing has been insufficient if you didn't test changing the system formats.

As a user who prefer using ISO standards, this is one of the struggles I have with software that don't support the system formats. I want ISO 8601 date format for example, yet there are software basing the date format on the language, and worse, only offers US English, with the backwards format. All this wouldn't be an issue for me, or anyone else for that matter, if software consistently kept using the system formats.

**Comment by SteveDaulton** [comment] 2022-02-15 10:41
Following a recent thread on the Audacity forum, and a discussion on Audacity Dev discord channel, I'm in agreement with [Liggliluff](https://github.com/Liggliluff) that Audacity should use Windows number format settings.

Language settings are not the same thing as number format settings, and there are good reasons why a user may need to use different number format setting from those that are traditionally associated with a particular language. One good example (provided by Wikipedia) is that several countries that use a comma decimal separator by literary convention, but use a dot as decimal separator for IT and finance - specifically it says that Switzerland uses a comma in handwriting, but a dot in government publications and finance.

Peter wrote:
> it is a design decision made by the originator of this application, Dominic Mazzoni, 20+ years ago when he first wrote it.

I don't think that is true. As far as I'm aware, very old versions of Audacity always used a dot, irrespective of the locale. Looking at Audacity 1.2.6, there is no "System" option for language, and after testing a selection of languages, it seems that Audacity always uses a dot.

At some time later, a comma was added as the decimal separator for languages where a comma is thought to be the "official" number format style. In my opinion, the fact that this can conflict with the system's number format setting is a bug, or at least an inadequately implemented feature.

[LWinterberg](https://github.com/LWinterberg) wrote:
> you're the first person who reports it

That's definitely not true. It's not reported very often because the vast majority of Windows users never change the number format from what Microsoft decide is correct for their locale, and of those that are affected, only  small proportion report the problem. However, the issue has been raised from time to time for many years.

I don't see this as a high priority bug, because it is relatively rare, but I do think that it is a bug and should be fixed.

**Comment by petersampsonaudacity** [comment] 2022-02-15 11:05
I have been thinking about this a lot and I now agree with @SteveDaulton and @Liggliluff  (the OP for this bug) that the number formatting should be based on locale (or what the user has set in their system settings) and **_NOT_** be based on the language set for Audacity.

A particularly interesting use case is Switzerland which has 3 official languages: German, French and Italian _(actually 4 if you include Romantsch - though I doubt that may computers are set to a Romantsch locale somehow)_.

My understanding is that the German speaking part of Switzerland uses different separators to those used in Germany - so in this case basing the separators on "Deutsch" language in Audacity is fundamentally wrong.  

I only have personal knowledge of the Swiss-German - but I suspect that the French speaking Swiss may well use different separators to that which the French themselves use.

**Comment by petersampsonaudacity** [comment] 2022-02-15 11:09
Another interesting use case is the US which has two official languages: English and Spanish.

The US English uses period "." for its decimal separator, whereas Spain (and thus I assume possibly US Spanish) uses comma "," for its decimal separator.

**Comment by petersampsonaudacity** [comment] 2022-02-15 12:01
And we do have some inconsistencies.

In Sweden they use comma as the decimal separator and space for the thousands separator - but if we change the Audacity language to Swedish (Svenska) we see:
![image](https://user-images.githubusercontent.com/50205984/154057252-4a40e679-69d5-4bf0-9684-fa2a4853a07f.png)
Here we can see that in the effect comma is used as the decimal separator.

BUT inconsistently in the Selection toolbar the period is used for decimal separator - plus the thousands separator is a comma and bot a space.

_However, I can recall of no Swedes ever complaining about this._

**Comment by petersampsonaudacity** [comment] 2022-02-15 12:06
Another possible issue is German (Deutsch):
![image](https://user-images.githubusercontent.com/50205984/154058355-9fc7ef29-a566-4745-b34d-9c89e1416f66.png)


Here we see consistency with the comma used as the decimal separator in both the effect and the Selection toolbar.

BUT space is used as the thousands separator and not period _(which is my understanding of German usage from Internet research)_.  This came about because some releases back a German speaker complained about the comma usage and insisted that space was more correct and logged a bug in Bugzilla for this.  Accordingly we changed it to be so - but now I'm not so sure that was the right thing to do.

**Comment by petersampsonaudacity** [comment] 2022-02-15 12:30
> I don't see this as a high priority bug, because it is relatively rare, but I do think that it is a bug and should be fixed.

I agree with @SteveDaulton  and @Liggliluff  that this is a bug and not just an enhancement - accordingly I removed the enhancement flag and added a bug flag.

**Comment by LWinterberg** [comment] 2022-07-21 08:41
This is a [known issue](https://github.com/audacity/audacity/wiki/Known-Issues).

**Closed by LWinterberg** 2022-07-21 08:41 UTC
Labels: bug, Design / UX, Known Issue, translation / i18n

**Comment by SteveDaulton** [comment] 2022-07-21 09:31
If this issue is not going to be fixed (presumably because "The issue is a minor issue which doesn't fit well into our Roadmap"), then perhaps better to revert to the old style of always using a dot as the decimal separator. At least then there will be consistency that can easily be documented. Even if that approach does look _archaic_, imo it's less bad than _broken_.

**Comment by Liggliluff** [comment] 2022-07-22 06:57
@SteveDaulton
> then perhaps better to revert to the old style of always using a dot as the decimal separator

That's a worse idea, since you'll have even more mismatches. At least the German locale is using the decimal comma in both inputs and the toolbar, but your idea would make the German locale be inconsistent.

I understand that this bug has low priority, so for the meantime, can the Swedish locale be updated to reflect the Swedish default settings at least? A decimal comma and a thousand space separator. I'd love an English (Sweden) locale too with this, but I'll run Audacity in Swedish until either the bug is resolved or an English (Swedish) locale is added.

**Comment by SteveDaulton** [comment] 2022-07-22 08:09
> That's a worse idea, since you'll have even more mismatches.

The old style was to use the dot as the decimal separator everywhere, consistently and without exception. In contrast, the current style attempts to use the correct, localized decimal separator, but does it incorrectly, causing the wrong decimal separator to be used in some places for some users. Neither option is great.

**Comment by Liggliluff** [comment] 2022-07-23 07:58
> The old style was to use the dot as the decimal separator everywhere, consistently and without exception

Except it's not consistent with the operating system. At least when the software locale and the system locale matches, the symbols are correct ... almost, some translations do need updating. How do I report incorrect translations? It should be rather quick to update each locale to match the values form CLDR.
