### ISSUE TITLE
MP3 file not Importing even after FFmpeg is Installed

### ISSUE THREAD

**Issue by MridulTi** [audacity/audacity#2734] opened 2022-03-26 13:54 UTC
**Describe the bug**
Whenever I have tried to open an mp3 file the audacity gave an "Error Importing" Like Audacity didn't recognize the file".
Try installing FFmpeg.
I have Installed FFmpeg as well and added it to my environment variables as well and FFmpeg is working as well. 
But it still shows this error and does not import the file.
I guess this is a little bug, then

**To Reproduce**
1. Just build Audacity as given in the instructions
2. Then try and open the Mp3 file" It will show the error"
3. You can also Install FFmpeg if you want
4. IT will still show the Error

**Expected behavior**
It should not show the error after installing FFmpeg
**Screenshots**
![image](https://user-images.githubusercontent.com/92802892/160242532-8daf072b-0409-49bb-8cd3-6a91b2a0e059.png)

**Additional information (please complete the following information):**
 - OS: Windows 11
 -Audacity Version 3.2.0-alpha-20220321

**Comment by petersampsonaudacity** [comment] 2022-03-26 15:20
@LWinterberg  leo,This looks like a duplicate of 
 Audacity doesn't recognize a mp3 file even though it's a mp3 file. #2634

**Closed** 2022-03-26 16:01 UTC
