### ISSUE TITLE
Audacity hangs in AudioIO::StopStream

### ISSUE THREAD

**Issue by kevgrig** [audacity/audacity#508] opened 2020-05-01 18:47 UTC
**Describe the bug**
Clicked play, then clicked stop and the program became fully hung.

**To Reproduce**
Sporadic; I could not reproduce it but I gathered a core dump during the first hang (guessing that this is probably some race condition that's hard to reproduce).

**Expected behavior**
No hang

**Screenshots**
The program stops painting when hung.

**Additional information (please complete the following information):**
 - OS: Fedora 31
 - Version 2.3.3-1.fc31

**Additional context**

I have a 1.4GB core dump if needed. pstack output:

```
Thread 8 (Thread 0x7f4f72e41700 (LWP 225885)):
#0  0x00007f4f8cafad45 in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007f4f7a99884c in pa_threaded_mainloop_wait () at /lib64/libpulse.so.0
#2  0x00007f4f7aa01914 in pulse_wait_operation () at /usr/lib64/alsa-lib/libasound_module_pcm_pulse.so
#3  0x00007f4f7aa00179 in pulse_stop () at /usr/lib64/alsa-lib/libasound_module_pcm_pulse.so
#4  0x00007f4f8b05ab96 in snd_pcm_ioplug_drop () at /lib64/libasound.so.2
#5  0x00007f4f8b00ee05 in snd_pcm_drop () at /lib64/libasound.so.2
#6  0x000055cf0f295b1b in AlsaStop (stream=stream@entry=0x55cf100dbc50, abort=<optimized out>) at src/hostapi/alsa/pa_linux_alsa.c:3042
#7  0x000055cf0f29884a in OnExit (data=0x55cf100dbc50) at src/hostapi/alsa/pa_linux_alsa.c:3393
#8  0x000055cf0ebfca6a in __pthread_cleanup_routine (__frame=<synthetic pointer>) at /usr/include/pthread.h:612
#9  CallbackThreadFunc (userData=0x55cf100dbc50) at src/hostapi/alsa/pa_linux_alsa.c:4185
#10 0x00007f4f8caf44e2 in start_thread () at /lib64/libpthread.so.0
#11 0x00007f4f8ab486a3 in clone () at /lib64/libc.so.6
Thread 7 (Thread 0x7f4f70e3d700 (LWP 225884)):
#0  0x00007f4f8caf697e in __pthread_mutex_lock_full () at /lib64/libpthread.so.0
#1  0x00007f4f7a932ea2 in pa_mutex_lock () at /usr/lib64/pulseaudio/libpulsecommon-13.99.so
#2  0x00007f4f7a9981b1 in poll_func () at /lib64/libpulse.so.0
#3  0x00007f4f7a989811 in pa_mainloop_poll () at /lib64/libpulse.so.0
#4  0x00007f4f7a989e93 in pa_mainloop_iterate () at /lib64/libpulse.so.0
#5  0x00007f4f7a989f40 in pa_mainloop_run () at /lib64/libpulse.so.0
#6  0x00007f4f7a9980ed in thread () at /lib64/libpulse.so.0
#7  0x00007f4f7a933dac in internal_thread_func () at /usr/lib64/pulseaudio/libpulsecommon-13.99.so
#8  0x00007f4f8caf44e2 in start_thread () at /lib64/libpthread.so.0
#9  0x00007f4f8ab486a3 in clone () at /lib64/libc.so.6
Thread 6 (Thread 0x7f4f4effd700 (LWP 225734)):
#0  0x00007f4f8ab3da3f in poll () at /lib64/libc.so.6
#1  0x00007f4f8b10986e in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#2  0x00007f4f8b1099a3 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#3  0x00007f4f784fd93d in dconf_gdbus_worker_thread () at /usr/lib64/gio/modules/libdconfsettings.so
#4  0x00007f4f8b133022 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#5  0x00007f4f8caf44e2 in start_thread () at /lib64/libpthread.so.0
#6  0x00007f4f8ab486a3 in clone () at /lib64/libc.so.6
Thread 5 (Thread 0x7f4f7a03a700 (LWP 225556)):
#0  0x00007f4f8cafef55 in nanosleep () at /lib64/libpthread.so.0
#1  0x00007f4f8bf24350 in wxMicroSleep(unsigned long) () at /lib64/libwx_baseu-3.0.so.0
#2  0x000055cf0ec9df8e in AudioThread::Entry() (this=0x55cf0fef0940) at AudioIO.cpp:2566
#3  0x00007f4f8bf1fe1a in wxThread::CallEntry() () at /lib64/libwx_baseu-3.0.so.0
#4  0x00007f4f8bf20197 in wxThreadInternal::PthreadStart(wxThread*) () at /lib64/libwx_baseu-3.0.so.0
#5  0x00007f4f8caf44e2 in start_thread () at /lib64/libpthread.so.0
#6  0x00007f4f8ab486a3 in clone () at /lib64/libc.so.6
Thread 4 (Thread 0x7f4f7a8bc700 (LWP 225555)):
#0  0x00007f4f8cafef55 in nanosleep () at /lib64/libpthread.so.0
#1  0x00007f4f8bf24350 in wxMicroSleep(unsigned long) () at /lib64/libwx_baseu-3.0.so.0
#2  0x000055cf0ec999e4 in MidiThread::Entry() (this=0x55cf0fe9b1f0) at AudioIO.cpp:2589
#3  0x00007f4f8bf1fe1a in wxThread::CallEntry() () at /lib64/libwx_baseu-3.0.so.0
#4  0x00007f4f8bf20197 in wxThreadInternal::PthreadStart(wxThread*) () at /lib64/libwx_baseu-3.0.so.0
#5  0x00007f4f8caf44e2 in start_thread () at /lib64/libpthread.so.0
#6  0x00007f4f8ab486a3 in clone () at /lib64/libc.so.6
Thread 3 (Thread 0x7f4f73642700 (LWP 225547)):
#0  0x00007f4f8ab3da3f in poll () at /lib64/libc.so.6
#1  0x00007f4f8b10986e in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#2  0x00007f4f8b109bf3 in g_main_loop_run () at /lib64/libglib-2.0.so.0
#3  0x00007f4f8a188fca in gdbus_shared_thread_func () at /lib64/libgio-2.0.so.0
#4  0x00007f4f8b133022 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#5  0x00007f4f8caf44e2 in start_thread () at /lib64/libpthread.so.0
#6  0x00007f4f8ab486a3 in clone () at /lib64/libc.so.6
Thread 2 (Thread 0x7f4f7be43700 (LWP 225546)):
#0  0x00007f4f8ab3da3f in poll () at /lib64/libc.so.6
#1  0x00007f4f8b10986e in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#2  0x00007f4f8b1099a3 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#3  0x00007f4f8b1099f1 in glib_worker_main () at /lib64/libglib-2.0.so.0
#4  0x00007f4f8b133022 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#5  0x00007f4f8caf44e2 in start_thread () at /lib64/libpthread.so.0
#6  0x00007f4f8ab486a3 in clone () at /lib64/libc.so.6
Thread 1 (Thread 0x7f4f896ddb00 (LWP 225540)):
#0  0x00007f4f8caf5b27 in __pthread_timedjoin_ex () at /lib64/libpthread.so.0
#1  0x000055cf0f293d03 in PaUnixThread_Terminate (self=self@entry=0x55cf100dbdf0, wait=<optimized out>, exitResult=exitResult@entry=0x7ffedb9a3564) at src/os/unix/pa_unix_util.c:449
#2  0x000055cf0f295c1c in RealStop (stream=0x55cf100dbc50, abort=<optimized out>) at src/hostapi/alsa/pa_linux_alsa.c:3102
#3  0x000055cf0ec99ac4 in AudioIO::StopStream() () at AudioIO.cpp:2218
#4  0x000055cf0ed885fc in ProjectAudioManager::Stop(bool) (this=0x7f4f5c005e10, stopStream=<optimized out>) at ProjectAudioManager.cpp:329
#5  0x00007f4f8bf50fbe in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () at /lib64/libwx_baseu-3.0.so.0
#6  0x00007f4f8bf510c3 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () at /lib64/libwx_baseu-3.0.so.0
#7  0x00007f4f8bf51420 in wxEvtHandler::TryHereOnly(wxEvent&) () at /lib64/libwx_baseu-3.0.so.0
#8  0x00007f4f8bf514ab in wxEvtHandler::ProcessEventLocally(wxEvent&) () at /lib64/libwx_baseu-3.0.so.0
#9  0x00007f4f8bf51551 in wxEvtHandler::ProcessEvent(wxEvent&) () at /lib64/libwx_baseu-3.0.so.0
#10 0x00007f4f8c4f349a in wxWindowBase::TryAfter(wxEvent&) () at /lib64/libwx_gtk3u_core-3.0.so.0
#11 0x00007f4f8bf512db in wxEvtHandler::SafelyProcessEvent(wxEvent&) () at /lib64/libwx_baseu-3.0.so.0
#12 0x000055cf0f1ccd7d in AButton::Click() (this=0x55cf0fca8500) at /usr/include/wx-3.0/wx/window.h:846
#13 0x000055cf0f1cddad in AButton::OnMouseEvent(wxMouseEvent&) (this=0x55cf0fca8500, event=...) at widgets/AButton.cpp:481
#14 0x00007f4f8bf50fbe in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () at /lib64/libwx_baseu-3.0.so.0
#15 0x00007f4f8bf510c3 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () at /lib64/libwx_baseu-3.0.so.0
#16 0x00007f4f8bf51420 in wxEvtHandler::TryHereOnly(wxEvent&) () at /lib64/libwx_baseu-3.0.so.0
#17 0x00007f4f8bf514ab in wxEvtHandler::ProcessEventLocally(wxEvent&) () at /lib64/libwx_baseu-3.0.so.0
#18 0x00007f4f8bf51551 in wxEvtHandler::ProcessEvent(wxEvent&) () at /lib64/libwx_baseu-3.0.so.0
#19 0x00007f4f8bf512db in wxEvtHandler::SafelyProcessEvent(wxEvent&) () at /lib64/libwx_baseu-3.0.so.0
#20 0x00007f4f8c325b73 in gtk_window_button_release_callback () at /lib64/libwx_gtk3u_core-3.0.so.0
#21 0x00007f4f8b755e3b in _gtk_marshal_BOOLEAN__BOXED () at /lib64/libgtk-3.so.0
#22 0x00007f4f8b1f3742 in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#23 0x00007f4f8b207604 in signal_emit_unlocked_R () at /lib64/libgobject-2.0.so.0
#24 0x00007f4f8b20fa21 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#25 0x00007f4f8b2109d3 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#26 0x00007f4f8b7009b3 in gtk_widget_event_internal () at /lib64/libgtk-3.so.0
#27 0x00007f4f8b5bc1e8 in propagate_event () at /lib64/libgtk-3.so.0
#28 0x00007f4f8b5be44b in gtk_main_do_event () at /lib64/libgtk-3.so.0
#29 0x00007f4f8b2a4f79 in _gdk_event_emit () at /lib64/libgdk-3.so.0
#30 0x00007f4f8b2d8096 in gdk_event_source_dispatch () at /lib64/libgdk-3.so.0
#31 0x00007f4f8b109570 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#32 0x00007f4f8b109900 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#33 0x00007f4f8b109bf3 in g_main_loop_run () at /lib64/libglib-2.0.so.0
#34 0x00007f4f8b5bd43d in gtk_main () at /lib64/libgtk-3.so.0
#35 0x00007f4f8c3049a5 in wxGUIEventLoop::DoRun() () at /lib64/libwx_gtk3u_core-3.0.so.0
#36 0x00007f4f8bdfef61 in wxEventLoopBase::Run() () at /lib64/libwx_baseu-3.0.so.0
#37 0x00007f4f8bdbfbda in wxAppConsoleBase::MainLoop() () at /lib64/libwx_baseu-3.0.so.0
#38 0x00007f4f8be5383c in wxEntry(int&, wchar_t**) () at /lib64/libwx_baseu-3.0.so.0
#39 0x000055cf0ebffea6 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at AudacityApp.cpp:801
```

I installed all the debuginfo packages, so if you want me to run some `gdb` commands on the dump, let me know. Here's `bt` with function argument values:

```
(gdb) bt
#0  __GI___pthread_timedjoin_ex (threadid=139979206694656, thread_return=thread_return@entry=0x7ffedb9a3530, abstime=abstime@entry=0x0, block=block@entry=true) at pthread_join_common.c:142
#1  0x00007f4f8caf58b0 in __pthread_join (threadid=<optimized out>, thread_return=thread_return@entry=0x7ffedb9a3530) at pthread_join.c:24
#2  0x000055cf0f293d03 in PaUnixThread_Terminate (self=self@entry=0x55cf100dbdf0, wait=<optimized out>, exitResult=exitResult@entry=0x7ffedb9a3564) at src/os/unix/pa_unix_util.c:449
#3  0x000055cf0f295c1c in RealStop (stream=0x55cf100dbc50, abort=<optimized out>) at src/hostapi/alsa/pa_linux_alsa.c:3102
#4  0x000055cf0ec99ac4 in AudioIO::StopStream() () at AudioIO.cpp:2218
#5  0x000055cf0ed885fc in ProjectAudioManager::Stop(bool) (this=0x7f4f5c005e10, stopStream=<optimized out>) at ProjectAudioManager.cpp:329
#6  0x00007f4f8bf50fbe in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) (event=..., handler=<optimized out>, entry=...) at ../include/wx/app.h:439
#7  wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) (entry=..., handler=<optimized out>, event=...) at ../src/common/event.cpp:1365
#8  0x00007f4f8bf510c3 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) (this=<optimized out>, event=..., self=self@entry=0x55cf0ff08ab0) at ../src/common/event.cpp:996
#9  0x00007f4f8bf51420 in wxEvtHandler::TryHereOnly(wxEvent&) (this=0x55cf0ff08ab0, event=...) at ../src/common/event.cpp:1587
#10 0x00007f4f8bf514ab in wxEvtHandler::TryBeforeAndHere(wxEvent&) (event=..., this=0x55cf0ff08ab0) at ../include/wx/event.h:3671
#11 wxEvtHandler::ProcessEventLocally(wxEvent&) (this=0x55cf0ff08ab0, event=...) at ../src/common/event.cpp:1520
#12 0x00007f4f8bf51551 in wxEvtHandler::ProcessEvent(wxEvent&) (this=0x55cf0ff08ab0, event=...) at ../src/common/event.cpp:1493
#13 0x00007f4f8c4f349a in wxWindowBase::TryAfter(wxEvent&) (this=0x55cf0fca8500, event=...) at ../include/wx/window.h:846
#14 0x00007f4f8bf512db in wxEvtHandler::SafelyProcessEvent(wxEvent&) (this=<optimized out>, event=...) at ../src/common/event.cpp:1611
#15 0x000055cf0f1ccd7d in AButton::Click() (this=0x55cf0fca8500) at /usr/include/wx-3.0/wx/window.h:846
#16 0x000055cf0f1cddad in AButton::OnMouseEvent(wxMouseEvent&) (this=0x55cf0fca8500, event=...) at widgets/AButton.cpp:481
#17 0x00007f4f8bf50fbe in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) (event=..., handler=<optimized out>, entry=...) at ../include/wx/app.h:439
#18 wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) (entry=..., handler=<optimized out>, event=...) at ../src/common/event.cpp:1365
#19 0x00007f4f8bf510c3 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) (this=<optimized out>, event=..., self=self@entry=0x55cf0fca8500) at ../src/common/event.cpp:996
#20 0x00007f4f8bf51420 in wxEvtHandler::TryHereOnly(wxEvent&) (this=0x55cf0fca8500, event=...) at ../src/common/event.cpp:1587
#21 0x00007f4f8bf514ab in wxEvtHandler::TryBeforeAndHere(wxEvent&) (event=..., this=0x55cf0fca8500) at ../include/wx/event.h:3671
#22 wxEvtHandler::ProcessEventLocally(wxEvent&) (this=0x55cf0fca8500, event=...) at ../src/common/event.cpp:1520
#23 0x00007f4f8bf51551 in wxEvtHandler::ProcessEvent(wxEvent&) (this=0x55cf0fca8500, event=...) at ../src/common/event.cpp:1493
#24 0x00007f4f8bf512db in wxEvtHandler::SafelyProcessEvent(wxEvent&) (this=<optimized out>, event=...) at ../src/common/event.cpp:1611
#25 0x00007f4f8c325b73 in gtk_window_button_release_callback () at ../src/gtk/window.cpp:1546
#30 0x00007f4f8b2109d3 in <emit signal ??? on instance 0x55cf0fccff80 [wxPizza]> (instance=instance@entry=0x55cf0fccff80, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3453
    #26 0x00007f4f8b755e3b in _gtk_marshal_BOOLEAN__BOXED
    (closure=closure@entry=0x55cf0ff0b130, return_value=return_value@entry=0x7ffedb9a3c50, n_param_values=n_param_values@entry=2, param_values=param_values@entry=0x7ffedb9a3cb0, invocation_hint=invocation_hint@entry=0x7ffedb9a3c30, marshal_data=marshal_data@entry=0x0) at gtkmarshalers.c:83
    #27 0x00007f4f8b1f3742 in g_closure_invoke (closure=0x55cf0ff0b130, return_value=0x7ffedb9a3c50, n_param_values=2, param_values=0x7ffedb9a3cb0, invocation_hint=0x7ffedb9a3c30) at ../gobject/gclosure.c:810
    #28 0x00007f4f8b207604 in signal_emit_unlocked_R
    (node=<optimized out>, detail=detail@entry=0, instance=instance@entry=0x55cf0fccff80, emission_return=emission_return@entry=0x7ffedb9a3de0, instance_and_params=instance_and_params@entry=0x7ffedb9a3cb0) at ../gobject/gsignal.c:3641
    #29 0x00007f4f8b20fa21 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7ffedb9a3e90) at ../gobject/gsignal.c:3407
#31 0x00007f4f8b7009b3 in gtk_widget_event_internal (event=0x55cf0f8b16f0, widget=0x55cf0fccff80 [wxPizza]) at gtkwidget.c:7808
#32 gtk_widget_event_internal (widget=0x55cf0fccff80 [wxPizza], event=0x55cf0f8b16f0) at gtkwidget.c:7677
#33 0x00007f4f8b5bc1e8 in propagate_event_up (topmost=<optimized out>, event=<optimized out>, widget=0x55cf0fccff80 [wxPizza]) at gtkmain.c:2584
#34 propagate_event (widget=<optimized out>, event=0x55cf0f8b16f0, captured=<optimized out>, topmost=0x0) at gtkmain.c:2687
#35 0x00007f4f8b5be44b in gtk_main_do_event (event=0x55cf0f8b16f0) at gtkmain.c:1917
#36 gtk_main_do_event (event=<optimized out>) at gtkmain.c:1687
#37 0x00007f4f8b2a4f79 in _gdk_event_emit (event=event@entry=0x55cf0f8b16f0) at gdkevents.c:73
#38 0x00007f4f8b2d8096 in gdk_event_source_dispatch (source=source@entry=0x55cf0f8b0a00, callback=<optimized out>, user_data=<optimized out>) at gdkeventsource.c:367
#39 0x00007f4f8b109570 in g_main_dispatch (context=0x55cf0f8b23a0) at ../glib/gmain.c:3216
#40 g_main_context_dispatch (context=context@entry=0x55cf0f8b23a0) at ../glib/gmain.c:3881
#41 0x00007f4f8b109900 in g_main_context_iterate (context=0x55cf0f8b23a0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:3954
#42 0x00007f4f8b109bf3 in g_main_loop_run (loop=0x55cf10a9dcc0) at ../glib/gmain.c:4148
#43 0x00007f4f8b5bd43d in gtk_main () at gtkmain.c:1325
#44 0x00007f4f8c3049a5 in wxGUIEventLoop::DoRun() (this=0x55cf0f8f16b0) at ../src/gtk/evtloop.cpp:65
#45 0x00007f4f8bdfef61 in wxEventLoopBase::Run() (this=0x55cf0f8f16b0) at ../src/common/evtloopcmn.cpp:78
#46 0x00007f4f8bdbfbda in wxAppConsoleBase::MainLoop() (this=0x55cf0f8790d0) at ../src/common/appbase.cpp:334
#47 0x00007f4f8be5383c in wxEntry(int&, wchar_t**) (argc=<optimized out>, argv=<optimized out>) at ../include/wx/app.h:439
#48 0x000055cf0ebffea6 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at AudacityApp.cpp:801
```
I'm guessing it's just waiting for thread 8 to finish. Here's that thread's `bt`:
```
(gdb) info threads
  Id   Target Id                                    Frame 
* 1    Thread 0x7f4f896ddb00 (LWP 225540)           __GI___pthread_timedjoin_ex (threadid=139979206694656, thread_return=thread_return@entry=0x7ffedb9a3530, abstime=abstime@entry=0x0, block=block@entry=true) at pthread_join_common.c:142
  2    Thread 0x7f4f7be43700 (LWP 225546)           0x00007f4f8ab3da3f in __GI___poll (fds=0x55cf0fa0bfa0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  3    Thread 0x7f4f73642700 (LWP 225547)           0x00007f4f8ab3da3f in __GI___poll (fds=0x7f4f6c0133c0, nfds=7, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  4    Thread 0x7f4f7a8bc700 (LWP 225555)           0x00007f4f8cafef55 in __GI___nanosleep (requested_time=requested_time@entry=0x7f4f7a8bb8d0, remaining=remaining@entry=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  5    Thread 0x7f4f7a03a700 (LWP 225556)           0x00007f4f8cafef55 in __GI___nanosleep (requested_time=requested_time@entry=0x7f4f7a0398a0, remaining=remaining@entry=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  6    Thread 0x7f4f4effd700 (LWP 225734)           0x00007f4f8ab3da3f in __GI___poll (fds=0x55cf10964500, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  7    Thread 0x7f4f70e3d700 (LWP 225884)           __pthread_mutex_lock_full (mutex=0x55cf10a7cbd0) at ../nptl/pthread_mutex_lock.c:424
  8    Thread 0x7f4f72e41700 (LWP 225885) (Exiting) futex_wait_cancelable (private=0, expected=0, futex_word=0x55cf108e728c) at ../sysdeps/unix/sysv/linux/futex-internal.h:80
(gdb) thread 8
[Switching to thread 8 (Thread 0x7f4f72e41700 (LWP 225885))]
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x55cf108e728c) at ../sysdeps/unix/sysv/linux/futex-internal.h:80
80        int err = lll_futex_timed_wait (futex_word, expected, NULL, private);
(gdb) bt
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x55cf108e728c) at ../sysdeps/unix/sysv/linux/futex-internal.h:80
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55cf10a7cbd0, cond=0x55cf108e7260) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x55cf108e7260, mutex=0x55cf10a7cbd0) at pthread_cond_wait.c:638
#3  0x00007f4f7a9332eb in pa_cond_wait (c=<optimized out>, m=<optimized out>) at pulsecore/mutex-posix.c:139
#4  0x00007f4f7a99884c in pa_threaded_mainloop_wait (m=0x55cf10aad580) at pulse/thread-mainloop.c:216
#5  0x00007f4f7aa01914 in pulse_wait_operation (p=0x55cf10a0cf90, o=o@entry=0x55cf0fce3b40) at pulse.c:72
#6  0x00007f4f7aa00179 in pulse_stop (io=<optimized out>) at pcm_pulse.c:279
#7  0x00007f4f8b05ab96 in snd_pcm_ioplug_drop (pcm=0x55cf10988dc0) at pcm_ioplug.c:499
#8  0x00007f4f8b00ee05 in snd_pcm_drop (pcm=0x55cf10988dc0) at pcm.c:1301
#9  0x000055cf0f295b1b in AlsaStop (stream=stream@entry=0x55cf100dbc50, abort=<optimized out>) at src/hostapi/alsa/pa_linux_alsa.c:3042
#10 0x000055cf0f29884a in OnExit (data=0x55cf100dbc50) at src/hostapi/alsa/pa_linux_alsa.c:3393
#11 0x000055cf0ebfca6a in __pthread_cleanup_routine (__frame=<synthetic pointer>) at /usr/include/pthread.h:612
#12 CallbackThreadFunc (userData=0x55cf100dbc50) at src/hostapi/alsa/pa_linux_alsa.c:4185
#13 0x00007f4f8caf44e2 in start_thread (arg=<optimized out>) at pthread_create.c:479
#14 0x00007f4f8ab486a3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by LWinterberg** [comment] 2021-12-23 16:36
When adding tons of tracks (200 or so) and rapidly hitting play and stop, I can sometimes manage to get this error:
```
{
    "timestamp": 1640276910,
    "event_id": "8df59c3ca1b74c468d1cd115c1393eca",
    "platform": "native",
    "release": "audacity@3.1.3",
    "contexts": {
        "os": {
            "type": "os",
            "name": "Unix",
            "version": "5.13.0"
        }
    },
    "exception": {
        "values": [
            {
                "type": "Error",
                "value": "Error opening sound device.\nTry changing the audio host, playback device and the project sample rate.",
                "mechanism": {
                    "type": "runtime_error",
                    "handled": false
                }
            }
        ]
    }
}
```
However, Audacity recovers afterwards and can play audio again. Closing this bug as I can't reproduce it and it's quite old.

**Closed by LWinterberg** 2021-12-23 16:36 UTC
Labels: bug-distros
