### ISSUE TITLE
Utilize zstandard compression for save files for increased speed and smaller file sizes

### ISSUE THREAD

**Issue by scottchiefbaker** [audacity/audacity#4010] opened 2022-12-01 22:27 UTC
### Your idea

I have an 80 minute multi-track podcast recording that comes out to 3.5GB when saved to disk. Saving this much data can take a lot of time depending on the speed of your HDD, and also consumes a lot of disk space.

Just for comparison I did a test using [zstandard](https://facebook.github.io/zstd/) lossless compression on the `.aup3` file. Utilizing the `--fast` option I can compress this recording down to 744MB in 2.3 seconds. If `zst` compression were built in to Audacity we could save disk space, and speed up file saving. Writing 744MB file to disk will be much faster than the full 3.5GB. 

### Problem to be solved

1. Speed up saving to slow HDDs
2. Save disk space for file saves

### Prior art

Lots of applications are embedding `zstd` compression. Some high profile projects: Linux Kernel, PostgreSQL, MySQL, TrueNAS, curl, tar, RSync, League of Legends, Blender, Fedora and Ubuntu.

More complete list: https://facebook.github.io/zstd/

### Additional context

zstd has a pretty robust API with [decent documentation](https://raw.githack.com/facebook/zstd/release/doc/zstd_manual.html).

**Comment by LWinterberg** [comment] 2022-12-02 00:21
I was unable to reproduce significant space savings from zst, especially when compared to wavpack (wv)
![image](https://user-images.githubusercontent.com/87814144/205184747-145a3cd8-b33b-415e-bbb2-5697eb6ddb48.png)

This isn't entirely surprising; general-purpose encoders can't really make any assumptions about the files they're working with, whereas for audio (and photo and video for that matter), the encoder can know what the signal is going to look like in the vast majority of cases.

But to zstd's credit, it achieved its 0.42% compression in about 4 seconds for the 2h stream while wavpack took about 32s.

**Comment by scottchiefbaker** [comment] 2022-12-02 19:01
@LWinterberg wow you're right. I just did a random test with and handful of `.aup3` files I had laying around and the average compression I got was about 4-6%. Must be something special about those multi-track podcast recordings I have (They're [Craig](https://craig.chat/) recordings), as they all compress INSANELY well.

```
$ zstd *aup3 --fast --verbose
*** zstd command line interface 64-bits v1.3.8, by Yann Collet ***
general-order-one-01.aup3 : 42.92%   (3438596096 => 1475902837 bytes, general-order-one-01.aup3.zst)
general-order-one-02.aup3 : 41.47%   (1560899584 => 647328223 bytes, general-order-one-02.aup3.zst)
general-order-one-03.aup3 : 30.33%   (2608652288 => 791141835 bytes, general-order-one-03.aup3.zst)
general-order-one-04.aup3 : 25.60%   (3049426944 => 780650643 bytes, general-order-one-04.aup3.zst)
general-order-one-05.aup3 : 34.77%   (2849259520 => 990706174 bytes, general-order-one-05.aup3.zst)
general-order-one-06.aup3 : 51.94%   (1655799808 => 860076379 bytes, general-order-one-06.aup3.zst)
general-order-one-07.aup3 : 33.68%   (2983903232 => 1005098652 bytes, general-order-one-07.aup3.zst)
```

This is an average compression ratio of 63% (!!!), which is a totally different story.

**Comment by LWinterberg** [comment] 2022-12-05 12:47
I suspect your recordings have a lot of perfect silences in them then, which zstd can pick up on more easily. 

Anyway, closing this: while we need to look at the project format again more closely eventually, zstd compression isn't the way, and audacity 3.x isn't the version to do it in

**Closed by LWinterberg** 2022-12-05 12:47 UTC
Labels: Enhancement Request, P4, medium feature
