### ISSUE TITLE
Normalize 6ch vs stereo

### ISSUE THREAD

**Issue by colemar** [audacity/audacity#4835] opened 2023-06-24 14:34 UTC
### Bug description

If you normalize a stereo track leaving [Normalize stereo channels independently] off
![image](https://github.com/audacity/audacity/assets/3066000/206304f4-1b86-4c83-aa35-bac698633a29)
then the 2 channels will be amplified by the same amount (as expected).

If the track has 6 channels (6 sync-locked mono tracks, selected together) then each channel will be normalized independently, even if [Normalize stereo channels independently] is off, which most of the times is bad.

### Steps to reproduce

See above.

### Expected behavior

An option to properly normalize multichannel tracks.

### Actual behavior

See above.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by LWinterberg** [comment] 2023-06-26 00:37
Duplicate of #4272

**Closed by LWinterberg** 2023-06-26 00:37 UTC
Labels: bug
