### ISSUE TITLE
Discarding undo/redo history when closing project takes a long time to complete

### ISSUE THREAD

**Issue by Dan33185** [audacity/audacity#7382] opened 2024-09-20 21:26 UTC
### Bug description

I am getting a pop up when I close a project in Audacity that says " Discarding undo/redo history". I’m not sure what it is, but it’s taking sometimes up to 20 minutes to complete before I can close Audacity. Seems to be more common with 24-Bit Files, and with versions newer than 3.5.1.

### Steps to reproduce

1. Open a .WAV file
2. Make any kind of edits
3. Export audio
4. Close the project
5. Close Audacity

A window then pops up saying "Discarding undo/redo history" with an ETA of when it will finish, which starts out at 30 seconds or so and grows as it proceeds. Average wait time is 15-20 minutes, I usually just end up force it closed through the task manager.

### Expected behavior

Audacity should close in a timely manner (a few seconds)

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by brettcl** [comment] 2024-09-22 01:13
I have a very similar experience since recent update (ver 3.6.3 or perhaps earlier?) but I am not using 24 bit files. Instead, I notice it when I have I have long recordings of a few hours or longer -- the longer the recording, the longer it takes to discard undo/redo history when quitting. 

When I quit and indicate NOT to save changes, it can take up to several minutes to complete the "Discarding undo/redo history". At no point have I saved the aup3 file, so there should be no need to save the undo/redo history.

It seems the correct thing to do would be to simply (and quickly) delete the working file and exit ASAP -- as it always used to do.

Not 100% sure but it doesn't seem to have anything to do with the number of edits, only the length of discarded material. 

Workflow details: I am recording audio at either 44.1kHz and 48 kHz often for several hours at a time. I set Audacity to Record with USB input to digitize old audio cassettes, so only first 60-90 minutes have audio. When I come back -- often hours later -- I stop, trim the file, edit, export to WAV/MP3, and then quit.

Thanks!

**Comment by petersampsonaudacity** [comment] 2024-09-22 07:52
> It seems the correct thing to do would be to simply (and quickly) delete the working file and exit ASAP

That seems eminently sensible to me too.

**Comment by dozzzzer** [comment] 2024-09-24 13:20
I tried importing a 1-minute stereo WAV file (24-bit) and then followed the STRs but to no avail. Also worth mentioning that I've used WAV 24-bit when exporting in step 3, if that matters.

**Comment by saintmatthieu** [comment] 2024-09-24 19:23
Hello @Dan33185, thanks for your report, and @brettcl, too, for contributing.

Unfortunately I can't reproduce it either, but I know a bit the mechanisms involved and maybe you can help me diagnose the problem.

A bit of background:

During the lifetime of the project, recording, importing new audio or applying an effect may add data to the .aup3 project file, increasing its size. _Removing_ audio, on the other hand, doesn't reduce it. This is because the data is kept there in case the user decides to undo.
The undo history is discarded on project close, though: when re-opening it, you can't undo the last action you did before closing.
The aforementioned data can therefore be then discarded on close. References to the data blocks in the project file were kept, allowing these blocks to be then deleted. It's when their combined deletions takes a lot of time that you see this "Discarding undo/redo history" progress bar.
This time should be proportional to the amount of such blocks, yet 20mn seems abnormally long ...

I have created a branch where a [build](https://github.com/saintmatthieu/audacity/actions/runs/11020122492) just finished. You can download it: you need to be logged in github, and then at the bottom of the page you will see this section: 
![image](https://github.com/user-attachments/assets/fc867e49-570b-4f0d-b270-1b8105191d5f)
You can download e.g. the bottommost build, or whichever is suitable.

If you run this build, produce such blocks (I tell you an easy way in the next paragraph) and then close without saving, it will create two text files in your Documents folder: DeleteCount.log and DeleteDur.log: 
![image](https://github.com/user-attachments/assets/2bfd0fc3-686f-49fa-a463-cd05e9eb9e7e)
The former logs how many blocks get deleted, and the latter, how long it takes for each to be deleted. On my machine, it's about half a millisecond per block, let's see if it's much higher on yours, or if somehow you have an extremely large amount of blocks.

How do you "produce such blocks" ? An easy way is to get some audio in your project, not necessarily a very large file, select it all, apply an effect (e.g. Volume and Compression > Amplify) once, then Ctrl+R repeatedly: this will repeat applying the effect, each time creating new blocks.

I hope you'll be willing to make this additional effort.

**Comment by Dan33185** [comment] 2024-09-25 03:37
I've attached the log files
[DeleteCount.log](https://github.com/user-attachments/files/17124170/DeleteCount.log)
[DeleteDur.log](https://github.com/user-attachments/files/17124172/DeleteDur.log)

**Comment by Dan33185** [comment] 2024-09-25 03:39
I've attached both files
[DeleteCount.log](https://github.com/user-attachments/files/17124185/DeleteCount.log)
[DeleteDur.log](https://github.com/user-attachments/files/17124187/DeleteDur.log)

**Comment by saintmatthieu** [comment] 2024-09-25 06:32
Fantastic, thanks!

Here's the histogram of the calls:
![DeleteDur](https://github.com/user-attachments/assets/cd9f75aa-0c3d-49aa-80dc-8fc12c554e3b)
Your median call time, 0.76ms, looks about normal ; out of the 2280 total calls, over 2000 are in that tall bucket on the left.
If all calls lasted that long, the total amount of time needed for the deletion would have been less than 2s.
Instead, it took almost 10s. Problematic are the remaining 200 calls. Basically, 10% of the calls account for 90% of the time spent.

The sequence of call durations is interesting:
![DeleteDurSequence](https://github.com/user-attachments/assets/3c2a6a69-c5e4-4d91-b234-5fe9f89d5d42)
To a couple of exceptions, about 250 calls in a row concentrate all the outliers. What happened then?..

I just looked in more detail at the `SqliteSampleBlock::Delete()` method, whose execution time we measure here. The only non-trivial calls to other methods it makes are all from the SQLite library. (There is a mutex, but I verified that, at least in this context, there cannot be contention because it only gets called from one same thread. Besides this,) We haven't upgraded that library since 3.5.1, so we can exclude this root cause.

So I have two hypotheses:
1. The time taken by these `Delete` calls is most of the time you have to wait for Audacity to close. In that case, the problem should also exist with 3.5.1 and earlier, and it makes this bug less critical - basically we haven't fucked up anything in the 3.6 release.
2. The code around this method causes even more delay. In that case, further investigation would be necessary.

To decide which one is valid, helpful would be if you could remember about how long you had to wait for Audacity to close when you ran my build. Was it about 10s?
If it was, then hypothesis 1 is more likely, but we could verify it if you downloaded 3.5.1 from [fosshub](https://www.fosshub.com/Audacity-old.html) and tried again.
If it was much more, then I also have to think much more :D

**Comment by saintmatthieu** [comment] 2024-09-25 06:58
> It seems the correct thing to do would be to simply (and quickly) delete the working file and exit ASAP -- as it always used to do.

I don't think it's correct to say it's always used to do that: the mechanism I described in my [background note](https://github.com/audacity/audacity/issues/7382#issuecomment-2372164286) integrates the blocks to be discarded in the project file ; this has been this way since Audacity adopted SQLite, which is a few years back already.

Just exiting ASAP is then not an option, or the size of the projects after close would be unnecessarily large.

**Comment by Dan33185** [comment] 2024-09-25 15:51
> To decide which one is valid, helpful would be if you could remember about how long you had to wait for Audacity to close when you ran my build. Was it about 10s? If it was, then hypothesis 1 is more likely, but we could verify it if you downloaded 3.5.1 from [fosshub](https://www.fosshub.com/Audacity-old.html) and tried again. If it was much more, then I also have to think much more :D

10 seconds sounds about right, I definitely know it was faster than 3.6.x versions. I am currently using 3.5.1 as my daily program until this issue gets resolved, and that usually takes 5 seconds or less to close.

**Comment by saintmatthieu** [comment] 2024-09-25 18:34
So the method that causes the delay hasn't been touched since 3.5.1 ...
Maybe it's now called more often?
I've added my logging patch onto 3.5.1, [build](https://github.com/saintmatthieu/audacity/actions/runs/11038922741) is in progress. I don't expect to see the same erratic behaviour since you're positive it's better on that release, but I don't have a better idea. If that doesn't bother you too much please use it about the same way you did with the previous test build and attach the result again.

**Comment by saintmatthieu** [comment] 2024-09-25 19:13
@Dan33185 also helpful could be to make a screen recording of you reproducing the problem. Alternatively we could organize a video call - saintmatthieu@gmail.com is my email, we'd take it from there.

**Comment by brettcl** [comment] 2024-09-25 20:27
Impressed by the analysis and energy of the devs working on this. Thank you.

I'm happy to do the testing as requested, but I first wanted to add a different data point that reflects my workflow, which seems very different from others reported here and different from the scenario mentioned by @saintmatthieu in which an effect is applied.

Again, I'm digitizing audio cassettes. The workflow is typically:
1. Set record and walkaway
2. Come back several hours later, stop recording. 
3. Delete very long blank section at end
4. Delete short section at beginning (before audio from tape starts)
5. Delete short section in middle (as recording stops and is flipped from side A to side B in original recording, either manually or by auto-reverse)
6. Export audio in WAV format. Update file name and simple meta data
7. Export audio in MP3 format (with previously-added meta data)
8. Quit without ever saving anything (other than exported audio).

I just tried a test with just over 24 hours of silence. I followed the exact workflow described above, deleting sections as if they were outside of a real recording at approximate the same places (i.e. deleted approx 1h36m --> 24h, then 0m00s --> 0m10s, then  47m15s --> 47m45s -- Note that the middle section is shifted left due to previous deletion at start). Then exported audio with simple metadata in WAV and MP3 as described above.

Finally, I then QUIT Audacity, chose the "No don't save", and saw the "Discarding undo/redo history". 

*** The discard took about 4m15s. ***

Again, I never saved anything except to export audio.

Would it be useful to do a similar test again using the upcoming new build with v2 logging patch?

**Comment by petersampsonaudacity** [comment] 2024-09-25 20:54
@brettcl 

>Again, I'm digitizing audio cassettes. The workflow is typically:
1. Set record and walkaway
2. Come back several hours later, stop recording. 
3. Delete very long blank section at end

You can set Audacity to record for  specific period of time bu using Timer Record - see:  https://manual.audacityteam.org/man/timer_record.html

**Comment by Dan33185** [comment] 2024-09-25 21:04
So I downloaded the 3.5.1 alpha build linked [here](https://github.com/audacity/audacity/issues/7382#issuecomment-2374876861), and did a screen recording, here are the results (It crashed upon closing and upon starting it again I was asked if I wanted to recover the project)

3.5.1 video:

https://github.com/user-attachments/assets/cc76585a-be18-4c75-988e-6dd28e3af149

3.5.1 DeleteCount:

[3.5.1 DeleteCount.log](https://github.com/user-attachments/files/17138557/3.5.1.DeleteCount.log)

But, downloading 3.6.4 for comparison sake, it actually seemed to skip the "Discarding undo/redo history" step, but it did get hung up on "Checkpointing" for 37 seconds. When I was using 3.6.4 before, I downloaded the installer version, just now I used the .zip version (I'm assuming the portable version?) and that seems to work fine.

3.6.4 video:

https://github.com/user-attachments/assets/23b89b36-dd17-4aa3-8b7a-9274c11da699

**Comment by saintmatthieu** [comment] 2024-09-26 16:09
Thanks to both @Dan33185 and @brettcl for your effort.
@Dan33185 I noticed that the `Delete()` method was actually never called on 3.5.1, but a change I did since while fixing another issue changed that. I'm sorry I missed that and it caused you so much bother.
So I reverted that change in this ticket's associated PR, which should bring back the behavior as you know it from 3..5.1. It would be great if you could test it early, to see it it really fixes it for you. [Build](https://github.com/audacity/audacity/actions/runs/11055992046) is ongoing.

**Comment by Dan33185** [comment] 2024-09-26 17:20
That build seems to be working as expected, I just edited an hour+ long 24-Bit file and it closed within a couple seconds.

**Comment by dozzzzer** [comment] 2024-09-27 09:54
Tested

**Closed** 2024-09-27 12:11 UTC
Labels: bug, regression, project file
