### ISSUE TITLE
Finnish Windows translation problem in the menus when language set to English

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#3794] opened 2022-10-10 15:29 UTC
### Bug description

This problem was reported by a forum user.

On a Finnish Windows system when the Audacity Language is changed to English, some Effects Menu remain in Finnish (Paul Licameli and Steve Daulton in particular) .

See the original report here: https://forum.audacityteam.org/viewtopic.php?p=456899#p456899

### Steps to reproduce

See https://forum.audacityteam.org/viewtopic.php?p=456899#p456899

### Expected behavior

Menus should be in English

### Actual behavior

Menus stay in Finnish

### Audacity Version

other

### Operating system

Windows

**Comment by JohnColket** [comment] 2022-10-10 18:37
The Original Forum poster has verified the problem still remains in 3.2.1, and mentioned the following menu items are affected:

Generate
- Pluck
- Risset Drum
- Rhythm track

Effect
- Clip fix
- Vocoder
- Vocal Reduction and Isolation
- Notch Filter

Tools
- Nyquist Plugin Installer
- Sample Data Import
- Sample Data Export
- Regular Interval Labels


Analyze
- Label Sounds
- Beat Finder

**Comment by LWinterberg** [comment] 2022-10-10 19:33
duplicate of https://github.com/audacity/audacity/issues/2764

**Closed by LWinterberg** 2022-10-10 19:33 UTC
Labels: bug, translation / i18n
