### ISSUE TITLE
AppImage version doesn't follow my system's GTK 3 theme

### ISSUE THREAD

**Issue by itaranto** [audacity/audacity#4481] opened 2023-04-02 20:27 UTC
### Bug description

The AppImage version doesn't follow my system's GTK theme.

These are my current settings:

```sh
> gsettings get org.gnome.desktop.interface gtk-theme
'Arc-Dark'
> gsettings get org.gnome.desktop.interface color-scheme
'prefer-dark'
```

After taking a look at the `apprun-hooks/linuxdeploy-plugin-gtk.sh` file inside the AppImage it looks like it *should* pick up *at least* my dark/light preference:

```bash
#! /usr/bin/env bash

gsettings get org.gnome.desktop.interface gtk-theme 2> /dev/null | grep -qi "dark" && GTK_THEME_VARIANT="dark" || GTK_THEME_VARIANT="light"
APPIMAGE_GTK_THEME="${APPIMAGE_GTK_THEME:-"Adwaita:$GTK_THEME_VARIANT"}" # Allow user to override theme (discouraged)

export APPDIR="${APPDIR:-"$(dirname "$(realpath "$0")")"}" # Workaround to run extracted AppImage
export GTK_DATA_PREFIX="$APPDIR"
export GTK_THEME="$APPIMAGE_GTK_THEME" # Custom themes are broken
export GDK_BACKEND=x11 # Crash with Wayland backend on Wayland
export XDG_DATA_DIRS="$APPDIR/usr/share:/usr/share:$XDG_DATA_DIRS" # g_get_system_data_dirs() from GLib
export GSETTINGS_SCHEMA_DIR="$APPDIR//usr/share/glib-2.0/schemas"
export GI_TYPELIB_PATH="$APPDIR//usr/lib/x86_64-linux-gnu/girepository-1.0"
export GDK_PIXBUF_MODULE_FILE="$APPDIR//usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache"
```

But it doesn't.

It seems it's checking for *both" the `gtk-theme` setting *and* the `GTK_THEME_VARIANT` environment variable.

So  I tried exporting `GTK_THEME_VARIANT=dark` too, but it doesn't work.

Setting `APPIMAGE_GTK_THEME=Arc-Dark` also doesn't work.

### Steps to reproduce

1. Run the AppImage version (`audacity-linux-3.2.5-x64.AppImage`)
2. Observe the GUI theme

### Expected behavior

My current GTK theme *or at least* my dark/light theme preference are applied.

### Actual behavior

My current GTK theme nor my dark/light theme preference are applied.

It looks like this:

![image](https://user-images.githubusercontent.com/11463919/229377275-c68457e2-d6f3-49b3-8348-b5c42eada623.png)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Additional context

Tested both with i3wm and Sway under Arch Linux.

**Comment by LWinterberg** [comment] 2023-04-02 22:59
This is a known limitation with the Appimage and is necessary to ensure compatibility with a wider range of distributions. Audacity 4.x won't be using GTK anymore, 

Duplicate of #3734

**Closed by LWinterberg** 2023-04-02 22:59 UTC
Labels: bug
