### ISSUE TITLE
Audacity locked up after accidentally creating a very small loop region.

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3316] opened 2022-07-29 15:05 UTC
**Describe the bug**
After accidentally catching the "L" key (probably), a single sample period was set as the loop region. I didn't notice until later when playing the track. When playback reached the loop region, Audacity froze with 100% CPU on one core.

**To Reproduce**
1. Select one sample
2. Press "L"
3. Press "Space"

**Actual behavior**
Audacity freezes with 100% CPU use on one core.

**Expected behavior**
Not to freeze.

**Screenshots**
If applicable, add screenshots/video to help explain your problem.

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version 3.2.0 AppImage

**Additional context**
Quick Play looping did not have this problem.

**Comment by petersampsonaudacity** [comment] 2022-07-29 15:39
Fails on W10 with the edge case of a single sample loop

But it works fine on W10 with 10 samples for the loop - however if while the loop is playing you contract the loop region to a single sample or less it goes doolally - technical term ;-) 

1) generate a 1 second chirp
2) set cursor to mid point 
3) zoom in to sample level
4) select 10 samples
5) Set loop to selection
6) turn looping on
7) Press Play
8) Observe it works fine
9) while it is looping contract the loop region in the timeline
10) Observe that at about 5 samples it stops playing
11) contract the loop region some more
12) Observe: as the loop region gets minimally small the playback goes doolally

The original issue and this corollary are undoubtedly edge cases - but they should be dealt with.

**Comment by petersampsonaudacity** [comment] 2022-07-29 15:52
Note too that if you have a real-life loop that you are adjusting you can drag the right loop edge to the left of the left edge and vice versa (expected behavior)

But if you line up the left and right  edges of a loop region so that they coincide then the loop region disappears altogether.  
a) Is this intended, designed, behavior?
b) is it desired behavior?

**Comment by LWinterberg** [comment] 2022-07-29 20:29
duplicate of known issue #2000

**Closed by LWinterberg** 2022-07-29 20:29 UTC
