### ISSUE TITLE
Sound generation: Cannot enter a duration

### ISSUE THREAD

**Issue by IMBJR** [audacity/audacity#4639] opened 2023-04-30 09:45 UTC
### Bug description

Attempting to generate a chirp, pluck, tone or noise fails as the user cannot enter a duration of the sound to generate.

### Steps to reproduce

1. Select Generate menu option.
2. Select Tone option.

### Expected behavior

Expected to be able to enter a duration for the sound to be generated.

### Actual behavior

The GUI has no field for entry of a duration:
![Screenshot_2023-04-27_19-06-14](https://user-images.githubusercontent.com/5891311/235346503-70ad66ec-7266-4341-a6d4-1a3aee0b3051.png)

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

This is under Arch Linux.

**Comment by petersampsonaudacity** [comment] 2023-04-30 10:00
Testing on W10 with 3.3.1

I cannot reproduce this on Windows - works fine there:
![image](https://user-images.githubusercontent.com/50205984/235347145-48d25811-80f6-4ee7-a4e2-405e29b1640d.png)

**Comment by TakuikaNinja** [comment] 2023-05-01 12:27
The Selection Toolbar also fails to display its values for the same reason. On top of that, opening a new window (the recent files menu consistently triggers this) will cause the Selection Toolbar to either disappear, or grow in size to the point of overlapping the audio tracks (shown below). 
I am on Arch Linux as well. 
![image](https://user-images.githubusercontent.com/43363447/235451278-9884ad1d-8eda-420e-bcf6-0e46a881115d.png)

**Comment by solsticedhiver** [comment] 2023-05-01 22:59
same here
![Capture d’écran du 2023-05-02 00-59-24](https://user-images.githubusercontent.com/105990/235545964-678819e4-e976-4d5a-91ad-2c1bd76d0c1f.png)

**Comment by solsticedhiver** [comment] 2023-05-02 22:02
seems ok now with 1:3.3.1-2 on arhclinux 
![Capture d’écran du 2023-05-03 00-02-28](https://user-images.githubusercontent.com/105990/235795607-d04ab956-8ccf-4350-9d6f-52ae0029ec17.png)

**Comment by Ryan-Miller-Audacity** [comment] 2023-05-04 12:39
Confirmed fixed in my Ubuntu VM via PR #4464. Duration field now properly displays within Generators. Sanity checked Windows and MacOS and confirmed no adverse behaviors.

**Closed** 2023-05-05 08:03 UTC
Labels: bug, Linux
