### ISSUE TITLE
The scale for the recording volume slider is badly wrong

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#3690] opened 2022-09-26 14:02 UTC
### Bug description

On default settings, the range of the recording volume slider is 60db.
This slider maps exactly onto the Windows volume slider for the device. A pointed out by "guzmann" on discord, the range of the Windows volume slider depends on the device. For example, the microphone in my webcam has a range of 24db, which is quite different from the range of 60db shown in Audacity.
I think it's very confusing for users that the scale is so inaccurate.

### Steps to reproduce

Change the recording volume slider by x db

### Expected behavior

The recorded volume reduces by x db

### Actual behavior

The recorded volume reduces by y db, where x and y are quite different.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Before the mixer and meter toolbars were merged, the recording volume slider had a scale 0 to 1.0, which is the same scale which is used by the Windows recording volume slider, by default.

**Comment by Ryan-Miller-Audacity** [comment] 2022-09-27 12:30
I agree it's quite confusing that the slider can be set in such a manner being effected by windows settings; however, I believe the real answer is just decoupling the windows recording setting and Audacity recording setting so that Audacity can independently set it's own recording values without interference from windows settings (as you would see in many common DAWs). We have talked about this in design meetings a few times. 

/cc @Tantacrul @LWinterberg

**Comment by crsib** [comment] 2022-09-27 12:41
I think users won't be happy with such a change at all.

**Comment by Tantacrul** [comment] 2022-09-27 16:03
I wonder about that. However, I think we can possibly get out of jail for free by providing a default 'Same as system' option, as well as the ability to manually adjust your mic settings.

Both Discord and Zoom do this and it's rather nice.

**Comment by crsib** [comment] 2022-09-27 16:13
On Windows Zoom adjusts system level for both input and output. Discord does the opposite, which is fun :-)

In any case - the problem is that after we have merged meter and slider - it is (is it?) expected that slider and meter are using the same scale, which is not the case currently. And while we can make it work for the output, it is not quite possible to do the same for the input now.

**Comment by Tantacrul** [comment] 2022-09-27 16:16
Well, we do need to discuss 'per track' input monitoring anyway, which will kill the recording meter on the top bar completely. I assert that this will solve all our problems 👀

**Comment by DavidBailes** [comment] 2022-09-28 09:05
> And while we can make it work for the output

Testing using Reaper with a loopback input, then at least on Windows, the scale of the output slider appears to be correct.

**Comment by SteveDaulton** [comment] 2022-10-19 16:51
Seems to be a similar issue to https://github.com/audacity/audacity/issues/3322

**Comment by petersampsonaudacity** [comment] 2022-11-09 11:52
@LWinterberg @dozzzzer 

is this not fixed by #3810 ??

**Comment by SteveDaulton** [comment] 2022-11-09 12:14
> @LWinterberg @dozzzzer
> 
> is this not fixed by #3810 ??

If anything, it is even more confusing now that the tool tip displays a "percentage" that disagrees with the "dB" scale (50% = -30 dB ???).

**Comment by petersampsonaudacity** [comment] 2022-11-09 13:16
> If anything, it is even more confusing now that the tool tip displays a "percentage" that disagrees with the "dB" scale (50% = -30 dB ???).

But the slider scales have **_never_** been in dB - for example in2.4.2  they were decimal fractions:
![image](https://user-images.githubusercontent.com/50205984/200840149-62e625b7-4556-4d21-affb-2e751e32ae8b.png)

**Comment by petersampsonaudacity** [comment] 2022-11-09 13:28
Even in DarkAudacity 2.3.2 where @JamesCrook  first tried incorporating the sliders with the meters and losing the mixer toolbar he had decimal fractions for the slider values.

He avoided the dB versus percentage/decimal fraction by removing the numbers and hence the dB in the meters:
![image](https://user-images.githubusercontent.com/50205984/200842494-ce75ecd4-4aa4-4a31-9244-09c7bf2759a1.png)

**Comment by Tantacrul** [comment] 2022-11-09 13:36
I've just tested it and I don't find it confusing at all. You get two different kinds of information and I they don't contradict each other.

If someone knows what dB is, they're not going to be confused by this, methinks.

**Comment by petersampsonaudacity** [comment] 2022-11-09 13:42
> If someone knows what dB is, they're not going to be confused by this, methinks.

@Tantacrul :  For my money, I'd adopt @JamesCrook 's DarkAudacity approach and do away with the numbers and the "dB" in the meters altogether.

**Comment by DavidBailes** [comment] 2022-11-09 14:08
> I've just tested it and I don't find the display of % values when moving the slider confusing at all.
> The user now has two different kinds of information available to them and they don't contradict each other.

By two kinds of information, do you mean the percentage value given in the tooltip, and value on the db scale of the meter?
On Windows:
- the percentage value is the same as the percentage value of the corresponding level slider provided by Windows in the sound dialog and other places. Note that this isn't a linear scale.
- the db scale of the meter does NOT give the correct value for the recording level in db.

**Comment by petersampsonaudacity** [comment] 2022-11-09 14:11
> * the db scale of the meter does NOT give the correct value for the recording level slider in db.

Another good reason, perhaps, for getting rid of the numbers on the meters.

**Comment by SteveDaulton** [comment] 2022-11-09 14:59
> If someone knows what dB is, they're not going to be confused by this, methinks.

Do you not think that this looks like the output level is set between -24 dB and -12 dB ?

![meters](https://user-images.githubusercontent.com/11681097/200864279-e4baac45-bd79-4d14-be7c-468dda4efb62.png)

**Comment by SteveDaulton** [comment] 2022-11-09 15:18
> @Tantacrul : For my money, I'd adopt @JamesCrook 's DarkAudacity approach and do away with the numbers and the "dB" in the meters altogether.

That would be a significant step backwards for "professional" users. There are good reasons why all other audio editors / DAWs display the meter scale. I've seen many user requests for better metering, but no requests for worse metering.

**Comment by Tantacrul** [comment] 2022-11-09 16:16
I think we should keep the dB range and do a few things to ultimately solve all of this:

- Make the readings more accurate
- Users can enable / disable dB range (potentially we disable it for horizontal view)
- We also make it dockable (vertically) on the right of the screen. In this instance, dB would be enabled by default
- Eventually make the mixer much more prominent and easy to show/hide, which will cater to the pros a little more

**Comment by petersampsonaudacity** [comment] 2022-11-09 17:49
> * Make the readings more accurate

The output readings seem to be accurate to me.

This is a 0.5 amplitude tone - on playback the  Playback meter shows -6dB
It says these two correspond in several places in the Manual.

![image](https://user-images.githubusercontent.com/50205984/200903399-5fefdf62-fd4b-4d99-a9e5-44842477a85b.png)

**Comment by DavidBailes** [comment] 2022-11-10 08:54
> > * Make the readings more accurate
> 
> The output readings seem to be accurate to me.

The problem is not with the values of the meters - it's with the value of the recording level slider (and the playback level slider in some cases).

**Comment by petersampsonaudacity** [comment] 2022-11-10 09:23
@DavidBailes  was that always the case with old deprecated Mixer Toolbar, 
or is this a regression introduced with the merging of the sliders on the meter toolbars?  

If it's a regression on which version is it so?

**Comment by DavidBailes** [comment] 2022-11-10 10:23
> @DavidBailes was that always the case with old deprecated Mixer Toolbar, or is this a regression introduced with the merging of the sliders on the meter toolbars?
> 
> If it's a regression on which version is it so?

It's a regression introduces with the merging of the sliders and the meters which first appeared in 3.2.0

**Comment by petersampsonaudacity** [comment] 2022-11-10 10:47
> Do you not think that this looks like the output level is set between -24 dB and -12 dB ?
![image](https://user-images.githubusercontent.com/50205984/201070208-a550fc39-90ef-4784-86c8-3b2deb35325d.png)

Possibibly but ...

The big problem is that the meter is on a dB scale and the slider is a linear scale.  If the Slider were also to be the same dB scale the given that -6db roughly corresponds to 50% volume _(I think I am correct in saying that - the Manual certainly says so)_ then the 50-100% volume control would take place in the last 10th or so of the meter surely.

**Comment by SteveDaulton** [comment] 2022-11-10 13:14
> The big problem is that the meter is on a dB scale and the slider is a linear scale.

The big problem is that **the slider and the scale are unrelated**, yet whenever we look at a control against a scale anywhere else (speedometer, clock, oven temperature control, audio amp volume, thermostatic radiator valve ...) the scale is always directly related to the control. This design goes against a design pattern that is omnipresent in the modern world.

**Comment by petersampsonaudacity** [comment] 2022-11-10 15:04
> (speedometer, clock, oven temperature control, audio amp volume, thermostatic radiator valve ...) the scale is always directly related to the control.

And these are always scaled linearly - they are never logarithmic (certainly all the ones I've ever had)

**Comment by Ryan-Miller-Audacity** [comment] 2023-05-23 16:10
After discussing this issue within the design team, we will not be moving forward with this issue for a few reasons but the TLDR; is: 

* The windows controller only goes to -24dB on some devices, which would bottom out the slider halfway across the default meter
* On some systems, we can't set the system mic volume anyway (this is always true for DirectSound)
* The long-term fix for this is to have the slider be client-side, so a -6dB is an actual 6dB reduction, and to not ever have a input slider affect system mic volume

**Closed by Ryan-Miller-Audacity** 2023-05-23 16:10 UTC
Labels: bug, P3, Won't fix
