### ISSUE TITLE
Benchmark test fails

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3387] opened 2022-08-17 14:35 UTC
### Bug description

Running the Benchmark tool fails.

### Steps to reproduce

1. "Tools menu > Run Benchmark"
2. Click the "Run" button.

### Expected behavior

The benchmark test to complete and give meaningful results.

### Actual behavior

```
Using 57260 chunks of 293 samples each, for a total of 32.0 MB.
Preparing...
Performing 100 edits...
Trial 0
Expected len 16777180, track len 33415771.
TEST FAILED!!!
Benchmark completed successfully.
```

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by LWinterberg** [comment] 2022-08-17 14:40
duplicate of #3364

**Closed by LWinterberg** 2022-08-17 14:40 UTC
Labels: bug
