### ISSUE TITLE
After some time, Audacity will begin playing past the end of selected audio

### ISSUE THREAD

**Issue by yeroca** [audacity/audacity#3940] opened 2022-11-15 06:22 UTC
### Bug description

Ordinarily, if I select some audio, and click Play, Audacity will only play the audio in the selected region.  However, I've noticed that at some point it will start playing past the end point of the selection, and after doing that once, it never goes back to stopping at the end of the selection again until I save the project, and restart Audacity.

I'm seeing this bug in Audacity 3.2.1 on Windows 10, but I've seen it many many times before in older releases as well.

### Steps to reproduce

I can't say exactly, because I see it only after using Audacity, editing some audio for a period of time.   That includes amplifying, copy/pasting, etc.

### Expected behavior

I expect that it will always stop playing at the end of the clip.

### Actual behavior

Continues playing past the end of a selection.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by Tantacrul** [comment] 2022-12-02 14:29
Could you possibly provide steps to reproduce this issue? I've tried quite a bit and have been unable to achieve the state you've described. I know the issue is intermittent, so I appreciate it might be tricky.

I'm going to close this for now - unless you can provide some steps. Perhaps you might experience it again and at that moment, will notice some specific details that might help us to get to the bottom of it. Without this info, this bug will likely just sit here forever.

Will reopen if we can get more info that allows us to reproduce.

**Closed by Tantacrul** 2022-12-02 14:29 UTC
Labels: bug

**Comment by DavidBailes** [comment] 2022-12-02 14:39
Possible cause: accidentally turn on looping, and any looping region is before the selection.

**Comment by yeroca** [comment] 2022-12-04 01:11
Thank you for your response on this bug report. If I see this behavior again, I'll be sure to check for a loop region.

**Comment by DavidBailes** [comment] 2022-12-04 10:10
> Thank you for your response on this bug report. If I see this behavior again, I'll be sure to check for a loop region.

Just to clarify, what you need to check is whether the loop button, which is just to the right of the record button, is pressed, ie is on.

**Comment by yeroca** [comment] 2022-12-04 10:12
Ah, I didn't know about that button. I was going to just check for a loop region being set.  Thanks again!
