### ISSUE TITLE
Crash on first run when disabling auto-update

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#4521] opened 2023-04-09 15:44 UTC
### Bug description

Audacity may crash on first run if attempting to disable auto-update.

### Steps to reproduce

1. Download the latest Windows alpha version ZIP and do a fresh install (or create a "Portable Settings" folder.
2. Launch Audacity.
3. In the notification pop-up, select the link to disable auto-update

### Expected behavior

Audacity's preferences to open, allowing auto-update to be disabled.

### Actual behavior

Audacity crashes.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

Considering past outcry regarding privacy issues, it looks very bad that Audacity crashes when attempting to opt-out of Audacity's phone home features.

**Comment by crsib** [comment] 2023-04-09 15:51
Most likely this is already fixed, fix will be merged Monday

**Comment by crsib** [comment] 2023-04-09 15:53
Rereading the bug, it is definitely fixed. Closing as a duplicate of #4506

**Closed by crsib** 2023-04-09 15:53 UTC
Labels: bug
