### ISSUE TITLE
Can no longer “Export selection”

### ISSUE THREAD

**Issue by JapanYoshi** [audacity/audacity#5730] opened 2023-12-01 07:09 UTC
### Bug description

Prior to 3.4, I separated my recordings into clips, selected what I need, and exported the selection into individual WAV files as needed.

I can no longer do this because of the new (IMO unnecessarily) bespoke export dialog that doesn’t remember the last place and file name that I exported to.

### Steps to reproduce

1. Open or start any project in Audacity
2. Make sure there is some audio to export
3. Select a range
4. Try to export the selected audio

### Expected behavior

The system file picker should appear and offer to export the selection immediately upon selecting “Export selection” (or using your own hotkey assigned to it).

### Actual behavior

A bespoke file picker appears that forgets my settings.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by LWinterberg** [comment] 2023-12-01 08:08
Duplicate of #5581

**Closed by LWinterberg** 2023-12-01 08:08 UTC
Labels: bug
