### ISSUE TITLE
remove "Preferences: Playback: Vari-speed Play" option

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#2586] opened 2022-02-23 13:47 UTC
This is the documentation for this option in the manual:

Vari-Speed Play: With this checked, the speed of [Play-at-Speed](https://alphamanual.audacityteam.org/man/Play-at-Speed_Toolbar) can be varied dynamically as you play audio. However skipping and seeking using the left-arrow and right-arrow keyboard keys is disabled. The default setting is "on".
With Vari-Speed Play turned "on", some machines may experience clicky playback if you have extremely low setting for you buffer size (less than 20 ms or 30ms if you are using the default MME host on Windows).

As of Audacity 3.1.0, seeking using left/right arrows is not disabled when this option is on.
Given this, does this option still need to exist?

**Comment by LWinterberg** [comment] 2022-03-15 09:13
yeah, I think this option can just be removed

**Comment by MridulTi** [comment] 2022-03-20 12:20
Has somebody else been assigned to this?
If not then I will ask you to kindly assigned this to me.

**Comment by LWinterberg** [comment] 2022-03-20 17:23
@MridulTi go ahead!

**Comment by MridulTi** [comment] 2022-03-21 03:09
I have created a pull request for you to check 
namely "Remove Vari-Speed_Play from PlaybackPrefs.cpp"

**Closed** 2023-01-24 16:12 UTC
Labels: Enhancement Request, feature tweak

**Comment by LWinterberg** [comment] 2023-01-24 16:15
verified and merged

**Comment by petersampsonaudacity** [comment] 2023-01-24 18:40
Testing on W10 with latest alpha:  audacity-win-3.3.0-alpha-20230124+fcd5758-x64-msvc2022

This is now fixed

a)  The preference is removed from Playback prefs

b) The behavior is effectively always "on" i.e. Vari-speed play can always be changed dynamically during Vari-speed playback

c) the left/right skip arrows work as intended.

**Comment by petersampsonaudacity** [comment] 2023-01-24 18:40
I have updated the Reference Manual for this change:

https://alphamanual.audacityteam.org/man/Playback_Preferences
