### ISSUE TITLE
Crash closing project while x42 dialog is open (macOS)

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#4062] opened 2022-12-13 12:07 UTC
### Steps to reproduce

1. Make or open a project with an x42 plug-in in the sidebar (I tried x42-dpl mono)
2. Open the sidebar and the dialog (fancy native UI)
3. Command+W to close the project OR Command+Q to close the program

Kaboom

But -- no crash if you first close the dialog, then close the project.

### Expected behavior

Don't crash, silly boy

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

**Comment by dozzzzer** [comment] 2022-12-13 12:39
I've failed to reproduce it with 4 different x42 plugins on my macOS M1 machine

**Comment by Paul-Licameli** [comment] 2022-12-13 15:26
I'm getting this crash reliably in debug builds on an Intel Macbook.

The problem involves memory overwrites, so it is understandable that symptoms might vary with the build.

**Comment by Paul-Licameli** [comment] 2022-12-13 16:29
When I make a Release build for Intel Mac, I also reproduce this problem easily

**Comment by Ryan-Miller-Audacity** [comment] 2022-12-14 12:32
I was able to reproduce this on my M1 Macbook in the Audacity 3.2.2 release build (downloaded from audacityteam.org) using the dpl plugin as Paul noted. 

I have a intel mac as well, but I haven't been able to hunt down the charger for it to test there as well. 

Here is the sentry report that is collected when I observe the crash: https://sentry.audacityteam.org/share/issue/1eed6e8dfba641d8a06ee90471078167/

**Comment by Paul-Licameli** [comment] 2022-12-14 14:12
The call stack is unhelpful.  I think the buggy plug-in smashes some memory because of a dangling pointer, but the crash happens at a later point.

There is a known way to compensate for this and prevent the crash, but at the expense of memory leaks.

**Comment by Ryan-Miller-Audacity** [comment] 2022-12-22 13:56
Confirmed no longer receiving a crash dialog when closing project with x42 plugins open. Program closes as normal, no recovery dialog offered when opening again either.

**Comment by Paul-Licameli** [comment] 2023-01-10 12:50
I reopen this because the quick fix that was in 3.2.3 was a compromise that introduced memory leaks.  A better but more complicated fix that does not have a memory leak is pending review.

**Comment by dozzzzer** [comment] 2023-08-31 10:45
The issue is no longer reproducible

**Closed by dozzzzer** 2023-08-31 10:45 UTC
Labels: bug, P1, crash / freeze
