### ISSUE TITLE
Mac: Updater for Apple Silicon version downloads x86_64 version

### ISSUE THREAD

**Issue by codeman38** [audacity/audacity#4036] opened 2022-12-07 20:42 UTC
### Steps to reproduce

1. Install the arm64 version of Audacity 3.2.1 on macOS.
2. Go to Help &rarr; Check for Updates.
3. Click "Install Update".

### Expected behavior

audacity-macOS-3.2.2-arm64.dmg is downloaded.

### Actual behavior

audacity-macOS-3.2.2-x86_64.dmg is downloaded.

### Audacity Version

3.2.1 / 3.2.2

### Operating system

macOS

**Comment by dozzzzer** [comment] 2022-12-08 10:39
I was able to reproduce it on my machine

**Comment by dozzzzer** [comment] 2022-12-09 13:10
Closing as not planned at the moment.
It's hard to detect in a reliable way, which architecture the user has. So there will always be a chance that the wrong architecture package will be downloaded. In the future, when we move from _x86_64/arm64_ packages and instead provide a single _universal_ build, this problem will no longer exist.

**Closed by dozzzzer** 2022-12-09 13:10 UTC
Labels: bug, P2, macOS

**Comment by gnaservicesinc** [comment] 2022-12-13 21:07
If you are currently on the M1 version, there is nothing to detect, it's M1 so just get that one, that can easily be implemented without having to detect anything about the system. 

It would actually probably be fine to leave it at that and just follow what people already have. X86 version updates to X86 and M1 version updates to M1 with no architecture detection needed.  A simple preprocessor to record if the build is M1 or X86 at build time would be 100% reliable for that.

If you did want to get fancy and detect when someone is on the X86 version but on an M1 (so running under Rosetta), apple provides a way to programmatically determine when a process is running under Rosetta translation, "call the sysctlbyname function with the sysctl.proc_translated flag, as shown in the following example. The example function returns the value 0 for a native process, 1 for a translated process, and -1 when an error occurs.

int processIsTranslated() {
   int ret = 0;
   size_t size = sizeof(ret);
   if (sysctlbyname("sysctl.proc_translated", &ret, &size, NULL, 0) == -1) 
   {
      if (errno == ENOENT)
         return 0;
      return -1;
   }
   return ret;
}
"
source:
https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment

I mention this because while a universal build may be apple's preferred answer, for those of us, one an M1 with limited disk space, it is not an appreciated answer.  It wastes space by including two versions of the program.

**Comment by crsib** [comment] 2022-12-13 21:33
The initial plan was to distribute universal binary, which changed very late in the development cycle. This is why the update XML was not extended to support different architectures for macOS. This issue was unfortunately overlooked, and it is somewhat too late to fix it now. 

Starting from 3.2.3 the universal binary will be shipped as the update, so the problem will somewhat go away.
