### ISSUE TITLE
VST2 effects not shown in add effect menu of 3.2.2, if effect registered using 3.2.1

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#4039] opened 2022-12-08 12:21 UTC
### Bug description

The VST effects are not shown in the add effect menu of 3.2.2 if they have been registered with 3.2.1. They are shown if registered with 3.2.2, so this only affects those who are upgrading, and have previously installed VST plugins.

### Steps to reproduce

Using portable versions of 3.2.1 and 3.2.2 with a portable settings folder created in the same folder as the audacity executable in each of these versions.

1. If not already installed, intall the reaplugs plugins, which are VST.
2. Run 3.2.1 so that the plugins are registered, and then close it.
3. Copy the contents of 3.2.1 portable settings folder to the empty 3.2.2 portable settings folder.
4. Run 3.2.2, and press the add effect button in the realtime effects pane. A menu opens.

### Expected behavior

vst2 effects appear in the menu

### Actual behavior

vst2 effects don't appear in the menu

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

Noticed this in the context of a problem with a vst3 plugin, and wanted to check if there was a problem with the vst2 plugin, but it was not available in the menu.

If you delete the config files for plugins, the vst2 effects then appear in the menu.

**Comment by dozzzzer** [comment] 2022-12-08 12:29
I wasn't able to reproduce this on my Windows 11 machine

**Comment by LWinterberg** [comment] 2022-12-08 12:30
could not reproduce - after starting audacity after the upgrade, the plugin scan found and enabled VST2 plugins as expected

**Comment by DavidBailes** [comment] 2022-12-08 12:42
> could not reproduce - after starting audacity after the upgrade, the plugin scan found and enabled VST2 plugins as expected

These are my observations. The vst2 plugins which were installed prior to the upgrade are shown and enabled in the plugin manager, appear on the Effects menu, but don't appear on the add effect menu.

**Comment by LWinterberg** [comment] 2022-12-08 12:51
yes. They show up in the realtime effect menu, 
![image](https://user-images.githubusercontent.com/87814144/206451077-f833035e-9874-4515-8e6d-0811bbaf0764.png)

**Comment by DavidBailes** [comment] 2022-12-08 13:12
> yes. They show up in the realtime effect menu,

This is puzzling, I don't get the reaplugs appearing in the add effect menu. I confirmed this finding using the following steps.
1. The reaplugs plugins have already been installed.
2. I'm using portable versions of 3.2.1 and 3.2.2, both with portable settings folders.
3. Run 3.2.1 and close it.
4. Copy the contents of 3.2.1 portable settings folder to the empty 3.2.2 portable settings folder.
5. Run 3.2.2. The add effect menu does not contain the reaplugs plugins (unlike your screenshot).

**Comment by DavidBailes** [comment] 2022-12-08 18:39
Had a quick look at the code. My tentative conclusion is the whether a plugin can do "realtime" is determined by the version of audacity which registered the plugin, not the current version. If so, this is clearly incorrect, and hence the bug (which can't be reproduced).

**Comment by DavidBailes** [comment] 2022-12-09 08:00
> Had a quick look at the code. My tentative conclusion is the whether a plugin can do "realtime" is determined by the version of audacity which registered the plugin, not the current version. If so, this is clearly incorrect, and hence the bug (which currently hasn't been reproduced by anyone but me).

@Paul-Licameli @crsib Is my understanding of this correct?

**Comment by petersampsonaudacity** [comment] 2022-12-09 14:52
See also:  VST2: Crash when applying Reacomp after upgrade from 3.1.3 to 3.2.2 #4046

**Comment by DavidBailes** [comment] 2022-12-10 09:38
> I wasn't able to reproduce this on my Windows 11 machine

@dozzzzer . I've updated the steps to reproduce to make things clearer. Could you please retest using these steps?

**Comment by LWinterberg** [comment] 2023-03-10 15:02
given the easy workaround (regenerate the list via rescan plugins), this won't be fixed

**Closed by LWinterberg** 2023-03-10 15:02 UTC
Labels: bug, Won't fix, plugins
