### ISSUE TITLE
Pasting into a new track moves clips in other tracks

### ISSUE THREAD

**Issue by billw58** [audacity/audacity#7293] opened 2024-09-09 17:41 UTC
### Steps to reproduce

1. Start Audacity 3.6.2
2. Tracks Behaviors > [X] Editing a clip can move other clips
3. Generate something
4. Cut it into a few clips
5. Select a range and Copy
6. New Audio Track
7. Click somewhere in the new track
8. Paste

### Expected behavior

The clip is pasted into the new track and the audio in the first track does not move.

### Actual behavior

Clips in the first track move.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS (Peter: and Windows)

### Additional context

Version 3.6.1 behaves properly. To see this happen you need to cut the first track into clips and there needs to be clips (in the first track) to the right of the insert point.

**Comment by DavidBailes** [comment] 2024-09-09 18:30
> To see this happen you need to cut the first track into clips and there needs to be clips (in the first track) to the right of the insert point.

Alternatively, just create one clip in the first track, and move it to the right. Position the edit cursor in the second track before the start of the clip in the first track.

**Comment by LWinterberg** [comment] 2024-09-09 18:36
yes, this setting essentially is a global ripple (as opposed to per-track ripple) now. Where did you run into this issue, bill?

**Comment by DavidBailes** [comment] 2024-09-09 20:02
> yes, this setting essentially is a global ripple (as opposed to per-track ripple) now.

The setting is a global ripple for pasting, but per track for all other operations, such a delete, cut, generate a clip.
Very confusing for users.

**Comment by billw58** [comment] 2024-09-09 20:42
> Where did you run into this issue, bill?
Actually I was testing for something else. I was surprised when it happened because Audacity never did this before.
If this is a deliberate change, I think it's a mistake.
What uses cases were you thinking of when you made this change?
I'm sure I could come up with workflows or use cases where the user want clips to move when editing in a track, but doesn't want clips in other tracks to move when editing in a different track.

**Comment by billw58** [comment] 2024-09-09 21:48
Is this the fix for Issue #7146 ?
If I understand correctly (looking at your video), you want tracks to ripple where there is a selection in multiple tracks even though the paste happens in one track. But what about the case where there is a selection in only one track?

**Comment by DavidBailes** [comment] 2024-09-10 14:47
> Testing on W10 shows that this is a regression on 3.6.1 ad all earlier versions of Audacity - and thus unexpected behavior for the experienced user
> 
> _@DavidBailes and that is why it is currently undocumented. If it remains as a new ripple "feature" rather than a "bug" then it should be documented. But for my money this is a true bug, a regression bug._

@petersampsonaudacity .
My understanding is that this new behaviour was intended. In description of this commit: https://github.com/audacity/audacity/pull/7146, it says:
"Paste behaviour change: when pasting all clips and labels to the right from the beginning of selection intrval should move accordingly, if sync lock disabled and "...clips can move" option is enabled"

Whether you think that it's a good idea to change the setting in preferences to be ripple edit over all the tracks, rather than per track, the current state is ripple edit over all tracks for pasting and ripple edit per track for all other relevant actions. This is not at all user friendly.

Eg. Start with a couple of clips in a couple of tracks:
![image](https://github.com/user-attachments/assets/69e7f4d2-691b-4a2e-b2e9-3a019c2e0826)

Copy either of the clips, place the cursor in the second track before the start of the clip and paste:
![image](https://github.com/user-attachments/assets/e6afda2c-ca62-4199-b93c-40b961f03e5c)

Cut the first clip in the second track:
![image](https://github.com/user-attachments/assets/9748e858-071e-462e-b91d-f6f494b42218)

Would a user expect that to be the result?

**Comment by billw58** [comment] 2024-09-12 22:35
If the global ripple on pasting into a track is going to remain, could we add "Editing a clip can move other clips" to the track context menu for easy access? I have a feeling a lot of users will now want to switch between the two behaviours depending on what they're trying to do. A trip to Preferences every time would get frustrating pretty quickly.

**Comment by SteveDaulton** [comment] 2024-09-25 11:28
> yes, this setting essentially is a global ripple (as opposed to per-track ripple) now. Where did you run into this issue, bill?

Is this intentional or a bug?

If it is intentional, how do I disable global ripple and enable per-track ripple editing? (I assume that the team appreciates why per-track ripple is essential to many users).

**Comment by petersampsonaudacity** [comment] 2024-09-26 08:41
@LWinterberg @Tantacrul

Perhaps we need a new preference to turn "gobal rippling" on and off.

A setting that is independent of the "editing a clip can move other clips" setting in Tracks Behaviors preferences.

**Comment by DavidBailes** [comment] 2024-09-26 08:47
> Perhaps we need a new preference to turn "gobal rippling" on and off.

The present behaviour is a mixture of global and per track ripple which not what the user would expect, and will lead to unexpected changes to the user's project.

@dozzzzer . I think that the current behaviour is a bug, and needs to be fixed.

**Comment by billw58** [comment] 2024-09-26 14:51
If the user wants "global ripple" on paste they should turn on sync-lock. What it does now is silly.

**Comment by petersampsonaudacity** [comment] 2024-09-28 09:04
And from today this confused Forum poster troubled by this global ripple change:

https://forum.audacityteam.org/t/confusing-changes-in-update/119078

**Comment by DavidBailes** [comment] 2024-09-28 14:31
Issue raised on r/audacity:
https://www.reddit.com/r/audacity/comments/1fp0orx/pasting_a_clip_moves_other_tracks/

**Comment by petersampsonaudacity** [comment] 2024-09-29 10:37
And another Forum user complaint re global rippling today:

https://forum.audacityteam.org/t/copy-paste-bug-adds-dead-space-to-all-other-tracks/119170

**Comment by petersampsonaudacity** [comment] 2024-09-29 10:59
@billw58  wrote

> If the user wants "global ripple" on paste they should turn on sync-lock. 

@LWinterberg @Tantacrul @dozzzzer 
I have been testing on earlier versions of Audacity and with "Editing a clip can move other clips" is turned on and Sync-locking is turned on too, then indeed global rippling occurs on paste.

Note, however, that this only applies to the Sync-Locked Track Group that the track that is being pasted into belongs too.  It is quite possible to have multiple SLTGs each defined by having a label track beneath it.  So it is only with a single SLTG that one gets the global ripple - with multiple STLGs it is an SLTG ripple.

**Comment by billw58** [comment] 2024-09-29 14:22
I think it makes sense for "global ripple" to happen only within a sync-locked track group. The uses has specifically set up the project so the one group is sync-locked and other tracks are not.
With sync-lock on, when a clip is pasted in a track and the start of that clip is in the middle of other clips, those other clips are _split_ to maintain sync. With the current global ripple and sync-lock off, the overlapping clips are simply _moved forward_, not split, which doesn't make sense to me.

**Comment by SteveDaulton** [comment] 2024-09-29 20:54
> The setting is a global ripple for pasting, but per track for all other operations, such a delete, cut, generate a clip.
> Very confusing for users, and undocumented.

I think this is a very important observation. Not only is it an unexpected, unrequested and unannounced break  from a commonly used and longstanding behaviour, it is also highly inconsistent.

I think I can guess why this new behaviour has been implemented, but I don't see why we need two different forms of "global ripple". If the new behaviour has some benefit over "Sync-Lock", then perhaps Sync-Lock could be extended, or in some other way consolidate Sync-Lock and Global Ripple in a way that does not penalise end users that rely on previous functionality.

**Comment by dozzzzer** [comment] 2024-09-30 13:35
@DavidBailes @billw58 This will be fixed soon and delivered in the next release.

**Comment by petersampsonaudacity** [comment] 2024-09-30 15:19
> This will be fixed soon and delivered in the next release.

@dozzzzer  - fixed in what way please, can you clarify?

**Comment by dozzzzer** [comment] 2024-09-30 17:43
@petersampsonaudacity 

> Expected behavior
> The clip is pasted into the new track and the audio in the first track does not move.

**Comment by petersampsonaudacity** [comment] 2024-09-30 22:17
@dozzzzer 

it's not just the first track ,in a multi-track project right now with 3.5.4 ALL the other tracks move with the global-ripple

**Comment by DavidBailes** [comment] 2024-10-01 08:25
> it's not just the first track ,in a multi-track project right now with 3.5.4 ALL the other tracks move with the global-ripple

The expected behaviour quoted by @dozzzzer is for the STR, where there are only two tracks.

**Comment by billw58** [comment] 2024-10-01 15:02
To add to Peter's comment, I think what we're asking for is a return to the pre-3.6.2 behavior, where there is no global ripple when pasting into a track and sync-lock is not enabled. The comments on the Forum speak for themselves.

**Comment by petersampsonaudacity** [comment] 2024-10-02 11:09
Testing on W10 with @DavidBailes 's test branch build for this:  audacity-win-3.7.0-alpha-20241002+ea208cf-x64

This appears to have properly restored to the 3.6.1 and earlier behavior, before this regression occurred.

1. With "Editing a clip can move other clips" turned off (default) with insufficient space fore the paste, it is blocked with an appropriate error message.

2. With "Editing a clip can move other clips" turned on and sync-locking turned OFF the a past ripple only occurs in the track that is being pasted into.

3. With "Editing a clip can move other clips" turned on and sync-locking turned ON then a past ripple occurs in all tacks in the  Sync-Locked Track Group (SLTG) that the track that is being pasted into belongs.  No other SLTG in the project experiences the ripple.

_@billw58 @SteveDaulton @dozzzzer  - perhaps you can check that this is now the "correct" behavior, i.e. the pre 3.6.2 behavior?_

**Comment by dozzzzer** [comment] 2024-10-02 14:47
I've tried it out and it looks correct to me.

**Comment by Tantacrul** [comment] 2024-10-02 22:41
As @dozzzzer implied earlier. We didn't intentionally introduce 'global' ripple. It was a bug. Once we found out about it, we popped it at the top of the priority list.

**Comment by DavidBailes** [comment] 2024-10-03 08:02
> As @dozzzzer implied earlier. We didn't intentionally introduce 'global' ripple. It was a bug. Once we found out about it, we popped it at the top of the priority list.

@Tantacrul . Just for the record, it can be seen from the commit message and the code, the PR https://github.com/audacity/audacity/pull/7146 intentionally introduced global ripple.

**Comment by DavidBailes** [comment] 2024-10-03 08:04
Please note that the PR I have submitted to fix this issue will cause the reintroduction of the issue: https://github.com/audacity/audacity/issues/7124

**Comment by DavidBailes** [comment] 2024-10-03 10:04
I've submitted another PR which doesn't also reintroduce issue: https://github.com/audacity/audacity/issues/7124

**Comment by petersampsonaudacity** [comment] 2024-10-03 15:48
Testing on W10 with @DavidBailes 's revisedtest branch build for this:  audacity-win-3.7.0-alpha-20241003+1c7e683-x64

This also appears to have properly restored to the 3.6.1 and earlier behavior, before this regression occurred.

1. With "**Editing a clip can move other clips**" turned **off** (default) with insufficient space fore the paste, it is blocked with an appropriate error message.

2. With "**Editing a clip can move other clips**" turned **on** and **sync-locking** turned **OFF** the a paste ripple only occurs in the track that is being pasted into.

3. With "**Editing a clip can move other clips**" turned **on** and **sync-locking** turned **ON** then a paste ripple occurs in all tracks in the  Sync-Locked Track Group (SLTG) that the track that is being pasted into belongs.  No other SLTG in the project experiences the ripple.  This is what sync-locking is for.

AND

4. This does **_NOT_** reintroduce issue #7124

**Closed** 2024-10-07 08:31 UTC
Labels: bug, regression, Tracks

**Comment by LgnGithub** [comment] 2025-03-20 20:41
> [@DavidBailes](https://github.com/DavidBailes) [@billw58](https://github.com/billw58) This will be fixed soon and delivered in the next release.

Still not fixed. I paste a clip on a track and it pastes on track below it.

**Comment by Tantacrul** [comment] 2025-03-20 21:11
@LgnGithub can you share a video or share screenshots with an explanation so we can see the steps, please? It's possible we fixed one aspect and missed another.

@LWinterberg fyi. We may need to reopen
