### ISSUE TITLE
Audio devices (sinks/sources) only exist when actively playing / recording

### ISSUE THREAD

**Issue by majenkotech** [audacity/audacity#4476] opened 2023-03-31 10:50 UTC
### Bug description

In Linux the playback and record endpoints in jack / pipewire etc only exist while actively playing or recording audio. This makes it impossible to do manual audio routing in `qpwgraph` or `qjackctl`, and you can only ever connect audio to whatever physical devices Audacity happens to think you have (which itself isn't always correct).

### Steps to reproduce

Use Linux and try and route audio...

### Expected behavior

The devices should be created at the start (or at any reconfiguration time) and remain until the project or program is closed. (Look at Ardour for an example of how it *should* be handled)

### Actual behavior

The devices come and go at will never letting you set up any routing.

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

**Comment by LWinterberg** [comment] 2023-03-31 11:05
Duplicate of #711

**Closed by LWinterberg** 2023-03-31 11:05 UTC
Labels: bug
