### ISSUE TITLE
Misbehavior of alignment with sync-locked labels

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#4942] opened 2023-07-22 14:16 UTC
### Bug description

Tracks > Align Tracks > various commands don't treat label tracks properly

### Steps to reproduce

Try this with and without sync lock:

1. Make some sound starting at time 0
2. Import some MIDI starting at time 10 (approximately)
3. make a label track with at least one region label starting at 20, maybe more labels; either below or between the tracks
4. Select all
5. Use one of the Tracks > Align commands and observe

### Expected behavior

a. Label tracks are ignored when decided how far anything moves
b. Label tracks  should not change when there is no sync lock
c. A label track should move with the track immediately above it when there is sync lock

### Actual behavior

a. correct
b. correct
c. sync lock applies only when not aligning end-to-end or together; when it does apply, it shifts labels wrongly (sometimes off screen into negative time)

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by DavidBailes** [comment] 2023-07-22 14:35
> ### Actual behavior
> a. End to End does nothing to the label track b. Average is computed as 5 and the track doesn't move
> b. Average is computed as 5 and the track doesn't move

I think this is by design. Quote from manual page: https://manual.audacityteam.org/man/tracks_menu_align_tracks.html

"When aligning end to end or aligning together, the tracks are always moved individually to enforce the requested alignment (as described below). Label tracks are not affected by these two commands."

What would be the use case of the expected behaviour that you describe?

**Comment by Paul-Licameli** [comment] 2023-07-22 16:41
> > ### Actual behavior
> > a. End to End does nothing to the label track b. Average is computed as 5 and the track doesn't move
> > b. Average is computed as 5 and the track doesn't move
> 
> I think this is by design. Quote from manual page: https://manual.audacityteam.org/man/tracks_menu_align_tracks.html
> 
> "When aligning end to end or aligning together, the tracks are always moved individually to enforce the requested alignment (as described below). Label tracks are not affected by these two commands."
> 
> What would be the use case of the expected behaviour that you describe?

Well, let's debate.  Maybe a. and b. can stand.  However, plainly the other symptoms don't reflect any good design.

Do you think label tracks should be simply not counted in the averaging and not affected at all by alignment?

In the course of my refactorings, I am discovering that Tracks distinguish "Offset" and "Start time" but just what this means isn't explained and `LabelTrack::SetOffset` is the cause of the weird last cases.  The argument of that virtual function is treated as an absolute time in other overrrides but as relative in LabelTrack.

This is something I want to clean up, and to do it, we need to agree just what Align commands should do with label tracks.

We must also consider just what should happen when there is sync lock, which might affect label tracks.  As it is written now, sync lock state is ignored when aligning tracks end-to-end or aligning together (which averages start times).  All other choices move all the selected tracks by a common distance and the intention appears to be, to move the sync-locked tracks the same distance, but again that is implemented wrongly in `LabelTrack::SetOffset`.

**Comment by petersampsonaudacity** [comment] 2023-07-23 15:56
Label tracks are difficult little critters to manage in this regard as there is no way of telling to which particular track, in a multi-track use case, they belong to and may thus require retaining alignment with that track.

So in many ways it may be best that label tracks are never affected by any Align Tracks commands.

This is why folks (and Koz in particular) have long been asking for markers on the waveform tracks themselves (as is the case in many video editors)

**Comment by DavidBailes** [comment] 2023-07-24 09:10
> > > ### Actual behavior
> > > a. End to End does nothing to the label track b. Average is computed as 5 and the track doesn't move
> > > b. Average is computed as 5 and the track doesn't move
> > 
> > 
> > I think this is by design. Quote from manual page: https://manual.audacityteam.org/man/tracks_menu_align_tracks.html
> > "When aligning end to end or aligning together, the tracks are always moved individually to enforce the requested alignment (as described below). Label tracks are not affected by these two commands."
> > What would be the use case of the expected behaviour that you describe?
> 
> Well, let's debate. Maybe a. and b. can stand. However, plainly the other symptoms don't reflect any good design.
> 
> Do you think label tracks should be simply not counted in the averaging and not affected at all by alignment?

I think that label tracks should be unaffected by the align together and align end to end commands because I can't think of any cases where the user would want them to be included in these commands.

However, for all the other alignment commands, all the selected tracks are time shifted by the same amount, and so it is useful for any label tracks to be also time shifted, which is the current behaviour (apart from the bug which you have found if only one or more label tracks are selected).

> 
> In the course of my refactorings, I am discovering that Tracks distinguish "Offset" and "Start time" but just what this means isn't explained and `LabelTrack::SetOffset` is the cause of the weird last cases. The argument of that virtual function is treated as an absolute time in other overrrides but as relative in LabelTrack.

I too couldn't work out why there was both Offset and start time and why they are different for label tracks when I was writing this PR: https://github.com/audacity/audacity/pull/4647

> 
> This is something I want to clean up, and to do it, we need to agree just what Align commands should do with label tracks.
> 
> We must also consider just what should happen when there is sync lock, which might affect label tracks. As it is written now, sync lock state is ignored when aligning tracks end-to-end or aligning together (which averages start times).

For these two commands, I think that sync lock should be ignored, as is the current behavior. What would the command do if it wasn't ignored?!

> All other choices move all the selected tracks by a common distance and the intention appears to be, to move the sync-locked tracks the same distance, but again that is implemented wrongly in `LabelTrack::SetOffset`.

That seems to be the right thing to do, apart from bug when only label tracks are selected.

**Comment by Paul-Licameli** [comment] 2023-07-24 10:27
> > > > ### Actual behavior
> > > > a. End to End does nothing to the label track b. Average is computed as 5 and the track doesn't move
> > > > b. Average is computed as 5 and the track doesn't move
> > > 
> > > 
> > > I think this is by design. Quote from manual page: https://manual.audacityteam.org/man/tracks_menu_align_tracks.html
> > > "When aligning end to end or aligning together, the tracks are always moved individually to enforce the requested alignment (as described below). Label tracks are not affected by these two commands."
> > > What would be the use case of the expected behaviour that you describe?
> > 
> > 
> > Well, let's debate. Maybe a. and b. can stand. However, plainly the other symptoms don't reflect any good design.
> > Do you think label tracks should be simply not counted in the averaging and not affected at all by alignment?
> 
> I think that label tracks should be unaffected by the align together and align end to end commands because I can't think of any cases where the user would want them to be included in these commands.
> 
> However, for all the other alignment commands, all the selected tracks are time shifted by the same amount, and so it is useful for any label tracks to be also time shifted, which is the current behaviour (apart from the bug which you have found if only one or more label tracks are selected).
> 
> > In the course of my refactorings, I am discovering that Tracks distinguish "Offset" and "Start time" but just what this means isn't explained and `LabelTrack::SetOffset` is the cause of the weird last cases. The argument of that virtual function is treated as an absolute time in other overrrides but as relative in LabelTrack.
> 
> I too couldn't work out why there was both Offset and start time and why they are different for label tracks when I was writing this PR: #4647
> 
> > This is something I want to clean up, and to do it, we need to agree just what Align commands should do with label tracks.
> > We must also consider just what should happen when there is sync lock, which might affect label tracks. As it is written now, sync lock state is ignored when aligning tracks end-to-end or aligning together (which averages start times).
> 
> For these two commands, I think that sync lock should be ignored, as is the current behavior. What would the command do if it wasn't ignored?!
> 
> > All other choices move all the selected tracks by a common distance and the intention appears to be, to move the sync-locked tracks the same distance, but again that is implemented wrongly in `LabelTrack::SetOffset`.
> 
> That seems to be the right thing to do, apart from bug when only label tracks are selected.

Something should be done for sync-lock.

Maybe something better could be done even in the aligning together or end to end cases.

Suppose I have a wave track, label track, wave track, and label track.  Suppose I select all and align end to end or together.

Now, nothing happens to the label tracks.

I think better would be, that the label tracks shift by different amounts, but each keeping synched to the track just above it.

But the labels do not affect the calculation of how far the wave tracks move.

**Comment by Paul-Licameli** [comment] 2023-07-24 11:28
I just read something more closely.  Label tracks are indeed ignored now, when determining how far to shift, because in `DoAlign` the track ranges are filtered by type `AudioTrack` and a comment says this was always the intention:

`// Only align Wave and Note tracks end to end.`

I will update the issue description.

**Comment by LWinterberg** [comment] 2023-07-25 12:45
I'm minded to agree with David here - the bulk of the "align" commands essentially just move clips left and right, and it makes sense to keep the labels sync'd up with them while doing it. 

However, in a situation like this: 
![image](https://github.com/audacity/audacity/assets/87814144/e9908b5c-4fe6-46c8-b968-3c94e9dbddc8)

aligning end to end or aligning together breaks synchronization of labels and clips either way, so here doing nothing is appropriate.

**Comment by LWinterberg** [comment] 2024-10-15 10:36
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.

**Closed by LWinterberg** 2024-10-15 10:36 UTC
Labels: AU3-bug, Scheduled for replacement, Labels
