### ISSUE TITLE
New exporter

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#4317] opened 2023-02-15 11:34 UTC
The goal of this new exporter is to simplify the exporting experience:

* Use a dedicated dialog for exporting options, consolidating various currently separate option (channels, advanced mixing options, export selection, export multiple, sample rate)
* Allow the use of the Windows 10 style explorer

Figma can be found here: https://www.figma.com/file/YozSr5RHvEOiJeE6r6QY1N/27_WX-Import%2FExport?node-id=303%3A22

**Comment by DavidBailes** [comment] 2023-04-28 08:40
> Figma can be found here: https://www.figma.com/file/YozSr5RHvEOiJeE6r6QY1N/27_WX-Import%2FExport?node-id=303%3A22

@LWinterberg Could this design please be made publicly accessible is some convenient format?

**Comment by petersampsonaudacity** [comment] 2023-05-02 14:18
@LWinterberg  I do have a Figma account - BUT I do need access to be granted in order to view this new Export design.

**Comment by petersampsonaudacity** [comment] 2023-05-02 15:34
Havind had a look at the Figma for this - I can't see where **Ignore blank space at the beginning** fits in.

It is an option in **Import/Export** options at the moment (off by default) - but I don't see it anywhere in any of the Figma images.

**Comment by petersampsonaudacity** [comment] 2023-05-02 15:41
Maybe the new Export Audio dialog in the Export Range section could have:

**Multiple parts**  rather than  **Split in parts**  -  or even  **Split in multiple parts**

So as to aid "discoverabilty" for users who are long-used to **Export Multiple**

**Comment by petersampsonaudacity** [comment] 2023-05-03 08:59
With regard to the new **export multiple "spit in parts"** dialog.

The Figma shows the **Include audio before first label** remaining (but moved to the top).

Personally I would advocate for just removing it - I see no real pint in it
a) if the user want that audio they can place a label at/near the beginning
b) since the exported filename is based on the label, if there is no label for the initial audio there is no name for the first exported file
c) it is probably wrong to give it prominence at the top as it only applies to export by labels and export by tracks.

_I base these comments from having used Export Multiple many thousands of times over the years as I digitized my (and my wife's) LP and tape collection._

**Comment by DavidBailes** [comment] 2023-05-03 09:01
> @LWinterberg Could this design please be made publicly accessible in some convenient format?

@LWinterberg . I take it that the answer is No.

**Comment by LWinterberg** [comment] 2023-05-03 09:33
> Could this design please be made publicly accessible in some convenient format?

What is a "convenient format"? Like, I could export some 30 pngs from it, which lose their special relations and between the time you asked and now they already have fallen out of date. 

> The dialog for the Split in parts has the same title as the Export Audio dialog 

It's the same dialog, it just expands when split in parts is selected.

> The Figma shows the Include audio before first label remaining (but moved to the top).

It's not moved to the top, rather the text field is removed. The "include audio before first label" option is just supposed to take the name from the main name field, which is what the arrow represents.

**Comment by DavidBailes** [comment] 2023-05-03 10:55
> > Could this design please be made publicly accessible in some convenient format?
> 
> What is a "convenient format"? Like, I could export some 30 pngs from it, which lose their special relations and between the time you asked and now they already have fallen out of date.

OK, I hadn't appreciated how many images are involved. I've requested access via my figma account.

**Comment by petersampsonaudacity** [comment] 2023-05-06 09:45
@vsverchinsky @lw
Consideration will likely need to be made with regard to the Maro/Scripting commands that are currently available for exporting from a Macro:
![image](https://user-images.githubusercontent.com/50205984/236616640-0a7fa137-7d99-487b-89d1-073e27d50e34.png)

**Comment by petersampsonaudacity** [comment] 2023-05-09 14:49
@LWinterberg @vsverchinsky 

**A question**
Does this "Task" for new exporter have any impact on the quality settings in:
a) Audio Setep toolbar > Audaio Settings,
b) Audio Setttings preferences,
both of which of course do exactly the same thing.

**Comment by vsverchinsky** [comment] 2023-05-29 09:04
> @vsverchinsky @LWinterberg Consideration **_may_** need to be made with regard to the Macro/Scripting commands that are currently available for exporting from a Macro and Scripting.
> ### Macro
> 
> ![image](https://user-images.githubusercontent.com/50205984/236616640-0a7fa137-7d99-487b-89d1-073e27d50e34.png)
> ### Scripting
> 
> ![image](https://user-images.githubusercontent.com/50205984/236618179-4bab1299-6fec-4d6c-ac1e-b15adc963868.png)

@petersampsonaudacity The only problems with these commands I see so far is that a) user cannot customize export parameters used in the command transparently, b) command does export using same paramters as with last manual export. In the new branch I preserved this behavior.

**Comment by vsverchinsky** [comment] 2023-05-29 09:07
> @LWinterberg @vsverchinsky
> 
> **A question** Does this "Task" for new exporter dialog have any impact on the quality settings in: a) Audio Setep toolbar > Audaio Settings, b) Audio Setttings preferences, both of which of course do exactly the same thing.

@petersampsonaudacity no, sample rate setting in the new export dialog does not change any preference outside this dialog.

**Comment by DavidBailes** [comment] 2023-06-01 09:46
@vsverchinsky @LWinterberg 

Testing with commit: https://github.com/audacity/audacity/commit/8b5e2253d0ce97bc8acf1a947ff1b5a22c44eb6d
There are a number of accessibility issues:

1. Navigation of export range radio buttons. When the middle radio button, "current selection" is not available (there aren't any selected audio tracks), then using up/down arrows, it is not possible to change the selection from the first button to the third button, or from the third button to the first button. This appears to be a long standing bug in wxWidgets: https://forums.wxwidgets.org/viewtopic.php?f=1&t=14604
Incidentally, is it intentional that the availability of the current selection radio button is determined by whether there are any selected audio tracks rather than the presence of selected audio tracks and a selected time range?

2. Accessibility names of export range radio buttons. "Export range:" is not read by screen readers (It's not the name of a group box.) So if the export range radio buttons aren't in a group box, then the accessibility names of the radio buttons need to be set to provide the context. Accessibility names such as "Export entire project", "Export current selection", and "Export split in parts".

3. The availability of the Configure button. Is it intended that this button is available (and so in the tab order) whether or not the custom mapping radio button is selected? I think it would be better if the button was available only when the custom mapping radio button is selected. However if it's decided that it should always be available, then it would be helpful to set the accessibility name of the button to provide some context. For example, an accessibility name "configure custom mapping".

4. Audio options: accessibility of check boxes. (For example, when the format is mp3, there's a "force export to mono" check box.) The name isn't read by screen readers, you can't click on the name of the check box to change its state, and the visual indication of focus is in the wrong place. A straightforward fix, assuming that it's acceptable visually, is to use a wxCheckBox with style wxALIGN_RIGHT so the text appears on the left of the check box, as is done in the plain gui for VST3 effects.

5. Audio options: accessibility of sliders. (For example, when the format is Ogg Vorbis Files, there's a "Quality" slider.) The name isn't read by screen readers. Sliders created using Shuttlegui automatically have a WindowAccessible set, so all that is needed is a call to ShuttleGui & Name( const TranslatableString &name ), to set the name.

6. Access keys. It would be helpful if at least the most important controls had access keys, so that, for example, a user can set the export range using one, rather than potentially having to use a large number of tabs. In order not to run out of unique access keys, then they could be omitted from the audio options which vary with the format, and the controls that are only shown when the export range is set to split in parts.

**Comment by petersampsonaudacity** [comment] 2023-06-22 12:05
Re @DavidBailes 's point 3 see:   New Export: Configure button should only be available when "Custom mapping" is selected #4818

**Comment by vsverchinsky** [comment] 2023-07-07 10:24
> Incidentally, is it intentional that the availability of the current selection radio button is determined by whether there are any selected audio tracks rather than the presence of selected audio tracks and a selected time range?

@DavidBailes 

No, it used to show "Select the audio..." warning, but this was lost during refactoring, thanks!

I updated the branch, issue 4 is partly resolved and issue 6 is not resolved yet

**Comment by DavidBailes** [comment] 2023-07-07 12:44
> No, it used to show "Select the audio..." warning, but this was lost during refactoring, thanks!
> 
> I updated the branch, issue 4 is partly resolved and issue 6 is not resolved yet

@vsverchinsky . Thanks for the fixes. Issue 1 also remains unresolved, though the availability criterion for the "current selection" radio button is now fixed.

If the "current selection" radio button is unavailable:
A.  If the "entire project" radio button is initially selected, then when a keyboard user tabs to this group of radio buttons, the "entire project" radio button will be the initial focus. If they then press down arrow once, they would expect to move the focus to and select the "split in parts" radio button. But this does not happen - the Edit metadata button becomes the focus (at least on Windows).
B. If the "split in parts" radio button is initially selected, and a keyboard user has tabbed to it, if they press up arrow, they would expect to move the focus to and select the "entire project" radio button. Again this does not happen - one of the controls in the audio options grouping becomes the focus.

**Comment by LWinterberg** [comment] 2023-07-10 10:39
![image](https://github.com/audacity/audacity/assets/87814144/2428c063-ddcf-4a5e-9c93-59a831a1945d)
@DavidBailes It seems like Audacity used to never use radio buttons, so I'm somewhat unsure if each item needs to be accessible or if it's enough for the radio button group to be accessible. This would be my suggestion for it though.

**Comment by petersampsonaudacity** [comment] 2023-07-10 11:31
See also this related ENH:   New Export - changes could be extended to Export of Labels and MIDI #4891

**Comment by DavidBailes** [comment] 2023-07-14 10:18
> If the "current selection" radio button is unavailable:
> A. If the "entire project" radio button is initially selected, then when a keyboard user tabs to this group of radio buttons, the "entire project" radio button will be the initial focus. If they then press down or right arrow once, they would expect to move the focus to and select the "split in parts" radio button. But this does not happen - the Edit metadata button becomes the focus (at least on Windows). Pressing up or left arrow, does correctly select the "split in parts" radio button.
> B. If the "split in parts" radio button is initially selected, and a keyboard user has tabbed to it, if they press up or left arrow, they would expect to move the focus to and select the "entire project" radio button. Again this does not happen - one of the controls in the audio options grouping becomes the focus. Pressing down or right arrow, does correctly select the "entire project" radio button.

@LWinterberg 
Assuming that the "current selection" radio button is the only one of the export range radio buttons that might be unavailable, then a straightforward fix for the above serious keyboard navigation problem would be to change the order of the radio buttons to:
1. Entire project
2. Multiple files
3. Current selection.
Would that be an acceptable fix?

**Comment by LWinterberg** [comment] 2023-07-14 10:34
that works for me

**Comment by DavidBailes** [comment] 2023-07-14 10:47
> that works for me

@vsverchinsky Could you please make that change to the order of the export range radio buttons, ie
1. Entire project
2. Multiple files
3. Current selection

**Comment by DavidBailes** [comment] 2023-07-19 08:26
@LWinterberg Pressing the Browse button now brings up a standard dialog for saving a file, rather than selecting a folder.
I find this confusing. The dialog has a save button, but when you press save, no file is saved. I don't know of any uses of this standard dialog where pressing the save button does not save a file. A minor issue is title of the dialog no longer seems appropriate.

**Comment by petersampsonaudacity** [comment] 2023-07-19 09:11
@DavidBailes  @LWinterberg  -  testing on W10 with @vsverchinsky 's latest branch build:  audacity-win-3.4.0-alpha-20230713+e7f58dd-x64

This looks fine to me:
![image](https://github.com/audacity/audacity/assets/50205984/1bd54b31-328e-4aff-8f6e-60e53cebf5fc)

**Comment by DavidBailes** [comment] 2023-07-19 09:38
> But yes, the Save here is a little confusing - but that's because Muse are presumably using the Windows standard UI /dialog rather than bothering to write a bespoke one.

Given that pressing the Save button saves a file in all the other instances of the standard save dialog that the user has encountered (to the best of my knowledge), there is a danger that the user thinks that once they have pressed the button the file is saved. They then might cancel the export dialog, assuming the file has been saved. But it hasn't, and they may end up loosing their data.

**Comment by petersampsonaudacity** [comment] 2023-07-19 09:52
I suspect too that in many (maybe even most cases) folk will use thhe default location - or the one they set in directories prefs for Saves - and thus will not use the Browse button.

**Comment by DavidBailes** [comment] 2023-07-26 08:57
@vsverchinsky . Only recently noticed that there are a couple of other accessibility names that need setting. When the format is set to Custom FFmpeg Export, there are two text controls: Current format and Current Codec. These currently have empty accessible names. WindowAccessible is automatically set as the accessible object for text controls in ShuttleGui, so all that is needed is to set the accessible name for these text controls (like you did for sliders).

**Comment by chinakov** [comment] 2023-07-31 11:47
@vsverchinsky - I have completed testing this feature set, everything seems to be in order, except for a couple of things:
- https://github.com/audacity/audacity/issues/4969
- https://github.com/audacity/audacity/issues/4959
According to @dozzzzer, these 2 issues can be fixed post-merge, before the release.

I have also found some other issues, but they are of lesser priority. Here is the full list of all issues present: https://github.com/audacity/audacity/issues?q=is%3Aissue+is%3Aopen+%22New+Export%22+label%3Aimport-export

Apart from this, we are ready to merge.

**Comment by crsib** [comment] 2023-07-31 12:08
I don't think that 4969 is related to this branch

**Comment by petersampsonaudacity** [comment] 2023-07-31 12:21
>I don't think that 4969 is related to this branch

@crsib 

Not related to export - BUT this issue only occurs in @vsverchinsky 's branch build  for New Expoty - it does NOT happen in 3.3.3 or tje latest alpha for 3.4.0

**Comment by dozzzzer** [comment] 2023-07-31 12:23
> Not related to export - BUT this issue only occurs in @vsverchinsky 's branch build for New Expoty - it does NOT happen in 3.3.3 or the latest alpha for 3.4.0

No worries. It will get fixed anyway once @vsverchinsky 's branch gets rebased onto the most recent `master`

**Comment by petersampsonaudacity** [comment] 2023-07-31 12:35
Looking forward to this merge - as I will have a lot of work to do in the Manual for new Export

**Comment by petersampsonaudacity** [comment] 2023-08-01 08:23
Testing on W10 with @vsverchinsky 's latest branch build:  audacity-win-3.4.0-alpha-20230731+e132f93-x64

#4969 now works properly (as predicted yesterday by @crsib )

**Comment by petersampsonaudacity** [comment] 2023-08-01 10:25
>  New Export: Custom Mapping Sums all Stereo Channels into the first 2 channels #4959 

Testing on W10 with @chinakov 's STR's I can't seem to be able to reproduce #4959 - not on @vsverchinsky 's latest new export branch build nor on 3.3.3 or the latest alpha test build for 3.4.0

**Comment by vsverchinsky** [comment] 2023-08-01 10:36
> > New Export: Custom Mapping Sums all Stereo Channels into the first 2 channels #4959
> 
> Testing on W10 with @chinakov 's STR's I can't seem to be able to reproduce #4959 - not on @vsverchinsky 's latest new export branch build nor on 3.3.3 or the latest alpha test build for 3.4.0

I attempted to fix that, but still I'm not yet sure that fix is complete

**Closed** 2023-08-02 12:26 UTC
Labels: Task
