### ISSUE TITLE
3.2.5 and 3.3.2 - slider won't appear when zooming in a track

### ISSUE THREAD

**Issue by rado84-github** [audacity/audacity#4815] opened 2023-06-19 22:18 UTC
### Steps to reproduce

Right click on any audio track (format doesn't matter) and click "Open with... Audacity".
Using Ctrl + rolling the mouse wheel upwards zoom in the track as many times as you want, so that you can see things more clearly.
Watch the bottom of the Audacity's screen - the slider which helps moving left and right on the zoomed in track doesn't appear.
The only way to make it appear is to change the theme to anything else and change it back to the theme you wanna use.
I made a video showing the problem and it's attached to this report.

[audacity-3.2.5-and-3.3.2-slider-missing.mkv.zip](https://github.com/audacity/audacity/files/11793516/audacity-3.2.5-and-3.3.2-slider-missing.mkv.zip)

### Expected behavior

Zooming in a track should make the slider appear.

### Actual behavior

The slider doesn't appear when zooming in a track.

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

The soundcard is integrated into the motherboard, so it's Realtek ALC892.

Here's hardware and system info, in case you need it.

[rado@arch]: ~>$ sysinfo
rado@arch 
--------- 
OS: ArchLinux 
Kernel: 6.1.34-1-lts 
Uptime: 3 days, 13 hours, 9 mins 
Packages: 1609 (pacman) 
Shell: bash 5.1.16 
Resolution: 1920x1080 
DE: Cinnamon 5.2.7 
WM: Mutter (Muffin) 
WM Theme: BGT-v2.2-GTK3_Cinn-5.2.7 (Cinnamox-Rhino) 
Theme: BGT-v2.2-GTK3_Cinn-5.2.7 [GTK2/3] 
Icons: Humanity-Dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-4770 (8) @ 3.400GHz 
GPU: NVIDIA GeForce GTX 1660 Ti 
Memory: 3.87GiB / 31.27GiB (12%) 
GPU Driver: NVIDIA 525.89.02 
CPU Usage: 4% 
Disk (/): 27G / 110G (26%) 
Font: Open Sans Semi-Bold 11 [GTK2/3]

**Comment by LWinterberg** [comment] 2023-06-20 06:21
Duplicate of #2937

**Closed by LWinterberg** 2023-06-20 06:21 UTC
Labels: bug
