### ISSUE TITLE
VST'S

### ISSUE THREAD

**Issue by Minsmereway** [audacity/audacity#3754] opened 2022-10-03 15:44 UTC
### Your idea

To designate on a PC by the user where to find VST'S! Either a designated folder,  or drive please. 

### Problem to be solved

User can define where effects are stored!

### Additional context

Thank you for your consideration. Regard's, Joseph.

**Comment by LWinterberg** [comment] 2022-10-04 04:22
duplicate of #1396

**Closed by LWinterberg** 2022-10-04 04:22 UTC
Labels: Enhancement Request
