### ISSUE TITLE
AMR export is no longer available

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4446] opened 2023-03-25 14:31 UTC
### Bug description
AMR export is no longer available from the **File > Export > Export Audio** menu

This is a regression on 3.2.1

### Steps to reproduce
1. launch 3.2.1
2. get some audio
3. File > Export > Export Audio
4. Observe in the Save as type dropdown **AMR** is available as a option
5. exit Audacity
6. launch 3.2.5 or 3.3.0 alpha
7. get some audio
8. File > Export > Export Audio
9. Observe in the Save as type dropdown **AMR** is  _**NOT**_ available as a option

### Expected behavior
![image](https://user-images.githubusercontent.com/50205984/227723533-faaadd0b-23e6-4ac6-9757-718ab2920c35.png)

### Actual behavior
**3.2.5 or 3.3.0 alpha**
![image](https://user-images.githubusercontent.com/50205984/227723612-13a66f25-904a-4fb5-943f-4e116428e222.png)

### Audacity Version
3.2.5 and 3.3.0 alpha

### Operating system
Windows 10 - but assuyme all OS

### Additional context
Reported on the Forum:

https://forum.audacityteam.org/t/unable-to-export-to-amr/72062

**Comment by LWinterberg** [comment] 2023-03-25 19:58
![image](https://user-images.githubusercontent.com/87814144/227738841-4f30af0d-efff-46f8-b3f2-41d950d760ae.png)

maybe relevant - custom FFmpeg shows no codec assigned to the amr format

**Comment by LWinterberg** [comment] 2023-03-25 20:15
Found the cause - the FFmpeg 5 version on buanzo's site is compiled without libopencore_amrnb. If you use an alternate FFmpeg version, it'll show up (even without relaunching Audacity!)

cc @crsib

**Closed** 2023-03-31 13:21 UTC
Labels: dependency, bug, P3, regression, import-export

**Comment by LWinterberg** [comment] 2023-03-31 13:48
I have updated https://support.audacityteam.org/basics/installing-ffmpeg to reflect that the default installer doesn't do AMR anymore.

**Comment by petersampsonaudacity** [comment] 2023-04-01 15:06
I have updated the manual to expunge AMR
