### ISSUE TITLE
HTTP request to audacityteam.org fails

### ISSUE THREAD

**Issue by tim-lebedkov** [audacity/audacity#891] opened 2021-05-14 07:59 UTC
**Describe the bug**
I use Go to get the source code of the page https://www.audacityteam.org/download/windows/ to determine the current version of Audacity. It fails with "bad status: 403 Forbidden". If was not the case some weeks ago.

**To Reproduce**
1. Go to https://ci.appveyor.com/project/tim-lebedkov/npackd
2. Click on the first job
3. Scroll down to 'Audacity'

**Expected behavior**
HTML is returned.

**Screenshots**
https://ci.appveyor.com/project/tim-lebedkov/npackd/build/job/oe2oighwecvjfbot#L376

**Additional information (please complete the following information):**
 - OS: Windows (AppVeyor)
 - Version 

**Additional context**
-

**Comment by JamesCrook** [comment] 2021-05-14 10:09
This is a duplicate of a 'bug' reported elsewhere.
The resolution is to modify your script to go to [GitHub Releases](https://github.com/audacity/audacity/releases) instead.

**Closed by JamesCrook** 2021-05-14 10:09 UTC
Labels: Meta, Request
