### ISSUE TITLE
Missing horizontal time bar on Debian

### ISSUE THREAD

**Issue by Mte90** [audacity/audacity#4292] opened 2023-02-07 16:46 UTC
### Bug description

I was the guy at the Mozilla booth that showed the issue to one of the Audacity's dev. That person invited me to open a ticket there instead on Debian to see if they can fix it on this side.
Basically on the Debian Sid package (I don't know if it happens also in the other branches) the horizontal bar also if enabled doesn't appear.
I have to disable and renable to show it.

This problem is there since the new UI so I think 1-2 months.

If can help I can compile it on my machine

### Steps to reproduce

* Get a debian sid machine
* Install audacity and test

### Expected behavior

* Get the horizontal bar

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

Audacity: 3.2.4+dfsg-1

**Comment by LWinterberg** [comment] 2023-02-07 17:01
Which horizontal bar are you talking about specifically? The scroll bar (#2937)? Or something else (scrub bar, timeline, title bar, menu bar, toolbars come to mind)

**Comment by Mte90** [comment] 2023-02-07 17:14
You are right, the scroll bar.
So I think this ticket is a duplicate as #2937 already mention that.
I can replicate with my various machines with Debian Sid.

**Comment by LWinterberg** [comment] 2023-02-08 15:28
Alright, in which case I'll close this as a duplicate of #2937

**Closed by LWinterberg** 2023-02-08 15:28 UTC
Labels: bug, Linux
