### ISSUE TITLE
Tools and Analyze menu items untranslated when changing from German (locale) to English

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5853] opened 2024-01-10 11:29 UTC
### Bug description
Some **Tools** and **Analyze** menu items are untranslated when changing from German (in a German locale computer) to English

Analyze / Geräusche beschriften...   -   this should be **Label Sounds**

Tools / Apply Macro / Enden ausblenden  -  should be **Fade Ends**
Tools / Apply Macro / MP3-Umwandlung  -  should be **MP3 Conversion**
Tools / Nyquist Erweiterungs-Installer  -  should be **Nyquist Plugin Installer**
Tools / Sample Datenexport...  -  should be **Sample Data Export**
Tools / Sample Datenimport...  -  should be  **Sample Data Import**
Tools / Textmarken in regelmäßigen Intervallen...  -  should be **Regular Interval Labels**

### Steps to reproduce
1. On a Deutsch locale computer ensure Audacity Language (Sprache) is default set to System - so computer is running in Deutsch
2. **Bearbeiten > Einstellungen > Schnittstelle** and choose **English** in the **Sprache** dropdown menu
3. go to the Tools menu
4. Observe: menu items untranslated to English
5. go to the Analyze menu
6. Observe: Geräusche beschriften... remains untranslated to English

### Expected behavior
Menu items should be translated to English

### Actual behavior
Menu items should be translated to English

### Audacity Version
latest stable version (from audacityteam.org/download) - 3.4.2

### Operating system
Unknown

### Additional context
Reported to me offline in an email conversation by German user Heiner Meyer

Note that if I set Audacity to run in Deutsch on my English locale W10 PC and then set it back to "System" i.e. English - the all the Tools and Analyze commands are properly reverted to English.  So it looks as though this issue is with German/Deutsch locale rather than Audacity's language setting per se.

**Comment by LWinterberg** [comment] 2024-01-10 11:50
Duplicate of https://github.com/audacity/audacity/issues/2764

This only happens with Nyquist plugins. I found that a rescan plugins works around this though.

**Closed by LWinterberg** 2024-01-10 11:50 UTC
Labels: bug, translation / i18n
