### ISSUE TITLE
Performance and file size issues when copying and pasting a small portion of a very large clip

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#3820] opened 2022-10-17 12:15 UTC
### Bug description (edited by @Tantacrul)

Audacity 3.2.1

1) Generate a 1 hour chirp
2) Select the very small portion of the audio and copy it
3) Paste it into a new project
4) Notice the entire original clip has been pasted, which massively increases the file size of the new project

See comments below from @Tantacrul for a proposed solution.

---

**Secondly**, there have been reports of large performance problems as a result of copying and pasting data working with large clips. These need to be investigated @Ryan-Miller-Audacity @dozzzzer.

**Comment by mapisilafi** [comment] 2022-10-19 11:38
Struggling with this too. It appeared after installing 3.2.1. Usually recording hours and then taking small snippets from here and there using copy-paste. It takes minutes to paste to a new file. During operation Disk usage at 100%, 400MB/s. Previously that operation took only few seconds.

**Comment by petersampsonaudacity** [comment] 2022-10-22 13:26
A close cousin of this is that the **Edit>Remove Special**  commands
a) Split Cut
b) Split Delete
c) Trim Audio
do _**NO LONGER**_  delete the removed audio.

Rather the remaining audio clips are turned into "smart clips" with the ostensibly removed audio still present as part of the clip(s) but hidden.  This new behavior is a regression on earlier Audacity, introduced in 3.1.0 - and will be a surprise to most users (if they notice it at all).

What it does do is to unnecessarily increase the size of a users project as several users have reported - and this is how we found this odd behavior.

Normally when one uses a delete, cut or trim command one expects the removed data to be actually removed (and in the case of cut placed on the clipboard).  Certainly that is the case when one uses Word or Excel, or other apps that I us.

It seems to me that if you do want to have such functionality it should be new commands which make it explicitly clear that data is not being removed but merely hidden.

AFAICT this hidden creation of "smart clips" is not documented or announced anywhere.

### Steps To Reproduce
1. generate a 30 second chirp
2. select 20-20 seconds
3. Edit > Remove Special > Spit Delete (or Trim Audio or Split Cut)
4. Drag at the top edge of the remaining clips
5. Observe: the supposedly deleted audio is revealed as the smart clip expands

Note too that with Spit Delete and Split Cut _**BOTH**_ of the remaining "smart clips" have the not just the full data that has allegedly been removed they also have the full 30 second clip that can be dragged out and more - so you then have not one but two copies of the full clip.

Flagging @Tantacrul and @LWinterberg as this is a UX/Design issue

**Comment by JohnColket** [comment] 2022-10-22 14:29
> Plus you can carry on doing this to get even more multiple copies of data that users thought they had removed. So it's little wonder that users' project files are growing bewilderingly large

I suspect, but have not confirmed, that the "bewilderingly" only happens when the tiny clips are pasted into  a new project and the undesired "audio information" has to be copied into the new project, perhaps multiple times.  It is entirely possible that the tiny clip only contains a pointer to the original "audio information".

The main problem being that when a user tries to reduce the size of his project by creating tiny clips, he inadvertently starts increasing it.

**Comment by petersampsonaudacity** [comment] 2022-10-23 14:27
Another example of this weird behavior

1. Generate a 30 second chirp
2. Place the cursor at 20 seconds and Ctrl+I to split the chirp
3. zoom out 2 or 3 times
4. Move the second clip well to the right
5. Click on the upper left of the second clip and drag Rightwards by 5 seconds
6. Observe: clip shrinks to a 5 second on-screen (and playable) chirp - _expected behavior_
7. Click on the upper left of the second clip and drag leftwards for 25 seconds or more
8. Observe: the second clip now shows as a full 30 second clip and not just the ten second clip that it was at Steps 2 & 3
9. Click on the upper right of the first clip and drag Rightwards for ten seconds or more
10. Observe: the first clip now also shows as a full 30 second clip
11. Observe: we now have two 30 second clips and _**NOT**_ a 20 second clip and a 10 second clip

The behaviors shown in steps 8, 10 and 11 just look **_totally_** wrong to me.

**Comment by LWinterberg** [comment] 2022-10-24 10:41
raising priority as users have been reporting orders of magnitude larger files

**Comment by Tantacrul** [comment] 2022-10-24 11:06
Good call, @LWinterberg

**Comment by petersampsonaudacity** [comment] 2022-10-24 13:07
My view is that there should be  only one way to create a "Smart Clip", which would have been by dragging the end of the clip to resize it.

It is not good that smart clips are created automatically, and hidden with no indication to the user, when **Edit** commands like **Audio Clips > Clip** or **Remove Special > Split Delete** are used

**Comment by Tantacrul** [comment] 2022-10-24 13:15
We do have some designs ready for improvements to clips that will help to solve this (and make it clearer too). My view is that if you select the whole clip (either by selecting the header or double-clicking), it'll copy the full clip, including extra data. If you copy a bit of a clip, that's all you should copy.

The design fixes I mentioned will make that visually clearer. Not for 3.3 however.

**Comment by petersampsonaudacity** [comment] 2022-10-24 15:54
> > this glitch was introduced in 3.1.0 which was released just a few days shy of a year ago.
> 
> No. This is a new bug/feature introduced in 3.2.

No I'm talking about the glitch whereby creating a split in a clip produces two clips both of which are "smart clips" that can be expanded to the full audio of the original un-split clip (as in the use case above that I posted yesterday).

And I just tested again on W10 and that definitely happens in 3.1.0 when the clip-handles were first introduced.  This does **NOT** happen in 3.0.5 and earlier

**Comment by petersampsonaudacity** [comment] 2022-10-25 15:24
> We do have some designs ready for improvements to clips that will help to solve this (and make it clearer too). My view is that if you select the whole clip (either by selecting the header or double-clicking), it'll copy the full clip, including extra data. If you copy a bit of a clip, that's all you should copy.

@Tantacrul 
But that is not what I was complaining about - what I was talking about was the fact that if you now (3.1.0 onwards) split a clip, then both parts of the split contain not just the audio visible in that clip but the audio of the whole originating clip and that can be dragged out from the "smart clip".

If this is new intended/designed behavior it does not appear to be clearly documented or mentioned in the Release Notes nor in your What's New videos.

This was not the case before in 3.0.5

**Comment by Tantacrul** [comment] 2022-10-28 17:32
> A close cousin of this is that the **Edit>Remove Special** commands a) Split Cut b) Split Delete c) Trim Audio do _**NO LONGER**_ delete the removed audio.
> 
> Rather the remaining audio clips are turned into "smart clips" with the ostensibly removed audio still present as part of the clip(s) but hidden. This new behavior is a regression on earlier Audacity, introduced in 3.1.0 - and will be a surprise to most users (if they notice it at all).
> 
> What it does do is to unnecessarily increase the size of a users project as several users have reported - and this is how we found this odd behavior.
> 
> Normally when one uses a delete, cut or trim command one expects the removed data to be actually removed (and in the case of cut placed on the clipboard). Certainly that is the case when one uses Word or Excel, or other apps that I us.
> 
> It seems to me that if you do want to have such functionality it should be new commands which make it explicitly clear that data is not being removed but merely hidden.
> 
> AFAICT this hidden creation of "smart clips" is not documented or announced anywhere.
> 
> ### Steps To Reproduce
> 1. generate a 30 second chirp
> 2. select 20-20 seconds
> 3. Edit > Remove Special > Spit Delete (or Trim Audio or Split Cut)
> 4. Drag at the top edge of the remaining clips
> 5. Observe: the supposedly deleted audio is revealed as the smart clip expands
> 
> Note too that with Spit Delete and Split Cut _**BOTH**_ of the remaining "smart clips" have the not just the full data that has allegedly been removed they also have the full 30 second clip that can be dragged out and more - so you then have not one but two copies of the full clip.
> 
> Plus you can carry on doing this to get even more multiple copies of data that users thought they had removed. So it's little wonder that users' project files are growing bewilderingly large.
> 
> Flagging @Tantacrul and @LWinterberg as this is a UX/Design issue

Can we mark this as a separate issue so we can stick to the issue at hand here?

**Comment by Tantacrul** [comment] 2022-10-28 17:35
> But that is not what I was complaining about - what I was talking about was the fact that if you now (3.1.0 onwards) split a clip, then both parts of the split contain not just the audio visible in that clip but the audio of the whole originating clip and that can be dragged out from the "smart clip".

I think that's desirable behaviour ultimately. The only reason we might not want to do it now is for file size reasons. I don't understand what the UX harm is. Not expected isn't a good enough answer. What does the user lose by providing this behaviour?

**Comment by petersampsonaudacity** [comment] 2022-10-29 10:53
@Tantacrul 

I am strongly minded to agree with @mapisilafi  (and others who have written on the Forum)

One of my regular workflows is to take a 2-hour project, two of them in fact, webcast music shows.  I listen to the show and note a song(s) I may want to clip out for later repeat listening.

There are a number of ways to do this with Audacity 3.2.x

1) select the song, label it, select and delete the audio from T=0 to start of the label.  Select and delete the audio from the end of the label to the end of the project.  Save the project.

2) Select the song and use Remove Special>Trim. Save the project.

3) Select the song.  Audio Clips>Split.  Delete clips 1 and 3.  Save the project.

4) Select the song.  Edit>Copy to copy song to clipboard.  Add new stereo track.  Paste the song into new track with Edit>Paste.  Delete the original 2-hour track.  Save the project.

A)  With method one which does not involve clips/smart-clips I end up with a 62.8MB project (what I'd expect for a 3 minute project.

B)  with methods 2,3 & 4 all of which involve smart-clips I end up with a huge 2.5GB project (and this is because the smart-clip that remains is actually carrying the full 2 hours-worth of stereo data.


So there are a couple of what I would regard  as UX problems associated with this:

**i) Disk size occupancy**
It is somewhat ridiculous to be getting a project for a 3 minute song that is 40 times larger (in this case) than it either needs to be or as the user reasonably expects it to be.

You might argue that disk space is cheap these days and disks are generally larger - but a couple of factors apply here:
**One,** the user may end up having several of such over-large projects around, and this is not unreasonable.
**Two,** many computers these days are supplied with a smallish 128GB or 256GB SSD - and the OS and apps take up a goodly portion of that room.

**ii) lack of visual cue for the smart-clip**
As I explained earlier one of the big problems with this is that the poor old user has absolutely no idea that they have been given bloated smart-clips as there is _**NO**_ visual cue at all to alert them to this.


### Management Summary
a) the upshot of this is that many users writing on the Forum about this end up deciding to revert to earlier versions of Audacity that do not have smart-clips.  I'm sure you will agree that this is not ideal, as you really want to get most users onto the latest release version (that's why you introduced the version update alert in Audacity).  Some users (@mapisilafi for example) are even abandoning Audacity, and that is an even worse outcome - and can lead to reputational damage.

b) I concede that smart-clips can be useful for some users, even in the use-case I outline above as it would allow me to expand and contract my 3-minute song even after I have saved and re-opened the project,  But I agree with @mapisilafi that it should be a configurable option (i would prefer it "off" by default, but I suspect you would likely prefer it "on" by default)

c) You did agree earlier in this thread that you would be likely to fix the use-case in method 4 where a partial copy an paste fro a clip only copies the selection and not the whole clip.





### Test methodolgy
I simulated this by generating a 2-hour stereo clip which resulted in a 2.5GB project, selection from 1h00m00s to 1h03m00s and then applying methods 1 through 4 in turn.

The results can be seen in this screenshot:
![image](https://user-images.githubusercontent.com/50205984/198827364-af9b8f83-8685-437c-a5a8-3afe9ce4eb29.png)

**Comment by Tantacrul** [comment] 2022-10-29 18:05
So, to me this is an issue with space and not with UX. Copied clips should be handled efficiently so that they can be copied 100 times with not increase in the project's file size. With that solved, then there are some very straight-forward visual improvements that can be made so that the user can understand the nature of the clip.

This is the most elegant way to solve the problem because it means that all clips behave in the same way in all circumstances.

**Comment by crsib** [comment] 2022-10-29 19:24
Let's verify that copying does not increase the file size (@dozzzzer @Ryan-Miller-Audacity), but I'm pretty sure it works as expected

**Comment by Tantacrul** [comment] 2022-10-29 20:37
OK, I've done a bit of poking around and I think I can make a few reasonable conclusions now.

First, we specifically took steps so that copying / splitting clips **does not** exponentially keep increasing file size in a single project. You can see what I mean in t**[his video](https://www.dropbox.com/s/mpfkaytwcyqfszx/Chirpy_Chirpy.mp4?dl=0)**. If we find an instance where this does happen, it's a bug that we'll need to fix. I'm unable to find such a bug right now.

However, we did not consider how this might affect the use case of copying and pasting **between different projects**. In that case, I definitely understand how problematic it can be, since it necessarily copies the entire original clip.

We're just discussing the technical feasibility but I would suggest the following fix: if pasting from one project to another, we display a dialog that asks something like [**Would you like to paste the whole original clip or just the part of the clip you selected (don't show me this again**?]

Lastly, I do not think there is any UX issue here at all. Quite the opposite. We intend to fix any file size bloating problems but we are not undoing this UX change which does not change the experience at all. It only offers more options than users had in previous versions.

**Comment by mapisilafi** [comment] 2022-10-29 21:06
> So, to me this is an issue with file size management and not with functionality. Copied clips should be handled efficiently so that they can be copied 100 times with no increase in a project's file size. That's 100% of the problem. We don't fix that by making smart clips optional. That complicates the experience and sweeps the issue under the rug. @mapisilafi - your issue is a file size issue, not a design issue.
> 
> With the size issue solved, then there are some very straight-forward visual improvements that can be made so that the user can understand whether or not there is 'hidden' extra audio data in a given clip.
> 
> This is the most elegant way to solve the problem because it means that clips behave the same way in all circumstances and everyone gets what they want.
> 
> By the way, I agree the file size issue is extremely serious. Just want to make that point. It has to be solved.

To me the file size is not the main issue, the first and foremost issue is the significant performance degradation due to increased processing requirement of smart clips. Therefore it certainly shows as user experience issue when working with large originals. As said, when my key routines take minutes instead of seconds before, it makes the product unusable. 
I would be really cautious re-specifying standard and well known idioms such as cut-copy-paste. Like said, I might want to enable smart clips when I need it, but as default configuration it makes the whole software seem inefficient for those who didn't know how it used to perform. One of the reasons why I have chosen to use Audacity is it's nature of offering solid basic features without resource hungry gimmicks and I would love to see it continue on that path.

**Comment by Tantacrul** [comment] 2022-10-29 21:14
> To me the file size is not the main issue, the first and foremost issue is the significant performance degradation due to increased processing requirement of smart clips.

This is also a legit concern and really shouldn't be happening, so I'll check on that too. Again, turning off the feature isn't the answer. Fixing performance & file size knock-on effects is clearly what's needed.

**Comment by Tantacrul** [comment] 2022-10-29 21:27
I have updated the issue to focus on file size / performance. Investigation will be needed for the latter. I've also cleared away a lot of conversational noise so our developers can focus on the meat of the reported issues.

**Comment by petersampsonaudacity** [comment] 2022-10-31 12:45
I have spent some time experimenting with a 2-hour stereo file (2.5 GB), adding lots of new tracks and copy&pasting many "small" clips all over the place - and I am satisfied that there is no exponential growth above the 2.5GB, nor any apparent decrease in performance.

However if I select a 3 minute "song" from the 2-hour stereo track and then open a new project and paste that song into the new project it ,as we now well know, copies the full 2-hour smart clip.  

The downsides to this are:
a) it takes 52 seconds (YMMV) to copy over the  "3 minute" song - but while it is doing it Audacity looks as though it is hung and can, sometimes but not always, display the Blue-Circle-Of-Death - there is no progress message shown to the user to indicate that something is happening.
b) the new 3 minute project also occupies 2.5GB on the disk.

### Recommendation

So @Tantacrul 's suggestion to offer the user who is pasting a partial clip to a nee project the option to copy just the selection duration would be most welcome.  

But a progress dialog with a progress bar would also be great if the user is making large copies into a new project.

**Comment by dozzzzer** [comment] 2022-10-31 13:31
>Let's verify that copying does not increase the file size

It **does** increase the file size for me in 3.2.1 and the latest release branch build, both on macOS and Windows

**Comment by crsib** [comment] 2022-10-31 13:32
Please provide the steps. It appears that it works fine for Peter

**Comment by dozzzzer** [comment] 2022-10-31 13:34
> Please provide the steps. It appears that it works fine for Peter

1. generate a 1h chirp/tone
2. copy a small portion of it (15-16s long in my case)
3. ctrl (cmd) + N
4. ctrl (cmd) + V
5. save the project and check its size

Act. result: the file size in my case is around 634 Mb

**Comment by petersampsonaudacity** [comment] 2022-10-31 15:47
### 2 hour stereo chirp weighing in at 2.5GB
![image](https://user-images.githubusercontent.com/50205984/199049572-00cddb5e-63db-4125-b655-963a5a5c731a.png)
![image](https://user-images.githubusercontent.com/50205984/199049890-a1b461a9-8915-4e7d-a820-92998fa7ca99.png)


### After a lot of cut&paste

**Comment by dozzzzer** [comment] 2022-10-31 15:48
Please ignore my previous comment: I was trying to copy and paste portions of the clip to a new project.
When copying/splitting a long clip within the same project, it doesn't massively increase its file size. 
Checked on macOS as well as Windows.

**Comment by petersampsonaudacity** [comment] 2022-10-31 16:18
But when I do some processing the file size does start to increase.  I selected and amplified down the whole project (and the performance on that is noticeably slow)
![image](https://user-images.githubusercontent.com/50205984/199056560-6b439b20-a608-4b3e-9c9a-f671878cdd3c.png)
![image](https://user-images.githubusercontent.com/50205984/199056809-82afab35-1af1-4a7b-b98b-b0156cb74769.png)


And after saving and closing the project I end up with a VERY large project of nearly 9GB:
![image](https://user-images.githubusercontent.com/50205984/199057197-94315321-8c35-468c-8afd-a4b52de661ab.png)

**Comment by petersampsonaudacity** [comment] 2022-10-31 16:42
So my conclusions from this are:

a) if all you are doing is copy&pasting bits of clips and/or moving clips around then the data size does not increase exponentially

b) However as soon as you start to do processing of the clips then the data size starts to grow alarmingly

_On the basis of this, I personally would probably not be using "smart-clips"._

**Comment by Tantacrul** [comment] 2022-10-31 19:17
Again, the problem isn't smart clips. The problem is just optimising for the new system. Can we please just stop jumping to the conclusion that we need to disable smart clips? 

he obvious solution to the problem described is that you'd only apply the processing to the visible bits of audio.

Even then, we're getting into serious edge case territory.

**Comment by crsib** [comment] 2022-10-31 20:05
I was pretty confident that we only apply the destructive processing to the visible part only. It is quite odd that we don't

**Comment by Tantacrul** [comment] 2022-10-31 20:57
This is also - without doubt - a separate bug. @petersampsonaudacity - would you mind raising it when you have time?

**Comment by petersampsonaudacity** [comment] 2022-11-01 09:16
> I was pretty confident that we only apply the destructive processing to the visible part only. It is quite odd that we don't

I believe that @crsib Dmityr is correct

1. Generate a 30 second chirp
2. select from 20-20 secs
3. Edit>Remove Special>Trim
4. Amplify the signal down
5. un-trim the clip on the left and the right
6.  Observe: 0-10s and 20-30s have been unchanged by Step 4

![image](https://user-images.githubusercontent.com/50205984/199200795-ad2116e5-6010-4a75-9892-1b43b5b973a0.png)

**Comment by petersampsonaudacity** [comment] 2022-11-01 09:24
> This is also - without doubt - a separate bug. @petersampsonaudacity - would you mind raising it when you have time?

@Tantacrul  - I am unsure what you have in mind as "a separate bug" - can you please clarify ...

**Comment by vsverchinsky** [comment] 2022-11-01 09:43
@petersampsonaudacity 
In your project after effect was applied destrictively, you have: 2 hours of the original data hidden in trimmed area of the clips + 2 hours of the original data modified by applying effect destructively (1 track in the list) + ~2.5 hours of data modified destructively on the other tracks, which yields ~6.5 hours of unique data. This matches the project's size growth.

**Comment by Tantacrul** [comment] 2022-11-01 10:16
> > This is also - without doubt - a separate bug. @petersampsonaudacity - would you mind raising it when you have time?
> 
> @Tantacrul - I am unsure what you have in mind as "a separate bug" - can you please clarify ...

Sure. What I mean is that you are introducing a new issue when describing problems with applying destructive effects. It is not relevant to this issue so should be logged separately so as not to confuse the developer who takes this issue on. This issue is now completely about the UX and performance of copying bits of large clips into new projects.

**Comment by crsib** [comment] 2022-12-07 13:23
Copying clips within a project doesn't create a data copy.

**Comment by vsverchinsky** [comment] 2022-12-07 13:29
> b) It is unclear to me whether or not the user's choice for "Selected only" or "Whole" is sticky and retained/remembered if they have ticked the "Don't show me this again" check-box.

I'll update dialog texts shortly

> c) if the user has checked the "Don't show me this again" check-box - then there appears to be no way for the user to set this dialog to be displayed again (except with a Tools > reset Configuration which may be way more drastic than the user requires).

There should be an option under `Tracks Behaviors` section
![image](https://user-images.githubusercontent.com/20165230/206191706-a262053b-9e77-4e99-a5f2-5cac0a3a4df3.png)

**Comment by petersampsonaudacity** [comment] 2022-12-07 13:36
> Copying clips within a project doesn't create a data copy.

If I copy a small clip to another track (or even in the same track) - then I get a fully expandable smart-clip which can be expanded to the full length of the original clip.

Surely that then leads to the project becoming bloated - or have I got that wrong

**Comment by crsib** [comment] 2022-12-07 13:45
There is no data copy performed in this case. The new data will be created only when you perform destructive editing.

**Comment by petersampsonaudacity** [comment] 2022-12-07 13:57
@vsverchinsky   Vitaly, the new addition to **Tracks Behaviors** prefs is misleading in its labeling of "**Wave Track**"  - it really should be something like "**Audio Track**"

It's not just waveform tracks that can have selections copied, Spectrogram view also can be copied.

**Comment by DavidBailes** [comment] 2022-12-07 14:16
Some comments on the dialog:
1. You should be able to close the dialog by pressing Esc, but you can't.
2. I'm not sure why its title is clip copy. The options presented are for how the data on the clipboard is pasted. The user could have done either a copy or a cut to get stuff on the clipboard.
3. I think that a common users understanding of the question in the dialog might be that if they choose whole, then the whole original clip is pasted and all of it is visible. I suspect it may not be possible to make it more easily understandable without making the text slightly longer.  
4. Minor point, but the text for the check box should include an access key.

**Comment by vsverchinsky** [comment] 2022-12-07 19:53
@petersampsonaudacity I've updated PR which fixes the bug you've mentioned and changed text in the dialog. Other fixes/changes will follow

**Comment by petersampsonaudacity** [comment] 2022-12-13 12:53
This should be ameliorated by @vsverchinsky 's latest branch build, his pull request:
https://github.com/audacity/audacity/actions/runs/3684872982

Vitaly has added the requested clip copy dialog and associated Tracks Behaviors prefs from 
 **Add prompt dialog when copying clips between projects #4004** 

I have tested those changes on W10 with Vitaly's branch build and they look good to me

**Comment by petersampsonaudacity** [comment] 2023-01-01 15:15
@vsverchinsky @crsib 

what is the current status of this please?  I ask as we are 
a) losing some users to other apps
b) getting users reverting to older versions of Audacity
neither of which is ideal

The functionality works fine for me (as a sighted user) but I'm not sure if @DavidBailes  accessibility suggestions have been made yet,.

-----------------------------------

I'm also finding the Prefs change a little clunky:
![image](https://user-images.githubusercontent.com/50205984/210175451-39d1e7ca-3708-4a00-8a71-7a61fe74f657.png)
Rather than the three radio buttons I would have thought that a single checkbox, say:
>Paste selected audio only

And personally I would prefer the default for that to be checked "**on**"

All the other settings in this preference dialog rely on just a checkbox and most are just as complex as this new one

Tagging @Tantacrul and @DilsonsPickles and @LWinterberg as this is a design/UX matter

**Comment by LWinterberg** [comment] 2023-01-18 09:49
> what is the current status of this please? 

It's under review and on track for Audacity 3.3

> All the other settings in this preference dialog rely on just a checkbox and most are just as complex as this new one

and do so to a fault IMHO. Each requires you to untangle several bits of information: 

* What is this term (smart clip, cut line, selection edge, etc)?
* What scenario am I imagining?
* What does this option do when I leave it on?
* What does the option do when I have it off?

In some cases, a user can be expected to be able to figure this out on their own (if in doubt: test it with users!). But especially once special terms get introduced, it is impossible to untangle without consulting the manual: What is a simple solo button? Is a cut line the thing you get when splitting a clip? Is it "Enable dragging (selection edges)", "Enable (dragging selection edges)" or "Enable (dragging selection) edges"?

So yeah, while something like `Paste smart clips between projects [yes/no/ask]` may be possible, it's an olympic exercise in understanding and imagining Audacity.

**Comment by dozzzzer** [comment] 2023-02-08 20:05
An unwanted horizontal scroll bar appears in **Preferences > Track behaviors** on macOS:

![2023-02-08_20-57-34 (2)](https://user-images.githubusercontent.com/70063970/217638181-cab2bcd7-effb-4e25-8ee7-bfa92f7a72ea.gif)

**Comment by dozzzzer** [comment] 2023-02-10 08:08
Another thing that may possibly be a separate issue, but I feel like it's worth to be mentioned here:

When clicking Cancel in the paste progress dialog, it doesn't terminate the process and ends up pasting the clip anyways.

STR:
1. Generate 3h of noise
2. Copy a region
3. Ctrl + N
4. Ctrl + V
5. Select "Smart clip" > Continue
6. Click the red cross button in the upper left of the progress dialog

<img width="285" alt="image" src="https://user-images.githubusercontent.com/70063970/218036564-7f9482e7-d29f-4d40-b617-8a546141f145.png">

As a result, the clip gets pasted anyway, ignoring the fact that it was canceled.

**Comment by petersampsonaudacity** [comment] 2023-02-10 09:44
Testing on W10 with @vsverchinsky 's  branch build:  

Eventually I get the same result i.e. the clip is erroneously pasted ignoring the request to cancel the copy into the new project.

BUT in the meantime Audacity appears _(to the user at least)_ to go into a hang state, which is not good.

![image](https://user-images.githubusercontent.com/50205984/218058413-cdeb8c77-6226-46a2-8923-0c787615b5e9.png)

**Comment by dozzzzer** [comment] 2023-02-10 11:52
@petersampsonaudacity 
No need for a separate ticket. For now, we're simply gonna get rid of the red cross button.

**Comment by petersampsonaudacity** [comment] 2023-02-10 17:18
Testing on @vsverchinsky 's latest branch build:  audacity-win-3.3.0-alpha-20230210+429a3c0-x64

I confirm that the Copy dialog no longer has the "X" to cancel the process

BUT consider this use case
1. Generate a five hour chirp to simulate a long recording project
2. select a three minute "song"
3. Ctrl+N to open a new project
4. Ctrl+V to paste the entire smart clip in (the default setting in the dialog)
5. Observe: this takes 2min 24secs on my machine with _**NO**_ longer any ability to interrupt this 

If you make a mistake and intended only to copy in just the selection (which takes less than a second) 0t's like watching paint dry as you wait !

Removing the "X" cancel as a "fix" seems a very kludgy approach and poor UX.

**Comment by Tantacrul** [comment] 2023-02-10 17:52
@petersampsonaudacity - as pointed out, the 'X' didn't work anyway, so removing it isn't a bad UX decision. It removes a miscommunication that confuses users.

I suggest we consider the potential adding of a 'cancel' button (properly labelled) separately.

**Comment by Tantacrul** [comment] 2023-02-10 17:53
Also, if / when we do create a 'Cancel' button, it should be a properly labelled button, not a 'close' button.

**Comment by dozzzzer** [comment] 2023-02-20 17:13
Verified

**Closed** 2023-02-20 19:20 UTC
Labels: bug, P2, Design / UX, regression, Clips

**Comment by petersampsonaudacity** [comment] 2023-02-21 16:16
I have added this changed behavior to the Tracks Behaviors preferences page
https://alphamanual.audacityteam.org/man/Tracks_Behaviors_Preferences

![image](https://user-images.githubusercontent.com/50205984/220400028-7339512f-e7bf-4679-b147-23cebc380050.png)
