### ISSUE TITLE
Convert VST3 effects to new stateless system

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#2606] opened 2022-03-01 13:22 UTC
- [x] #2969
- [ ] #3313
- [ ] #3306
- [ ] #3307
- [ ] #3308

**Comment by pietro68** [comment] 2022-05-06 13:37
- [ ] define the settings struct, to capture VST3 parameters
- [ ] write FetchSettings method, to get settings from the plugin instance
- [ ] write StoreSettings method, to set settings to the plugin instance

**Comment by Paul-Licameli** [comment] 2022-05-06 14:29
I recall these non-obvious details were discovered in conversation with @vsverchinsky:

- `ComponentHandler` objects may be created and destroyed with opening and closing of dialogs (don't need long life), so are part of Validator
- The `performEdit` override happens during GUI event callbacks, and is where EffectSettingsAccess should be used
- The duplicate inter-thread communication mechanism (uses of `.exchange`) will be removed, and the `Access` class in `RealtimeEffectState.cpp` will handle that instead
- `VST3Effect::LoadSettings` should not need a `ComponentHandler` just to retrieve values from the config and put them into `EffectSettings`
- Our subclass of `IParameterChanges` needs to be reimplemented "somehow" (details not yet clear) to detect only the difference between before-and-after versions of EffectSettings, and send that to the VST libraries
- `VST3Effect::ProcessBlock`, also now using `getPendingChanges`, is only on the path of single-threaded, destructive effect processing, without concurrent changes of settings; therefore, it might be simplified (use a different `IParameterChanges` subclass?)

That's my brain dump of details.  These might become sub-sub-tasks in broken-out issues later.  Some related to the Validator; others, to "Elimination of duplicate inter-thread-communication" which I might make a main item in the checkbox list.

**Comment by vsverchinsky** [comment] 2022-05-06 14:52
> ComponentHandler objects may be created and destroyed with opening and closing of dialogs (don't need long life), so are part of Validator

Theoretically yes, it is said that IComponentHandle is resposible `transfer of parameter editing to component (processor) via host` and , but at the same time it is marked as `mandatory` [https://steinbergmedia.github.io/vst3_doc/vstinterfaces/classSteinberg_1_1Vst_1_1IComponentHandler.html#details](url)
Maybe UI is not always the reason for parameters to change?

>Our subclass of IParameterChanges needs to be reimplemented "somehow" (details not yet clear) to detect only the difference between before-and-after versions of EffectSettings, and send that to the VST libraries

As far as know there is only single source of parameter change: via `IComponentHandler`, usually begin/end are invoked only for those parameters that have changed. 

>therefore, it might be simplified (use a different IParameterChanges subclass?)

Yes, it's possible

**Comment by Paul-Licameli** [comment] 2022-05-06 16:20
Maybe ComponentHandler can have a longer lifetime if necessary, but it  can hold a changing pointer to EffectSettingsAccess which may sometimes be null.

 But then I think it must be associated with the Instance, not the stateless Effect object, and more than one longer lived ComponentHandler may coexist

**Comment by Paul-Licameli** [comment] 2022-06-03 17:18
My thoughts after talking to @pietro68 today and studying the code; let's us three talk again on Monday.

The model I'm trying to use in the new framework is this:

- There is some state in `EffectSettings`, managed by `EffectSettingsAccess`, which is, for `EffectUIHost` in the main thread, just an abstraction of a variable with a getter and a setter function.
- The functions that load sets of settings (for import, defaults, user presets, factory presets) should be written just to mutate a given `EffectSettings` object, and trust the framework to do the rest of the communication.
- The changes of settings need to propagate, one way, to dialogs -- and the details of that should be implemented for VST3 (or any other protocol) in just one place, in the `TransferDataToWindow` override, which at a later stage of the transformation, becomes the `UpdateUI` override of the Validator object.
- The changes need to propagate another way, inter-thread, which is managed as implementation details of `EffectSettings` subclasses; then, that `EffectSettings` is made available to the various overrides named `::Realtime*`.

`SyncParameters` is a cause for some doubt and confusion: and I think the problem is that it unites different responsibilities that should be separated according to the plan above.

- It is called in `LoadUserPresets` and @pietro68 tells me @vsverchinsky says, that is necessary to update the dialog.  But if that is true, then it should have been called also for loading imported settings, defaults, and factory presets.
- It is not only updating the user interface, but also doing the inter-thread communication of settings by the other mechanism in the `internal::ComponentHandler` class.
- It is also called when initializing the dialog in `PopulateUI`.

My recommendations for the present stage are:

- The call is removed from `LoadUserPresets` but added to a new `TransferDataToWindow` override, which will cover the problem of UI update also for imports, defaults, and factory presets.
- Other calls remain as they are.
- The first stage of transformation of VST3 effects will be written and tested.

After that, in another stage of transformation:

- Eliminate the redundant special case inter-thread communication for VST3, relying instead on the more generalized system in `RealtimeEffectState::Access`.
- `UpdateUI`, as for AudioUnit effects, will use `StoreSettings` to update the `EffectInstance` object (which means the `mEffectComponent` object?).
- `PopulateUI` is like `UpdateUI`.
- The other uses of `SyncParameters` are replaced with code in the worker-thread `::Realtime*` functions that then determine the pending changes to communicate to the effect component (the `EffectInstance`?), in `VST3ProcessBlock`.

**Comment by Paul-Licameli** [comment] 2022-06-09 00:46
I understand now that it is this line in `VST3Effect::VST3Effect`:
```
      mEditController->setComponentHandler(mComponentHandler);
```

that sets up for Steinberg to call back into whatever methods we implement for the transferring of parameter changes to the audio processor, and those methods may be called even if we never do so directly as now in SyncParameters.

**Closed** 2022-08-23 10:38 UTC
Labels: Task, Effects
