### ISSUE TITLE
Seeking left at start while playing causes timeline misalignment

### ISSUE THREAD

**Issue by tjkirch** [audacity/audacity#5876] opened 2024-01-20 04:53 UTC
### Bug description

I was learning Audacity hotkeys and tried out "Seek left (long period) during playback" which is shift+left by default.  I hit shift+left shortly after starting playback, and was surprised to hear that the audio restarted from 0 (as expected) but the play head was gone, only showing up almost 15 seconds later, scrolling in from the left and misaligned with what was playing.  (In this "negative play head" state, the selection toolbar shows the time as "--h--m--.---s".)

### Steps to reproduce

1. Open Audacity and import an audio file
2. Hit play
3. Hit the left arrow key, or shift+left, until the play head disappears (goes negative)
4. Listen to the audio playing versus the play head location (when the play head reappears)

### Expected behavior

1. I do not expect to be able to seek left past 0 (in other words, the play head shouldn't go left off the screen) assuming the start of the track is aligned to 0.
2. I expect the play head to always point at the playing audio.

### Actual behavior

1. I can seek left beyond 0.
2. The audio always starts playing at 0 (this part is correct) but the play head is negative, so nothing should be playing.  When the play head hits 0.0, the audio has already been playing for several seconds (however long you seeked backward) so they're misaligned.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

(Not sure whether this happens on other operating systems, but I assume so.)

**Comment by DavidBailes** [comment] 2024-01-20 09:40
This is a regression wrt Audacity 3.0.5

**Comment by DavidBailes** [comment] 2024-01-20 09:53
Appears to be a duplicate of https://github.com/audacity/audacity/issues/2133

**Comment by tjkirch** [comment] 2024-01-20 16:50
> Appears to be a duplicate of https://github.com/audacity/audacity/issues/2133

Agreed! Thank you for looking.

**Closed** 2024-01-20 16:51 UTC
Labels: bug, regression
