### ISSUE TITLE
note labels (C2 etc) on y-axis for spectrogram

### ISSUE THREAD

**Issue by tpapp** [audacity/audacity#978] opened 2021-06-14 07:25 UTC
I am using Audacity to transcribe music using spectrograms.

Displaying named notes of a chromatic scale (eg A2 = 110Hz, A#2 = 116Hz, ...) on the y-axis of spectrograms would be useful to identify notes. These could be shown instead of or in addition to the frequency.

Customizations of this could include 

1. changing the A4 frequency (default 440Hz), or
2. possibly custom scales (user could specify notes across an octave and have them transposed for all octaves, or load a frequency-label table from a file),
3. horizontal rulers/guides at notes across the spectrogram

but even the simple default above would help a lot.

It is sufficient if this is done for the log scale, otherwise labeling the low end gets tricky because labels overlap.

**Comment by LWinterberg** [comment] 2022-03-03 11:58
duplicate of #445

**Closed by LWinterberg** 2022-03-03 11:58 UTC
Labels: Enhancement Request, spectrogram / spectral toolbar

**Comment by KoenT-SS** [comment] 2024-06-12 12:21
I was also looking for an option/setting for this myself today, and found this issue.
But apparently this issue here is closed, and the duplicate it mentioned #445 is also closed...
So did this feature request get totally removed now, or am I missing something (perhaps yet another ticket still tracks this)?

This would be a very valuable (and kind of expected) feature to have for musical audio (in addition to the ticket to make the x axis of the "plot spectrum" window zoomable, which is #2250 and kind of related, as they are both about better usability of the frequency axis display).
