### ISSUE TITLE
The beats&measures ruler doesn't update denotations accordingly when changing time signatures (macOS)

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4486] opened 2023-04-04 09:58 UTC
### Bug description

When changing time signatures from, say, 4/4 to 16/16 or 8/8, the ruler denotations should remain the same while, in fact, the ruler shows wrong beats and bars denotations, and only updates accordingly after a click anywhere off the toolbar.

### Steps to reproduce

1. launch [this build](https://github.com/audacity/audacity/actions/runs/4599859841)
2. enable **Time Signature** toolbar
3. make sure it reads 4/4
4. now enter '8' in the upper time signature (UTS) text box **without pressing Enter**
5. select '8' as a lower time signature (LTS) value
6. observe the ruler denotations
7. now left-click anywhere outside the toolbar

### Expected behavior

As soon as the LTS value is selected, the ruler updates accordingly.

### Actual behavior

The ruler shows wrong beat and bar denotations when LTS is selected;
The ruler shows correct denotations after clicking anywhere outside.

It seems that the numerator – UTS – doesn't get updated unless submitted either by pressing the Enter key or by clicking outside, which results in displaying the denotation for 4/8 (if referring to the STRs above) not 8/8

https://user-images.githubusercontent.com/70063970/229758050-95322eed-c373-4cbe-bd1d-31744ad3997f.mp4

### Audacity Version

other https://github.com/audacity/audacity/actions/runs/4599859841

### Operating system

macOS

**Comment by crsib** [comment] 2023-04-26 09:03
I cannot reproduce this issue (reliably) anymore @dozzzzer

**Comment by dozzzzer** [comment] 2023-04-26 11:31
@crsib it remains to be the case on macOS only

**Comment by LWinterberg** [comment] 2024-10-15 11:28
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.

**Closed by LWinterberg** 2024-10-15 11:28 UTC
Labels: AU3-bug, P4, macOS, Music
