### ISSUE TITLE
Latest 64 bit version Crashes on Launch

### ISSUE THREAD

**Issue by TheOriginalBytePlayer** [audacity/audacity#3731] opened 2022-10-01 06:47 UTC
### Steps to reproduce

1 Download latest version on Windows 10
2. Install It
3. Double-Click it to launch

Boom.

### Expected behavior

It should launch

### Actual behavior

It crashes almost instantly.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

[Audacity Crash log.zip](https://github.com/audacity/audacity/files/9689729/Audacity.Crash.log.zip)

**Comment by petersampsonaudacity** [comment] 2022-10-01 07:50
I cannot reproduce this on W10 with 3.2.0 - launches and runs fine for me on W10.

**Comment by LWinterberg** [comment] 2022-10-01 11:37
This was fixed by https://github.com/audacity/audacity/pull/3712 and will be put in a update in the very near future. In the meantime, you can delete the audacity.cfg to make it work

**Closed by LWinterberg** 2022-10-01 11:37 UTC
Labels: bug
