### ISSUE TITLE
 Import: Incorrect handling over 0 dB

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1553] opened 2021-08-29 15:44 UTC
**Describe the bug**
Import: Incorrect handling over 0 dB

This was originally logged on Bugzilla as P3 2730
https://bugzilla.audacityteam.org/show_bug.cgi?id=2730

**To Reproduce**
1) Create an MP3 that has a peak level of +24 dB.
2) Check that it plays correctly in VLC (with the volume turned down low)
3) Import into Audacity
4) Observe that the waveform becomes corrupted when the signal level gets very high.

**Expected behavior**
Correct handling of the audio

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: all OS
 - Version all

**Additional context**
None

**Comment by LWinterberg** [comment] 2023-04-10 19:48
I cannot reproduce this anymore, it may have been fixed with the transition from mad to mpg123 as the importer

**Closed by LWinterberg** 2023-04-10 19:48 UTC
Labels: Could not reproduce, bug, P3
