### ISSUE TITLE
(macOS) Crash when launching AUMultibandCompressor on 3.5

### ISSUE THREAD

**Issue by gitgasm** [audacity/audacity#6262] opened 2024-04-11 22:02 UTC
### Bug description

Attempting to use AUMultibandCompressor results in crash every time

### Steps to reproduce

1 - open audio file
2- select audio
3 - open AUMultibandCompressor

### Expected behavior

AUMultibandCompressor should appear, instead app crashes

### Actual behavior

Crash with Exception code 0x1

### Audacity Version

latest beta

### Operating system

macOS

### Additional context

Operating system: Mac OS X
                  14.4.1 23E224
CPU: arm64
     10 CPUs

GPU: UNKNOWN

Crash reason:  EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
Crash address: 0xa0
Process uptime: 87 seconds

**Comment by LWinterberg** [comment] 2024-04-12 08:37
Duplicate of #5799

**Closed by LWinterberg** 2024-04-12 08:37 UTC
Labels: bug
