### ISSUE TITLE
Track disappears when playing

### ISSUE THREAD

**Issue by tkozybski** [audacity/audacity#6959] opened 2024-07-24 11:20 UTC
### Bug description

When playing a track, it visually disappears after several seconds. You have to resize the window to bring it back, until it breaks again.
[Recorded bug.webm](https://github.com/user-attachments/assets/dba09a3b-b009-42ea-a42d-9e39277a7ee3)

### Steps to reproduce

1. Play a clip
2. Wait enough time (5-30 seconds)

### Expected behavior

Not disappearing?

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

Arch Linux, Audacity version 3.6.1

**Comment by dozzzzer** [comment] 2024-07-24 12:23
I couldn't reproduce it on Ubuntu 22.04 w/ Audacity 3.6.1.

**Comment by dozzzzer** [comment] 2024-07-24 12:24
@tkozybski did you build it from sources?

**Comment by tkozybski** [comment] 2024-07-24 12:27
No, it's from the Arch repo. Is there any debug options I can use to see if there are any logs?
It is not occurring with version 3.5.1

**Comment by tkozybski** [comment] 2024-07-24 12:29
I also tested with both X11 and Wayland. Same issue.

**Comment by tkozybski** [comment] 2024-07-24 12:39
@dozzzzer I now noticed that this only happens when “Continuous scrolling” is enabled

**Comment by dozzzzer** [comment] 2024-07-24 13:17
@tkozybski [this PR](https://github.com/audacity/audacity/pull/6955) might fix your issue. It will be included in version 3.6.2, which we'll be releasing soon. Until then, you might want to try building it yourself and see if it works.

**Comment by Djhg2000** [comment] 2024-07-27 14:18
Can confirm with version `3.6.1+dfsg-1` on Debian Sid.

The same or a similar bug can also be triggered by quickly zooming in and out a lot with the scroll wheel, which I do very frequently as a part of my workflow (sample-matching short recordings, detailed editing of long recordings, etc).

**Comment by tkozybski** [comment] 2024-07-28 09:06
I just built Audacity from source, and can confirm that it is fixed in the 3.6.2 branch.

**Closed** 2024-07-29 02:04 UTC
Labels: Could not reproduce, bug

**Comment by irrationalpie7** [comment] 2024-08-10 21:59
Is there any timeline on when 3.6.2 will be released?

**Comment by gensfleish** [comment] 2024-08-26 12:07
If anyone has found an easier work-around than building audacity by oneself, I'd be happy to read about it. This issue absolutely kills my workflow.

**Comment by irrationalpie7** [comment] 2024-08-26 14:14
Not sure if this helps, but I looked into the PR that fixes this bug and it's something to do with the position of the right edge of either an audio clip or the view port, not sure exactly which, being divisible by a certain number. But I have run into the issue a lot less since I stopped horizontally scrolling my project, instead zooming in and out to travel and re-center where I need to look, and doing as much as I can super zoomed out. I can also often recover the screen if it disappears by reversing the most recent zoom command, changing the window size, and then returning to the window size I actually want, whereas just changing the window size seemed to have a much lower success rate and did not allow returning to the original window size/shape. I do still run into the problem when recording (possibly because at some point the new clip will be the exact wrong length?) but it was not being able to do pin-point edits that was really killing my workflow. That, and this one time one of the clips on a lower track must have been in the exact wrong spot/length with respect to the default zoom, and every single time I tried to scroll down to see that track without zooming, the project blanked
