### ISSUE TITLE
Playback. Unexpected amplification when replaying huge number of same tracks

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2515] opened 2022-02-04 16:22 UTC
**Describe the bug**
I don't know how common this case is. 
But it could bring a heart attack.

Seriously, this is amusing but extremely unexpected. 

**To Reproduce**

**_Turn off the master volume on your device or take off headphones. This is not a joke._**

1. Generate a pluck
2. Effects-Normalize to - 24 dB on peak
![image](https://user-images.githubusercontent.com/25851359/152560868-dc3dbfdb-28a8-442f-8b18-0c6da188c819.png)
3. Duplicate the tack many times up to 500-700 tracks
4. Turn any track to Solo and click the Play button
Peak stays still at -24 dB
![image](https://user-images.githubusercontent.com/25851359/152562294-442c6873-c8d0-41c0-ae87-0bde3199c4db.png)

**_Are you ready?_**

5. Turn off Solo mode and click the Playback button again
![image](https://user-images.githubusercontent.com/25851359/152562404-bb7baa55-b3d4-4a65-b398-e38152b8e667.png)

**Expected behavior**
Number of replayed tracks should not affect on output volume level.
In this case, even two plucks increase volume level from -24 to -18 dB

![image](https://user-images.githubusercontent.com/25851359/152564320-ed68c075-5d74-474e-92ff-dbf8b3f25e4d.png)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version 3.2

**Comment by LWinterberg** [comment] 2022-02-04 16:32
Unfortunately, while it's unexpected for unexperienced people, it's very expected if you know what you're doing. Mixing audio works by adding wave data together:it literally is just simple addition, if you have a tone at 0.5 amplitude and add a duplicate of itself, the resulting wave will have 1 amplitude = 0 dBFS (something something constructive interference). 

I'm not super sure what the best solution for this would be to educate people about this fact, but it definitely is not a bug - just physics at work

**Comment by Penikov** [comment] 2022-02-04 16:34
Ahah. I suspected that. Thanks @LWinterberg

**Comment by Penikov** [comment] 2022-02-04 16:46
Right!
There a the same waveforms. So this is just amplification.
![image](https://user-images.githubusercontent.com/25851359/152568498-a8891299-268a-442f-a3f9-d8fbbe7818ab.png)

**Comment by petersampsonaudacity** [comment] 2022-02-04 16:51
This is an issue that the late Gale Andrews was well aware of and wrote this Proposal ten years ag, which is in the Wiki _(not transferred to GitHub)_

Proposal Easy Avoid Clipping on many tracks
https://wiki.audacityteam.org/wiki/Proposal_Easy_Avoid_Clipping_on_many_tracks

**Closed** 2022-02-04 17:57 UTC
Labels: Known Issue
