### ISSUE TITLE
Effect grouping preferences should be reflected in the RT effects panel

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3866] opened 2022-10-27 14:15 UTC
### Your idea

Currently, whatever option you select for grouping the effects, it's only reflected in the main Effect menu. While in the RT effects panel, the effects are always grouped by author, no matter what is selected in the Preferences.

In order to remain consistent and ease up the navigation among the plugins, especially in cases when there're multiple different families of the same effect installed in the system, we need to reflect the grouping option set in Preferences > Effects menu in both places, including the RT effects panel.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/70063970/198310664-08516fb0-512f-4399-abdc-1e374f1349b5.png">

### Problem to be solved

Troublesome navigation through the list of the RT effects.

**Comment by petersampsonaudacity** [comment] 2022-11-14 12:30
Surely this is a duplicate of:   Effect grouping preferences not reflected in realtime effects menu #3311

**Comment by Ryan-Miller-Audacity** [comment] 2023-02-07 12:29
During testing I am finding that it is taking a full close/reopen of Audacity for the preference change to update in the realtime effects menu. The change is applied to the destructive effects menu instantly. Seems this needs a little more refinement to work exactly correct.

**Comment by dozzzzer** [comment] 2023-02-23 19:04
@vsverchinsky 
When changing **Realtime effect organization** option to "Group by category" in Preferences, in the RT effects panel appear some effects that aren't supposed to be there, such as: Delay, Limiter, etc.

I believe this issue is coupled with another one: https://github.com/audacity/audacity/issues/3423

Having this issue discoverable in yet another place now - RT effects panel - I think it needs to be addressed first.

**Comment by dozzzzer** [comment] 2023-02-28 17:07
> When changing **Realtime effect organization** option to "Group by category" in Preferences, in the RT effects panel appear some effects that aren't supposed to be there,

This is now fixed in PR #4171

**Comment by dozzzzer** [comment] 2023-03-02 11:44
@vsverchinsky  
Also, testing PR #4171 shows that the list of publishers isn't sorted by name (A>Z):

<img width="429" alt="image" src="https://user-images.githubusercontent.com/70063970/222419362-f2e4f0d5-ab14-47af-a8c1-463e6599cad3.png">

**Comment by dozzzzer** [comment] 2023-03-03 13:23
Tested

**Closed** 2023-03-03 19:02 UTC
Labels: Enhancement Request, Effects, feature tweak
