### ISSUE TITLE
[Bug] in version 3.5 quality selection does not work when exporting to ogg vorbis

### ISSUE THREAD

**Issue by NektoNektovich** [audacity/audacity#6511] opened 2024-05-27 14:21 UTC
### Bug description

I have to use version 3.3.3 because the new export interface does not allow the selection of ogg vorbis quality

### Steps to reproduce

1. click export audio
2. I choose ogg vorbis
3. I want to select a quality, for example q8 or q7, but the slider does not move, stuck on q10.
![Uploading 2024-05-27_17-23-44.png…]()

### Expected behavior

I want to select a quality, for example q8 or q7, but the slider does not move, stuck on q10.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

**Comment by dozzzzer** [comment] 2024-05-27 14:27
duplicate of https://github.com/audacity/audacity/issues/5626

**Closed by dozzzzer** 2024-05-27 14:27 UTC
Labels: bug

**Comment by NektoNektovich** [comment] 2024-05-27 14:34
> дубликат [#5626 ](https://github.com/audacity/audacity/issues/5626)

sad :( will have to stay on version 3.3.3 :(
