### ISSUE TITLE
Build failure on Linux with latest git master

### ISSUE THREAD

**Issue by evertvorster** [audacity/audacity#4879] opened 2023-07-06 00:57 UTC
### Bug description

Building Audacity from sources pulled from the latest git master (2023-07-06) fails. 

### Steps to reproduce

1. Checkout the latest git
2.   cmake -G "Unix Makefiles" ../audacity \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -Daudacity_use_ffmpeg=loaded \
        -Daudacity_use_vst3sdk=system

### Expected behavior

Complete Build

### Actual behavior

Build failure. 

The pertinent error in the build log is this:
```
[ 10%] Building CXX object libraries/lib-time-and-pitch/CMakeFiles/lib-time-and-pitch.dir/AudioContainer.cpp.o
/mnt/int/system/aur/audacity-local-git/src/audacity/locale/be.po:4472: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 1, the argument size specifier is invalid.
/usr/bin/msgfmt: found 1 fatal error
make[2]: *** [locale/CMakeFiles/locale.dir/build.make:140: Release/locale/be/LC_MESSAGES/audacity.mo] Error 1
make[2]: *** Deleting file 'Release/locale/be/LC_MESSAGES/audacity.mo'
make[2]: *** Waiting for unfinished jobs....
```

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

System software versions:
```
Operating System: Arch Linux 
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.10
Kernel Version: 6.4.1-AMD-znver2 (64-bit)
Graphics Platform: Wayland
Processors: 8 × AMD Ryzen 7 4700U with Radeon Graphics
Memory: 36.9 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: LENOVO
Product Name: 20T8001JUS
System Version: ThinkPad E15 Gen 2
```

**Comment by crsib** [comment] 2023-07-06 07:26
Arch has updated gettext. There is a PR to address this issue in QA. 

https://github.com/audacity/audacity/pull/4866

**Comment by crsib** [comment] 2023-07-06 09:55
Closing as a duplicate of #4847

**Closed by crsib** 2023-07-06 09:55 UTC
Labels: bug
