### ISSUE TITLE
inability to move tracks if they are increased to the maximum value, a white stripe on the upper channel of the track when moving the track after splitting without connecting.

### ISSUE THREAD

**Issue by AdventurerRussia** [audacity/audacity#2573] opened 2022-02-19 23:32 UTC
before version 3.04, it was possible to move tracks through the movement tool, even if they were maximized, it helped not to look at small points, now you can move up to a certain increase, then the opportunity disappears. 
![image](https://user-images.githubusercontent.com/14019010/154822601-bcb6edf4-18fe-424b-88a9-a13d798dbb0a.png)
---
- **a rare bug, it is not always possible to reproduce,**
Secondly, on version 3.1.3, a bug appears when you split the tracks with a special deletion without connection and you start to move, the upper channel becomes white, on version 3.0.4 this does not happen, there is no white stripe on the upper channel.
--
3.1.3 https://youtu.be/SqVoHZ73uq8
3.0.4 https://youtu.be/8YyJZgIuKzg

**Comment by AdventurerRussia** [comment] 2022-02-19 23:35
as for moving at maximum magnification, maybe there is a way to do this? Maybe I just don't know how?!

**Comment by petersampsonaudacity** [comment] 2022-02-20 12:49
I cannot reproduce this on W10 with 3.1.3 or the latest aplha test master I have for the upcoming 3.2.0

**Comment by Penikov** [comment] 2022-02-24 13:43
I've tried to reproduce this on Win 10 but didn't get the same result. I think this is a Win-11 specific issue, I'll check it in VM with Win 11.

**Comment by Penikov** [comment] 2022-02-24 13:43
I've tried to reproduce this on Win 10 but didn't get the same result. I think this is a Win-11 specific issue, I'll check it in VM with Win 11.

**Comment by LWinterberg** [comment] 2022-02-27 18:52
I can sometimes reproduce the clip handles disappearing, but I'm not sure how exactly. It's not always fully zoomed in, but always on the sample level, and I believe it usually happens with stereo tracks.

**Comment by LWinterberg** [comment] 2024-10-15 11:08
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.

**Closed by LWinterberg** 2024-10-15 11:08 UTC
Labels: AU3-bug, P3
