### ISSUE TITLE
Reset Configuration or changing Theme causes the meter annotations to become squished

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#6685] opened 2024-06-13 15:26 UTC
### Bug description
Now that the default Theme has changed for 3.6.0 using Reset Configuration or changing the Them causes the numerical annotations on the Playback and Recording toolbars to become squished.

a) Rolling your cursor over the meters will restore the numbers properly,.
b) Pressing Record will restore the numbers on the Recording Meter.
c) Pressing Play will restore the numbers on the Playback Meter.

This is a regression on 3.5.1 (and earlier Audacity versions)

### Steps to reproduce
1. launch latest alpha master for 3.6.0
2. Observe Meters have squished annotations

### Expected behavior
![image](https://github.com/audacity/audacity/assets/50205984/fb0b28f8-3c12-448f-83b0-def0a0642cb3)

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/09c1e13f-33ba-44e4-84dc-896a97bf2c64)

### Audacity Version
current master / alpha / nightly build:  audacity-win-3.6.0-alpha-20240613+eb40d2e-x64-msvc2022

### Operating system
Windows 10

### Additional context
Looks ropey

**Comment by dozzzzer** [comment] 2024-06-13 15:36
Duplicate of https://github.com/audacity/audacity/issues/6676

**Closed by dozzzzer** 2024-06-13 15:36 UTC
Labels: bug, regression
