### ISSUE TITLE
Effect Amplify: "New Peak Amplitude" has garbage value at startup

### ISSUE THREAD

**Issue by pietro68** [audacity/audacity#2780] opened 2022-04-08 11:00 UTC
**Describe the bug**
When using an Amplify effect, the "New Peak Amplitude" field will show a garbage value

**To Reproduce**
1. Start Audacity
2. create a noise track, select a bit of it
3. Effect | Amplify...

**Actual behavior**
field "New Peak Amplitude" will show a garbage value, i.e. a value which has no connection with the peak of the selected audio and the amplification value

**Expected behavior**
the above field should show what would be the new peak value if the selected amplification would be applied (hint: move the slider slightly, and bring it back to its initial position, to see what the value should be)

**Screenshots**
![Capture](https://user-images.githubusercontent.com/16491307/162422866-470bde5e-f9bf-4a70-93f5-9030d0386598.PNG)

**Additional information (please complete the following information):**
 - OS: Win10
 - Version: happens on master, commit hash 793cd28

**Comment by petersampsonaudacity** [comment] 2022-04-08 14:41
@pietro68   this is a duplicate of #2700

**Comment by SteveDaulton** [comment] 2022-04-08 19:34
The proposed fix does not reinstate the behaviour prior to this bug. Issue #2700 describes how the Amplify effect behaved in all previous versions of Audacity.

**Comment by petersampsonaudacity** [comment] 2022-04-09 11:44
> The proposed fix does not reinstate the behaviour prior to this bug. Issue #2700 describes how the Amplify effect behaved in all previous versions of Audacity.

See the Audacity Manual for the required behavior:
https://manual.audacityteam.org/man/amplify.html

where it clearly says:
>When the Amplify dialog first appears it shows in the Amplification (dB) box the amplification amount needed to create a New Peak Amplitude of 0 dB, thus maximizing the volume of the selected track. If this is your goal you can just click the OK button.
>
>Note that when applied to a single stereo track or to multiple tracks, Amplify shows the amplification needed to maximize the volume of the loudest track or channel and will apply that amount of amplification to all selected tracks and/or channels. In this way, Amplify preserves the relative volumes of the selected tracks and/or channels. This is different from the Normalize effect which can be optionally set to maximize the volume of each track or channel independently.

**Closed** 2022-04-12 07:49 UTC
Labels: bug, Effects

**Comment by dozzzzer** [comment] 2022-04-13 14:44
Tested.

- Win 10 x64
- [audacity-win-3.2.0-alpha-20220412+77aea2d-x64-msvc2022](https://github.com/audacity/audacity/suites/6087523642/artifacts/211013563)
