### ISSUE TITLE
The text inside the check box on the "Welcome to Audacity!" dialog is not visible when using the dark mode on Ubuntu 22 LTS.

### ISSUE THREAD

**Issue by abdullahfarwees** [audacity/audacity#5050] opened 2023-08-17 07:37 UTC
### Bug description

While using the Ubuntu dark mode, user unable to read the text "Don't show this again at start up".

OS info:
Distributor ID:	Ubuntu
Description: Ubuntu 22.04.2 LTS
Release: 22.04
Codename: jammy

### Steps to reproduce

To reproduce the issue, Keep the Ubuntu in Dark mode (settings->appearance->Dark)
1. Install fresh Audacity from Ubuntu Software
2. open the "Audacity" software
3. "Welcome to Audacity!" dialog box appear

### Expected behavior

"Don't show this again at startup" text should visible in any Ubuntu Dark appearance mode

![image](https://github.com/audacity/audacity/assets/11908787/69720be8-7820-458f-8432-2a98af8a2675)

### Actual behavior

"Don't show this again at start up" text Not visible in dark mode. 
<img width="478" alt="dark-mode" src="https://github.com/audacity/audacity/assets/11908787/0c4a8a3f-f7b8-4e22-8064-5a8a911b668b">

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

**Comment by petersampsonaudacity** [comment] 2023-08-17 08:39
Works fine on W10
![image](https://github.com/audacity/audacity/assets/50205984/956ca947-ec09-49e1-9d67-12937f77d1bd)

**Comment by LWinterberg** [comment] 2023-08-17 09:30
You may need to also put Audacity into dark mode via Edit -> Preferences -> Interface

**Comment by dozzzzer** [comment] 2023-08-17 12:34
Duplicate of #2024

**Closed** 2023-08-17 14:55 UTC
Labels: bug, Linux
