### ISSUE TITLE
Split New can create a spurious unwanted additional silent clip

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2846] opened 2022-04-20 15:35 UTC
**Describe the bug**
If you select a lop or part of a clip and extend the selection rightwards beyond the clip (but not so as to abut or overlap the next adjacent clip) the Split New causes a spurious unwanted additional silent clip to be created. 

And note the silent clip is in-named.

**To Reproduce**
1. Create a 30 second chirp
2. Split the clip at 15 seconds
3. Move the second clip rightwards by 15 seconds
4. Select from 10-20 seconds
5. Edit > Audio Clips > Split New
6. Observe: a spurious unwanted silent clip is produced from 15-20 seconds
7. Observe: the clip has no clip-name

**Actual behavior**
A spurious unwanted silent clip is produced

**Expected behavior**
No spurious unwanted silent clip should be produced

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/164269396-95a4d167-385e-4c6e-88ff-d9fbfa56f477.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version 3.2.0 latest master audacity-win-3.2.0-alpha-20220420+97d0c34-x64-msvc2022

**Additional context**
1) The first set of steps, above - blank space on the right appears to be a regression o 1.3.6 (or maybe 1.3.7-1.3.9 as I don't have those) - fails on 1.3.10 and later.

2) the second set of steps, below - blank space on the left appears to have been the case eve since Split New was introduced

**Comment by petersampsonaudacity** [comment] 2022-04-20 16:20
Selecting with blank space on the left of the clip produces a strand spurious result too.

1. Create a 30 second chirp
2. Split the clip at 15 seconds
3. Move the second clip rightwards by 15 seconds
4. Select from 25-30 seconds
5. Edit > Audio Clips > Split New
6. Observe: The 30-35 second split clip is moved to 25-30 seconds
7. 
![image](https://user-images.githubusercontent.com/50205984/164276953-1daac31e-b61c-4d79-b668-9fd15c841e0f.png)

**Comment by petersampsonaudacity** [comment] 2022-04-20 16:34
See also:   Split New fails with multiple partial clip selections #2816

**Comment by Connorbub** [comment] 2022-04-20 22:07
So just to be certain, the expected behavior is that we will never create a silent clip? If that's the case, then I believe the PR above should take care of that, as well as the issue with the end clip not lining up properly.

**Comment by Connorbub** [comment] 2022-04-20 22:14
For reference, here's the new behavior on the test case above:
![test1](https://user-images.githubusercontent.com/13750510/164333790-f82743a5-b5cc-4b91-a701-397053aa5767.png)

And here it is on a more complex test case:
![test2](https://user-images.githubusercontent.com/13750510/164333821-67ed521c-b5af-4b71-8423-c7754d191cc4.png)

**Comment by petersampsonaudacity** [comment] 2022-04-21 10:12
Testing on W1 with  @Connorbub branch build audacity-win-3.2.0-alpha-20220421+c693975-x64-msvc2022 

1)  It no longer appears to be creating the unwanted spurious silences

2) There is still an issue when the blank selection is before the clip

a) before Split New
![image](https://user-images.githubusercontent.com/50205984/164432569-f900ba54-2039-441f-b4b0-814b06fe29e5.png)

b) After Split New
![image](https://user-images.githubusercontent.com/50205984/164432754-b3b1a3a5-8bd8-4dbe-b247-04d6f6e3b51c.png)


3) This use case gets an odd result
c) before Split Cut
![image](https://user-images.githubusercontent.com/50205984/164432996-ca2fbc8d-3da0-4d5e-bfef-3e22616f3be4.png)

d) after Split Cut
![image](https://user-images.githubusercontent.com/50205984/164433179-0cc4eb00-c6a7-4957-b7e5-07e8d288fc76.png)

**Comment by Connorbub** [comment] 2022-04-21 16:24
@petersampsonaudacity I was indeed able to recreate the bug shown in parts a/b, but not the one you showed in c/d. Nonetheless, the new commit I just pushed seems to fix the issue seen in a/b on my machine. Since I can't seem to reproduce the issue, maybe someone else could check and make sure that the c/d bug is fixed as well?

**Comment by petersampsonaudacity** [comment] 2022-04-22 07:29
@Connorbub  - I cant test this as your branch build is not building - its current status is shown on GitHub as "**Action required**"

**Comment by LWinterberg** [comment] 2022-04-22 08:30
This is because we haven't merged anything from Connor yet, so I need to click a button to send CI to work.

**Comment by petersampsonaudacity** [comment] 2022-04-22 14:12
Testing on W10 with @Connorbub latest branch audacity-win-3.2.0-alpha-20220422+8d27b17-x64-msvc2022 

### Use Case with trailing silence
this now fails - it was ok with the previous buld
e) before

**Comment by Connorbub** [comment] 2022-04-22 17:40
OK, the latest commit may have finally made it work? It seems to work on all of your above test cases, but I was unable to reproduce the partial selection error so that may still be a problem.

By the way, thanks for testing my code so thoroughly. I definitely missed a lot of potential problems...

**Comment by petersampsonaudacity** [comment] 2022-04-23 08:22
Testing on W10 with @Connorbub latest branch build  audacity-win-3.2.0-alpha-20220422+026e1ca-x64-msvc2022 

All seems fine now with this latest branch build - _**ALL**_ use cases previously examined in this thread now work as expected.

There are no unwanted silences, no shiftings of audio position and no disappearing audio.

@LWinterberg @dozzzzer   - from a user-test perspective this looks good to go.

**Comment by petersampsonaudacity** [comment] 2022-06-09 09:39
@dozzzzer   testing on W10 with 3.0.3 latest alpha master  

I am now still seeing the issues I reported in the first two posts in this thread -  following the steps to reproduce in those pasts.

Accordingly this needs reopening

**Comment by petersampsonaudacity** [comment] 2022-11-09 12:17
Still the case on the latest 3.2.2 alpha:  audacity-win-3.2.2-beta-20221109+f0bb347-x64-msvc2022

**Comment by petersampsonaudacity** [comment] 2023-02-08 16:50
Testing on W10 wit @vsverchinsky 's branch build:  audacity-win-3.3.0-alpha-20230208+88d6d18-x64
which I assume is based on @Connorbub 's latest branch build.

This mow looks to be working properly in this branch build

**Comment by dozzzzer** [comment] 2023-02-10 13:58
Looks good on both Windows 11 and macOS 13

**Closed** 2023-02-14 13:56 UTC
Labels: bug, P2, regression, Clips

**Comment by petersampsonaudacity** [comment] 2023-02-14 15:25
Testing on the latest 3.3.0 alpha master:  audacity-win-3.3.0-alpha-20230214+ea8163f-x64-msvc2022

I confirm that this issue is properly fixed.
