### ISSUE TITLE
[Plugin issue] 

### ISSUE THREAD

**Issue by evertvorster** [audacity/audacity#4249] opened 2023-01-29 11:41 UTC
### Plugin

Calf Equalizer and Calf Deesser

### Plugin Format

VST2

### Plugin source

https://calf-studio-gear.org/ (but installed from Arch Linux repo)

### Bug description

In Audacity release 3.1.3, this plugin worked normally. 
When hitting "Play" button (now gone, replaced by "preview" button, I presume)  the plugin would show a spline representing the effect the plugin would have on the waveform of the audio, as well as displaying the waveform. 

In Audacity release 3.2.4, this spline and waveform are no longer displayed. 
I first thought it was an artifact of the qt branch, which I follow, but I see the same issue on the main branch and the 3.2.4 release. 

To confirm that this is not just an artifact of how I build it, I tested with the Appimage as well. It had the same issue. 

### Steps to reproduce

Record some noise
Select the area of interest
Run Calf 12 Band Equalizer

### Expected behavior

A nice spline displayed on the equalizer, as well as a waveform

### Actual behavior

No spline or waveform

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Architecture

64 bit Intel/AMD processors

**Comment by LWinterberg** [comment] 2023-01-29 15:30
Duplicate of #3314

**Closed by LWinterberg** 2023-01-29 15:30 UTC
Labels: bug, plugins
