### ISSUE TITLE
Audacity UI bug

### ISSUE THREAD

**Issue by TRNEEDANAME** [audacity/audacity#6976] opened 2024-07-27 18:30 UTC
### Bug description

The track view and some UI element become white

### Steps to reproduce

1. Get multiple tracks
2. have a clip with multiples divisions
3. zoom in and move aroud the clip

### Expected behavior

The track view should stay visible

### Actual behavior

[AudacityBug.webm](https://github.com/user-attachments/assets/ee27d1cf-890b-44bf-afc6-45ff51cc4eeb)

Video for easier understanding.
The audio works as intended, I can still select it, change it and such, it just makes it very difficult.
Zooming in or out does not fix the issue.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

Arch Linux, latest version, Desktop environment is KDE

**Comment by pgibler** [comment] 2024-07-28 05:22
Having the same issue here, also on Linux.

**Comment by kryksyh** [comment] 2024-07-28 14:00
@TRNEEDANAME @pgibler this is a duplicate of #6959 , fixed in 3.6.2, which will be released soon.

**Closed by kryksyh** 2024-07-28 14:00 UTC
Labels: bug

**Comment by pgibler** [comment] 2024-07-28 18:35
@kryksyh Thank you! Appreciate you and the team getting a fix in for this.
