### ISSUE TITLE
IME input (japanese/chinese character input) freezes Audacity

### ISSUE THREAD

**Issue by LuoZhongYao** [audacity/audacity#805] opened 2021-04-14 01:35 UTC
**Describe the bug**
Open Audacity, perform some operations, click menus or buttons or use shortcut keys, it is very likely that the GUI interface does not respond to any input. Check the task manager, Audacity is not dead, right-click on the taskbar to close, Audacity will still pop up Save the modification dialog, but still does not respond to any input 

**To Reproduce**
1. run audacity
2. some operations, etc click menu, click buttons, use shortcut key
3. audacity don't respond any input

**Expected behavior**
Audacity works normally 

**Screenshots**

**Additional information (please complete the following information):**
 - OS:Windows 10.0.19042.867
 - Version: Audacity 3.0.0

**Additional context**
It is easier to reproduce the problem by using shortcut keys

**Comment by LuoZhongYao** [comment] 2021-05-11 01:30
Is anyone tracking this issue? 3.0.2 version still exists, and this problem is very bad

**Comment by JamesCrook** [comment] 2021-05-13 18:54
What system language is your OS set to?  We did see problems with a bad interaction with a particular windows update (on Korean and Japanese systems).

**Comment by LuoZhongYao** [comment] 2021-05-15 00:44
> 
> 
> What system language is your OS set to? We did see problems with a bad interaction with a particular windows update (on Korean and Japanese systems).

Simplified Chinese

**Comment by petersampsonaudacity** [comment] 2021-05-17 13:34
I have transferred this issue to our Bugzilla bugtracker and thus will close this GitHub Issue in favor of that.
https://bugzilla.audacityteam.org/show_bug.cgi?id=2789
Bug 2789 - Windows: Simplified Chinese locale Audacity fails to respond

**Comment by mkht** [comment] 2021-11-24 12:51
This issue continues to occur in the latest version of Audacity 3.1.2.
I'm using the Japanese version of Windows 10 21H2.
I can't use Audacity at all because Audacity becomes completely unresponsive after I type any key once. This is a serious problem.

Is the team working on a fix?
I'll provide as much information as I can if needed.

**Comment by mkht** [comment] 2021-12-16 03:02
@petersampsonaudacity @JamesCrook 
Please allow me to ping.
I would like to hear about the status of this issue.
My organization is unable to use Audacity due to this issue.

**Comment by LWinterberg** [comment] 2021-12-16 07:55
as per https://github.com/audacity/audacity/issues/1618#issuecomment-989838081
> This problem can be solved by turning on the compatibility option of the IME on Windows 10.

**Comment by mkht** [comment] 2021-12-16 07:59
Thank you kindly for your help.
Is there any hope of a fix on the Audacity side?
I doubt that Windows will provide IME compatibility options for any length of time.

**Comment by LWinterberg** [comment] 2021-12-16 08:28
[Windows 10 still can run DOS applications](https://superuser.com/a/1184195), so there's a chance it'll stay around for some time still. We believe this may be an issue with wxWidgets, and since we are looking to ditch wxWidgets in the medium-term future anyway, we're not looking to fix this just now.

**Comment by SteveDaulton** [comment] 2022-02-16 10:01
I notice that both this bug, and https://github.com/audacity/audacity/issues/2419 have been closed, yet no mention of a fix. Is that intentional?

**Comment by imciner2** [comment] 2022-02-18 02:07
This bug looks open to me, and it is not actually an Audacity problem, it is either a full Windows problem or a wxWidgets problem (other programs that use wxWidgets also freeze in this same way under IME).

**Comment by mkht** [comment] 2022-05-01 12:28
Why is the Audacity team closing this issue without a fix or explanation?

**Comment by LWinterberg** [comment] 2022-05-01 13:46
This is a [known issue](https://github.com/audacity/audacity/wiki/Known-Issues) and a bug in wxWidgets. We won't fix it as we're planning to migrate away from wxWidgets.

**Comment by SteveDaulton** [comment] 2022-05-30 10:18
> a bug in wxWidgets.

Has that been confirmed? I don't see it logged on either the WxWidgets issue tracker or filezilla issue tracker, though I have seen many reports of the problem with Audacity.

**Comment by LWinterberg** [comment] 2022-05-30 12:13
It is a thing in [kicad](https://gitlab.com/kicad/code/kicad/-/issues/9882) and I believe someone (@DavidBailes maybe?) confirmed this behavior affecting other wx apps. 

If it isn't a wx-bug, then it seems like a large portion of programmers are all doing the same thing wrong :)

**Comment by SteveDaulton** [comment] 2022-05-30 13:06
OK, so it does seem to be an issue somewhere between Microsoft IME and wxWidgets 3.1.x.
As this issue won't be addressed in Audacity until some unknown time in the (far?) future of Audacity 4.x, can't anything be done to mitigate the issue? Perhaps linking a list of "known issues and workarounds" to the FAQ section of the Audacity manual?

**Comment by DavidBailes** [comment] 2022-05-31 08:50
> I believe someone (@DavidBailes maybe?) confirmed this behavior affecting other wx apps.

I don't remember it being me.

**Comment by LWinterberg** [comment] 2022-11-08 11:35
I found someone claiming to have found the root of this issue: 

> Okay. So the issue with label track edits is in Audacity. Label tracks don't use a standard Windows or wxWidgets edit control, and have instead a bunch of code to implement a basic text edit field. The root issue is in this code in **CommandManager.cpp**:
> 
> ```c++
>    // Convert the key down event to a unicode string.
>    wxString GetUnicodeString(const wxKeyEvent & event)
>    {
>       wxString chars;
> 
> #if defined(__WXMSW__)
> 
>       BYTE ks[256];
>       GetKeyboardState(ks);
>       WCHAR ucode[256];
>       int res = ToUnicode(event.GetRawKeyCode(), 0, ks, ucode, 256, 0);
>       if (res >= 1)
>       {
>          chars.Append(ucode, res);
>       }
> ```
> 
> Audacity is handling `WM_KEYDOWN` events (these are wrapped in `wxKeyEvent` objects), and then calling `ToUnicode` to convert key events to Unicode characters. This isn't the right way to get character input on Windows. The `ToUnicode` function doesn't cover all Windows input cases, even for standard Windows keyboards and IMEs. Instead, Audacity should be accepting `WM_CHAR` events and processing these ([MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/gg153546(v=vs.85).aspx)).
> 
> From the description in http://bugzilla.audacityteam.org/show_bug.cgi?id=1778, it sounds like similar issues are arising in macOS. See also discussion in http://forum.audacityteam.org/viewtopic.php?p=319325.

https://github.com/keymanapp/keyman/issues/523#issuecomment-358548571

(NB, the code has moved to [KeyboardCapture.cpp](https://github.com/audacity/audacity/blob/master/src/KeyboardCapture.cpp#L308))

**Comment by cartony** [comment] 2022-12-16 05:28
Is this ever going to be fixed? It's really frustrating, I've been waiting almost a year. It really interferes with my daily work. I work in both English and Japanese and if I ever accidentally tab into Audacity while working in Japanese it's an incredibly frustrating experience to open task manager, forcibly close audacity, etc , every time. It has happened to me three times today. It's not that easy to just "remember to switch languages before tabbing back"

**Comment by dozzzzer** [comment] 2022-12-16 13:46
> Is this ever going to be fixed?

Yes, it's scheduled for version 3.4 of Audacity which we plan to release sometime next year.

**Comment by mcdurdin** [comment] 2024-03-19 01:44
> I found someone claiming to have found the root of this issue:

That is a root cause analysis for a compatibility problem with Keyman, specifically just around editing labels (see also #5163), and is not related to the IME freezing issue described here.

**Comment by tanhoaian01** [comment] 2024-05-17 16:07
Hello, this bug still exists in May 2023. Whenever I switch from English to Microsoft Pinyin (Chinese mode), Audacity freezes and needed to be closed with Task Manager. Does anyone have any solutions or recommendations for a Chinese keyboard that works well with Audacity? I'm trying to learn Chinese and audiobook is important to my workflow. 

### Screen recording
OS: Windows 10 Pro 22H2
Audacity: 3.5.1

https://github.com/audacity/audacity/assets/133650669/68d5b431-554b-4577-927d-fcf34cb0d0e7

**Comment by LWinterberg** [comment] 2024-05-17 18:01
> Does anyone have any solutions or recommendations for a Chinese keyboard that works well with Audacity?

Allegedly This problem can be solved by turning on the compatibility option of the IME on Windows 10.

**Comment by JimLee168** [comment] 2024-09-25 10:08
Modify the following files yourself.
Testing in Traditional Chinese (倉頡 / 注音) executes normally.

### Files
```
src\AudacityApp.cpp
src\AutoRecoveryDialog.cpp
```

### Original
```
wxEventLoopBase::GetActive()->YieldFor(wxEVT_CATEGORY_UI);
```

### Modify
```
wxEventLoopBase::GetActive()->YieldFor(wxEVT_CATEGORY_UI | wxEVT_CATEGORY_USER_INPUT);
```

**Closed** 2024-09-26 20:26 UTC
Labels: bug, P2, crash / freeze, translation / i18n, keyboard
