### ISSUE TITLE
Chinese IME crashes application

### ISSUE THREAD

**Issue by popyoung** [audacity/audacity#3895] opened 2022-11-05 09:25 UTC
### Bug description

If I'm using an IME(Input Method Editor) like Microsoft Pinyin, when I press the keyboard, the application will get stuck.

### Steps to reproduce

1. open audacity
2. turn on Microsoft Pinyin(if you have got it, you can use the shortcut of win+space)
3. press any key(A, B, C, and even ctrl)

### Expected behavior

App will not get stuck

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by LWinterberg** [comment] 2022-11-08 11:37
Duplicate of https://github.com/audacity/audacity/issues/805

**Closed by LWinterberg** 2022-11-08 11:37 UTC
Labels: bug
