### ISSUE TITLE
Audacity crashes when pasting over a clip in 192k/24-bit

### ISSUE THREAD

**Issue by mapisilafi** [audacity/audacity#5792] opened 2023-12-17 14:13 UTC
### Bug description

My workflow involves copy-pasting from a multi-hour recording to individual tracks. I usually select-copy from the original and paste to another Audacity track on another Audacity window. If I directly paste on top of selected audio, the Audacity crashes and exits completely. If I delete the content of the track first, and paste on it only after deletion, it works fine. Happened several times. Sending crash report fails. 

<details>Here's the beginning of the crash dump:
Operating system: Windows NT
                  10.0.22621 2861
CPU: amd64
     family 6 model 158 stepping 13
     12 CPUs

GPU: UNKNOWN

Crash reason:  EXCEPTION_ACCESS_VIOLATION_READ
Crash address: 0x0
Process uptime: 676 seconds</details>

### Steps to reproduce

1. Open a large, multi-hour recording (192k/24b)
2. Select a few minutes of that recording
3. Copy using ctrl+c
4. ctrl+n for a new file
5. ctrl+v -> "only selected audio"
6. switch to the original project, copy another few minute snippet of the audio
7. switch back to the other Audacity window with a short audio clip (which is currently selected)
8. ctrl-v to paste over selected audio

### Expected behavior

Paste over should replace selected audio on the track.

### Actual behavior

Crash

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Not reproducible on macOS 14.2 as well as Fedora 39

**Comment by dozzzzer** [comment] 2023-12-18 13:55
I couldn't reproduce this on my Windows 11 machine, neither with a mono nor with a stereo track. @mapisilafi could you possibly share the screen recording depicting this issue?

**Comment by mapisilafi** [comment] 2023-12-18 18:18
Sure, here u are:
[audacity crash when pasting over existing clip.zip](https://github.com/audacity/audacity/files/13707153/audacity.crash.when.pasting.over.existing.clip.zip)

**Comment by mapisilafi** [comment] 2023-12-18 18:20
Btw: I previously opted out for ability to trim the copied snippet afterwards.

**Comment by mapisilafi** [comment] 2023-12-18 21:01
This is 100% reproducible on my computer.

**Comment by dozzzzer** [comment] 2023-12-19 11:20
Alright, I was able to reproduce the issue now. It will most likely get fixed in version 3.5 @mapisilafi

**Closed** 2024-03-15 10:56 UTC
Labels: bug, P1, crash / freeze, Windows
