### ISSUE TITLE
Separate macro commands for "Get Noise Profile" and "Apply Noise  Reduction"

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1443] opened 2021-08-09 09:01 UTC
**Is your feature request related to a problem? Please describe.**
"Noise Reduction" is very awkward to use in Macros.

**Describe the solution you'd like**
Two new commands:
1. Get Noise Profile
2. Apply Noise Reduction
(The names above are for illustration purposes only. "Noise Reduction Get Profile" and "Noise Reduction Apply" might be better)

**Describe alternatives you've considered**
There really isn't a workaround if you need to use Noise Reduction in a batch process.

**Additional context**
A common scenario is  that users have a bunch of voice recordings, where each file begins with a few seconds of "noise only". The user wants to run a batch process which includes:
1. Get a noise profile  from the first few seconds of  the file
2. Apply Noise Reduction to the entire file.

Recent related posts from the forum:
* https://forum.audacityteam.org/viewtopic.php?f=20&t=119624
* https://forum.audacityteam.org/viewtopic.php?f=20&t=119628
* https://forum.audacityteam.org/viewtopic.php?f=47&t=112504
* https://forum.audacityteam.org/viewtopic.php?f=40&t=118155
* https://forum.audacityteam.org/viewtopic.php?f=46&t=118166

**Comment by LWinterberg** [comment] 2022-06-10 19:43
duplicate of #1318

**Closed by LWinterberg** 2022-06-10 19:43 UTC
Labels: Enhancement Request, macros / scripting, Effects
