### ISSUE TITLE
'Windows protected your PC' - Microsoft Defender is blocking the running of the RC

### ISSUE THREAD

**Issue by Tantacrul** [audacity/audacity#1039] opened 2021-06-21 13:12 UTC
### Bug Description
Microsoft Defender is blocking the running of the RC

### Steps To Reproduce

- Download 32/64bit version of Audacity
- Try to open the executable file

### Current result
Windows defender popup appears: 'Microsoft Defender SmartScreen prevented an unrecognised app from starting. Running this app might put your PC at risk.'

### Build and OS info

- Windows x32;
- Windows x64;

**Comment by crsib** [comment] 2021-06-21 13:32
This is kinda won't fix issue. Or rather it will fix itself. The problem is - our certificate is new and our certificate is not EV. The Microsoft will pick it up shortly and the problem will be solved

**Closed** 2021-08-04 12:25 UTC
Labels: Bug severity: Low, P1, bug

**Comment by AnitaBats** [comment] 2021-08-04 12:31
resolved; no actions needed
