### ISSUE TITLE
Stop recording by the next click on the Recording button

### ISSUE THREAD

**Issue by MurzNN** [audacity/audacity#4442] opened 2023-03-24 05:20 UTC
### Your idea

Now when I'm clicking on the Recording button first time - it starts the recording, and that is okay.
But when the recording is active and I click on the Recording button again, it just does nothing!
Most of the other recording apps do stop or pause recording action on such clicks. 
So, will be good to implement the same behavior in Audacity too!

### Problem to be solved

Make the recording button behavior the same as in most of the other apps.

**Comment by LWinterberg** [comment] 2023-06-17 07:49
Duplicate of #2380

**Closed by LWinterberg** 2023-06-17 07:49 UTC
Labels: Enhancement Request, feature tweak
