### ISSUE TITLE
Behavior of GVST Realtime effects is confusing when duplicating tracks

### ISSUE THREAD

**Issue by juzzlin** [audacity/audacity#7733] opened 2024-11-16 10:23 UTC
### Bug description

I'm not sure if this is intended behavior or if it happens with all effects, but I find it confusing that at least some of the GVST Realtime effect instances are not duplicated when I duplicate a track, but shared with the duplicated track and affect the both tracks. This leads to a mess and unintended effect settings later when you don't understand anymore which effects are sharing the same instance and which are not. 

### Steps to reproduce

1. Have a track
2. Insert a GVST realtime effect e.g. GGain
3. Duplicate the track (Edit => Duplicate)
4. Adjust GGain of the first track

### Expected behavior

Gain of the first track changes, gain of the duplicated track remains unchanged. 

### Actual behavior

Gains of both tracks change, which means that they are now sharing the same effect instance. 

Now when you add new effects on these tracks it becomes a mess, because all effects looks the same - shared or not. Sharing the effect instance is "desired" and convenient for some type of effects, but not for all and not always. 

### Audacity Version

Audacity 3.7.x

### Operating system

Linux

**Comment by dozzzzer** [comment] 2024-11-22 09:57
Duplicate of https://github.com/audacity/audacity/issues/4169

**Comment by dozzzzer** [comment] 2024-11-22 09:57
We will try to tackle this issue as soon as possible.

**Closed by dozzzzer** 2024-11-22 09:57 UTC
Labels: AU3-bug
