### ISSUE TITLE
Export to original file location

### ISSUE THREAD

**Issue by jamshark70** [audacity/audacity#6405] opened 2024-05-09 03:07 UTC
### Your idea

A common Audacity use case is:

1. Import one audio file.
2. Do stuff to it (normalize, trim, fade in/out, simple stuff).
3. Export.

This is 99% of my Audacity usage. In the vast majority of cases, I want to export to the location from which the audio file was imported.

So I'd suggest either:

- a/ a preference for default export location (e.g. a/ Export directory from preferences, b/ Last export location, c/ Location of original file if it can be determined unambiguously),
- or b/ a button in the export dialog to switch to the imported file's location.

### Problem to be solved

In the above noted case -- if you're in a hurry and not paying attention to the export location, then you export, and in the system file browser, navigate to the location where you want your work was supposed to be focused, and find... no exported file.

Your last export might have been days ago -- no, I don't have space in my brain to remember my exact last Audacity usage -- so the file could be *anywhere*. There's only one way to find out where the file went: open another export, check the location, and cancel.

I mean... OK, this isn't a *major* issue...? But neither can it be called precisely user-friendly.

Obviously, if multiple files have been imported into one Audacity project, from different locations, then there's no unambiguous "original file location," and in that case it could fall back to current behavior.

But if I do file-browser > right-click on audio file > "Open with Audacity" and do a few simple edits, I think Export could be smarter about the target location.

**Comment by LWinterberg** [comment] 2024-05-09 08:09
Duplicate of #762

**Closed by LWinterberg** 2024-05-09 08:09 UTC
Labels: Enhancement Request
