### ISSUE TITLE
Share Audio button wrongly positioned in upper tooldock

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#6075] opened 2024-02-29 17:05 UTC
### Bug description

In the latest 3.5.0 Beta build by @crsib :  audacity-win-3.5.0-beta-20240229+a2a7f8c-x64-msvc2022

The Share Audio button is wrongly positioned in upper tooldock
![image](https://github.com/audacity/audacity/assets/50205984/896f940d-d509-454b-9323-fd74ce9186df)

Tested with both the exe and the zip downloads

### Steps to reproduce
1. clear the audacity settings folder
2. load latest 3.5.0 Beta
3. Observe:  Share Audio button wrongly positioned in upper tooldock

### Expected behavior
![image](https://github.com/audacity/audacity/assets/50205984/745537ff-9b3d-4dc8-80bc-dd37acd8a126)

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/896f940d-d509-454b-9323-fd74ce9186df)

### Audacity Version
latest beta:  audacity-win-3.5.0-beta-20240229+a2a7f8c-x64-msvc2022

### Operating system
Windows 10 but assume all OS

### Additional context
Regression on 3.4.2 and earlier

**Comment by petersampsonaudacity** [comment] 2024-02-29 17:11
If you position it correctly manually and then use **Tools > Reset Configuration** it then also mis-places it on the line below.

**Comment by petersampsonaudacity** [comment] 2024-02-29 17:21
Also note that the Timeline does not have the new gear-wheel (even though the "What's new in 3.5 says tht is the case)

![image](https://github.com/audacity/audacity/assets/50205984/400de691-96df-4fff-8b0c-5fbab3523308)

Other 3.5.0 alpha builds that I have previously tested DO have the gear-wheel

**Comment by petersampsonaudacity** [comment] 2024-02-29 17:48
If you update to 3.5.0 beta from 3.4.2 then the Share Audio button is in the correct place when you launch 3.5.0

But Reset Configuration will send it to the wrong place again.

**Comment by dozzzzer** [comment] 2024-02-29 18:26
> Does this need logging separately?

Yes please

**Comment by dozzzzer** [comment] 2024-02-29 18:26
Duplicate of #5966

**Closed by dozzzzer** 2024-02-29 18:26 UTC
Labels: bug, regression
