### ISSUE TITLE
Windows DirectSound Microphone Gain Control seems inoperative

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#4068] opened 2022-12-14 14:53 UTC
### Bug description

Audacity's  Microphone Gain Control (Windows DirectSound) does not initially move and cannot be used to adjust the gain on my Laptop built-in microphone. This is a regression over 3.0.5.

This error was initially reported by forum user Pnokio, in this post: https://forum.audacityteam.org/viewtopic.php?p=460750#p460750

### Steps to reproduce

1) Tools > Reset Configuration
2) Audio Setup > Host > Windows DirectSound
3) Manually move recording Meter Level control to 100%
4) Exit Audacity
5) Restart Audacity
6) Record

### Expected behavior

Audacity's microphone gain control can be used to adjust the incoming recorded level.

### Actual behavior

Audacity's microphone gain control is STUCK, and will not move.

If I RESTART the recording, it is movable, BUT, it has NO EFFECT on the recorded audio.

This is a regression on 3.0.5 where the Audacity control moved in lock-step with the Windows control in mmsys.cpl.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

See also #3322, #3690, #3696, #3810

**Comment by petersampsonaudacity** [comment] 2022-12-15 10:33
Testing on W10 with 3.2.2

At first I thought that this was working for me when I was just recording
a) The mic slider could be moved wile recording
b) The Microsoft Sounds mic array shadowed the mic slider position

But then I tried monitoring without recording
c) to start with the mic slider moved and the Microsoft Sounds mic array shadowed the mic slider position
d) after a short while the Audacity mic slide jumped to the right 100%
e) the Microsoft Sounds mic slider could still be moved to control the input level

![image](https://user-images.githubusercontent.com/50205984/207837098-dedef8d9-3082-497a-9311-e370ad82cb77.png)

**Comment by dozzzzer** [comment] 2023-03-17 13:28
I was able to reproduce this one on Windows 11

**Comment by dozzzzer** [comment] 2023-03-17 14:16
Closing as **not planned** to be fixed since DirectSound support will be deprecated in future releases anyway.

**Closed as not planned by dozzzzer** 2023-03-17 14:16 UTC
Labels: AU3-bug, regression
