### ISSUE TITLE
Clip Name should be Saved via Text Input Unfocus

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#7808] opened 2024-11-27 13:45 UTC
### Problem to be solved

Currently, in Audacity 4, the User can't apply a new name for a clip after entering the name via losing focus of the text input. 

Simply put, the User HAS to press Enter to commit changes to the clip name. 

AU3 has a different behaviour, where the changes are commited if the text input box loses focus. 

### Your idea

Make AU4 commit changes on unfocus of the text input box for clips.

**Comment by dozzzzer** [comment] 2024-11-27 14:08
Duplicate of https://github.com/audacity/audacity/issues/7674 ? @chinakov

**Closed** 2024-11-27 14:09 UTC
Labels: Enhancement Request
