### ISSUE TITLE
Some Nyquist-related menu item titles + Apple AU plugins ignore the language settings

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3213] opened 2022-07-11 19:24 UTC
**Describe the bug**
Some Nyquist-related menu item titles ignore the language settings and use system locale language instead.

**To Reproduce**
1. set regional settings as follows: <img width="600" alt="image" src="https://user-images.githubusercontent.com/70063970/178341882-5185eb20-f857-4606-8597-18b867738beb.png">
2. set language = English in Audacity's Preferences
3. check **Effect** and **Generate** menu items OR
4. open up any Apple AU plugin

**Actual behavior**
There're some items that are displayed in Russian:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/70063970/178342157-5b94de1e-90d9-4e5b-9e3c-1f4d2b5911e2.png">
<img width="500" alt="image" src="https://user-images.githubusercontent.com/70063970/179983867-e6b42ac8-0faa-4f48-9154-7cdc2ee6a5f2.png">

**Expected behavior**
All menu items are 100% translated into the language set in Preferences

**Additional information (please complete the following information):**
 - OS: MacOS 12.2.1
 - Version: latest master

**Comment by LWinterberg** [comment] 2022-10-10 19:32
duplicate of https://github.com/audacity/audacity/issues/2764

**Closed by LWinterberg** 2022-10-10 19:32 UTC
Labels: bug, P3
