### ISSUE TITLE
Stuck when using mouse wheel to zoom in

### ISSUE THREAD

**Issue by umonaca** [audacity/audacity#2348] opened 2021-12-26 18:19 UTC
**Describe the bug**
1. Open any mp3 file.
2. Press Ctrl (Windows machine, not Mac) and use mouse to scroll up.
3. The entire program freezes. No matter how long I wait it does not respond to any click event. I have to end the process with task manager.

**To Reproduce**
Same as above

**Expected behavior**
It should not freeze when Ctrl + mouse wheel up.

**Screenshots**
No screenshot is available -- it looks normal but it does not respond to any mouse click.

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: Audacity 3.1.3 64bit

**Comment by Penikov** [comment] 2021-12-27 09:41
@umonaca Hi!

Could you send me, please, audacity.cfg file? (C:\Users\<user>\AppData\Roaming\audacity)
I want to try to reproduce the bug with your actual settings. I've checked 3.1.3 with default preferences, but the bug hasn't been reproducing.

**Comment by petersampsonaudacity** [comment] 2021-12-27 12:00
Tested on W10 with 3.1.3 I cannot reproduce this either.

----------------------------------------------------------------------


But I do note that when holding down control when over the waveform to zoom you get a most odd, idiosyncratic, cursor icon which is a rightward-pointing gloved-hand.

**Comment by umonaca** [comment] 2022-01-03 04:27
Tried a few times and I figured out what's going on.  
I have no idea how to reliably reproduce this bug or debug the program. There is a certain mp3 file (copyrighted, no DRM, I will upload it somewhere once I am certain that this file is relevant) that sometimes can trigger this bug. Once the bug is triggered, even if I terminate the audacity process with task manager, the Ctrl + Wheel will still always freeze the program. The only way to fix is to **reboot the computer**.  
Yes, it sounds weird. I suspect there is some kind of DLL issue (such as a hidden bug in the mp3 codec). (Maybe it's wrong, sorry I don't really understand Windows.) Otherwise I could not explain what is happening above.

**Comment by LWinterberg** [comment] 2022-01-04 09:16
Here's another report of similar behavior on macOS: https://forum.audacityteam.org/viewtopic.php?f=47&t=122593

**Comment by petersampsonaudacity** [comment] 2022-01-04 12:12
> Here's another report of similar behavior on macOS: https://forum.audacityteam.org/viewtopic.php?f=47&t=122593

Testing on macOS 12.0.1 Monterey with 3.1.3 I cannot reproduce with using any of these:

a) Zoom buttons in the Edit Toolbar

b) View > Zoom commands

c) keyboard zoom shortcuts

d) CMD and the virtual scroll-wheel on my magic mouse

**Comment by pffang** [comment] 2022-08-09 08:09
Same issue, also version 3.1.3 64bit on Windows 10.
Not only stuck when try to zoom, but also stuck when try to play/stop by Space key.
Clicking on UI Play/Stop buttons works fine, but always stuck when using keyboard.

Always reproducible on Windows 10, but can't reproduce on Ubuntu 20.04.

**Comment by umonaca** [comment] 2022-11-23 03:05
I just found out why this is happening. When I'm using the Microsoft Pinyin (it's for Chinese language) as the default input method, the program will randomly freeze, but if I switch the IME to English before launching the program, Audacity does not freeze at all.

**Comment by pffang** [comment] 2022-11-23 07:07
> I just found out why this is happening. When I'm using the Microsoft Pinyin (it's for Chinese language) as the default input method, the program will randomly freeze, but if I switch the IME to English before launching the program, Audacity does not freeze at all.

I debug from source code several days, but didn't find the root cause.
Good finding! This also fixed my stuck.

**Comment by pffang** [comment] 2022-12-28 02:51
My similar issue is not reproducible from version 3.2.2.

**Comment by 0x391F** [comment] 2023-03-02 10:36
This bug still exist in Audacity 3.2.5, I do a series of tests: 
1. Using English (US) IME before launch: using mouse wheel to zoom in is OK. 
2. Using English (US) IME before launch, then switch to Microsoft Pinyin (Chinese): stuck when using mouse wheel to zoom in. 
3. Kepping Microsoft Pinyin (Chinese) IME: stuck when using mouse wheel to zoom in. 
4. Using Microsoft Pinyin IME before launch, don't do any thing but switch to English (US) IME: OK.

**Comment by 0x391F** [comment] 2023-03-02 10:42
Audacity even stuck when using Ctrl to multiple select in Automatic Crash Recovery dialog. Switch to English (US) IME and launch Audacity again, everything is OK.

**Comment by LWinterberg** [comment] 2023-03-02 11:08
okay, so it's another IME issue. #805 is the bug for that, I'll close this bug in favor of it.

**Closed by LWinterberg** 2023-03-02 11:08 UTC
Labels: Could not reproduce, bug, crash / freeze
