### ISSUE TITLE
The time position indicator can be duplicated in some cases

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2318] opened 2021-12-20 15:04 UTC
**Describe the bug**

related to #2122

**To Reproduce**
Just move the cursor quickly across the timeline as shown on the video:

https://user-images.githubusercontent.com/25851359/146787838-2bb74d0a-168d-4b4d-adcd-cf781232d3ba.mp4

**Expected behavior**
The time position indicator disappears at all tracks on the screen if the cursor points out of the timeline

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version 3.1.3

**Comment by petersampsonaudacity** [comment] 2021-12-21 09:41
Testing on W10 with @Paul-Licameli 's latest branch build Audacity_Windows_64bit_1604442846_791f03b 
I cannot reproduce this issue

If I use this earlier alpha that I downloaded yesterday  Audacity_Windows_64bit_1602134390_7887ba0 
then I can readily reproduce this bug.

Therefore the issue looks to be fixed by Paul's latest pending change.

**Comment by petersampsonaudacity** [comment] 2021-12-21 15:31
Testing on W10 with the latest 3.1.3 alpha build:  Audacity_Windows_64bit_1607168309_32a36d2 

I cannot reproduce this issue - looks to be fixed for 3.1.3

**Closed** 2021-12-22 09:02 UTC
Labels: bug, P2, regression
