### ISSUE TITLE
Conan builds all four types of targets for every Audacity dependency

### ISSUE THREAD

**Issue by werame** [audacity/audacity#2433] opened 2022-01-15 22:32 UTC
**Describe the bug**
I may have futzed around a bit with the `-DAUDACITY_BUILD_LEVEL=` but I only set it to 0 (and that build failed pretty quickly in the `cmake -G` phase) and then I set it to 2 and eventually managed to get a build of all dependencies (after completely turning off the Defender AV--exclusions alone were not enough).

Nonetheless, I'm pretty sure I didn't ask conan to build all 4 (CMake-style) build types for every library Audacity uses. Yet, that's what it did. I'm not sure if this is normal. The `.conan` dir is >6GB now.

![image](https://user-images.githubusercontent.com/97036286/149639578-d70e893f-3c02-4f6b-bba6-879aba0f56f1.png)

And I can see that all 4 build types were also copied to the destination dir(s):

```
 /m/gh/aud-build/shared
$ ls -R
.:
Debug/  MinSizeRel/  RelWithDebInfo/  Release/

./Debug:
FLAC++.dll*         wxbase313ud_net_vc_x64_custom.dll*
FLAC.dll*           wxbase313ud_vc_x64_custom.dll*
libexpatd.dll*      wxbase313ud_xml_vc_x64_custom.dll*
ogg.dll*            wxmsw313ud_adv_vc_x64_custom.dll*
opus.dll*           wxmsw313ud_aui_vc_x64_custom.dll*
portaudio_x64.dll*  wxmsw313ud_core_vc_x64_custom.dll*
portmidi.dll*       wxmsw313ud_html_vc_x64_custom.dll*
sndfile.dll*        wxmsw313ud_qa_vc_x64_custom.dll*
vorbis.dll*         wxmsw313ud_xrc_vc_x64_custom.dll*
vorbisenc.dll*      zlibd1.dll*
vorbisfile.dll*

./MinSizeRel:
FLAC++.dll*         wxbase313u_net_vc_x64_custom.dll*
FLAC.dll*           wxbase313u_vc_x64_custom.dll*
libexpat.dll*       wxbase313u_xml_vc_x64_custom.dll*
ogg.dll*            wxmsw313u_adv_vc_x64_custom.dll*
opus.dll*           wxmsw313u_aui_vc_x64_custom.dll*
portaudio_x64.dll*  wxmsw313u_core_vc_x64_custom.dll*
portmidi.dll*       wxmsw313u_html_vc_x64_custom.dll*
sndfile.dll*        wxmsw313u_qa_vc_x64_custom.dll*
vorbis.dll*         wxmsw313u_xrc_vc_x64_custom.dll*
vorbisenc.dll*      zlib1.dll*
vorbisfile.dll*

./RelWithDebInfo:
FLAC++.dll*         wxbase313u_net_vc_x64_custom.dll*
FLAC.dll*           wxbase313u_vc_x64_custom.dll*
libexpat.dll*       wxbase313u_xml_vc_x64_custom.dll*
ogg.dll*            wxmsw313u_adv_vc_x64_custom.dll*
opus.dll*           wxmsw313u_aui_vc_x64_custom.dll*
portaudio_x64.dll*  wxmsw313u_core_vc_x64_custom.dll*
portmidi.dll*       wxmsw313u_html_vc_x64_custom.dll*
sndfile.dll*        wxmsw313u_qa_vc_x64_custom.dll*
vorbis.dll*         wxmsw313u_xrc_vc_x64_custom.dll*
vorbisenc.dll*      zlib1.dll*
vorbisfile.dll*

./Release:
FLAC++.dll*         wxbase313u_net_vc_x64_custom.dll*
FLAC.dll*           wxbase313u_vc_x64_custom.dll*
libexpat.dll*       wxbase313u_xml_vc_x64_custom.dll*
ogg.dll*            wxmsw313u_adv_vc_x64_custom.dll*
opus.dll*           wxmsw313u_aui_vc_x64_custom.dll*
portaudio_x64.dll*  wxmsw313u_core_vc_x64_custom.dll*
portmidi.dll*       wxmsw313u_html_vc_x64_custom.dll*
sndfile.dll*        wxmsw313u_qa_vc_x64_custom.dll*
vorbis.dll*         wxmsw313u_xrc_vc_x64_custom.dll*
vorbisenc.dll*      zlib1.dll*
vorbisfile.dll*
```

**Expected behavior**
I'm not sure if this is normal or not for conan, but it's certainly not very desirable. The build of the dependencies takes 4 times longer than it could otherwise etc.

**Additional information (please complete the following information):**
 - OS: Windows 10; Conan version 1.44.0
 - Version: Audacity 3.2-master

I'm not sure why my conan is version 1.44.0 and not version 1.44.1, which what github uses, since I've only installed it through pip a couple of days ago. (Ah, ok, I see 1.44.1 was released on  13-Jan-2022. I may have missed it by a few hours.)

**Comment by werame** [comment] 2022-01-16 09:17
This conan issue seems related https://github.com/conan-io/cmake-conan/issues/156 Apparently they do default to all 4 cmake build types, but you can also select them individually. I guess Audacity doesn't do the latter for dependecies.

**Comment by crsib** [comment] 2022-01-17 10:12
This is very much intentional when using the multi config generators, like Visual Studio or Xcode. We will speed up this process by providing prebuilt binaries, likely by the end of this week.

**Comment by LWinterberg** [comment] 2022-01-17 10:12
this may be a duplicate of #2211

**Closed** 2022-01-17 10:12 UTC
Labels: Build / CI

**Comment by werame** [comment] 2022-01-17 11:39
Ok, thanks for the info.
