### ISSUE TITLE
Track Alignment Feature Regression

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#3118] opened 2022-06-20 21:04 UTC
This is from the forum.  See this post: https://forum.audacityteam.org/viewtopic.php?f=47&t=126072

"So what I'm having trouble with if the tracking tool in the newest update. When I was taking track selections and trying to align them together manually, I would be able to have my tool selection on a certain part of the track and if I pressed up or down on my keyboard, that line would extended to both tracks where I could align the dots. As of the newest update, when I try to accomplish this same task, I get a noise like I'm clicking out of bounds and the only way to somewhat recreate this is by selecting the track, holding shift and then clicking on the bottom track but sometimes it selects a piece of the song when I'm only checking the alignment. Is there a way to get this back? If so, please let me know. Thank you."

This was reported on MacOS.  I am able to duplicate this (regression) on Windows 10 as well.  The feature seems to work properly on 2.4.2 and on 3.0.2.  It does not work on 3.1.3.

To duplicate, on 2.4.2 or on 3.0.2:

1) Generate two separate tracks.  (I used DTMF and Tone).
2) Click anywhere on the bottom track. A Selection Line appears.
3) Press the UpArrow key. Focus changes to the upper track and the Selection Line extends into the upper track.

On 3.1.3, focus changes to the upper track BUT the Selection Line does not extend into the upper track  This severely hampers the ability to compare and align tracks.

**Comment by petersampsonaudacity** [comment] 2022-06-21 08:01
Testing on W10 confirms this - and shows that this is a regression on 3.0.5 introduced in 3.1.0

**Comment by crsib** [comment] 2022-06-23 11:31
Looks like Shift-Up/Down doing the trick, or I miss something?

In general, having arrow key to manipulate the selection without any modifiers feels a bit odd to me

(@LWinterberg FYI)

**Comment by LWinterberg** [comment] 2022-06-23 12:15
Pressing Up and then Enter also works. 

I don't think the original way is desirable here, shift+up to also select the track above feels much more reasonable to me. 

Fwiw, we have some designs for the future where the point selection would be displayed like a playhead, so the line would go across all tracks always. 
![image](https://user-images.githubusercontent.com/87814144/175295431-7ab1ed46-dbbc-45c3-8b50-4956a23a420b.png)

so yeah, I'm calling this a wontfix

**Closed by LWinterberg** 2022-06-23 12:15 UTC
Labels: regression
