### ISSUE TITLE
Audacity support website has wrong information about Cut/Copy/Paste buttons

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4242] opened 2023-01-27 13:09 UTC
### Bug description
The audacity Support website in its Missing Features section has incorrect (out of date) information about the cut/copy/paste buttons:
https://support.audacityteam.org/troubleshooting/missing-features

It states there:
>The Cut/Copy/Paste buttons have been removed in version 3.2.0. You can access the functionality in the following ways instead: ...

This was true for 3.2.0 (and 3.2.1 and 3.2.2) but in 3.2.3 they were reintroduced in the new, hidden by default, **Cut/Copy/Paste** toolbar.  And for 3.2.4/3.3.0 the additional **Delete** button has been added.

### Steps to reproduce
1. go to:  https://support.audacityteam.org/troubleshooting/missing-features
2. read what it says about the Cut/Copy/Paste buttons 
3. Observe: the information is out of date

### Expected behavior
Updated information telling users about the **Cut/Copy/Paste**  toolbar

### Actual behavior
![image](https://user-images.githubusercontent.com/50205984/215093114-c698fc1d-07f6-42c0-8a28-595dad89226a.png)

### Audacity Version
other

### Operating system
Windows 10 - but assume all OS

### Additional context
Perhaps the updated information need to be moved possibly to the Editing Audio section
https://support.audacityteam.org/basics/audacity-editing

**Comment by LWinterberg** [comment] 2023-01-27 13:17
duplicate of https://github.com/audacity/audacity-support/issues/22

**Closed by LWinterberg** 2023-01-27 13:17 UTC
Labels: bug
