### ISSUE TITLE
audacity-win-3.4.0-alpha-20230804+ca2098e-x64-msvc2022: Export audio dialog - default cursor position

### ISSUE THREAD

**Issue by deus-e-x** [audacity/audacity#5000] opened 2023-08-06 13:40 UTC
### Your idea

Greetings Audacity Team,

with regards to the new audio export dialog, can we please have the cursor position default to the end of the file name in the file name input field, just like it used to be in the old audio export menu?

Right now it defaults to "stereo" in the audio options section, but I think altering the export file name is likely required much more often.

Thank you.

### Problem to be solved

The suggested change will save extra input steps and thus additional time required to reposition the cursor to the likely most used area of the audio export dialog, the edit file name field.

**Comment by LWinterberg** [comment] 2023-08-07 08:02
Duplicate of https://github.com/audacity/audacity/issues/4960

**Closed by LWinterberg** 2023-08-07 08:02 UTC
Labels: Enhancement Request
