### ISSUE TITLE
Linux: Track "stretch" icon rendered incorrectly

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#6017] opened 2024-02-21 18:16 UTC
### Bug description

The "stretch" icon, indicating that an audio clip has been stretched, is rendered as a black square on Xubuntu 22.04

### Steps to reproduce

1. Apply real-time stretch to a track

### Expected behavior

![stretch-windows](https://github.com/audacity/audacity/assets/11681097/73677a92-6042-4000-a558-a373e8c8df2d)

### Actual behavior

![stretch-linux](https://github.com/audacity/audacity/assets/11681097/bc2f97f4-47e0-445e-ab0e-9c8a9eb9d263)

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by petersampsonaudacity** [comment] 2024-02-22 08:24
This is duplicate of #5959

**Closed** 2024-02-22 08:28 UTC
Labels: bug, Linux

**Comment by SteveDaulton** [comment] 2024-02-22 14:15
> This is duplicate of #5959

That issue has been closed, but this bug is still present in a49f64.

**Comment by dozzzzer** [comment] 2024-02-22 14:29
@SteveDaulton that's right, thanks Steve
