### ISSUE TITLE
Bug in Screenshot macro command capturing all tracks

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#4716] opened 2023-05-21 15:16 UTC
### Bug description

Of small importance maybe, but a fix will be one visible consequence in what is otherwise an invisible refactoring PR soon to come

### Steps to reproduce

1. Define a macro with one command, Screenshot, capturing "all tracks" or "all tracks plus"
2. Make two stereo tracks
3. Run the macro
4. FIND the freakin file!!! (For me it ended up in ~/Library/Audio/Plug-Ins/LADSPA/All Tracks000.png)
5. Open

### Expected behavior

See all tracks

### Actual behavior

See only the first track

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

### Additional context

Note:  step 4 is an obvious other problem -- the file going to some hard to find place.  It's not the intended scope of this narrow issue.

**Comment by Ryan-Miller-Audacity** [comment] 2023-05-25 10:46
Confirmed i was able to reproduce this bug in current public release (Audacity 3.3.2).

**Comment by dozzzzer** [comment] 2023-06-01 10:33
I've failed to reproduce the issue; I'm consistently getting this error message on both Windows and macOS:
<img src="https://github.com/audacity/audacity/assets/70063970/91bc91c3-a4e8-47da-beb7-7b6b465826a6" width=400>

Due to that, I cannot obtain the screenshot image.
So please @Ryan-Miller-Audacity make sure the issue is fixed by PR #4738

**Comment by Ryan-Miller-Audacity** [comment] 2023-06-02 00:49
Testing in the build for PR #4738 I was able to confirm this behavior is fixed. Using the screenshot macro now appropriately captures all tracks when specified. 

One note (that may constitute a separate issue): 

1) Your screen does have to be an appropriate size in order for all tracks to be captured. If you cannot display all tracks at once within your window the macro will screenshot the correct size to display all tracks; however, it will not display the remaining tracks since it is not within the viewport of the window. I couldn't compare this behavior to previous releases since the function only captures the first track (the initial issue which I checked back to at least Audacity 3.2.5). This certainly presents a problem for users on smaller (aka laptop) screens. I could not make the Audacity window large enough on my Macbook Air in order to capture two stereo tracks with the screenshot macro (granted even a native screenshot wouldn't work either of course). 

See examples below.

Viewport not large enough to display all tracks. You can see that the area captured would include the additional channel not displayed: 


![Image](https://github.com/audacity/audacity/assets/88568755/2226e86c-53c5-4228-8ed7-740a835372df)

Viewport large enough to display all tracks: 


![Image](https://github.com/audacity/audacity/assets/88568755/6a10c22c-582d-4dbd-8b01-4938cb975f01)

If this is tracked separately or determined to be a non-issue. This is merge ready. Tested on Windows, MacOS, and Linux (Xubuntu VM)

**Closed** 2023-06-02 08:33 UTC
Labels: bug, P4, macros / scripting
