### ISSUE TITLE
unable to switch playback output automatically

### ISSUE THREAD

**Issue by jackcipher** [audacity/audacity#4050] opened 2022-12-11 06:03 UTC
### Bug description

When changing system audio output from MacBook Pro speakers to external headphones, there is no any simultaneously change in Audacity's playback output.

### Steps to reproduce

1. Open Audacity, with system default audio output, for Mac, it might be Macbook Pro speakers
2. Open Preferences --> Devices --> Playback, there is only one option for output Device.
3. Plugin external headphones, do step 2 again.
4. Bug: there is still only one option for ouput device.Plus, the value of output device doesn't keep pace with system.

### Expected behavior

Output Device could switch automatically keeping pace with system.

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by LWinterberg** [comment] 2022-12-11 13:49
Duplicate of https://github.com/audacity/audacity/issues/2409

In the meantime, you can go to Transport > Rescan Audio Devices

**Closed by LWinterberg** 2022-12-11 13:49 UTC
Labels: bug
