### ISSUE TITLE
Make jack connection persistent

### ISSUE THREAD

**Issue by ycollet** [audacity/audacity#3553] opened 2022-09-06 13:37 UTC
### Your idea

If the jack audio device is selected, then make the jack connections persistent.
Today, these connections only shows up when you click on play or record.
The connections must be made via the Audacity Gui is it not always easy to use. 
When you are doing your jack connections via a patchbay like NSM or Ray Session, it's better to make the connections here.

### Problem to be solved

This will solve the problem of non persistence jack connections.

**Comment by LWinterberg** [comment] 2023-03-31 11:04
Duplicate of #711

**Closed by LWinterberg** 2023-03-31 11:04 UTC
Labels: Enhancement Request, Linux
