### ISSUE TITLE
PlayLooped: Command missing

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3325] opened 2022-07-31 12:49 UTC
**Describe the bug**
PlayLooped: command is documented here: https://manual.audacityteam.org/man/scripting_reference.html and here: https://manual.audacityteam.org/man/transport_menu_playing.html#loop_play but appears to no longer exist in the App.

**To Reproduce**
1. Use any macro that has the "PlayLooped:" command

**Actual behavior**
The macro fails with error:
`Your batch command of PlayLooped was not recognized.`

**Expected behavior**
Loop Play

**Screenshots**
If applicable, add screenshots/video to help explain your problem.

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version [e.g. Audacity 2.5.1] Audacity 3.2.0 alpha

**Additional context**
"TogglePlayRegion" does not work  correctly  either.

**Comment by LWinterberg** [comment] 2022-08-02 11:22
duplicate of https://github.com/audacity/audacity/issues/2266

**Closed by LWinterberg** 2022-08-02 11:22 UTC
