### ISSUE TITLE
3.6.4 AppImage crashes on close (Linux Mint 22)

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#7397] opened 2024-09-23 18:54 UTC
### Bug description

When quitting Audacity 3.6.4 AppImage, after using Preferences, Audacity crashes.

### Steps to reproduce

1. Launch Audacity
2. Open Preferences
3. Click "OK" to close Preferences
4. Exit Audacity

### Expected behavior

Audacity to shut down properly.

### Actual behavior

Audacity crashes and produces a crash report (crash report sent).

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

Additional information from: https://forum.audacityteam.org/t/audacity-3-6-4-crashes-on-exit/120874

**Comment by chinakov** [comment] 2024-09-30 12:12
Hi, @SteveDaulton - I can't reproduce this issueon Linux Mint 22. Could you provide anymore details at all?

**Comment by kryksyh** [comment] 2024-10-02 14:43
@SteveDaulton I am also unable to reproduce this issue. Could you add more details for your setup:
- Which flavor of Mint do you use (cinnamon, mate, xfce)?
- Is this a virtual machine (and which one?) or a standard PC installation?
- You have mentioned that this is a brand new setup, so am I right to assume that no additional software was installed and you are running default desktop configuration (ie, default DE and window manager)

**Comment by SteveDaulton** [comment] 2024-10-03 19:05
> @SteveDaulton I am also unable to reproduce this issue

Strangely, neither can I today, though it was 100% repeatable when I logged it.
I'll close this issue for now, and re-open if the issue reappears.

**Comment by SteveDaulton** [comment] 2024-10-19 14:51
It seems that I missed a step in reproducing the issue. To reproduce the issue it is necessary to use Preferences.
I can now reproduce the issue in Audacity 3.6.4 AppImage.

Additional information came from this forum post: https://forum.audacityteam.org/t/audacity-3-6-4-crashes-on-exit/120874

**Comment by kryksyh** [comment] 2024-10-19 19:25
@SteveDaulton Awesome, I could also reproduce the crash using the provided steps.
Please check this build: https://github.com/audacity/audacity/actions/runs/11420140228 , the crash should be fixed.

**Closed** 2024-10-25 15:14 UTC
Labels: AU3-bug
