### ISSUE TITLE
AU Effect User presets are not saved/loaded properly

### ISSUE THREAD

**Issue by Ryan-Miller-Audacity** [audacity/audacity#2995] opened 2022-05-26 19:51 UTC
**Describe the bug**
In testing of #2934, it was noted that the AU Effect User presets are not being saved correctly. When a user saves a preset an entry is saved; however, the proper data doesn’t appear to be saved with it: i.e. when I select the preset later it does not load the settings from the preset as expected.
* I determined that saving is the problem as I observed that saving a preset from the test build and utilizing it within the current public release did not yield the correct settings; however, saving a preset from the current release and loading that preset within the test build did yield the correct result; therefore, it seems the issue lies within saving the preset metrics correctly, not loading the preset. 

**To Reproduce**
1. Go to https://github.com/audacity/audacity/actions/runs/2363414860 and retrieve the relevant macOS build from the artifacts
2. Open audacity 
3. Generate some sound (import an mp3, generate a chirp etc)
4. From the effects dropdown at the top choose an AudioUnit effect 
5. Edit the effect so that it is different than the default 
6. Use the hamburger menu to save the preset
7. Give the preset a unique name and click "ok"
8. Use the hamburger menu to reload the default option (under the factory settings option)
9. Use the hamburger menu and select your preset from the "user presets" option
10. Note that your preset is not properly displayed in the interface
      * You can also change the interface away from the default again and then load your preset and note that loads the default when you load your preset.

**Actual behavior**
User presets are not saved correctly and therefore do not load the correct settings that were saved.

**Expected behavior**
User presets should be correctly saved with correct info and load the info as expected when selected.

**Screenshots**
N/A

**Additional information (please complete the following information):**
 - OS: macOS Monterey 12.3.1
 - Version: Audacity 3.2.0-alpha-20220521 commit ID: da7cfe [Related Merge](https://github.com/audacity/audacity/actions/runs/2363414860)
 - (if relevant) Sound Device: N/A

**Additional context**
This effects AudioUnit effects only and does not seem to effect native effects.

**Comment by Paul-Licameli** [comment] 2022-05-29 02:08
"that saving a preset from the test build and utilizing it within the current public release did not yield the correct settings"

I could not confirm this problem when I tried it, and this is not the same problem as described in Steps to Reproduce.

Be aware of this:  on Mac, Audacity cabn be in a state where no windows are open, yet the application still runs.  If you try to run another version of Audacity by clicking on the icon, in fact it won't run because of single-instance checking, but instead the curent Audacity session continues.

Be very sure you actually quite Audacity, not just closing windows, when you want to switch versions for testing purposes.

This isn't a problem on the other operating systems, in which Audacity quits when all its windows close.

**Comment by Paul-Licameli** [comment] 2022-05-29 02:14
Comments in some old code suggest that there was a problem only with the display of the controls not updating, but a resize drag would cause an update to correct values.  See also the discussion at #2997.

Another test that the expected settings don't really reload -- is to apply the effect to some sound and listen (or, look at the waveform, or the spectrogram) to verify.

The description was not specific about which effect you tried for this.  Maybe you could generate white noise, which makes a flat spectrum and a uniform "snow" in spectrogram; then, apply a graphic or parametric EQ effect.

**Closed** 2022-06-14 19:36 UTC
Labels: bug, P1, macOS, Effects
