### ISSUE TITLE
"Play Cut Preview" does not exit "play mode"

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3792] opened 2022-10-10 08:46 UTC
### Bug description

After using "Play Cut Preview" (shortcut "C"), the Play button remains "down", and non-realtime effects are greyed out.

### Steps to reproduce

1. Generate a 30 second Chirp
2. Select a couple  of  seconds near the middle of the chirp
3. Press "C"

### Expected behavior

Playback to start before the selection, then skip the selection and continue playing for a short while and then "Stop" (the playback button returns to "up")

### Actual behavior

Playback to start before the selection, then skip the selection and continue playing for a short while and then playback stops but the Play button remains "down" (still in "play mode").

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux and W10

**Comment by petersampsonaudacity** [comment] 2022-10-10 09:36
I cannot reproduce this on W10 with 3.2.1 

nor with the latest 3.3.0 alpha build that I have:  audacity-win-3.2.2-beta-20221006+df0ffd2-x64-msvc2022

**Comment by DavidBailes** [comment] 2022-10-10 09:37
Tested on Windows 10.
Testing on different selections showed that this bug occurs often, but on some selections it doesn't occur.

This bug also occurs often, but not always on the following commands on the Transport sub menu of the extra menu:
Play before selection start
Play after selection start
Play before selection end
Play after selection end.

I so far haven't seen the bug on the commands:
Play before and after selection start
Play before and after selection end

**Comment by petersampsonaudacity** [comment] 2022-10-10 10:06
Ah yes @DavidBailes 

Now on retesting I can get this to happen with a 3 minute stereo song
a) if I select the whole track
b) if I select some audio from the start of the track
c) if I select some audio from the end of the track
d) If I select most of the track without involving the start or end points - 2 minutes worth does thgis - but a one minute selection works ok

**Comment by petersampsonaudacity** [comment] 2022-10-10 14:36
See also:  [The playhead stuck at the end of a clip while playback is running#2453](https://github.com/audacity/audacity/issues/2453)

**Comment by DavidBailes** [comment] 2022-10-11 08:20
Having all these play commands which often do not exit play mode is very unhelpful to users of screen readers, who do not have access to the visual indication that Audacity is unexpectedly stuck in play mode.

**Comment by petersampsonaudacity** [comment] 2022-10-11 08:50
> Having all these play commands which often do not exit play mode is very unhelpful to users of screen readers

I suspect that they are not very useful to most normally sighted users - especially since they are (rightly, in my view) hidden away in the normally not exposed **Extra** menu.  I, for one certainly never use them.

But I thought that the fundamental purpose of the **Extra** menu that @JamesCrook was to provide a set of commands for VI/unsighted users so that thy could access them via assigning keyboard shortcuts to the ones they needed most as well as access to the **Extra>Transport>Play...** commands in the menu via screen readers.

![image](https://user-images.githubusercontent.com/50205984/195044316-4213d362-c3fb-4161-b7c0-4e60e0c21bc7.png)

**Comment by SteveDaulton** [comment] 2022-10-11 13:19
I think the point that David is making is that those commands "should" exit play mode. The fact that they don't, is extremely unhelpful (and quite ironic  considering that the existence of those commands is to help VI users).

**Comment by Paul-Licameli** [comment] 2022-10-13 16:34
Relliable steps to reproduce might need very precise selection starts and lengths in samples.

**Comment by SteveDaulton** [comment] 2022-10-13 17:57
Mostly it fails for me, but yes it does appear that with some selections it exits playback mode correctly, and with others it doesn't. 
I've posted a minimal example for  you here: https://forum.audacityteam.org/viewtopic.php?f=70&t=127326#p457359
The difference between the regions marked "Works" and "Fails" is one sample.

**Comment by DavidBailes** [comment] 2022-10-25 10:32
If my PR https://github.com/audacity/audacity/pull/3844 tests OK, then it would be good if this fix was included in 3.2.2, as it is a very unhelpful bug for users of screen readers.

**Comment by petersampsonaudacity** [comment] 2022-10-25 15:00
Testing on W10 with @DavidBailes 's branch build with the the fix for this:  audacity-win-3.3.0-alpha-20221025+77e4692-x64

This now works properly with
1. Play Cut Preview
and also
2. Play before selection start
3. Play after selection start
4. Play before selection end
5. Play after selection end.

@crsib @LWinterberg 
And I agree with David's request that if possible this fix should be pulled into 3.2.2 maintenance release

**Comment by Ryan-Miller-Audacity** [comment] 2022-10-31 12:58
Tested and verified in David Baile's branch on windows 10 and noted the various transport options are properly exiting play mode.

**Closed by Ryan-Miller-Audacity** 2022-10-31 12:58 UTC
Labels: bug, P3, regression
