### ISSUE TITLE
'Select All Audio, if Selection is required' does not work if Nyquist Prompt is used.

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#5429] opened 2023-10-25 14:31 UTC
### Bug description

If a User has 'Select all Audio, if Selection is required' enabled in Preferences, and then applies a Nyquist prompt via 'Tools -> Nyquist prompt...', the User will recieve a warning message stating that 'Nyquist returned nil audio'. 

### Steps to reproduce

1. Launch Audacity
2. Create a mono or stereo track
3. Import or generate some audio
4. De-select the audio clip
5. Go to Preferences and enable the 'Select all audio, if selection is required' feature
6. Go to 'Tools -> Nyquist prompt'
7. Use a Nyquist prompt, for example: (scale 1.15 *track*)
8. Observe warning message that 'Nyquist returned nil audio' 
9. Observe no change in audio

### Expected behavior

The Nyquist prompt should be applied to the audio that would be selected by the 'Select all audio, if selection is required'.

### Actual behavior

The Nyquist prompt is not applied to the audio that would be selected by the 'Select all audio, if selection is required'.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS

### Additional context

This bug was also present in much earlier versions of Audacity, like 3.1.2

**Comment by dozzzzer** [comment] 2023-10-25 15:32
Duplicate of https://github.com/audacity/audacity/issues/4311

**Closed by dozzzzer** 2023-10-25 15:32 UTC
Labels: bug, P3
