### ISSUE TITLE
Can not exit full screen on Ubuntu 18.04.4

### ISSUE THREAD

**Issue by Honghe** [audacity/audacity#532] opened 2020-05-22 02:28 UTC
**Describe the bug**
Can not exit full screen on Ubuntu 18.04.
Audacity can enter full screen mode through F11, but can not exit full screen mode through F11.

**To Reproduce**
1. `F11`, enter full screen mode.
2. `F11`, can not exit full screen mode, nothing happen.

**Additional information (please complete the following information):**
 - OS: Ubuntu 18.04.4
 - Audacity 2.4.x or Audacity 2.3.x

**Comment by SteveDaulton** [comment] 2020-05-22 15:54
What Desktop are you using?

**Comment by Honghe** [comment] 2020-05-23 06:48
Ubuntu 18.04.4 default Desktop.

**Comment by JamesCrook** [comment] 2020-05-23 15:32
Works for me on Ubuntu 18.04.4, with GNOME (default)
Will close this issue presently, if no elaborations on steps to reproduce are given.

**Comment by Honghe** [comment] 2020-05-26 02:21
Where can I see the logs?
After reinstall of Audacity, It still can not exit full screen via F11.
BTW: I install Audacity from http://ppa.launchpad.net/ubuntuhandbook1/audacity/ubuntu

**Comment by JamesCrook** [comment] 2020-05-26 09:13
Logs for what?
Build information is in the about box, second tab.
I am not using the ppa.

**Comment by SteveDaulton** [comment] 2020-05-26 12:18
On the Audacity forum we have received multiple reports of packaging errors in Audacity 2.4.1 as supplied by that PPA. We do not know when those errors will be fixed as we have no involvement with that PPA.
My advice would be to either revert to the official Ubuntu deb package, or build Audacity yourself from the sourcecode. 
Detailed instructions for building Audacity 2.4.1 on Ubuntu are now available on the Audacity forum: https://forum.audacityteam.org/viewtopic.php?f=19&t=111043

**Comment by JamesCrook** [comment] 2020-06-06 18:38
Audacity not built correctly by third party.  Closing issue.
See https://wiki.audacityteam.org/wiki/Ppa_and_Distro_Issues

**Closed by JamesCrook** 2020-06-06 18:38 UTC
