### ISSUE TITLE
Audacity 3.2.4 freezes if Microsoft IME is active

### ISSUE THREAD

**Issue by leonfeng** [audacity/audacity#4321] opened 2023-02-16 17:50 UTC
### Bug description

The UI becomes completely unresponsive, and the only way to quit Audacity is killing it in Task Manager. Luckily, Audacity is able to recover the project every time.

### Steps to reproduce

1. Activate (or forget that you've activated) Microsoft Pinyin Chinese IME.
2. Switch between Audacity and another app.

### Expected behavior

Able to use Audacity normally.

### Actual behavior

Audacity freezes.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

OS version: Windows 10 Pro 21H2 build 19044.2604

**Comment by LWinterberg** [comment] 2023-02-16 18:02
Duplicate of #805

**Closed by LWinterberg** 2023-02-16 18:02 UTC
Labels: bug
