### ISSUE TITLE
WaveTrack::LinkConsistencyFix modifies the AUP3 state, but doesn't force the project table to update

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#5862] opened 2024-01-12 14:50 UTC
### Bug description

This issue was observed with a project reported corrupted here: https://forum.audacityteam.org/t/corrupt-or-otherwise-broken-audacity-project-recovery/64162/126

As it appears, in the case of this project `WaveTrack::LinkConsistencyFix` removes some zero-length clips it effectively removes the corresponding blocks from the `sampleblocks` table. However, the project is not marked as modified, nor is it (auto)saved. The project will get corrupted after Audacity is closed without the manual saving of the project.

This happens because Audacity checks for missing blocks before it checks for empty clips.

### Steps to reproduce

1. Make yourself a project with zero-length clip
2. Open it with 3.4.2 or latest master
3. Close Audacity
4. Observe that project can no longer be loaded. 

### Expected behavior

Project is not corrupted

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by DanPinGF** [comment] 2024-01-18 01:34
I've seen that the bug affects older projects regardless of length, and it's so bad it needs immediate fixing. Many of my Audacity projects are kept in case they need editing.

**Comment by Paul-Licameli** [comment] 2024-01-18 20:21
I still have not found exact enough steps to reproduce, but after some examination of the code, and over-complicated fixes, I found a surprisingly simple alternative that may work.

**Comment by chinakov** [comment] 2024-02-02 12:51
Tested. 

Managed to reproduce the issue in question on 3.4.2, and verified that the issue has been fixed.

Thank you.

**Comment by Paul-Licameli** [comment] 2024-02-05 11:10
I request that QA re-test this in recent master, because of some unusual moves involved in merging it with wave-clip-refactoring.

I doubt have serious doubts, but the implementation of this fix was disturbed again a little.

**Comment by dozzzzer** [comment] 2024-02-05 12:15
@chinakov ^

**Comment by chinakov** [comment] 2024-02-05 15:26
Will do!

**Comment by DanPinGF** [comment] 2024-02-05 20:32
'Fixed'? I don't see anything fixed in 3.4.2, as this is the latest stable build. The bug really concerns me because whenever I open an older Audacity project, it becomes corrupt without manually saving it and I have to permanently delete it, losing access to the project for good.

**Comment by LWinterberg** [comment] 2024-02-06 08:45
@DanPinGF Fixes from last week don't magically appear in a version released 3 months ago, indeed. It is fixed (pending verification from QA) in the current master (aka nightly or alpha), and will be present in the next release.

**Comment by chinakov** [comment] 2024-02-06 09:59
Re-tested, behaviour has not changed. Thanks!

**Closed** 2024-02-06 10:37 UTC
Labels: bug
