### ISSUE TITLE
Audacity 3.2 and above disables audio-in passthrough when using USB microphone on Mac

### ISSUE THREAD

**Issue by catchthetide** [audacity/audacity#4277] opened 2023-02-05 22:26 UTC
I use an Audio-Technica ATR2100-USB USB/XLR Microphone for recording on my Mac (Monterey 12.3.1), connected via USB. When my headphones are plugged into the microphone via 3.5mm jack, this allows me to hear instantaneous audio passthrough of my voice through the microphone to my headphones, as with a monitor. I have recorded using Audacity with this setup for many years.

As of Audacity 3.2 (including 3.2.4), the moment I press Record in Audacity, the audio passthrough from my microphone stops working and I can no longer hear myself in my headset. The problem will then persist system-wide for all software (not just Audacity) until I unplug the microphone and plug it back in. So it seems to be an issue of Audacity changing some unknown Mac setting temporarily.

Audacity 3.1 and earlier still work fine, so I’m sticking with the 3.1.3 build for the moment. I am aware that enabling “Software playthrough of input” on 3.2 is a partial fix, but it sounds worse with the slight delay and doesn’t address the problem of Audacity 3.2 disabling my microphone-to-monitor output system-wide.

**Comment by JohnColket** [comment] 2023-02-06 00:18
This is a duplicate of this issue: https://github.com/audacity/audacity/issues/3964

**Closed** 2023-02-08 17:14 UTC
