### ISSUE TITLE
Crash when using  1/3 octave spectrum analyzer (LV2)

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4370] opened 2023-02-28 17:01 UTC
### Plugin

1/3 Octave Spectrum Display Mono/Stereo

### Plugin Format

LV2

### Plugin source

http://x42-plugins.com/x42/x42-meters#spectr30mono

### Bug description

https://sentry.audacityteam.org/share/issue/b5c6ddc517444d31aacb3af96bb88cb0/

### Steps to reproduce

1. have some audio
2. Effect > (LV2) > 1/3 Octave Spectrum Display Mono (Stereo)

### Expected behavior

No crash, the plugin UI shows up

### Actual behavior

Crash

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

### Architecture

Apple Silicon (M1, M2, ...)

**Comment by Ryan-Miller-Audacity** [comment] 2023-03-31 12:56
This is a duplicate of #3331. Closing in favor of that item that already has some discussion.

**Closed by Ryan-Miller-Audacity** 2023-03-31 12:56 UTC
Labels: bug, P4, crash / freeze, plugins
