### ISSUE TITLE
Distortion effect: the Presets fail to work

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5184] opened 2023-09-11 11:04 UTC
### Bug description
When using the Distortion effect and trying to use any of the Factory Presets or any user presets they are not invoked and the settings in the effect remain as they were.

### Steps to reproduce
1. get some audio
2. Effect > Distortion
3. try to reset parameters using any of the Factory presets
4. Observe: the settings remain as they were at step 2
5. slide all the parameter to the left
6. save this as a a user preset called "Low"
7. change the parameter settings
8. try to reset parameters using the user preset "Low"
9. Observe: the settings remain as they were at step 7

### Expected behavior
Presets should work

### Actual behavior
Presets fail to be invoked

### Audacity Version
3.3.3 and 3.4.0 alpha

### Operating system
Windows 10 but assume all OS

### Additional context
None

**Comment by dozzzzer** [comment] 2023-09-11 11:08
A duplicate of #4326 ? @petersampsonaudacity

**Comment by petersampsonaudacity** [comment] 2023-09-11 11:08
This is a regression on earlier Audacity versions - as this worked properly in 2.4.2

_I'm sorry I don't have time right now to chase down the actual regression pooint_

**Closed** 2023-09-11 11:09 UTC
Labels: bug, regression, Effects
