### ISSUE TITLE
DPI Awareness support for High DPI Displays Resolutions

### ISSUE THREAD

**Issue by nvdavsamd** [audacity/audacity#4164] opened 2023-01-10 08:10 UTC
### Your idea

![audacity looks like shit no dpi awareness support](https://user-images.githubusercontent.com/122004809/211495126-e9596327-a7f9-4065-a443-6d36a65bf61d.jpg)
![audacity dpi unaware](https://user-images.githubusercontent.com/122004809/211495994-96997ef1-1b77-42b3-ae13-38af18ad39d0.jpg)

Hi,

Just have a good look at the above screenshot on high dpi display screen !
audacity looks terrible, horrible, blurry text and everything else, it's hard very hard to work with !
At normal resolution not scaled audacity is very small, and sadly i left my glasses on KRYPTON !

### Problem to be solved

make audacity **DPI Awareness** !

**Comment by vsverchinsky** [comment] 2023-01-10 08:53
To workaround that issue you can try override DPI scaling behavior: right-click on the app executable, select **Properties**, switch to **Compatibility** then check the **Override high DPI scaling behavior, scaling performed by** box and choose **Application** in the drop down list below

**Comment by poelzi** [comment] 2023-01-22 02:05
On my linux it is absolute unreadable. HI-DPI is not something exotic anymore. I seriously can't understand why people work on screens with less resolution then their phone.
![Screenshot_2023-01-22_03-00-20](https://user-images.githubusercontent.com/66107/213897362-fec5d181-d914-4e50-b944-a063e850eba8.png)

**Comment by LWinterberg** [comment] 2023-01-30 12:07
Duplicate of #503 - we're currently switching UI framework from wxwidgets to Qt and aren't looking to improve wx' HiDPI support as it'll be obsoleted soon anyway.

**Closed by LWinterberg** 2023-01-30 12:07 UTC
Labels: Enhancement Request
