### ISSUE TITLE
Some effects mess up envelope

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1529] opened 2021-08-25 09:28 UTC
**Describe the bug**
Most non-real-time effects mess up envelopes.

**To Reproduce**
1. Generate a 30 second tone
2. Add envelope points every 5 seconds in a recognizable pattern
3. select from about 7 seconds  to about 22 seconds
4. Apply a non-real-time (example: Graphic EQ)
5. Observe that the envelope between the start and end of the selection is destroyed.

**Expected behavior**
The effect to be applied  without changing the envelope.

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version audacity-linux-3.0.4-x86_64.AppImage

**Comment by crsib** [comment] 2021-08-25 10:06
This is a duplicate of #1500

**Closed by crsib** 2021-08-25 10:06 UTC
