### ISSUE TITLE
Linux: Missing horizontal scrollbar

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2937] opened 2022-05-16 10:23 UTC
**Describe the bug**
The horizontal scrollbar is missing

**To Reproduce**
1. Generate a 30 second tone
2. Zoom in

**Actual behavior**
Although part of the project is off-screen, there is no horizontal scrollbar

**Expected behavior**
A horizontal scrollbar to appear at the bottom of the tracks window when part of the project is off-screen.

**Screenshots**
If applicable, add screenshots/video to help explain your problem.

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version Audacity 3.2.0 2b5fa3

**Additional context**
Regression against Audacity 3.2.0 deaa3f

**Comment by petersampsonaudacity** [comment] 2022-05-16 11:15
Testing on W10 with audacity-win-3.2.0-alpha-20220513+2b5fa3c-x64-msvc2022

This works fine on Windows:
![image](https://user-images.githubusercontent.com/50205984/168580781-9cd22cbd-7ae4-42d7-a9ca-4ffd84ce1b55.png)

**Comment by petersampsonaudacity** [comment] 2022-05-16 12:33
Testing on macOS 12.3.1 Monterey with 
audacity-macOS-3.2.0-alpha-20220513+2b5fa3c-x86_64 

Works fine on Mac too.

**Comment by LWinterberg** [comment] 2022-05-17 09:22
duplicate of #2222

**Comment by SteveDaulton** [comment] 2022-05-17 10:56
> duplicate of #2222

It's the same symptoms, but not an exact duplicate, because the version of Audacity in #2222 worked correctly on Xubuntu 20.04.

Same machine, same OS, two different versions of Audacity - one works and the other doesn't.

**Comment by wchouser3** [comment] 2022-10-14 20:59
I can confirm - the horizontal scrollbar doesn't appear on the Flatpak, the Appimage or if you compile from source (Linux, that is) 
However, if you unmaximize, then re-maximize the scrollbar appears. Explain that one. I'm using Linux Mint 21, which is using the forked version of Mutter - under the X protocol. perhaps that has something to do with it.

**Comment by spicy-bah** [comment] 2023-01-29 00:10
I found a workaround for this. In preferences/interface, check *show scrub ruler* under *timeline*. That adds a few extra lines of pixels to the timeline, but now the horizontal scrollbar will show each time I open Audacity. 
Tested this with version 3.2.4 on Q4OS (Debian) and version 3.2.3 on KDE Neon, using the AppImage on both systems.

**Comment by Accidentaccio** [comment] 2023-02-05 22:02
I also report the bug on arch linux. Whenever audacity is started the ruler is not visible. The only way to get it is to go into settings, disable and re-enable it. I also report the bug on ubuntu, via appimage.

**Comment by Mte90** [comment] 2023-02-08 16:31
As I wrote it on https://github.com/audacity/audacity/issues/4292 I am able to replicate with various machines with just Debian Sid and the repository package.

**Comment by ossilator** [comment] 2023-02-09 17:31
for me, the minimal workaround to get the scrollbar is to simply resize the window ever so slightly.

probably a race condition in the event handling.

**Comment by Vladimyr0** [comment] 2023-03-17 17:45
none of the described workarounds work for me. 
ubuntu 18.04+unity

**Comment by mramendi** [comment] 2023-03-19 19:09
Issue manifests on Fedora 36,. Audacity 3.2.2, RPMFusion build. Changing window size does bring the scroll bar back.

**Comment by BiosElement** [comment] 2023-03-22 18:18
I can confirm this occurs on Arch Linux running KDE. Resizing the window returns the scroll bar. Happy to debug if needed. :)

**Comment by Cippo95** [comment] 2023-04-14 16:49
Same on Fedora 37 (i3wm spin) and Audacity 3.2.5,  tested on the appimage and flatpak.

**Comment by jwdevelab** [comment] 2023-05-11 09:46
> I can confirm this occurs on Arch Linux running Wayland and KDE. Resizing the window returns the scroll bar. Happy to debug if needed. :)

Arch Linux, Wayland and Hyprland. Even  though it's not that practical for a window manager, this worked for me. Thank you.

**Comment by rado84-github** [comment] 2023-06-20 11:22
> I can confirm this occurs on Arch Linux running Wayland and KDE. Resizing the window returns the scroll bar. Happy to debug if needed. :)

I'm using Xorg and Cinnamon. Resizing the window doesn't change anything. The only thing that brings up that horizontal slider (or scrollbar, if you will) is changing the theme to something else and reverting it back to the default Light theme.

Does anyone know of a version where this slider worked 100%, so that I can downgrade temporarily until the problem is fixed?

**Comment by Vladimyr0** [comment] 2023-06-21 12:28
> a version where this slider worked 100%

3.0.2

**Comment by rado84-github** [comment] 2023-06-21 13:55
> > a version where this slider worked 100%
> 
> 3.0.2

Unfortunately it turned out it's not as easy as I thought to downgrade audacity. Aside from the main dependencies, the system cries about a dozen other subdeps that I can't solve "just like that". I guess I have no choice but to wait for a fix of the problem. Considering it was reported a whole year ago, I don't think this will happen any time soon...

**Comment by rado84-github** [comment] 2023-09-01 13:38
> 

I was hoping it would be fixed for the non-snap versions cuz I'm not a fan of waiting half an hour to  compile and install 2 GB in order to run a few megabytes program.

**Comment by Vladimyr0** [comment] 2023-11-03 23:42
> if you unmaximize, then re-maximize the scrollbar appears

finally, on 3.4, this 'hack' works. 
not a fix yet, but the something....
(ubuntu unity 23.04, gtk3)

**Comment by rado84-github** [comment] 2023-11-04 09:37
> > if you unmaximize, then re-maximize the scrollbar appears
> 
> finally, on 3.4, this 'hack' works. not a fix yet, but the something.... (ubuntu unity 23.04, gtk3)

3.4 is still in extra-testing repo, so I'll wait till it gets moved to extra.

**Comment by miranda** [comment] 2024-05-09 20:04
This is happening to me with Audacity 3.5.1 in a Ubuntu 22 distrobox container.  Host OS is Arch Linux.  I created the Ubuntu container then built Audacity 3.5.1 in it, the resulting app has no horizontal scroll bar and there's no trick to get it to appear... although it seems to be just invisible, I can click in the area where it should be to scroll.

I tried installing the Ubuntu Audacity package which is version 2.4.2 and the scrollbar is there, so it's not anything wrong with my container or environment.

**Comment by zlice** [comment] 2024-06-01 16:17
#### resize logic

fwiw this patch seems to fix things by not hiding the scrollbars. i don't know the code that well and am confused on some of the variable names, but it looks like hiding scrollbars also disables them, which may mean they get no size or thumb position. that leads to the weird behavior of having to resize or double resize when you import/load a file and the scrollbar is deemed 'not needed'.

e.g.
- import file
- vertical scrollbar is not shown (single track fits in current track list window height)
- resize to smaller height to where vertical scrollbar IS needed
- vertical scrollbar is not shown
- resize height by a couple pixels (where the vertical scrollbar is still needed)
- vertical scrollbar is now shown

this fix is good enough for me, as i think the scrollbars should just always be shown and updated on size changes or added/removed tracks. some other variables could be removed if this is good. but if the goal is to make scrollbars disappear: the 'total' size + 'additional' 25% math needs adjusted (new file load does not have additional 25% extra empty space to scroll over, but resizing will lead to this extra empty space), and i think the old/new state vars may need to be int/double compares instead of bools.

#### patch

```diff
--- a/libraries/lib-viewport/Viewport.cpp	2024-06-01 09:25:58.915855057 -0400
+++ b/libraries/lib-viewport/Viewport.cpp	2024-06-01 11:06:08.779799589 -0400
@@ -326,10 +326,10 @@
    bool newvstate = panelHeight < totalHeight;

    // Hide scrollbar thumbs and buttons if not scrollable
-   if (mpCallbacks) {
-      mpCallbacks->ShowHorizontalScrollbar(newhstate);
-      mpCallbacks->ShowVerticalScrollbar(newvstate);
-   }
+   //if (mpCallbacks) {
+   //   mpCallbacks->ShowHorizontalScrollbar(newhstate);
+   //   mpCallbacks->ShowVerticalScrollbar(newvstate);
+   //}

    // When not scrollable in either axis, align viewport to top or left and
    // repaint it later
@@ -378,7 +378,7 @@
          totalHeight / scrollStep,
          panelHeight / scrollStep, true);

-   rescroll = (rescroll &&
+   rescroll = (rescroll ||
        (viewInfo.GetScreenEndTime() - viewInfo.hpos) < total);
    Publish({ (refresh || rescroll),
       (oldhstate != newhstate || oldvstate != newvstate), false });
```

#### old (current) behavior vs new (this patch) behavior

old on file load

![old-behavior](https://github.com/audacity/audacity/assets/8009811/03a883b7-76bf-40fd-b3f9-a52ca71a6d98)

resize and scroll to empty space

![old-behavior-resize-emptyspace](https://github.com/audacity/audacity/assets/8009811/d472d2e7-3d33-4eb2-baf6-67245dddab07)

new on file load

![new-behavior](https://github.com/audacity/audacity/assets/8009811/16b1140e-65e2-41af-a9b7-2355bc03c559)

scroll over to empty space without resizing

![new-behavior-empty-space](https://github.com/audacity/audacity/assets/8009811/85b35f0d-dd95-4365-88c5-527dd97f11cf)


#### side note

i noticed while capturing these screenshots that the version says 3.4.2 ... but the build is 3.5.1. some of the locale files still have 3.4.2 in them. not sure if that's my end or another bug.

**Comment by LWinterberg** [comment] 2024-06-01 21:27
Oh yeah, it seems like that hiding code is just broken. On Windows and mac, the scrollbar is just always visible at the moment. I think I'll be able to clean that up on monday.

**Comment by dozzzzer** [comment] 2024-06-03 12:21
Tested

**Closed** 2024-06-03 15:16 UTC
Labels: bug, P2, regression, Linux
