### ISSUE TITLE
audacity-win-3.4.0-alpha-20230804+ca2098e-x64-msvc2022: Graphic EQ - Shortcut for preset dialog

### ISSUE THREAD

**Issue by deus-e-x** [audacity/audacity#5001] opened 2023-08-06 13:53 UTC
### Your idea

Greetings Audacity Team,

can you please add a shortcut to the preset & settings dialog of the graphic eq? The shortcut has gone absent with the rewrite of several audio effects.

Furthermore, I think the graphic eq dialog can be improved by adding the ability to add buttons to the bottom of the dialog (below the graphic eq bars area) that each can represent a shortcut to a definable factory or user preset, thus eliminating the hassle of having to access the preset dialog.

Thank you.

### Problem to be solved

Improved accessibility to the factory/user-defined presets in the graphic eq dialog.

**Comment by DavidBailes** [comment] 2023-08-07 08:40
The absence of an access key for Presets & Settings is a duplicate of https://github.com/audacity/audacity/issues/3489.
There was a PR to fix that by @LWinterberg , which got delayed by lack of time for new translations, but has still not been merged.

**Comment by LWinterberg** [comment] 2023-09-06 11:24
![image](https://github.com/audacity/audacity/assets/87814144/a33742dd-9ea0-47ae-a73e-26abe05f2cb5)
I'd just pull out the presets into their own dropdown instead

**Closed by LWinterberg** 2023-09-06 11:24 UTC
Labels: Enhancement Request
