### ISSUE TITLE
Error on launch: Invalid IHDR data

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1726] opened 2021-09-23 18:33 UTC
**Describe the bug**
On launching Audacity 3.1.0 (debug) from a terminal window, the following error message  may be observed:
```Gtk-WARNING **: 17:13:37.483: Error loading theme icon 'gtk-cancel' for stock: Fatal error reading PNG image file: Invalid IHDR data```

**To Reproduce**
1. See above

**Expected behavior**
No errors on launch.

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: Audacity 3.1.0 (debug build)

**Comment by LWinterberg** [comment] 2021-12-23 18:32
I cannot reproduce this with the 3.1.3 appimage

**Comment by crsib** [comment] 2022-01-26 17:50
Likely it is. This is quite an infamous issue, which pops up from time to time on Linux. Generally, it happens if there is a libpng version mismatch between the application and GTK. I will try to move libpng out from the AppImage and see if it helps

**Comment by LWinterberg** [comment] 2023-02-27 16:07
This problem won't survive the transition to qt and won't be fixed before anyway.

**Closed by LWinterberg** 2023-02-27 16:07 UTC
Labels: bug, Linux, Won't fix
