### ISSUE TITLE
Support Opus format for audio 

### ISSUE THREAD

**Issue by Ygarr** [audacity/audacity#443] opened 2020-03-04 21:53 UTC
I can open and edit opus audio file, but cannot save(export) to same format 

**Describe the solution you'd like**
Export at least as same format edited audio for .opus audio

**Describe alternatives you've considered**
"Ocenaudio" has such feature. Just choose "Save as" and choose "Ogg OPUS" then "Replace existing"

**Comment by Pokechu22** [comment] 2020-03-04 23:14
Theoretically, ffmpeg should support this, but I can't seem to get that to work (perhaps I have an old ffmpeg version); it lists libopus as a codec but doesn't like selecting the opus format, and selecting the opus format and then libopus causes an error on export (see [Bug 2166](https://bugzilla.audacityteam.org/show_bug.cgi?id=2166)).

Something's definitely strange since [the ffmpeg documentation](https://ffmpeg.org/ffmpeg-codecs.html) mentions a second opus codec (their own implementation), which I don't see listed in audacity; that probably indicates something's outdated.

**Comment by finn64** [comment] 2020-03-06 01:19
Not sure if this helps, but opus steam is normally contained in webm

**Comment by petersampsonaudacity** [comment] 2020-04-03 13:36
We (Leland Lucius that is - thanks Leland) has just added Opus Export as a direct choice in Export Audio and Export Multiple for the soon to be upcoming 2.4.0.  I have been QA testing this and writing the documentation for the Manual - and so far all looks good

**Comment by JamesCrook** [comment] 2020-06-03 21:32
Removed 2.4.0 label, as 2.4.0 does not support opus on Mac (yet).
https://bugzilla.audacityteam.org/show_bug.cgi?id=2381

**Comment by MisterZeus** [comment] 2022-01-16 20:21
> Not sure if this helps, but opus steam normally uses webm as a container

For saving files though, it should probably use the Ogg container: https://github.com/xiph/ogg

**Comment by LWinterberg** [comment] 2022-02-28 09:21
Some starting points: 

* Opus support was done previously through FFMPEG (by the looks of it) but got axed due to some problems. https://bugzilla.audacityteam.org/show_bug.cgi?id=2381 has some commits and some related issues linked which themselves may contain relevant commits. 
* https://github.com/audacity/audacity/tree/master/src/export is where Audacity's export logic lives
* According to https://ffmpeg.org/ffmpeg-codecs.html#opus, the FFMPEG opus codec is worse than [xiph's libopus](https://opus-codec.org/development/)

**Comment by petersampsonaudacity** [comment] 2022-02-28 10:10
> * Opus support was done previously through FFMPEG (by the looks of it) but got axed due to some problems. https://bugzilla.audacityteam.org/show_bug.cgi?id=2381

That Bugzilla bug was transferred to GitHub a while back and remains open:
https://github.com/audacity/audacity/issues/1515

Note that the bug only relates to the Mac platform.  

Opus export and import works fine on W10 - I just tested with 3.1.3 and AFAIK also works OK on Linux:
![image](https://user-images.githubusercontent.com/50205984/155964739-fa66387d-6516-4cc0-a860-7679f1ef56db.png)

**Comment by crsib** [comment] 2022-02-28 10:15
Hi @Dhriti03!

> Hello, please can someone brief me through as to how should I start working on this issue.

You need to implement `ExportOpus.cpp` and `ImportOpus.cpp` similar to `ExportFLAC.cpp` and `ImportFLAC.cpp`. All the libraries required are already linked into Audacity

**Comment by Dhriti03** [comment] 2022-03-03 07:35
> Hi @Dhriti03!
> 
> > Hello, please can someone brief me through as to how should I start working on this issue.
> 
> You need to implement `ExportOpus.cpp` and `ImportOpus.cpp` similar to `ExportFLAC.cpp` and `ImportFLAC.cpp`. All the libraries required are already linked into Audacity

Can you please describe a bit more as to what changes should i make in the opus file different from the FLAC file

**Comment by LWinterberg** [comment] 2022-03-24 19:32
Just to confirm - does FFMPEG currently call the ffmpeg `opus` codec or the xiph `libopus` codec?

**Comment by crsib** [comment] 2022-03-24 22:19
>This one could be closed in favor of https://github.com/audacity/audacity/issues/1515

I disagree. #1515 seems is a problem with the specific build of ffmpeg, so it is not a bug in Audacity. This issue is about native OPUS support, without FFmpeg. 

>Just to confirm - does FFMPEG currently call the ffmpeg opus codec or the xiph libopus codec?

This depends on the specific build of FFmpeg

**Comment by petersampsonaudacity** [comment] 2023-10-13 13:33
Testing On W10 with @crsib 's latest branch build for this:  audacity-win-3.4.0-alpha-20231013+3fad59f-x64

The Opus export works properly (I re-imported the Opus file to check)

**Comment by dozzzzer** [comment] 2023-10-16 10:16
Tested

**Closed** 2023-10-16 10:49 UTC
Labels: Enhancement Request, medium feature
