### ISSUE TITLE
GUI. Theme changing works poor

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1369] opened 2021-07-27 11:19 UTC
**Describe the bug**
GUI elements do not change their appearance correctly

**To Reproduce**
1. Launch Audacity
2. Expand Audacity's window
2. Go to Preferences - Interface - change theme appearance from light to dark, then click Ok
4. See the bug - many GUI elements still displaying with previous theme look
5. Change Audacity windows size and all elements have the proper colour scheme

**Expected behavior**
The dark GUI looks at least like this: https://github.com/audacity/audacity/issues/1296

**Screenshots**
![изображение](https://user-images.githubusercontent.com/25851359/127144703-91fb3f74-4c37-4194-9a0d-0ba22b3385da.png)
![Full Window000](https://user-images.githubusercontent.com/25851359/127147428-e8453ca4-408f-4827-8c19-4a79571adc45.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 x64]
 - Version: Audacity 3.0.4-alpha-20210726

**Comment by petersampsonaudacity** [comment] 2021-07-27 12:07
This also affects Light theme when you go back to it from Dark theme
![image](https://user-images.githubusercontent.com/50205984/127150861-4bbc1e2c-07d4-4353-a24e-1254d0a751f6.png)

So it looks like a general theming regression

**Comment by Paul-Licameli** [comment] 2021-07-27 14:35
Is it confirmed that this does not happen in 3.0.3?

In @petersampsonaudacity 's shot I also see that the Time toolbar repainted wrong with inconsistent font sizes.  A separate issue if reproducible.

**Comment by petersampsonaudacity** [comment] 2021-07-27 15:04
> Is it confirmed that this does not happen in 3.0.3?

I confirm that on W10 this does not happen with 3.0.3 and is thus a regression on 3.0.2

**Comment by SteveDaulton** [comment] 2021-07-27 18:10
Audacity 3.0.3 (release) looks nice  on Linux with a dark Desktop  theme (I've not yet tried 3.0.4 alpha)

![Screenshot_2021-07-27_19-04-38](https://user-images.githubusercontent.com/11681097/127205964-06c3ad97-ce81-4207-a2b0-fc090e81841a.png)

**Comment by vsverchinsky** [comment] 2021-07-27 18:40
Seems like broken after this PR https://github.com/audacity/audacity/pull/1328 has been merged

**Comment by Paul-Licameli** [comment] 2021-08-04 12:01
I don't observe the problem in macOS.

**Closed** 2021-08-09 09:05 UTC
Labels: bug, regression, Bug severity: Low

**Comment by petersampsonaudacity** [comment] 2021-08-09 09:51
Tested on W10 with latest 3.1.0/3.0.4 alpha:   audacity-win-3.0.4-alpha-20210809+cf09f0a-64bit

I confirm that this now works correctly again on Windows.
