### ISSUE TITLE
Using Ctl-A when editing the text of a Label behaves inconsistently

### ISSUE THREAD

**Issue by eharris** [audacity/audacity#6036] opened 2024-02-25 14:09 UTC
### Bug description

Using Ctl-A when editing the text of a label behaves differently based on what was previously selected when it shouldn't.
If the current label track had been previously selected before editing a Label, then Ctl-A behaves as expected, and selects the text of the Label currently being edited.
But if the selection before editing the label was somewhere other than within the label track, Ctl-A selects the whole label track rather than the text of the label currently being edited.

### Steps to reproduce

1. Edit a project with an audio track and a label track
2. Place the selection/marker within the audio track
3. Click within a Label title to edit the label
4. Press Ctl-A

### Expected behavior

When editing the text of a Label, Ctl-A should behave consistently, and always select the whole text of the label currently being edited.

### Actual behavior

If the selection before editing a Label was not within the Label track, Ctl-A does not select the text within the label being edited.

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

Audacity 3.2.4 from Debian Stable (bookworm) amd64

**Comment by LWinterberg** [comment] 2024-02-28 11:55
Duplicate of https://github.com/audacity/audacity/issues/4941

It's fixed in 3.4

**Closed by LWinterberg** 2024-02-28 11:55 UTC
Labels: bug
