### ISSUE TITLE
Effects. Preview in some effects tend to be "Infinite"

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2546] opened 2022-02-11 09:24 UTC
**Describe the bug**
The elapsed time of preview still growing although preview playback is over

![image](https://user-images.githubusercontent.com/25851359/153566079-9e3e6470-3a22-45b5-991b-725a04ba443e.png)

**To Reproduce**
1.Add 0.5 sec clip 
2. Open Paulstretch effect
3. Click "Preview"

**Expected behavior**
The preview dialog should be closed after preview playback is run out. 

**Additional information (please complete the following information):**
 - OS: All
 - Version Audacity 3.2+

**Comment by petersampsonaudacity** [comment] 2022-02-11 12:52
Testing on W10 shows that this (with Paulstretch) is a regression on 3.1.3

_I can't find other effects that fail the preview like this._

**Comment by SteveDaulton** [comment] 2022-02-11 13:06
I don't see this bug on Xubuntu 20.04 with Audacity 3.2.0 commit #cf98d1

**Comment by SteveDaulton** [comment] 2022-02-11 13:14
I don't see this bug on Xubuntu 20.04 with Audacity 3.2.0 commit 698f8a either.

**Comment by Paul-Licameli** [comment] 2022-08-22 12:30
I can't reproduce and it may have been fixed by my 3b243ab3aad239d6f9a2dc7b8746f978edb623e9

**Comment by Ryan-Miller-Audacity** [comment] 2022-08-22 15:16
I was not able to reproduce this either in the [most recent master build](https://github.com/audacity/audacity/actions/runs/2888729076) on MacOS or Windows with the Paulstretch effect. I also briefly checked a few other native effects and did not see this.

**Closed by Ryan-Miller-Audacity** 2022-08-22 15:16 UTC
Labels: bug, P2, regression
