### ISSUE TITLE
Remove the "Click to merge clips" line

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2330] opened 2021-12-22 10:04 UTC
![image](https://user-images.githubusercontent.com/87814144/147074832-8f62bb80-5584-4aa1-8a0c-280ff03e3b4f.png)

... and put the option to merge clips in a context menu ("Join Clips") instead. This is because:

1. It gets in the way of selecting audio from the beginning/end of a clip when other clips are present (you can press Esc to toggle into a selection, but still)
2. It obscures the first sample in a clip if the clips are directly adjacent
3. When clips are not directly adjacent but still in a range for it to appear, it just kinda floats in empty space
4. With clips becoming more independent of the audio itself (with Smart Clips 1.0 and especially 2.0), having a one-click thing to merge clips becomes less and less useful, relative to Audacity's feature set

* See also #1497

The context menu option should function in the following way:
* If a range of audio is selected, `Right-Click > Join Clips` joins all selected clips (same as Edit > Clip Boundaries > Join)
* If no audio is selected and the cursor is on top of a Clip boundary, `Right-Click > Join Clips` joins the two adjacent clips (same thing as what clicking the line would do)

This resolves the following bugs in the process
* #1815
* #1663
* #2259
* #2905

**Comment by petersampsonaudacity** [comment] 2021-12-27 11:02
See related issue:
Impossible to select point audio with cursor at shared clip boundaries #1815

**Comment by petersampsonaudacity** [comment] 2022-01-09 11:04
See also #1497

**Comment by Kulkarniyash7** [comment] 2022-04-10 06:20
Where to locate code of this? Wanted to try if I can do it.

**Comment by co18332** [comment] 2022-04-10 16:08
> Where to locate code of this? Wanted to try if I can do it.

Hi @Kulkarniyash7 I was looking into the same issue, I have found the call to merging function in CutlineHandle (\audacity\src\tracks\playabletrack\wavetrack\ui\CutlineHandle.cpp), hope it helps. 

I came to this file by searching for the message "Left-click to merge clips"

**Comment by Kulkarniyash7** [comment] 2022-04-18 12:23
In my case text didn't appeared (Windows Platform) ! Is this issue is fixed ? Might not be marked as open issue !

**Comment by Kulkarniyash7** [comment] 2022-04-18 12:40
Made a pull request 
Changed the text "Left-click to merge clips" to "Join Clips".

**Comment by Kulkarniyash7** [comment] 2022-04-18 12:44
Let me know how can I locate code for context menu?

**Comment by Kulkarniyash7** [comment] 2022-04-20 07:54
How can I locate the code for context menu to add the option for joining clips ?

**Comment by SteveDaulton** [comment] 2022-06-09 13:29
I'm sure that some users will see it as a regression when they can no longer just click on a split line to join the clips.
 

> 1. It gets in the way of selecting audio from the beginning/end of a clip when other clips are present

Not really. When selecting part of the clip you can select "to" the clip boundary, and there's a handy yellow "snap" line to indicate when you are exactly on the edge of the clip. For selecting an entire clip, just double click on it, or single click on its handle.


> 2\. It obscures the first sample in a clip if the clips are directly adjacent

If that's really an issue (I don't personally think it is), then the sample dot could be made a fraction larger, or the split line moved a fraction to the side of the sample dot.

> 3\. When clips are not directly adjacent but still in a range for it to appear, it just kinda floats in empty space

If I recall correctly, that's because [Paul-Licameli](https://github.com/audacity/audacity/commits?author=Paul-Licameli) decided that clips should appear to start and end on the first / last sample dot (rather than ending at the end of a sample period). That has not always been the case and need not be the case in the future.

I do agree that clip boundaries are becoming heavily overloaded, and that is causing UX issues, but I don't think that the reasons given here justify removing a feature that many users have relied on for very many years.

Changing the "join" action from "left click" to "right click" would still require experienced Audacity users to retrain their "muscle memory", but in my opinion that would be much less bad than removing this feature altogether. I really don't think that this feature should be removed before there is an alternative that is at least "nearly" as easy and convenient.

**Comment by petersampsonaudacity** [comment] 2022-06-09 13:37
@SteveDaulton   of more concern to me is:
**Impossible to select point audio with cursor at shared clip boundaries** #1815 

Typically left click and left click and drag are primary means to make a selection in a track.  So I would like to see this left-click action (to join clips) removed.

However I would probably support your suggestion of changing that to be a right-click gesture.  But to be carefully considered is the fact that right-click gestures are often used to invoke context menu.  We don't had a context menu for tracks right now, but we could well do in the future.

**Comment by LWinterberg** [comment] 2022-06-09 13:56
> ... and put the option to merge clips in a context menu ("Join Clips") instead. 

I'm advocating to put it in a right click menu, yes.

**Comment by Paul-Licameli** [comment] 2022-06-09 14:23
> > 3. When clips are not directly adjacent but still in a range for it to appear, it just kinda floats in empty space
> 
> If I recall correctly, that's because [Paul-Licameli](https://github.com/audacity/audacity/commits?author=Paul-Licameli) decided that clips should appear to start and end on the first / last sample dot (rather than ending at the end of a sample period). That has not always been the case and need not be the case in the future.
> 

When did I decide that?  Was it years ago?

**Comment by petersampsonaudacity** [comment] 2022-08-31 16:04
@LWinterberg   is this still going to be fixed sometime - or will the left-click on the clip boundary to merge clips remain with us forever?

My understanding is that you were proposing to implement a right-click context menu to effect the merge/join neighboring clips.

**Comment by petersampsonaudacity** [comment] 2023-09-20 20:24
Tested on W111 with @saintmatthieu 's latest branch build: audacity-win-3.4.0-alpha-20230920+abaf04b-x64

This looks to be properly fixed in Matthieu's branch.

**Comment by saintmatthieu** [comment] 2023-09-20 20:26
Thanks for your contribution, Peter!

**Closed** 2023-09-22 13:13 UTC
Labels: Enhancement Request, Clips, feature tweak, Design Debt
