### ISSUE TITLE
Screen Stutters While Trying To Auto-Scroll

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#3049] opened 2022-06-08 15:17 UTC
**Describe the bug**
When the cursor reaches the end of the screen while playing audio, Audacity makes several false starts at refreshing the screen, resulting in a jumpy or stuttering screen. "It happens when the cursor reaches the right edge of the segment of the track currently displayed and Audacity refreshes the screen with the next track segment."

This problem was reported on the forum.  See: [[Screen stuttering in playback in Audacity 3.1.3](https://forum.audacityteam.org/viewtopic.php?p=449839#p449919)](https://forum.audacityteam.org/viewtopic.php?p=449839#p449839)

**Video**
 [Screen stuttering_edit.mp4](https://forum.audacityteam.org/download/file.php?id=35290)

**Additional information (please complete the following information):**
 - OS: Windows
Audacity 3.1.3
Audacity 3.2.0 - specifically: audacity-win-3.2.0-alpha-20220607+1ebe0e3-x64-msvc2019
This is a regression on 2.x.x.

**Comment by petersampsonaudacity** [comment] 2022-06-09 15:00
Testing on W10 with 3.1.2 1n latest alpha master audacity-win-3.2.0-alpha-20220608+a2b9986-x64-msvc2022

I cannot reproduce this on W10

And I do not recall seeing this over the last week on W11 when I was in Zurich with my Swiss laptop

**Comment by petersampsonaudacity** [comment] 2022-06-09 15:03
Testing on macOS 12.4 Monterey with 3.1.3 and latest 3.2.0 alpha master/

Mostly I get no such stutter in the display.

But with both versions if I 
1. set it to normal zoom levels with Cmd+2
2. Zoom in with the Zoom button 2 or 3 times
3. Then I can see a light stutter at the redraw - but nothing like as extreme as in the video that @JohnColket posted.

**Comment by Ryan-Miller-Audacity** [comment] 2022-07-08 12:26
I am struggling to reproduce any amount of stutter on either my windows (Windows 10 HP Omen Laptop)  or Mac (MacOS Monterey 12.3.1 Macbook Air M1) machines. Even if I utilize the additional steps @petersampsonaudacity noted above I am not seeing a stutter. 

Perhaps @dozzzzer could see if he can reproduce?

**Comment by dozzzzer** [comment] 2022-07-08 13:00
I wasn't able to reproduce it either (MacOS & Windows 11).

**Comment by LWinterberg** [comment] 2024-10-15 11:09
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.

**Closed by LWinterberg** 2024-10-15 11:09 UTC
Labels: AU3-bug, P3, UI
