### ISSUE TITLE
[Plugin issue] FFMPEG no longer works/is not detected

### ISSUE THREAD

**Issue by jadenquinn** [audacity/audacity#4947] opened 2023-07-24 02:17 UTC
### Plugin

FFMPEG

### Plugin Format

Other

### Plugin source

https://lame.buanzo.org/ffmpeg.php

### Bug description

I just tried this on a brand new install of MacOS High Sierra, brand new Audacity download, brand new FFmpeg download, it doesn't work. It simply doesn't "detect" it, even when I point it directly to the avformat thing that it says it wants.

This is not fixed, and I have been able to reproduce this on 4 different Macs on 3 different OS versions on 2 different architectures.

### Steps to reproduce

1. Install MacOS High Sierra.
2. Get Audacity.
3. Install FFMPEG plugin v5.0.0.
4. Get pissed because you need to get stuff done and it doesn't work.

### Expected behavior

When I download a program, I expect it to work as it should.

### Actual behavior

Audacity shows that the FFMPEG plugin is not installed, even right after installing it. If I point it to it, that doesn't change jack.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

### Architecture

64 bit Intel/AMD processors, Apple Silicon (M1, M2, ...)

### Additional context

Video of problem: https://youtu.be/7x69HBnHkuw
Screenshot of problem: https://user-images.githubusercontent.com/13245331/255453849-c3417b8f-c443-4226-87cf-549bbe75e74a.png

**Comment by crsib** [comment] 2023-07-24 08:35
Please post the log from the Help -> Diagnostics -> Show Log

**Comment by LWinterberg** [comment] 2023-07-24 11:29
Duplicate of #4796

**Comment by jadenquinn** [comment] 2023-07-25 19:40
Yes, it's a duplicate, I just didn't think the old one (since it was closed) to not get any more eyes so I started a new one.

**Comment by jadenquinn** [comment] 2023-07-31 20:04
I think it has something to do with the version I always download being the "universal" binary, as apparently this doesn't/hasn't happened to me on the new ARM Macs, only the Intel ones. ffmpeg support is detected and works just fine in Audacity 3.3.3 on an M2 Pro Mac mini on MacOS 14.0 Sonoma dev preview.

**Comment by crsib** [comment] 2023-08-01 11:04
This is not the case. "Universal" means that it works both on ARM and x64 Macs, and it surely works.

Please post the log from the `Help -> Diagnostics -> Show Log`, it is impossible to diagnose your problem otherwise

**Comment by jadenquinn** [comment] 2023-08-03 02:38
> This is not the case. "Universal" means that it works both on ARM and x64 Macs, and it surely works.
> 
> Please post the log from the `Help -> Diagnostics -> Show Log`, it is impossible to diagnose your problem otherwise

There are other problems of the same kind related to the "Universal binary" status.

**Comment by LWinterberg** [comment] 2023-08-03 06:36
So what does the log say?

**Comment by petersampsonaudacity** [comment] 2023-08-03 14:09
Testing on my Macbook Pro running Monterey macOS 12.6.7  (Intel-based Mac)

I just downloaded the latest alpha test build for 3.4.0 - the Universal build ad FFmpeg works fine for me.

1. the library is there and found
2. I can export AAC
3. I can import AAC

**Closed** 2023-09-06 11:25 UTC
Labels: Could not reproduce, bug, plugins

**Comment by stunlocked1** [comment] 2023-09-20 09:18
yeah I select the avformat.dll, press OK, nothing changes, no error messages, it just doesn't save the setting and keeps saying ffmpeg not found

**Comment by stunlocked1** [comment] 2023-09-20 09:19
and by the way the link to the installer doesn't work... So I had to download zip one from the github link on the same page

**Comment by stunlocked1** [comment] 2023-09-20 09:34
So apparently ffmpeg for audacity author holds a grudge against using VPNs and blocks them, well not to worry, unless you are him then keep malding, for you can download it using wayback machine

**Comment by jadenquinn** [comment] 2024-07-12 21:38
This is still a problem.

**Comment by itsthisjustin** [comment] 2024-07-31 16:02
I'm also having this issue on an m2 Macbook. I tried the Homebrew installation too and Audacity always reports that it's found the library in settings but if you try to open an m4a file it says it can't due to the missing library.
